--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                    Text)
values
    -- Notification Log
    ("zh_Hans_CN",  "LOC_FF16_NOTIFICATION_LOG_TITLE",      "消息记录"),
    ("zh_Hans_CN",  "LOC_FF16_LOGSIZE_OPTION",              "面板尺寸:"),
    ("zh_Hans_CN",  "LOC_FF16_MAXLOGSIZE_OPTION",           "最多条数:"),
    ("zh_Hans_CN",  "LOC_FF16_LOGSIZE_AUTO",                "自动"),
    ("zh_Hans_CN",  "LOC_FF16_CLEARLOG_OPTION",             "过回合清空消息记录"),
    ("zh_Hans_CN",  "LOC_FF16_LOG_OPTIONS_TITLE",           "消息记录偏好设置"),
    ("zh_Hans_CN",  "LOC_FF16_NOTIFICATION_LOG_TOOLTIP",    "偏好设置"),
    ("zh_Hans_CN",  "LOC_FF16_LOG_ENTRY_SINGLE",            "有新的小道消息，右键清空记录。"),
    ("zh_Hans_CN",  "LOC_FF16_LOG_ENTRY_MULTIPLE",          "有新的小道消息，右键清空记录。"),
    -- Configure Minimal City Distance
    ("zh_Hans_CN",  "LOC_CMCD_NAME",                        "最小城市间距"),
    ("zh_Hans_CN",  "LOC_CMCD_DESCRIPTION",                 "建立城市时的最近距离限制"),
    ("zh_Hans_CN",  "LOC_CMCD_HEADER_NAME",                 "[COLOR_Production]设置最小城市间距[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_CMCD_HEADER_DESCRIPTION",          "由DahakaMVl制作的 设置最小城市间距"),
    ("zh_Hans_CN",  "LOC_CMCD_FOOTER_NAME",                 "[COLOR_Production]设置最小城市间距 结束[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_CMCD_FOOTER_DESCRIPTION",          "用于填充的假选项"),
    -- RadialMeasuringTool
    ("zh_Hans_CN",  "LOC_RMT_WND_TITLE",                    "半径测量工具"),
    ("zh_Hans_CN",  "LOC_RMT_LBL1",                         "点击地图上的位置来可视化半径内的地格"),
    ("zh_Hans_CN",  "LOC_RMT_RAD_LBL",                      "半径:"),
    ("zh_Hans_CN",  "LOC_RMT_ALT_RAD_PREFIX",               "在"),
    ("zh_Hans_CN",  "LOC_RMT_ALT_RAD_SUFIX",                "格内"),
    ("zh_Hans_CN",  "LOC_RMT_ALT_RAD_CB_TT",                "选中后采用在x格内的计数方式"),
    ("zh_Hans_CN",  "LOC_RMT_CB_MULTI",                     "多重半径高亮"),
    ("zh_Hans_CN",  "LOC_RMT_CB_CITY_ONLY",                 "只高亮市中心"),
    ("zh_Hans_CN",  "LOC_RMT_CB_BONUS_RES",                 "忽略加成资源"),
    ("zh_Hans_CN",  "LOC_RMT_MAX_CITY_RAD",                 "- 市民可工作范围"),
    ("zh_Hans_CN",  "LOC_RMT_KEY_CITY_CEN",                 "市中心"),
    ("zh_Hans_CN",  "LOC_RMT_KEY_RES",                      "资源"),
    ("zh_Hans_CN",  "LOC_RMT_CB_TRANSP",                    "使用透明的窗口背景"),
    ("zh_Hans_CN",  "LOC_RMT_CB_WND_POS",                   "窗口位置");

-- Extended Map Search
--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                    Text)
values
    ("zh_Hans_CN",  "LOC_MSE_WINDOW_TITLE",                                                 "地图搜索扩展"),
    ("zh_Hans_CN",  "LOC_MSE_BTN_REMOVE_LAST_WORD",                                         "退格"),
    ("zh_Hans_CN",  "LOC_MSE_BTN_REMOVE_LAST_WORD_TT",                                      "删除输入框的最后一个词。"),
    ("zh_Hans_CN",  "LOC_MSE_APPEND",                                                       "追加搜索项目"),
    ("zh_Hans_CN",  "LOC_MSE_APPEND_TT",                                                    "将右侧面板中选择的项目追加至输入框中，取消勾选则会直接替代。"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA",                                                  "搜索满足下列条件的单元格"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_TT",                                               "只有满足下列勾选条件之一的地块才会被搜索。"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_ME",                                               "我的领土内"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_ME_TT",                                            "在我的领土内搜索。"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_OTHER",                                            "其他人的领土内"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_OTHER_TT",                                         "在其他人的领土内搜索。"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_NONE",                                             "无主地块"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_NONE_TT",                                          "在无主地块上搜索。"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_PURCHASED_BY_ME",                                  "我的城市附近"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_AREA_PURCHASED_BY_ME_TT",                               "在我的城市的3个单元格内搜索。"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_BTN",                                           "选项"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_BTN_TT",                                        "设置地图搜索扩展的选项"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_WND_TITLE",                                     "地图搜索扩展的选项"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_COLOR_TITLE",                                   "地块高亮配色"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_COLOR_FILL",                                    "地块高亮填充颜色"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_COLOR_BORDER1",                                 "地块高亮边框颜色"),
    ("zh_Hans_CN",  "LOC_MSE_SEARCH_OPTIONS_COLOR_BORDER2",                                 "地块高亮内部阴影颜色"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_BLACK",                                                  "黑"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_BLACK_TRANS",                                            "透明黑"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_WHITE",                                                  "白"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_WHITE_TRANS",                                            "透明白"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_GREY",                                                   "灰"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_GREY_TRANS",                                             "透明灰"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_GREEN",                                                  "绿"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_GREEN_TRANS",                                            "透明绿"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_GREEN_DEFAULT",                                          "默认的绿色"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_BLUE",                                                   "蓝"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_BLUE_TRANS",                                             "透明蓝"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_RED",                                                    "红"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_RED_TRANS",                                              "透明红"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_YELLOW",                                                 "黄"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_YELLOW_TRANS",                                           "透明黄"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_CYAN",                                                   "天蓝"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_CYAN_TRANS",                                             "透明天蓝"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_MAGENTA",                                                "品红"),
    ("zh_Hans_CN",  "LOC_MSE_COLOR_MAGENTA_TRANS",                                          "透明品红"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_DEST_SEARCH_TT",                                       "选择的项目将进入搜索项目。单击改为进入过滤项目。"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_DEST_FILTER_TT",                                       "选择的项目将进入过滤项目。单击改为进入搜索项目。"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_RESOURCE_TT",                                          "显示资源"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_CITY_TT",                                              "显示城市"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_CIVILIZATION_TT",                                      "显示文明"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_IMPROVEMENT_TT",                                       "显示改良设施"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_UNIT_TT",                                              "显示单位"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEL_WONDER_TT",                                            "显示奇观"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_WINDOW_TITLE",                                             "选择搜索项目"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_WINDOW_TITLE_FILTER",                                      "选择过滤项目"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEARCH_TERMS_IMPROVEMENT_DOES_NOT_MATCH_RESOURCE_DESC",    "搜索因未正确改良而无法享受收益的资源"),
    ("zh_Hans_CN",  "LOC_MSE_EXT_SEARCH_TERMS_IMPROVEMENT_DOES_NOT_MATCH_RESOURCE",         "未正确改良的资源");
