-- --------------------------------------------------------------------------------
-- -- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                                   Text)
values
    ("LOC_GOVERNOR_PROMOTION_GARRISON_COMMANDER_DESCRIPTION",                               "Units defending within the city's territory get +3 [ICON_Strength] Combat Strength. The city gains an additional [ICON_Ranged] Ranged Strike per turn. +100% building speed toward defensive buildings."),
    ("LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION",                              "Improved [ICON_RESOURCE_HORSES] Horses accumulate 3 more resources per turn. Receive a second light cavalry unit or Saka Horse Archer each time you train a light cavalry unit or Saka Horse Archer."),
    ("LOC_TRAIT_LEADER_AMABUTHO_DESCRIPTION",                                               "May form Corps (Mercenaries Civic) and Armies (Nationalism Civic) earlier."),
    ("LOC_TRAIT_LEADER_AMBIORIX_DESCRIPTION",                                               "Your civilization gains [ICON_CULTURE] Culture equal to 20% of the unit's cost when a non-civilian is trained. Melee, Anti-Cavalry, and Ranged Units receive +1 [ICON_Strength] Combat Strength for every adjacent unit."),
    ("LOC_TRAIT_LEADER_TRIEU_DESCRIPTION",                                                  "+3 [ICON_Strength] Combat Strength for units fighting in Rainforest, Marsh, or Woods tiles. +1 [ICON_Movement] Movement if they begin their turn there. Both these bonuses are doubled if the tile is your territory."),
    ("LOC_TRAIT_LEADER_MUTAL_DESCRIPTION",                                                  "Reveal plots within 6 tiles of the starting plot. Cities within 6 tiles of the [ICON_Capital] Capital gain +10% to all yields, and when founded receive a builder. Non capital cities within 9 tiles and outside 6 tiles of the [ICON_Capital] Capital yields remain usual. Other non capital cities receive -15% to all yields. +3 [ICON_Strength] Combat Strength to units within 6 tiles of the [ICON_Capital] Capital."),
    ("LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",                                          "[ICON_TechBoosted] Eurekas provide 84% of the [ICON_SCIENCE] Science for technologies. -50% [ICON_SCIENCE] Science per turn."),
    ("LOC_TRAIT_LEADER_ADVENTURES_ENKIDU_EXPANSION2_DESCRIPTION",                           "When at war with a common foe, they and their allies share pillage rewards and share combat experience gains if within 5 tiles. Their Alliances gain Alliance Points for being at war with a common foe."),
    ("LOC_DISTRICT_SEOWON_HD_DESCRIPTION",                                                  "A district unique to Korea. Replaces the Campus. +3 [Icon_Science] Science. Has more citizen slots."),
    ("LOC_TRAIT_LEADER_HWARANG_DESCRIPTION",                                                "+2 [ICON_Amenities] Amenities, +3 [Icon_Housing] Housing and +20 Loyalty per turn for your Capital and cities with an assigned Governor. -2 [ICON_Amenities] Amenities, -20 Loyalty per turn and -50% to all yields for cities that are not your Capital and do not have an assigned Governors. +25% [ICON_PRODUCTION] Production towards Districts and Buildings for cities that have a Seowon district. +15% [ICON_Production] Production and +15% [ICON_FOOD] Food for Cities have a Library. +100% Districts Adjacency (of corresponding yields) to all Districts for Cities that have a University. Cities with a Research Lab gain +10% to all yields and +1 to all [ICON_CITIZEN] citizen yields."),
    ("LOC_TRAIT_LEADER_EL_ESCORIAL_EXPANSION2_DESCRIPTION",                                 "Inquisitors can Remove Heresy one extra time. Inquisitors eliminate 100% of the presence of other Religions. Combat and Religious units have a bonus of +3 [ICON_Strength] Combat Strength against players following other Religions."),
    ("LOC_TRAIT_LEADER_LAUTARO_ABILITY_DESCRIPTION_ALT",                                    "+5 [ICON_Strength] Combat Strength when fighting Free Cities or civilizations that are in a Golden or Heroic Age. Defeating an enemy unit within the borders of an enemy city causes that city to lose 20 Loyalty and 40 loyalty if that civilization is in a Golden or Heroic Age."),
    ("LOC_TRAIT_CIVILIZATION_LAST_PROPHET_DESCRIPTION",                                     "Automatically receive the final [ICON_GreatProphet] Great Prophet when the next-to-last one is claimed (if you have not earned a [ICON_GreatProphet] Great Prophet already). +2 [ICON_Science] Science for each foreign city following Arabia's Religion."), 
    ("LOC_TRAIT_LEADER_CITADEL_CIVILIZATION_DESCRIPTION",                                   "+50% [ICON_Production] Production if either they have received a declaration of war in the past 10 turns or if they have liberated a city in the past 20 turns. +1 [Icon_Food] Food for all Pastures across the Nation. "), 
    ("LOC_TRAIT_CIVILIZATION_MALI_GOLD_DESERT_DESCRIPTION",                                 "City Centers gain +1 [ICON_FAITH] Faith and +1 [ICON_FOOD] Food for every adjacent Desert and Desert Hills tiles. Mines receive -1 [ICON_PRODUCTION] Production and +4 [ICON_GOLD] Gold. Mines over Luxury resources provide +2 [ICON_Gold] Gold. May purchase Commercial Hub district buildings with [ICON_Faith] Faith. -15% [ICON_PRODUCTION] Production toward constructing buildings or training units."),
    ("LOC_DISTRICT_SUGUBA_DESCRIPTION",                                                     "A district unique to Mali specializing in finance and trade that replaces the Commercial Hub. Units, Buildings, and Districts are 10% cheaper to purchase with [ICON_GOLD] Gold and [ICON_FAITH] Faith in this City.[NEWLINE][NEWLINE]+1 [ICON_Gold] Gold bonus for each adjacent Holy Site. +2 [ICON_Gold] Gold bonus from a tile containing a River edge. +1 [ICON_Gold] Gold bonus for every two adjacent district tiles."),
    ("LOC_TRAIT_LEADER_SAHEL_MERCHANTS_DESCRIPTION",                                        "International [ICON_TradeRoute] Trade Routes gain +1 [ICON_GOLD] Gold for every flat Desert or Desert hills tile in the origin city. Receive +1 [ICON_TradeRoute] Trade Capacity every time you enter a Golden Age. Earn extra 5 [ICON_GOLD] Gold for each era score earned."), 
    ("LOC_TRAIT_LEADER_JOAO_III_DESCRIPTION",                                               "All units receive +1 sight. +2 [ICON_TradeRoute] Trade Route capacity when meeting the first civilization. Open Borders with all city-states."), 
    ("LOC_BELIEF_CAPELLANI_DL_DESCRIPTION",                                                 "Religious units newly obtained from cities following this religion can provide +3 [ICON_Strength] Combat Strength to the Combat Units in the same tile (not retroactive).");

-- --------------------------------------------------------------------------------
-- -- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                    Text)
values
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_GARRISON_COMMANDER_DESCRIPTION",                "城市领土内的单位防御时可+3 [ICON_Strength] 战斗力。城市每回合获得一次额外的 [ICON_Ranged] 远程攻击机会。建造防御性建筑时加速100%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION",               "开发 [ICON_RESOURCE_HORSES] 马资源的牧场每回合额外+3 [ICON_RESOURCE_HORSES] 马资源积累。每次您训练一个轻骑兵或萨卡弓骑手，都可以再获得一个轻骑兵或萨卡弓骑手。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_AMABUTHO_DESCRIPTION",                                "可更早组建军团（需雇佣兵市政）和军队（需民族主义市政）。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_AMBIORIX_DESCRIPTION",                                "生产出一个非平民单位时，您的文明获得等同于该单位生产力花费20%的 [ICON_CULTURE] 文化值。近战、抗骑兵和远程单位每与一个其他单位相邻（无论该单位属于哪个文明），便+1 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_TRIEU_DESCRIPTION",                                   "在雨林、沼泽或树林单元格中战斗的单位+3 [ICON_Strength] 战斗力。如果单位在回合开始时处于这些地貌中，则+1 [ICON_Movement] 移动力。而如果这些地貌单元格是您的领土，则以上加成均加倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MUTAL_DESCRIPTION",                                   "揭示出生点6个单元格内的地块。[ICON_Capital] 首都6个单元格范围内城市所有产出+10%，且建成时将获得1名建造者。[ICON_Capital] 首都9个单元格范围内6个单元格外的的非首都城市所有产出不变。其他非首都城市所有产出-15%。[ICON_Capital] 首都6个单元格范围内的单位+3 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",                           "[ICON_TechBoosted] 尤里卡提供科技的84%的 [ICON_SCIENCE] 科技值。每回合的 [ICON_SCIENCE] 科技值-50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ADVENTURES_ENKIDU_EXPANSION2_DESCRIPTION",            "与同一个敌人交战时，如果他们与其盟友位于5个单元格以内，则共享掠夺奖励和战斗经验值。其同盟针对同一个敌人作战可获得同盟点数。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SEOWON_HD_DESCRIPTION",                                   "朝鲜特色区域，替代“学院”。+3 [Icon_Science] 科技值。拥有更多的专家槽位。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HWARANG_DESCRIPTION",                                 "首都或派遣了总督的城市获得+2 [ICON_Amenities] 宜居度，+3 [Icon_Housing] 住房和+20忠诚度。非首都且未派遣总督的城市-2 [ICON_Amenities] 宜居度，-8忠诚度，-50%全部产出。 有书院的城市建造区域和建筑+25% [Icon_Production] 生产力；有图书馆的城市+15% [ICON_Food] 食物和 [Icon_production] 生产力；有大学的城市，所有区域对应产出类型的相邻加成+100%；有实验室的城市所有产出+10%且每个人口额外1点全部产出。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_EL_ESCORIAL_EXPANSION2_DESCRIPTION",                  "审判官可额外进行一次“清除异教”操作。审判官能完全铲除其他宗教的势力。与信仰其他宗教的单位进行战斗时，战斗和宗教单位+3 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LAUTARO_ABILITY_DESCRIPTION_ALT",                     "与自由城市或处在黄金/英雄时代中的文明作战时+5 [ICON_Strength] 战斗力。在敌方城市边界中击杀敌方单位后，将使此城损失20点忠诚度（如此文明正处在黄金/英雄时代中，则损失40点忠诚度）。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LAST_PROPHET_DESCRIPTION",                      "当倒数第二个 [ICON_GreatProphet] 预言家被招募后（如果您尚未获得 [ICON_GreatProphet] 大预言家），自动获得最后一个大预言家。每座信奉阿拉伯宗教的外国城市+2 [ICON_Science] 科技值。"), 
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_CITADEL_CIVILIZATION_DESCRIPTION",                    "如他们在过去10回合内收到宣战书（或在过去20回合内解放一座城市），则+50% [ICON_Production] 生产力。牧场+1 [Icon_Food] 食物"), 
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MALI_GOLD_DESERT_DESCRIPTION",                  "每个相邻沙漠或沙漠丘陵单元格为市中心提供+1 [ICON_FAITH] 信仰值与+1 [ICON_FOOD] 食物。矿山-1 [ICON_PRODUCTION] 生产力，但+4 [ICON_GOLD] 金币，奢侈品资源矿产提供+2 [ICON_Gold] 金币，可用 [ICON_Faith] 信仰值购买商业中心区域建筑。建造建筑或生产单位时-15% [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SUGUBA_DESCRIPTION",                                      "马里特色区域，专精于经济与贸易，取代商业中心。使用 [ICON_GOLD] 金币和 [ICON_FAITH] 信仰值在此城中购买单位、建筑和区域时，花费-10%。[NEWLINE][NEWLINE] 与普通商业中心不同的是，其每相邻1个圣地获得+1 [ICON_Gold] 金币加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SAHEL_MERCHANTS_DESCRIPTION",                         "起始城市中的每个沙漠或沙漠丘陵单元格为国际 [ICON_TradeRoute] 贸易路线提供+1 [ICON_GOLD] 金币。文明进入黄金时代后可获得+1 [ICON_TradeRoute] 贸易路线容量。每获得1点时代分，额外获得5 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_JOAO_III_DESCRIPTION",                                "所有单位+1视野。与第一个文明相遇时+2 [ICON_TradeRoute] 贸易路线容量。对所有城邦开放边界。"), 
    ("zh_Hans_CN",  "LOC_BELIEF_CAPELLANI_DL_DESCRIPTION",                                  "强化后从信仰此宗教的城市中新获得的宗教单位为同一单元格军事单位+3 [ICON_Strength] 战斗力。");
