--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                 Text)
values
    ("LOC_LEADER_TRAIT_AKKAD_DESCRIPTION",                "May purchase support units with [ICON_Faith] Faith. Land units can escort moving civilian and support units at their [ICON_Movement] Movement speed. "),
    ("LOC_CIVILIZATION_AKKAD_BONUS",                      "May purchase support units with [ICON_Faith] Faith. Land units can escort moving civilian and support units at their [ICON_Movement] Movement speed. "),
    ("LOC_LEADER_TRAIT_KABUL_DESCRIPTION",                "Your units receive 50% more experience from battles they initiate."),
    ("LOC_CIVILIZATION_KABUL_BONUS",                      "Your units receive 50% more experience from battles they initiate."),
    ("LOC_LEADER_TRAIT_AUCKLAND_DESCRIPTION",             "Fishing Boats +1 [ICON_Production] Production. +1 extra [ICON_Production] Production if the player has entered Industrial Era. +2 [Icon_production] Production from each building inside Harbor District."),
    ("LOC_CIVILIZATION_AUCKLAND_BONUS",                   "Fishing Boats +1 [ICON_Production] Production. +1 extra [ICON_Production] Production if the player has entered Industrial Era. +2 [Icon_production] Production from each building inside Harbor District."),
    ("LOC_LEADER_TRAIT_RAPA_NUI_DESCRIPTION",             "Your Builders can now make Moai improvements.[NEWLINE][NEWLINE]Moai provide +1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every 2 adjacent Moai. +2 [ICON_Culture] Culture if on or adjacent to a Volcanic Soil tile. +2 [ICON_Culture] Culture if adjacent to a Coast or Lake tile . Additional [ICON_Culture] Culture and [ICON_Tourism] Tourism as you advance through the Civics and Technology Tree. Can be built on Plains, Plains Hills, Grassland, Grassland Hills, or Volcanic Soil. Can only be placed adjacent to a Lake or Coast tile."),
    ("LOC_CIVILIZATION_RAPA_NUI_BONUS",                   "Your Builders can now make Moai improvements.[NEWLINE][NEWLINE]Moai provide +1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every 2 adjacent Moai. +2 [ICON_Culture] Culture if on or adjacent to a Volcanic Soil tile. +2 [ICON_Culture] Culture if adjacent to a Coast or Lake tile . Additional [ICON_Culture] Culture and [ICON_Tourism] Tourism as you advance through the Civics and Technology Tree. Can be built on Plains, Plains Hills, Grassland, Grassland Hills, or Volcanic Soil. Can only be placed adjacent to a Lake or Coast tile."),
    ("LOC_LEADER_TRAIT_LA_VENTA_EXPANSION2_DESCRIPTION",  "Your Builders can now make Colossal Head improvements.[NEWLINE][NEWLINE]Colossal Heads provide +2 [ICON_Faith] Faith. +1 [ICON_Faith] Faith for every 2 adjacent Rainforest or for every adjacent Rainforest once Humanism is discovered. +1 [ICON_Faith] Faith for every 2 adjacent Woods or for every adjacent Woods once Humanism is discovered. [ICON_TOURISM] Tourism from [ICON_FAITH] Faith once Flight is discovered. Can only be built on Forest or Jungles."),
    ("LOC_CIVILIZATION_LA_VENTA_BONUS_XP2",               "Your Builders can now make Colossal Head improvements.[NEWLINE][NEWLINE]Colossal Heads provide +2 [ICON_Faith] Faith. +1 [ICON_Faith] Faith for every 2 adjacent Rainforest or for every adjacent Rainforest once Humanism is discovered. +1 [ICON_Faith] Faith for every 2 adjacent Woods or for every adjacent Woods once Humanism is discovered. [ICON_TOURISM] Tourism from [ICON_FAITH] Faith once Flight is discovered. Can only be built on Forest or Jungles."),
    ("LOC_LEADER_TRAIT_KANDY_DESCRIPTION",                "Earn +100% [ICON_Faith] Faith from all [ICON_GreatWork_Relic] Relics."),
    ("LOC_CIVILIZATION_KANDY_BONUS",                      "Earn +100% [ICON_Faith] Faith from all [ICON_GreatWork_Relic] Relics."),
    ("LOC_LEADER_TRAIT_KUMASI_DESCRIPTION",               "Your [ICON_TradeRoute] Trade Routes to any city-state provide +2 [ICON_Culture] Culture and +1 [ICON_Gold] Gold for every specialty district in the origin city."),
    ("LOC_CIVILIZATION_KUMASI_BONUS",                     "Your [ICON_TradeRoute] Trade Routes to any city-state provide +2 [ICON_Culture] Culture and +1 [ICON_Gold] Gold for every specialty district in the origin city."),
    ("LOC_LEADER_TRAIT_CHINGUETTI_DESCRIPTION",           "International and domestic [ICON_TradeRoute] Trade Routes receive +0.3 [ICON_FAITH] Faith for every follower in this city, of your founded or majority religion. +3 [Icon_Faith] Faith to all your Trade Routes."),
    ("LOC_CIVILIZATION_CHINGUETTI_BONUS",                 "International and domestic [ICON_TradeRoute] Trade Routes receive +0.3 [ICON_FAITH] Faith for every follower in this city, of your founded or majority religion. +3 [Icon_Faith] Faith to all your Trade Routes."),
    ("LOC_LEADER_TRAIT_NGAZARGAMU_DESCRIPTION",           "Land combat or Support units are 20% cheaper to purchase with [ICON_GOLD] Gold (or [ICON_Faith] Faith if allowed) for each Encampment district building in that city."),
    ("LOC_CIVILIZATION_NGAZARGAMU_BONUS",                 "Land combat or Support units are 20% cheaper to purchase with [ICON_GOLD] Gold (or [ICON_Faith] Faith if allowed) for each Encampment district building in that city."),
    ("LOC_LEADER_TRAIT_TARUGA_DESCRIPTION",               "+5% [ICON_SCIENCE] Science in all cities for each different improved Strategic resource they have."),
    ("LOC_CIVILIZATION_TARUGA_BONUS",                     "+5% [ICON_SCIENCE] Science in all cities for each different improved Strategic resource they have."),
    ("LOC_LEADER_TRAIT_VALLETTA_DESCRIPTION",             "City Center buildings and Encampment district buildings can be bought with [ICON_Faith] Faith. Purchasing Ancient, Medieval, and Renaissance Walls (including Tsikhe) is 50% cheaper, but they can only be bought with [ICON_Faith] Faith."),
    ("LOC_CIVILIZATION_VALLETTA_BONUS",                   "City Center buildings and Encampment district buildings can be bought with [ICON_Faith] Faith. Purchasing Ancient, Medieval, and Renaissance Walls (including Tsikhe) is 50% cheaper, but they can only be bought with [ICON_Faith] Faith."),
    ("LOC_LEADER_TRAIT_SINGAPORE_DESCRIPTION",            "Your International [ICON_TradeRoute] Trade Routes gain +2 [ICON_Production] Production. Your [ICON_TradeRoute] Trade Routes to an Ally's city or vassal city-state gain +4 [ICON_Gold] Gold."),
    ("LOC_CIVILIZATION_SINGAPORE_BONUS",                  "Your International [ICON_TradeRoute] Trade Routes gain +2 [ICON_Production] Production. Your [ICON_TradeRoute] Trade Routes to an Ally's city or vassal city-state gain +4 [ICON_Gold] Gold."),
    ("LOC_LEADER_TRAIT_VATICAN_CITY_DESCRIPTION",         "+2 [ICON_Culture] Culture and +2 [ICON_FAITH] Faith from each [ICON_GreatWork_WRITING] Great Work of Writing, [ICON_GreatWork_Sculpture] Great Work of Sculpture, [ICON_GreatWork_Portrait] Great Work of Portrait, [ICON_GreatWork_Landscape] Great Work of Landscape and [ICON_GreatWork_Religious] Great Work of Religious. +3 [ICON_Culture] Culture from each [ICON_GreatWork_RELIC] Relic."),
    ("LOC_CIVILIZATION_VATICAN_CITY_BONUS",               "+2 [ICON_Culture] Culture and +2 [ICON_FAITH] Faith from each [ICON_GreatWork_WRITING] Great Work of Writing, [ICON_GreatWork_Sculpture] Great Work of Sculpture, [ICON_GreatWork_Portrait] Great Work of Portrait, [ICON_GreatWork_Landscape] Great Work of Landscape and [ICON_GreatWork_Religious] Great Work of Religious. +3 [ICON_Culture] Culture from each [ICON_GreatWork_RELIC] Relic."),
    ("LOC_LEADER_TRAIT_BABYLON_DESCRIPTION",              "+3 [ICON_SCIENCE] Science from each [ICON_GreatWork_WRITING] Great Work of Writing, [ICON_GreatWork_RELIC] Relic and [ICON_GreatWork_Artifact] Artifact."),
    ("LOC_CIVILIZATION_BABYLON_BONUS",                    "+3 [ICON_SCIENCE] Science from each [ICON_GreatWork_WRITING] Great Work of Writing, [ICON_GreatWork_RELIC] Relic and [ICON_GreatWork_Artifact] Artifact."),
    ("LOC_LEADER_TRAIT_FEZ_DESCRIPTION",                  "+2 [ICON_SCIENCE] Science from each Shrine, Temple and Religious building."),
    ("LOC_CIVILIZATION_FEZ_BONUS",                        "+2 [ICON_SCIENCE] Science from each Shrine, Temple and Religious building."),
    ("LOC_LEADER_TRAIT_HATTUSA_EXPANSION2_DESCRIPTION",   "Provides you with 2 of each Strategic resource per turn that you have revealed."),
    ("LOC_CIVILIZATION_HATTUSA_BONUS_XP2",                "Provides you with 2 of each Strategic resource per turn that you have revealed."),
    ("LOC_LEADER_TRAIT_NALANDA_DESCRIPTION",              "Your Builders can now make Mahavihara improvements.[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] Science and +1 [Icon_Housing] Housing. +1 [ICON_Science] Science for every adjacent Campus district or Holy Site district. After researching Scientific Theory receive an additional +1 [Icon_Science] Science for every adjacent Campus. Must be built on flat terrain not adjacent to another Mahavihara."),
    ("LOC_CIVILIZATION_NALANDA_BONUS",                    "Your Builders can now make Mahavihara improvements.[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] Science and +1 [Icon_Housing] Housing. +1 [ICON_Science] Science for every adjacent Campus district or Holy Site district. After researching Scientific Theory receive an additional +1 [Icon_Science] Science for every adjacent Campus. Must be built on flat terrain not adjacent to another Mahavihara."),
    ("LOC_LEADER_TRAIT_ANTIOCH_DESCRIPTION",              "Your [ICON_TradeRoute] Trade Routes to foreign cities earn +2 [ICON_Gold] Gold for each Luxury resource at the destination."),
    ("LOC_CIVILIZATION_ANTIOCH_BONUS",                    "Your [ICON_TradeRoute] Trade Routes to foreign cities earn +2 [ICON_Gold] Gold for each Luxury resource at the destination."),
    ("LOC_LEADER_TRAIT_HUNZA_DESCRIPTION",                "Your [ICON_TradeRoute] Trade Routes generate +2 [ICON_Gold] Gold for every 5 tiles they travel."),
    ("LOC_CIVILIZATION_HUNZA_BONUS",                      "Your [ICON_TradeRoute] Trade Routes generate +2 [ICON_Gold] Gold for every 5 tiles they travel."),
    ("LOC_LEADER_TRAIT_JAKARTA_DESCRIPTION",              "Your districts and wonders on or next to Coast or Lake tiles provide +4 [ICON_Gold] Gold."),
    ("LOC_CIVILIZATION_JAKARTA_BONUS",                    "Your districts and wonders on or next to Coast or Lake tiles provide +4 [ICON_Gold] Gold."),
    ("LOC_LEADER_TRAIT_MUSCAT_DESCRIPTION",               "+1 [ICON_Amenities] Amenity in cities with a Commercial Hub district.+1 [ICON_Amenities] Amenity in cities with a Harbor district."),
    ("LOC_CIVILIZATION_MUSCAT_BONUS",                     "+1 [ICON_Amenities] Amenity in cities with a Commercial Hub district.+1 [ICON_Amenities] Amenity in cities with a Harbor district."),
    ("LOC_LEADER_TRAIT_SAMARKAND_DESCRIPTION",            "Your Builders can now make Trading Dome improvements.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold. +1 [ICON_Gold] Gold for every adjacent Luxury resource. Your outgoing international [ICON_TradeRoute] Trade Routes grant +2 [ICON_GOLD] Gold per Trading Dome at the origin. Cannot be built next to another Trading Dome."),
    ("LOC_CIVILIZATION_SAMARKAND_BONUS",                  "Your Builders can now make Trading Dome improvements.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold. +1 [ICON_Gold] Gold for every adjacent Luxury resource. Your outgoing international [ICON_TradeRoute] Trade Routes grant +2 [ICON_GOLD] Gold per Trading Dome at the origin. Cannot be built next to another Trading Dome."),
    ("LOC_LEADER_TRAIT_ARMAGH_EXPANSION2_DESCRIPTION",    "Your Builders can now make Monastery improvements.[NEWLINE][NEWLINE]Monasteries provide +2 [ICON_Faith] Faith. +15 HP healing for friendly religious unit on this tile that has not attacked this turn. +1 [ICON_FAITH] Faith for every adjacent Districts. +2 [ICON_FAITH] Faith for every adjacent Districts once Divine Right is discovered. Provides +1 [ICON_HOUSING] Housing. Receive an additional [ICON_HOUSING] Housing once Colonialism is discovered. Cannot be built next to another Monastery."),
    ("LOC_CIVILIZATION_ARMAGH_BONUS_XP2",                 "Your Builders can now make Monastery improvements.[NEWLINE][NEWLINE]Monasteries provide +2 [ICON_Faith] Faith. +15 HP healing for friendly religious unit on this tile that has not attacked this turn. +1 [ICON_FAITH] Faith for every adjacent Districts. +2 [ICON_FAITH] Faith for every adjacent Districts once Divine Right is discovered. Provides +1 [ICON_HOUSING] Housing. Receive an additional [ICON_HOUSING] Housing once Colonialism is discovered. Cannot be built next to another Monastery."),
    ("LOC_LEADER_TRAIT_LISBON_DESCRIPTION",               "Your Trader units are immune to being plundered on water tiles. [ICON_TradeRoute] Trade Routes between multiple continents receive bonus +6 [ICON_Gold] Gold for routes to other civilizations, and bonus +1 [ICON_Food] Food and +1 [ICON_Production] Production for routes between your own cities."),
    ("LOC_CIVILIZATION_LISBON_BONUS",                     "Your Trader units are immune to being plundered on water tiles. [ICON_TradeRoute] Trade Routes between multiple continents receive bonus +6 [ICON_Gold] Gold for routes to other civilizations, and bonus +1 [ICON_Food] Food and +1 [ICON_Production] Production for routes between your own cities."),
    ("LOC_LEADER_TRAIT_MOHENJO_DARO_DESCRIPTION",         "Your cities gain +1 [ICON_Housing] housing. Your cities have full [ICON_Housing] Housing from water, as if they were all next to a River."),
    ("LOC_CIVILIZATION_MOHENJO_DARO_BONUS",               "Your cities gain +1 [ICON_Housing] housing. Your cities have full [ICON_Housing] Housing from water, as if they were all next to a River."),
    ("LOC_LEADER_TRAIT_GRANADA_EXPANSION2_DESCRIPTION",   "Your Builders can now make Alcázar improvements.[NEWLINE][NEWLINE]Alcázars provide +2 [ICON_Culture] Culture. Provides [ICON_SCIENCE] Science equal to 75% of the tile's Appeal. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification. Provides [ICON_TOURISM] Tourism after researching Flight. Cannot be built next to another Alcázar."),
    ("LOC_CIVILIZATION_GRANADA_BONUS_XP2",                "Your Builders can now make Alcázar improvements.[NEWLINE][NEWLINE]Alcázars provide +2 [ICON_Culture] Culture. Provides [ICON_SCIENCE] Science equal to 75% of the tile's Appeal. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification. Provides [ICON_TOURISM] Tourism after researching Flight. Cannot be built next to another Alcázar."),
    ("LOC_LEADER_TRAIT_CARDIFF_DESCRIPTION",              "Cities receive +3 [ICON_Power] Power for every Harbor building."),
    ("LOC_CIVILIZATION_CARDIFF_BONUS",                    "Cities receive +3 [ICON_Power] Power for every Harbor building."),
    ("LOC_LEADER_TRAIT_PRESLAV_DESCRIPTION",              "+2 [ICON_SCIENCE] Science from each Encampment, Barracks, Stable, Armory and Military Academy."),
    ("LOC_CIVILIZATION_PRESLAV_BONUS_XP1",                "+2 [ICON_SCIENCE] Science from each Encampment, Barracks, Stable, Armory and Military Academy."),
    ("LOC_LEADER_TRAIT_AYUTTHAYA_DESCRIPTION",            "Theater, Holy Site, Commercial Hub and Wonders provide 2 [ICON_CULTURE] Culture if they are located near river."),
    ("LOC_CIVILIZATION_AYUTTHAYA_BONUS",                  "Theater, Holy Site, Commercial Hub and Wonders provide 2 [ICON_CULTURE] Culture if they are located near river."),
    ("LOC_LEADER_TRAIT_VILNIUS_DESCRIPTION",              "Increase 50% of theater district adjacent bonus and each ally level with other player provide extra 50% increase of theater district adjacent bonus."),
    ("LOC_CIVILIZATION_VILNIUS_BONUS_XP1",                "Increase 50% of theater district adjacent bonus and each ally level with other player provide extra 50% increase of theater district adjacent bonus."),
    ("LOC_LEADER_TRAIT_CAGUANA_DESCRIPTION",              "Unlocks the Builder ability to construct a Batey.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every adjacent Bonus Resource and Entertainment Complex (increased to +2 [Icon_Culture] Culture when Humanism is discovered). Provides [Icon_Tourism] Tourism after researching Flight. Cannot be built adjacent to another Batey or on Hills."),
    ("LOC_CIVILIZATION_CAGUANA_BONUS",                    "Unlocks the Builder ability to construct a Batey.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every adjacent Bonus Resource and Entertainment Complex (increased to +2 [Icon_Culture] Culture when Humanism is discovered). Provides [Icon_Tourism] Tourism after researching Flight. Cannot be built adjacent to another Batey or on Hills."),
    ("LOC_LEADER_TRAIT_NAN_MADOL_DESCRIPTION",            "Your Districts(except City center) and Wonders on or next to Coast or Lake tiles provide +2 [ICON_Culture] Culture."),
    ("LOC_CIVILIZATION_NAN_MADOL_BONUS",                  "Your Districts(except City center) and Wonders on or next to Coast or Lake tiles provide +2 [ICON_Culture] Culture.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_AKKAD_DESCRIPTION",                "可以使用信仰购买支援单位。陆地战斗单位可利用自身的 [ICON_Movement] 移动力护送平民和支援单位。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_AKKAD_BONUS",                      "可以使用信仰购买支援单位。陆地战斗单位可利用自身的 [ICON_Movement] 移动力护送平民和支援单位。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_KABUL_DESCRIPTION",                "您的单位由他们发起的战斗中获得额外50%经验值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_KABUL_BONUS",                      "您的单位由他们发起的战斗中获得额外50%经验值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_AUCKLAND_DESCRIPTION",             "渔船+1 [ICON_PRODUCTION] 生产力。若玩家进入工业时代则额外 +1 [ICON_Production] 生产力。港口内每级建筑+2 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_AUCKLAND_BONUS",                   "渔船+1 [ICON_PRODUCTION] 生产力。若玩家进入工业时代则额外 +1 [ICON_Production] 生产力。港口内每级建筑+2 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_RAPA_NUI_DESCRIPTION",             "建造者可以建造摩艾石像改良设施。[NEWLINE][NEWLINE]摩艾石像提供+1 [ICON_Culture] 文化值。每2个相邻的摩艾石像+1 [ICON_Culture] 文化值。在火山土单元格之上或与其相邻时，+2 [ICON_Culture] 文化值。与海岸或湖泊单元格相邻时，+2 [ICON_Culture] 文化值。随着市政与科技树的发展，可获得额外的 [ICON_Culture] 文化值与 [ICON_Tourism] 旅游业绩。可建在平原、平原丘陵、草原、草原丘陵或火山土之上。只能建在相邻湖泊或近海的单元格上。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_RAPA_NUI_BONUS",                   "建造者可以建造摩艾石像改良设施。[NEWLINE][NEWLINE]摩艾石像提供+1 [ICON_Culture] 文化值。每2个相邻的摩艾石像+1 [ICON_Culture] 文化值。在火山土单元格之上或与其相邻时，+2 [ICON_Culture] 文化值。与海岸或湖泊单元格相邻时，+2 [ICON_Culture] 文化值。随着市政与科技树的发展，可获得额外的 [ICON_Culture] 文化值与 [ICON_Tourism] 旅游业绩。可建在平原、平原丘陵、草原、草原丘陵或火山土之上。只能建在相邻湖泊或近海的单元格上。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_LA_VENTA_EXPANSION2_DESCRIPTION",  "建造者现在能够建造巨神头像改良设施。[NEWLINE][NEWLINE]+2 [ICON_Faith] 信仰值。与每2个雨林相邻+1信仰值，而解锁“人文主义”市政后与每1个雨林相邻便能+1信仰值。与每2个树林相邻+1信仰值，而解锁“人文主义”市政后与每1个树林相邻便能+1信仰值。研究“飞行”科技后可通过 [ICON_FAITH] 信仰值获得 [ICON_TOURISM] 旅游业绩。仅可建造在森林或雨林上。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_LA_VENTA_BONUS_XP2",               "建造者现在能够建造巨神头像改良设施。[NEWLINE][NEWLINE]+2 [ICON_Faith] 信仰值。与每2个雨林相邻+1信仰值，而解锁“人文主义”市政后与每1个雨林相邻便能+1信仰值。与每2个树林相邻+1信仰值，而解锁“人文主义”市政后与每1个树林相邻便能+1信仰值。研究“飞行”科技后可通过 [ICON_FAITH] 信仰值获得 [ICON_TOURISM] 旅游业绩。仅可建造在森林或雨林上。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_KANDY_DESCRIPTION",                "从所有 [ICON_GreatWork_Relic] 遗物中获得的 [ICON_Faith] 信仰值+100%。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_KANDY_BONUS",                      "从所有 [ICON_GreatWork_Relic] 遗物中获得的 [ICON_Faith] 信仰值+100%。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_KUMASI_DESCRIPTION",               "您通往任何城邦的 [ICON_TradeRoute] 贸易路线都为起源城市的每个专业化区域+2 [ICON_Culture] 文化值和+1 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_KUMASI_BONUS",                     "您通往任何城邦的 [ICON_TradeRoute] 贸易路线都为起源城市的每个专业化区域+2 [ICON_Culture] 文化值和+1 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_CHINGUETTI_DESCRIPTION",           "此城中每有1位您所创建（或主流）宗教的信徒，国际与国内 [ICON_TradeRoute] 贸易路线提供的 [ICON_FAITH] 信仰值便+0.3。所有商路+3 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_CHINGUETTI_BONUS",                 "此城中每有1位您所创建（或主流）宗教的信徒，国际与国内 [ICON_TradeRoute] 贸易路线提供的 [ICON_FAITH] 信仰值便+0.3。所有商路+3 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_NGAZARGAMU_DESCRIPTION",           "城市中每拥有1个“军营”内建筑，购买陆地战斗或支援单位所需的 [ICON_GOLD] 金币便减少20%，若可用 [ICON_Faith] 信仰购买，则费用也减少20%。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_NGAZARGAMU_BONUS",                 "城市中每拥有1个“军营”内建筑，购买陆地战斗或支援单位所需的 [ICON_GOLD] 金币便减少20%，若可用 [ICON_Faith] 信仰购买，则费用也减少20%。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_TARUGA_DESCRIPTION",               "对于所有城市，其3个单元格内每拥有一种已改良的战略资源，便+5% [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_TARUGA_BONUS",                     "对于所有城市，其3个单元格内每拥有一种已改良的战略资源，便+5% [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_VALLETTA_DESCRIPTION",             "[ICON_Faith] 信仰值可用来购买市中心建筑和军营区的建筑。购买远古、中世纪、文艺复兴城墙（包括堡垒）的费用降低50%，但只能通过 [ICON_Faith] 信仰值购买。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_VALLETTA_BONUS",                   "[ICON_Faith] 信仰值可用来购买市中心建筑和军营区的建筑。购买远古、中世纪、文艺复兴城墙（包括堡垒）的费用降低50%，但只能通过 [ICON_Faith] 信仰值购买。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_SINGAPORE_DESCRIPTION",            "您的国际 [ICON_TradeRoute] 贸易路线+2 [ICON_Production] 生产力。您通往盟友城市或宗主城邦的[ICON_TradeRoute] 贸易路线+4 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_SINGAPORE_BONUS",                  "您的国际 [ICON_TradeRoute] 贸易路线+2 [ICON_Production] 生产力。您通往盟友城市或宗主城邦的[ICON_TradeRoute] 贸易路线+4 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_VATICAN_CITY_DESCRIPTION",         "每本 [ICON_GreatWork_WRITING] 著作巨作+2 [ICON_Culture] 文化值和+2 [ICON_FAITH] 信仰值。每件 [ICON_GreatWork_Sculpture] 雕塑、 [ICON_GreatWork_Portrait] 肖像、 [ICON_GreatWork_Landscape] 风景和 [ICON_GreatWork_Religious] 宗教艺术巨作+2 [ICON_Culture] 文化值和+2 [ICON_FAITH] 信仰值。每件 [ICON_GreatWork_RELIC] 遗物+3 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_VATICAN_CITY_BONUS",               "每本 [ICON_GreatWork_WRITING] 著作巨作+2 [ICON_Culture] 文化值和+2 [ICON_FAITH] 信仰值。每件 [ICON_GreatWork_Sculpture] 雕塑、 [ICON_GreatWork_Portrait] 肖像、 [ICON_GreatWork_Landscape] 风景和 [ICON_GreatWork_Religious] 宗教艺术巨作+2 [ICON_Culture] 文化值和+2 [ICON_FAITH] 信仰值。每件 [ICON_GreatWork_RELIC] 遗物+3 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_BABYLON_DESCRIPTION",              "所有的 [ICON_GreatWork_WRITING] 著作巨作、[ICON_GreatWork_RELIC] 遗物和 [ICON_GreatWork_Artifact] 文物+3 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_BABYLON_BONUS",                    "所有的 [ICON_GreatWork_WRITING] 著作巨作、[ICON_GreatWork_RELIC] 遗物和 [ICON_GreatWork_Artifact] 文物+3 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_FEZ_DESCRIPTION",                  "为城市中的每个圣地建筑+2 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_FEZ_BONUS",                        "为城市中的每个圣地建筑+2 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_HATTUSA_EXPANSION2_DESCRIPTION",   "每回合提供2份文明已解锁战略资源。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_HATTUSA_BONUS_XP2",                "每回合提供2份文明已解锁战略资源。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_NALANDA_DESCRIPTION",              "您的建造者现在可以建造大寺改良设施。[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] 科技值、+1 [Icon_Housing] 住房。每与1座学院或圣地区域相邻，则+1 [ICON_Science] 科技值。研究完“科学理论”之后，每与1座学院相邻则额外+1 [Icon_Science] 科技值。必须建在平坦地貌上，不能与其他大寺相邻。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_NALANDA_BONUS",                    "您的建造者现在可以建造大寺改良设施。[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] 科技值、+1 [Icon_Housing] 住房。每与1座学院或圣地区域相邻，则+1 [ICON_Science] 科技值。研究完“科学理论”之后，每与1座学院相邻则额外+1 [Icon_Science] 科技值。必须建在平坦地貌上，不能与其他大寺相邻。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_ANTIOCH_DESCRIPTION",              "您通往海外城市的 [ICON_TradeRoute] 贸易路线可从目的地的每个奢侈品资源+2 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_ANTIOCH_BONUS",                    "您通往海外城市的 [ICON_TradeRoute] 贸易路线可从目的地的每个奢侈品资源+2 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_HUNZA_DESCRIPTION",                "您的 [ICON_TradeRoute] 贸易路线每经过5个单元格，其提供的 [ICON_Gold] 金币便+2。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_HUNZA_BONUS",                      "您的 [ICON_TradeRoute] 贸易路线每经过5个单元格，其提供的 [ICON_Gold] 金币便+2。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_JAKARTA_DESCRIPTION",              "您境内位于或与海岸湖泊单元格相邻的区域和奇观+4 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_JAKARTA_BONUS",                    "您境内位于或与海岸湖泊单元格相邻的区域和奇观+4 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_MUSCAT_DESCRIPTION",               "商业中心和港口区域均可为城市提供+1 [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_MUSCAT_BONUS",                     "商业中心和港口区域均可为城市提供+1 [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_SAMARKAND_DESCRIPTION",            "您的建造者现在能够建造圆顶市集改良设施。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币。每与一个奢侈品资源相邻则+1 [ICON_Gold] 金币。起源城市每有一座圆顶市集，对外国际贸易 [ICON_TradeRoute] 路线提供的 [ICON_GOLD] 金币便+2。无法建在另一座圆顶市集旁。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_SAMARKAND_BONUS",                  "您的建造者现在能够建造圆顶市集改良设施。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币。每与一个奢侈品资源相邻则+1 [ICON_Gold] 金币。起源城市每有一座圆顶市集，对外国际贸易 [ICON_TradeRoute] 路线提供的 [ICON_GOLD] 金币便+2。无法建在另一座圆顶市集旁。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_ARMAGH_EXPANSION2_DESCRIPTION",    "建造者现在能够建造修道院改良设施。[NEWLINE][NEWLINE]修道院提供+2 [ICON_Faith] 信仰值。此单元格上的友方宗教单位生命值恢复+15（前提是其当前回合未发动攻击）。每1个相邻的区域使其+1 [ICON_FAITH] 信仰值。解锁“王权神授”市政后每1个相邻的区域使其+2 [ICON_FAITH] 信仰值。提供+1 [ICON_HOUSING] 住房。解锁“殖民主义”市政后获得额外1点 [ICON_HOUSING] 住房。无法建在另一座修道院旁。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_ARMAGH_BONUS_XP2",                 "建造者现在能够建造修道院改良设施。[NEWLINE][NEWLINE]修道院提供+2 [ICON_Faith] 信仰值。此单元格上的友方宗教单位生命值恢复+15（前提是其当前回合未发动攻击）。每1个相邻的区域使其+1 [ICON_FAITH] 信仰值。解锁“王权神授”市政后每1个相邻的区域使其+2 [ICON_FAITH] 信仰值。提供+1 [ICON_HOUSING] 住房。解锁“殖民主义”市政后获得额外1点 [ICON_HOUSING] 住房。无法建在另一座修道院旁。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_LISBON_DESCRIPTION",               "您的商人单位对水域单元格的掠夺免疫。不同大陆之间的 [ICON_TradeRoute] 贸易路线将获得以下加成：通往其他文明的贸易路线获得+6 [ICON_Gold] 金币加成；本国城市间的贸易路线获得+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力加成。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_LISBON_BONUS",                     "您的商人单位对水域单元格的掠夺免疫。不同大陆之间的 [ICON_TradeRoute] 贸易路线将获得以下加成：通往其他文明的贸易路线获得+6 [ICON_Gold] 金币加成；本国城市间的贸易路线获得+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力加成。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_MOHENJO_DARO_DESCRIPTION",         "为您的所有城市+1 [ICON_Housing] 住房。无论您的城市是否相邻淡水，水源提供的基础 [ICON_Housing] 住房均与相邻淡水时相同。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_MOHENJO_DARO_BONUS",               "为您的所有城市+1 [ICON_Housing] 住房。无论您的城市是否相邻淡水，水源提供的基础 [ICON_Housing] 住房均与相邻淡水时相同。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_GRANADA_EXPANSION2_DESCRIPTION",   "建造者现在能够建造阿卡萨城堡改良设施。[NEWLINE][NEWLINE]阿卡萨城堡提供+2 [ICON_Culture] 文化值。提供等于单元格魅力75%的 [ICON_SCIENCE] 科技值。占领单位 [ICON_Strength] 防御力+4，并自动获得2回合防御工事。研究“飞行”科技后可提供 [ICON_TOURISM] 旅游业绩。无法建在另一座阿卡萨城堡旁。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_GRANADA_BONUS_XP2",                "建造者现在能够建造阿卡萨城堡改良设施。[NEWLINE][NEWLINE]阿卡萨城堡提供+2 [ICON_Culture] 文化值。提供等于单元格魅力75%的 [ICON_SCIENCE] 科技值。占领单位 [ICON_Strength] 防御力+4，并自动获得2回合防御工事。研究“飞行”科技后可提供 [ICON_TOURISM] 旅游业绩。无法建在另一座阿卡萨城堡旁。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_CARDIFF_DESCRIPTION",              "每个港口内建筑向城市提供3点 [ICON_Power] 电力。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_CARDIFF_BONUS",                    "每个港口内建筑向城市提供3点 [ICON_Power] 电力。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_PRESLAV_DESCRIPTION",              "城市中建成的每个军营及军营区域建筑提供+2 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_PRESLAV_BONUS_XP1",                "城市中建成的每个军营及军营区域建筑提供+2 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_AYUTTHAYA_DESCRIPTION",            "位于河流旁的剧院、圣地、商业中心和奇观提供2 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_AYUTTHAYA_BONUS",                  "位于河流旁的剧院、圣地、商业中心和奇观提供2 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_VILNIUS_DESCRIPTION",              "剧院广场区域的相邻加成提升50%，与其他玩家同盟后，每一级同盟都额外提升50%的剧院广场相邻加成。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_VILNIUS_BONUS_XP1",                "剧院广场区域的相邻加成提升50%，与其他玩家同盟后，每一级同盟都额外提升50%的剧院广场相邻加成。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_CAGUANA_DESCRIPTION",              "您的建造者现在可以建造改良设施巴特依。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值。每与1座加成资源和娱乐设施相邻，则+1 [ICON_Culture] 文化值（拥有“人文主义”市政后+2 [Icon_Culture] 文化值）。研究完“飞行”后将产出 [Icon_Tourism] 旅游业绩。无法建造在另一座巴特依旁。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_CAGUANA_BONUS",                    "您的建造者现在可以建造改良设施巴特依。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值。每与1座加成资源和娱乐设施相邻，则+1 [ICON_Culture] 文化值（拥有“人文主义”市政后+2 [Icon_Culture] 文化值）。研究完“飞行”后将产出 [Icon_Tourism] 旅游业绩。无法建造在另一座巴特依旁。"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_NAN_MADOL_DESCRIPTION",            "您境内位于或与海岸湖泊单元格相邻的区域(市中心外)和奇观+2 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_NAN_MADOL_BONUS",                  "您境内位于或与海岸湖泊单元格相邻的区域(市中心外)和奇观+2 [ICON_Culture] 文化值。");

--------------------------------------------------------------------------------
-- Language: zh_Hant_HK
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    ("zh_Hant_HK",  "LOC_LEADER_TRAIT_CARDIFF_DESCRIPTION",              "每個港口建築為城市提供+3 [ICON_Power] 電力。"),
    ("zh_Hant_HK",  "LOC_CIVILIZATION_CARDIFF_BONUS",                    "每個港口建築為城市提供+3 [ICON_Power] 電力。");

--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                 Text)
values
    ("LOC_CITY_NAME_HONG_KONG_1",                         "Baikonur"),
    ("LOC_CITY_NAME_HONG_KONG",                           "Baikonur"),
    ("LOC_CIVILIZATION_HONG_KONG_DESCRIPTION",            "Baikonur city-state"),
    ("LOC_CIVILIZATION_HONG_KONG_ADJECTIVE",              "Baikonur"),
    ("LOC_CIVILIZATION_HONG_KONG_NAME",                   "Baikonur"),
    ("LOC_LEADER_TRAIT_HONG_KONG_NAME",                   "Baikonur Suzerain Bonus"),
    ("LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_1", "Baikonur, formerly known as Leninsk (also, see Tyuratam), is a city of republic significancein Kazakhstan on the northern bank of the Syr Darya river, rented and administered by the Russian Federation. "),
    ("LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_2", "It was constructed to service the Baikonur Cosmodrome and was officially renamed Baikonur by Russian president Boris Yeltsin on December 20, 1995. During the Soviet period, it was sometimes referred to as Zvezdograd, Russian for 'Star City'."),
    ("LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_3", ""),
    ("LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_4", "");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    ("zh_Hans_CN",  "LOC_CITY_NAME_HONG_KONG_1",                         "拜科努尔"),
    ("zh_Hans_CN",  "LOC_CITY_NAME_HONG_KONG",                           "拜科努尔"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_HONG_KONG_DESCRIPTION",            "拜科努尔城邦"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_HONG_KONG_ADJECTIVE",              "拜科努尔的"),
    ("zh_Hans_CN",  "LOC_CIVILIZATION_HONG_KONG_NAME",                   "拜科努尔"),
    ("zh_Hans_CN",  "LOC_LEADER_TRAIT_HONG_KONG_NAME",                   "拜科努尔宗主国加成"),
    ("zh_Hans_CN",  "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_1", "拜科努尔——意思是“富裕的土地”——是位于哈萨克斯坦克孜勒奥尔达州的一座城市，位于锡尔河畔。面积57平方公里，人口约70,000人（2006年）。建于1955年，原名列宁斯克，以服务拜科努尔航天中心。苏联解体后由俄罗斯租用至2050年。1995年改名。"),
    ("zh_Hans_CN",  "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_2", "原来的“拜科努尔”位于这里400公里之遥，属于卡拉干达州。1961年4月把发射中心命名为拜科努尔通常被认为是苏联掩人耳目之举。"),
    ("zh_Hans_CN",  "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_3", ""),
    ("zh_Hans_CN",  "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HONG_KONG_CHAPTER_HISTORY_PARA_4", "");
