--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                               Text)
values
    -- ("LOC_TRAIT_CIVILIZATION_KHMER_BARAYS_EXPANSION2_DESCRIPTION",      "Cities with an Aqueduct receive +1 [ICON_AMENITIES] Amenity from entertainment and +1 [ICON_FAITH] Faith for every [ICON_CITIZEN] population. Farms provide +2 [ICON_FOOD] Food if adjacent to an Aqueduct and +1 [ICON_FAITH] Faith if adjacent to a Holy Site."),
    ("LOC_BUILDING_PALGUM_DESCRIPTION",                                 "A building unique to Babylon. Replaces Water Mill. +1 [ICON_HOUSING] Housing and +2 [ICON_PRODUCTION] Production. Freshwater tiles receive +1 [ICON_FOOD] Food. City must be adjacent to a River."),
    ("LOC_RESOURCE_FISH_NAME",                                          "Pacific Salmon"),
    ("LOC_RESOURCE_SALMON_NAME",                                        "Atlantic Salmon"),
    ("LOC_IMPROVEMENT_MOUNTAIN_TUNNEL_DESCRIPTION",                     "Unlocks the Military Engineer ability to construct a Mountain Tunnel.[NEWLINE][NEWLINE]Acts as a movement portal on a mountain range, allowing units to move into it and exit from another portal at the cost of 2 [ICON_Movement] Movement. Multiplier of  [ICON_Gold] Gold yield from districts at their destination [ICON_TradeRoute] Trade Routes passing through Mountain Tunnel is set to +100% (max. +100%). Can only be built on an adjacent Mountain tile. Cannot be pillaged or removed."),
    ("LOC_IMPROVEMENT_MOUNTAIN_ROAD_DESCRIPTION",                       "Unlocks the Builder ability to construct a Qhapaq Ñan, unique to Pachacuti.[NEWLINE][NEWLINE]Acts as a movement portal on a mountain range, allowing units to move into it and exit from another portal at the cost of 2 [ICON_Movement] Movement. Multiplier of  [ICON_Gold] Gold yield from districts at their destination [ICON_TradeRoute] Trade Routes passing through Qhapaq Ñan is set to +100% (max. +100%). Can only be built on an adjacent Mountain tile. Cannot be pillaged or removed."),
    ("LOC_LEADER_TRAIT_JOHANNESBURG_DESCRIPTION",                       "Cities receive +1 [ICON_Production] Production for each type of improved resource. After researching Industrialization it becomes +2 [ICON_PRODUCTION] Production."),
    ("LOC_BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION_DESCRIPTION",        "+20% [ICON_SCIENCE] Science and 10% [ICON_PRODUCTION] Production in all cities. If there are 5 Snow or Snow Hills tiles within 3 tiles of a city and owned by this player these yields are doubled. Must be built on a Snow or Snow Hills tile, and adjacent to a Campus with an Institute of Technology or Community College."),
    ("LOC_PROMOTION_STRAFE_DESCRIPTION",                                "+17 [ICON_Strength] Combat Strength vs. non-cavalry land units."),
    ("LOC_FEATURE_GALAPAGOS_DESCRIPTION",                               "Two tile impassable Natural Wonder. It appears on Coast tiles and provides +2 [ICON_Science] Science to adjacent tiles.");
