--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                     Text)
values
    -- UI Texts
    ("LOC_UNITCOMMAND_SACRIFICE_NAME",                                        "Human Sacrifice"),
    ("LOC_UNITCOMMAND_SACRIFICE_DESCRIPTION",                                 "Sacrifice this unit to God, gain +10 [ICON_Culture] Culture and +10 [ICON_Faith] for each builder charge the unit has. Remove the unit."),
    ("LOC_UNITCOMMAND_SACRIFICE_DISABLED_TT",                                 "[COLOR_RED]Must at City Center[ENDCOLOR]"),
    ("LOC_FLYOVER_AZTEC_SACRIFICE",                                           "Human Sacrifice[COLOR:ResCultureLabelCS]+{1_Amount}[ENDCOLOR][ICON_Culture][COLOR:ResFaithLabelCS]+{1_Amount}[ENDCOLOR][ICON_Faith]"),
    -- Main
    ("LOC_ABILITY_ENABLE_WALL_ATTACK_DESCRIPTION",                            "When adjacent to an enemy city, units do full damage to the city's Walls."),
    ("LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",                                     "{1_num}-tile regional effects: Its basic yields extend to each city center within {1_num} tiles. Multiple copies of this effect from the same type of building do not provide additional bonuses."),
    ("LOC_HAPPINESS_DELIGHTED_NAME",                                          "Delighted"),
    ("LOC_IMPROVEMENT_GOODY_BUILDER_NAME",                                    "Please Ignore"),
    ("LOC_LOYALTY_LEVEL_4_NAME",                                              "Unswervingly Loyal"),
    ("LOC_LOYALTY_LEVEL_4_DESCRIPTION",                                       "The citizens are Unswervingly Loyal to your civilization"),
    ("LOC_TURNS_BEFORE_DESTROY_HD",                                           "Completely destroy after {1_num} turns"),
    ("LOC_CANNOT_REMOVE_FEATURE_USING_RECONS",                                "Cannot remove features using Recon units"),
    ("LOC_VIZSOURCE_CHANCERY",                                                "Built Building Chancery"),
    ("LOC_VIZSOURCE_ACTION_CHANCERY",                                         "Build Building Chancery"),
    ("LOC_GOSSIP_SOURCE_CHANCERY",                                            "Your officier from Chancery informed that "),
    ("LOC_GOSSIP_SOURCE_GOV_SPIES",                                           "Your officier from GOV SPIES informed that "),
    ("LOC_VIZSOURCE_GOV_SPIES",                                               "Built Building GOV SPIES"),
    ("LOC_VIZSOURCE_ACTION_GOV_SPIES",                                        "Build Building GOV SPIES"),
    ("LOC_DISTRICT_LUXURY_GOLD",                                              "+{1_num} [ICON_Gold] Gold from the adjacent luxury resource."),
    ("LOC_PEDIA_CONCEPTS_PAGE_CITIES_12_CHAPTER_CONTENT_PARA_1",              "Your city will grow, or add more [ICON_Citizen] Citizens, with surplus [ICON_Food] Food. Any amount of [ICON_Food] Food over the total consumption of a city's [ICON_Citizen] Citizens, 3 per, is considered surplus, and is added as progress towards a new [ICON_Citizen] Citizen."),
    ("LOC_PEDIA_CONCEPTS_PAGE_CITIES_13_CHAPTER_CONTENT_PARA_1",              "A city requires 3 [ICON_Food] Food per [ICON_Citizen] Citizen (another term for ""[ICON_Citizen] Population"") per turn to avoid starvation. A city acquires [ICON_Food] Food (as well as other yields) by assigning its [ICON_Citizen] Citizens to ""work"" the land around the city. The city can work any tile within 3 spaces of the city that is also within the civilization's borders, provided as well that it is not being worked by another city. Cities cannot work tiles occupied by wonders."),
    ("LOC_DISTRICT_CANAL_GOLD",                                               "+{1_num} [ICON_Gold] Gold from the adjacent Canal."),
    ("LOC_DISTRICT_AERODROME_INDUSTRIAL_PRODUCTION",                          "+{1_num} [ICON_Production] Production from the adjacent Aerodrome."),
    ("LOC_DISTRICT_OIL_INDUSTRIAL_PRODUCTION",                                "+{1_num} [ICON_Production] Production from the adjacent Oil Well."),
    ("LOC_DISTRICT_SEAOIL_INDUSTRIAL_PRODUCTION",                             "+{1_num} [ICON_Production] Production from the adjacent Offshore Oil Rig."),
    ("LOC_DISTRICT_LUMBER_MILL_1_PRODUCTION",                                 "+{1_num} [ICON_Production] Production from the adjacent Lumber Mill."),
    ("LOC_PEDIA_CONCEPTS_PAGE_COMBAT_9_CHAPTER_CONTENT_PARA_2",               "Walls add extra protection to a city or Encampment, making it even more difficult to conquer. This protection is like armor, shielding the city from attacks. Melee units deal only 15% of their normal damage to walls, and ranged units deal only 75% of their normal damage. Only Bombard units deal 100% of their normal damage to walls, making them necessary to capture a fortified city. If the walls are damaged, they stop being as effective and the district's health will start taking a little bit of damage with every attack. Walls can only recover health with a Project found in the city's Production Queue, like repairing district buildings, that becomes available if the district has not taken any damage for 3 consecutive turns. Once a city has walls, it can make ranged attacks against enemy units using a ""City Ranged Strength"" stat.[NEWLINE][NEWLINE]The City Combat Strength is based on the [ICON_Strength] Combat Strength of the strongest melee unit built by your civilization, minus 10, or by the [ICON_Strength] Combat Strength of a garrisoned military unit.[NEWLINE][NEWLINE]The City Ranged Strength is based on the [ICON_Ranged] Ranged Strength of the strongest ranged unit built by your civilization.[NEWLINE][NEWLINE]The city gets additional bonuses to its City Combat Strength for each non-pillaged district it has, making big cities harder to capture, and from terrain and a few other modifiers sources."),
    ("LOC_ABILITY_KILL_GIVE_GREAT_GENERAL_POINTS_DESCRIPTION",                "Receive [ICON_GreatGeneral] Great General points when defeat a major or minor civilization's unit equal to 20% of the opposing unit's strength (Standard Speed)."),
    ("LOC_ABILITY_KILL_GIVE_GREAT_ADMIRAL_POINTS_DESCRIPTION",                "Receive [ICON_GreatAdmiral] Great Admiral points when defeat a major or minor civilization's unit equal to 20% of the opposing unit's strength (Standard Speed)."),
    ("LOC_ABILITY_INCA_IGNORE_HILLS_DESCRIPTION",                             "Qhapaq Ñan: ignore [ICON_MOVEMENT] movement penalty from Hills. "),
    ("LOC_ABILITY_KONGO_IGNORE_WOODS_DESCRIPTION",                            "Nkisi: Ignore [ICON_MOVEMENT] movement penalty from Forest and Jungle. "),
    ("LOC_ABILITY_AMANI_FERR_PROMOTION_DESCRIPTION",                          "1 free promotion from Amani "),
    ("LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_TERRAIN_DESCRIPTION",             "Ignore [ICON_MOVEMENT] movement penalty from all Terrians, Features and Rivers."),
    -- ("LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_RIVER_DESCRIPTION",               "Ignore river's extra movement penalty"),
    ("LOC_ABILITY_GUILDMASTER_TRAINED_BUILDER_MOVEMENT_DESCRIPTION",          "+1 [ICON_MOVEMENT] Movement from Liang's Training"),
    ("LOC_ABILITY_BISHOP_EXTRA_MOVEMENT_DESCRIPTION",                         "+1 [ICON_MOVEMENT] Movement from Bishop's Training"),
    ("LOC_ABILITY_BISHOP_TRAINED_UNIT_EXP_DESCRIPTION",                       "+100% EXP from Bishop's training"),
    ("LOC_ABILITY_BISHOP_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+5 [ICON_Strength] Combat Strength from Bishop's training"),
    ("LOC_ABILITY_VICTOR_TRAINED_UNIT_EXP_DESCRIPTION",                       "+25% EXP from Victor's training"),
    ("LOC_ABILITY_VICTOR_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+2 [ICON_Strength] Combat Strength from Victor's training "),
    ("LOC_ABILITY_KOTOKU_IN_TRAINED_FREE_PROMOTION_DESCRIPTION",              "1 free promotion from Kotoku In "),
    ("LOC_ABILITY_TRAINED_LIGHT_CAVALRY_PILLAGE_LESS_MOVEMENT_DESCRIPTION",   "Pillage costs 1 movement from Pillage Preparing city policy"),
    ("LOC_ABILITY_LIGHT_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "-7 [ICON_Strength] Combat Strength when attacking Districts"),
    ("LOC_ABILITY_HEAVY_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "-5 [ICON_Strength] Combat Strength when attacking Districts"),
    ("LOC_ABILITY_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_DESCRIPTION",        "+3 [ICON_Strength] Combat Strength from training in Military Academy"),
    ("LOC_ABILITY_SEAPORT_TRAINED_UNIT_STRENGTH_DESCRIPTION",                 "+3 [ICON_Strength] Combat Strength from training in Seaport"),
    ("LOC_ABILITY_BARRACKS_TRAINED_UNIT_STRENGTH_DESCRIPTION",                "+2 [ICON_Strength] Combat Strength from training in Barracks"),
    ("LOC_ABILITY_BASILIKOI_TRAINED_UNIT_STRENGTH_DESCRIPTION",               "+3 [ICON_Strength] Combat Strength from training in Basilikoi Paides"),
    ("LOC_ABILITY_STABLE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+3 [ICON_Strength] Combat Strength from training in Stable"),
    ("LOC_ABILITY_ORDU_TRAINED_UNIT_STRENGTH_DESCRIPTION",                    "+3 [ICON_Strength] Combat Strength from training in Ordu"),
    ("LOC_ABILITY_MOSQUE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+3 [ICON_Strength] Combat Strength from training in Mosque"),
    ("LOC_ABILITY_SCHOLASTICISM_BUFF_DESCRIPTION",                            "+7 [ICON_Strength] Combat Strength from Scholasticism Belief"),
    ("LOC_ABILITY_IKANDA_ANTI_CAVALRY_MOVEMENT_BONUS_DESCRIPTION",            "+1 [ICON_MOVEMENT] Movement from training in Ikanda"),
    ("LOC_ABILITY_JUST_WAR_RELIGIOUS_ALL_COMBAT_BUFF_DESCRIPTION",            "Just War : Combat units gain +5 [ICON_Strength] Combat Strength when plot has religious unit."),
    ("LOC_ABILITY_JUST_WAR_STRENGTH_DESCRIPTION",                             "Just War : +5 [ICON_Strength] Combat Strength"),
    ("LOC_ABILITY_MONASTIC_ISOLATION_INQUISITOR_CHARGE_DESCRIPTION",          "Isolation Inquisitor : inquisitors can spread Religion 1 extra time"),
    ("LOC_ABILITY_POLAND_CAVALRY_REDUCTION_DAMAGE_DESCRIPTION",               "50% less [ICON_Strength] Combat Strength reduction from being injured"),
    ("LOC_ABILITY_TERRITORY_COMBAT_HD_DESCRIPTION",                           "+4 [ICON_Strength] Combat Strength when defending in your territory"),
    ("LOC_BISHOP_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from Bishop's training"),
    ("LOC_VICTOR_TRAINED_UNIT_EXP_PREVIEW_TEXT",                              "from Victor's training"),
    ("LOC_VICTOR_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from Victor's training"),
    ("LOC_ABILITY_GOV_FAITH_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",           "from Episcopal Church"),
    ("LOC_ABILITY_GOV_MILITARY_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",        "from War Department"),
    ("LOC_ABILITY_GOV_MILITARY_MOVEMENT_MODIFIER_PREVIEW_TEXT",               "from War Department"),
    ("LOC_LIGHTNING_WARFARE_CAVALRY_STRENGTH_PREVIEW_TEXT",                   "from Lighting Warfare"),
    ("LOC_CAVALRY_WEAKER_ATTACKING_DISTRICT_PREVIEW_TEXT",                    "Attacking Districts"),
    ("LOC_GREAT_WALL_REDUCE_COMBAT_PREVIEW_TEXT",                             "adjacent to the Great Wall"),
    ("LOC_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",               "from training in Military Academy"),
    ("LOC_SEAPORT_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                        "from training in Seaport"),
    ("LOC_BARRACKS_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                       "from training in Barracks"),
    ("LOC_BASILIKOI_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                      "from training in Basilikoi Paides"),
    ("LOC_STABLE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from training in Stable"),
    ("LOC_ORDU_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                           "from training in Ordu"),
    ("LOC_MOSQUE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from training in Mosque"),
    ("LOC_SCHOLASTICISM_COMBAT_STRENGTH_BUFF_PREVIEW_TEXT",                   "from Scholasticism Belief"),
    ("LOC_ABILITY_JUST_WAR_STRENGTH_PREVIEW_TEXT",                            "Combat Strength from Just War"),
    ("LOC_POLAND_ALLY_COMBAT_STRENGTH_PREVIEW_TEXT",                          "+4 Combat Strength from Lithuanian Union"),
    ("LOC_UNIVERSITY_JUNGLE_SCIENCE",                                         "+{1_num} [ICON_Science] Science from the adjacent {1_num : plural 1?Jungle; other?Jungles;}."),
    ("LOC_DISTRICT_QUARRY_HALF_PRODUCTION",                                   "+{1_num} [ICON_Production] Production from the adjacent Quarries."),
    ("LOC_DISTRICT_CULTURE_DOUBLE_CITY_CENTER",                               "+{1_num} [ICON_CULTURE] Culture from adjacent City {1_Num : plural 2?Center; other?Centers;}."),
    ("LOC_DISTRICT_GOLD_CITY_CENTER",                                         "+{1_num} [ICON_Gold] Gold from adjacent City {1_Num : plural 1?Center; other?Centers;}."),
    ("LOC_DISTRICT_GOLD_HANSA",                                               "+{1_num} [ICON_Gold] Gold from adjacent Hansa {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_GOLD_INDUSTRIAL_ZONE",                                     "+{1_num} [ICON_Gold] Gold from adjacent Industrial Zone {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_COMMERCIAL_GOLD",                                          "+{1_num} [ICON_Gold] Gold from adjacent Commercial Hub {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_SUGUBA_GOLD",                                              "+{1_num} [ICON_Gold] Gold from adjacent Suguba {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_DESERT_SCIENCE",                                           "+{1_num} [ICON_Science] Science from adjacent Desert {1_Num : plural 1?Tile; other?Tiles;}."),
    ("LOC_DISTRICT_DESERT_HILLS_SCIENCE",                                     "+{1_num} [ICON_Science] Science from adjacent Desert hill {1_Num : plural 1?Tile; other?Tiles;}."),
    ("LOC_DISTRICT_HARBOR_INDUSTRIAL_PRODUCTION",                             "+{1_num} [ICON_Production] Production from adjacent Harbor {1_Num : plural 1?district; other?districts;}."),
    ("LOC_DISTRICT_ROYALDOCK_INDUSTRIAL_PRODUCTION",                          "+{1_num} [ICON_Production] Production from adjacent RoyalDock {1_Num : plural 1?district; other?districts;}."),
    ("LOC_DISTRICT_COTHON_INDUSTRIAL_PRODUCTION",                             "+{1_num} [ICON_Production] Production from adjacent Cothon {1_Num : plural 1?district; other?districts;}."),
    ("LOC_DISTRICT_RIVER_HANSA_PRODUCTION",                                   "+{1_num} [ICON_Production] Production from adjacent river."),
    ("LOC_DISTRICT_HARBOR_HANSA_PRODUCTION",                                  "+{1_num} [ICON_Production] Production from adjacent Harbor {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_ROYALDOCK_HANSA_PRODUCTION",                               "+{1_num} [ICON_Production] Production from adjacent RoyalDock {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_COTHON_HANSA_PRODUCTION",                                  "+{1_num} [ICON_Production] Production from adjacent Cothon {1_Num : plural 2?district; other?districts;}."),
    ("LOC_PROJECT_BREAD_AND_CIRCUSES_DESCRIPTION",                            "City project which increases the Loyalty pressure that this city exerts on itself and other cities nearby.[NEWLINE][NEWLINE]While active, each of your [ICON_Citizen] Citizens here exerts +1 Loyalty pressure to this city. This pressure also affects other cities within 9 tiles, but is 10% less effective per tile. Once completed, instantly gain +20 Loyalty in this city.[NEWLINE][NEWLINE]Requires: Entertainment Complex district."),
    ("LOC_ALLIANCE_LV2_RESEARCH_EFFECT_1",                                    "Every 10 turns (on Standard), you unlock a [ICON_TechBoosted] Eureka for a tech that your ally has researched or boosted, but you have not."),
    ("LOC_PEDIA_CONCEPTS_PAGE_ALLIANCES_1_CHAPTER_CONTENT_PARA_1",            "Alliances are a relationship between two different civilizations, a mutual agreement to work together in some way. To enter into an Alliance, you must first be Declared Friends with the civilization, and both civilizations must have researched the Civil Service civic.[NEWLINE][NEWLINE]There are several Alliance types, each one provides different mutual benefits according to its type. The effects of these levels are cumulative, so if you are in a Level 3 Alliance, you also gain the Level 1 and Level 2 effects. When you are in an Alliance with another Player, you gain Alliance Points every turn.  Collecting enough increases your Alliance Level, resulting in more benefits from your Alliances.  You can increase the rate at which you gain Alliance Points by trading with your Ally.[NEWLINE][NEWLINE]Every Alliance, regardless of its type, provides Open Borders and a Defensive Pact to both parties. Members of an Alliance cannot declare war on each other.[NEWLINE][NEWLINE]You may have only one kind of alliance with another civilization, and once you have created that alliance, you cannot have it with another civilization, although you might have another kind of alliance with them. For example, you might have a Research Alliance with Korea, so you cannot make a new Research Alliance with the Cree. You might create a Military, Cultural, Religious, or Economic Alliance with the Cree, however. Note that this limits you to five total Alliances in a game.[NEWLINE][NEWLINE]Research Alliance[NEWLINE][ICON_BULLET]Level 1: [ICON_TradeRoute] Trade Routes between allies grant additional [ICON_Science] Science.[NEWLINE][ICON_BULLET]Level 2: Allies share 1 Tech Boost every 10 turns (on Standard Speed).[NEWLINE][ICON_BULLET]Level 3: Gives bonus [ICON_Science] Science when studying the same technology as your ally or one that your ally has completed, and while your ally is researching a tech you have completed.[NEWLINE][NEWLINE]Cultural Alliance[NEWLINE][ICON_BULLET]Level 1: Allies do not exert Loyalty pressure on each other, and [ICON_TradeRoute] Trade Routes between allies grant additional [ICON_CULTURE] Culture.[NEWLINE][ICON_BULLET]Level 2: When your cities have [ICON_TradeRoute] Trade Routes with your ally, gain additional [ICON_GreatPerson] Great Person points in the origin cities based off of the districts in those cities.[NEWLINE][ICON_BULLET]Level 3: You gain a portion of your ally’s [ICON_Tourism] Tourism and [ICON_CULTURE] Culture from cities.[NEWLINE][NEWLINE]Military Alliance[NEWLINE][ICON_BULLET]Level 1: Allies gain bonus [ICON_Strength] Combat Strength against civilizations on whom both allies have declared war.[NEWLINE][ICON_BULLET]Level 2: Allies share visibility and gain bonus [ICON_Production] Production toward military units when either ally is at war.[NEWLINE][ICON_BULLET]Level 3: Units start with a bonus promotion.[NEWLINE][NEWLINE]Religious Alliance[NEWLINE][ICON_BULLET]Level 1: Ally cities do not exert Religious pressure on each other, and [ICON_TradeRoute] Trade Routes between allies grant additional [ICON_Faith] Faith.[NEWLINE][ICON_BULLET]Level 2: Allies gain [ICON_Religion] religious Combat Strength against Religions not founded by either ally.[NEWLINE][ICON_BULLET]Level 3: You gain Faith based on the number of your [ICON_Citizen] Citizens following your ally’s Religion, and bonus Religious Pressure in cities with no followers of your ally's Religion.[NEWLINE][NEWLINE]Economic Alliance[NEWLINE][ICON_BULLET]Level 1: [ICON_TradeRoute] Trade Routes between allies grant additional [ICON_Gold] Gold.[NEWLINE][ICON_BULLET]Level 2: Gain an [ICON_ENVOY] Envoy point for every City-State with your Ally as Suzerain.[NEWLINE][ICON_BULLET]Level 3: Allies share the Suzerain bonus of all city-states of which they are Suzerain.")
    ;

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                     Text)
values
    -- [MOD] Gift it to me
    ("zh_Hans_CN",  "LOC_GIFTITTOME_GIFT_THIS_UNIT",                                         "赠送单位（给当前位置领土的所有者）"),
    ("zh_Hans_CN",  "LOC_GIFTITTOME_GIFT_THIS_UNIT_DISABLED",                                "赠送单位[NEWLINE] - 需要在其他玩家的领土内[NEWLINE] - 宗教单位、开拓者和考古学家无法赠送给城邦[NEWLINE] - 征兵不能赠送[NEWLINE] - 匈牙利需要将单位与金币一起赠送给宗主的城邦[NEWLINE] - 不能赠送给与你处于战争状态的玩家[NEWLINE] - 已达到每回合赠送单位的上限：{1_MaxGifts}次[NEWLINE] - 单位血量必须超过90％"),
    ("zh_Hans_CN",  "LOC_HUD_UNIT_PANEL_ARE_YOU_SURE_GIFT",                                  "您确定要向其他玩家赠送（{2_GiftCount} / {3_MaxGiftCount}）你的{1_UnitName}吗？"),
    ("zh_Hans_CN",  "LOC_HUD_UNIT_PANEL_ARE_YOU_SURE_GIFT_PAY",                              "您确定要向城邦赠送（{3_GiftCount} / {4_MaxGiftCount}）您的{1_UnitName}和{2_Gold}金币吗？[NEWLINE]（匈牙利需要将黄金与单位一起赠送给宗主的城邦）"),
    ("zh_Hans_CN",  "LOC_GIFTITTOME_WARNING_HEADLINE",                                       "来自{1_LeaderName}的警告"),
    ("zh_Hans_CN",  "LOC_GIFTITTOME_WARNING_CONTENT",                                        "向我们的敌人赠送单位可能会导致外交行动。[NEWLINE]我们已经警告你了"),
    ("zh_Hans_CN",  "LOC_GIFTITTOME_INFO_HEADLINE",                                          "{1_LeaderName}给了你一个单位！"),
    ("zh_Hans_CN",  "LOC_GIFTITTOME_INFO_CONTENT",                                           "您收到了{1_UnitName}！"),
    -- UI texts 
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_SACRIFICE_NAME",                                        "活人献祭"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_SACRIFICE_DESCRIPTION",                                 "向神明献祭该单位，每有一次剩余劳动力获得10点 [ICON_Culture] 文化值和10点 [ICON_Faith] 信仰值，移除该单位。"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_SACRIFICE_DISABLED_TT",                                 "[COLOR_RED]必须位于市中心[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_FLYOVER_AZTEC_SACRIFICE",                                           "活人献祭[COLOR:ResCultureLabelCS]+{1_Amount}[ENDCOLOR][ICON_Culture][COLOR:ResFaithLabelCS]+{1_Amount}[ENDCOLOR][ICON_Faith]"),
    -- Main
    ("zh_Hans_CN",  "LOC_GOVERNMENT_INHERENT_BONUS",                                         "传承效果"), -- 官方好像在ui上面写反了。
    ("zh_Hans_CN",  "LOC_ABILITY_ENABLE_WALL_ATTACK_DESCRIPTION",                            "靠近敌人城市时，对城市城墙造成全额伤害。"),
    ("zh_Hans_CN",  "LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",                                     "{1_num}环辐射：其基础产出延伸到{1_num}个单元格内的市中心，但多个同种建筑的辐射不叠加。"),
    ("zh_Hans_CN",  "LOC_TYPE_TRAIT_CITIZENSLOTS",                                           "{1_Amount: number +#,###;-#,###} [ICON_Citizen] 公民{1_Amount : plural 1?槽位; other?槽位;}"),
    ("zh_Hans_CN",  "LOC_HAPPINESS_DELIGHTED_NAME",                                          "愉悦"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_GOODY_BUILDER_NAME",                                    "请忽略"),
    ("zh_Hans_CN",  "LOC_LOYALTY_LEVEL_4_NAME",                                              "绝对忠诚"),
    ("zh_Hans_CN",  "LOC_LOYALTY_LEVEL_4_DESCRIPTION",                                       "您的公民绝对忠于您的文明。"),
    ("zh_Hans_CN",  "LOC_TURNS_BEFORE_DESTROY_HD",                                           "将在{1_num}回合后被彻底摧毁"),
    ("zh_Hans_CN",  "LOC_CANNOT_REMOVE_FEATURE_USING_RECONS",                                "侦察类单位不能移除地貌"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_CHANCERY",                                                "建造了外交办"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_ACTION_CHANCERY",                                         "建造外交办"),
    ("zh_Hans_CN",  "LOC_GOSSIP_SOURCE_CHANCERY",                                            "外交办的官员获悉"),
    ("zh_Hans_CN",  "LOC_GOSSIP_SOURCE_GOV_SPIES",                                           "情报局的官员获悉"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_GOV_SPIES",                                               "建造了情报局"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_ACTION_GOV_SPIES",                                        "建造情报局"),
    ("zh_Hans_CN",  "LOC_DISTRICT_LUXURY_GOLD",                                              "相邻奢侈品资源提供+{1_num} [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_PEDIA_CONCEPTS_PAGE_CITIES_13_CHAPTER_CONTENT_PARA_1",              "城市里的每位 [ICON_Citizen] 公民（这是“ [ICON_Citizen] 人口”的另一种表达方式）每回合需要3份 [ICON_Food] 食物来避免饥饿。通过派遣其 [ICON_Citizen] 公民“改良”周围土地，城市能获得 [ICON_Food] 食物（以及其他收益）。城市能改良3个距离以内的任意单元格（位于文明境内且没被其他城市改良过）。城市无法改良被奇观占领的单元格。"),
    ("zh_Hans_CN",  "LOC_PROMOTION_SHELLS_DESCRIPTION",                                      "与区域防御战斗时+10 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_UNIT_GAUL_GAESATAE_DESCRIPTION",                                    "高卢特色远古时代单位，替代勇士。此单位拥有更高花费。与基础战斗力更高的单位作战时+10 [ICON_Strength] 战斗力。与区域防御战斗时+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_CANAL_GOLD",                                               "相邻运河提供+{1_num} [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_AERODROME_INDUSTRIAL_PRODUCTION",                          "相邻航空港提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_OIL_INDUSTRIAL_PRODUCTION",                                "相邻油井提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SEAOIL_INDUSTRIAL_PRODUCTION",                             "相邻海上钻机平台提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_LUMBER_MILL_1_PRODUCTION",                                 "相邻伐木场提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_PEDIA_CONCEPTS_PAGE_COMBAT_9_CHAPTER_CONTENT_PARA_2",               "城墙为城市或军营增加额外保护，让其更难被占领。这种保护如同护甲一般，使城市免受攻击。近战单位仅对城墙造成它通常伤害的15%，远程单位仅对城墙造成它通常伤害的75%。只有轰炸单位才能对城墙造成它100%的伤害，因此，轰炸单位是占领坚固城市的必需之物。如果城墙遭受损害，其会不再有效，同时，每一次攻击都会让区域生命值受到少量伤害。只有使用在城市生产队列中找到的项目才能回复城墙生命值，比如修理区域建筑，如果区域连续3回合没有遭受任何伤害，则可以进行修复。城市一旦拥有城墙，便可使用“城市远程攻击”对敌方单位发动远程攻击。[NEWLINE][NEWLINE]城市战斗力取决于您文明里最强近战单位的 [ICON_Strength] 战斗力大小，最小为10，或取决于驻军军事单位的战斗力。[NEWLINE][NEWLINE]城市远程攻击力取决于您文明里最强 [ICON_Ranged] 远程单位的远程攻击力大小。[NEWLINE][NEWLINE]城市所拥有的每个没被掠夺的区域会为其城市战斗力提供额外加成，使大城市更难被占领，城市也能从地形和一些其他改造者来源中获得额外加成。"),
    ("zh_Hans_CN",  "LOC_ABILITY_INCA_IGNORE_HILLS_DESCRIPTION",                             "印加路网：无视丘陵对 [ICON_MOVEMENT] 移动力的减益。"),
    ("zh_Hans_CN",  "LOC_ABILITY_KILL_GIVE_GREAT_GENERAL_POINTS_DESCRIPTION",                "击杀文明和城邦的单位时，获得等同于对方单位战斗力的20%（标准速度下）的 [ICON_GreatGeneral] 大将军点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_KILL_GIVE_GREAT_ADMIRAL_POINTS_DESCRIPTION",                "击杀文明和城邦的单位时，获得等同于对方单位战斗力的20%（标准速度下）的 [ICON_GreatAdmiral] 海军统帅点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_KONGO_IGNORE_WOODS_DESCRIPTION",                            "精神实体：无视森林和雨林对 [ICON_MOVEMENT] 移动力的减益。"),
    ("zh_Hans_CN",  "LOC_ABILITY_AMANI_FERR_PROMOTION_DESCRIPTION",                          "阿玛尼训练：免费晋升1级"),
    ("zh_Hans_CN",  "LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_TERRAIN_DESCRIPTION",             "无视地形、地貌和河流的移动力消耗。"),
    -- ("zh_Hans_CN",  "LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_RIVER_DESCRIPTION",               "无视河流造成的移动力损益"),
    ("zh_Hans_CN",  "LOC_ABILITY_GUILDMASTER_TRAINED_BUILDER_MOVEMENT_DESCRIPTION",          "梁训练：永久+1 [ICON_MOVEMENT] 移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BISHOP_EXTRA_MOVEMENT_DESCRIPTION",                         "莫克夏训练：永久+1 [ICON_MOVEMENT] 移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BISHOP_TRAINED_UNIT_EXP_DESCRIPTION",                       "莫克夏训练：永久+100% 经验值"),
    ("zh_Hans_CN",  "LOC_ABILITY_BISHOP_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "莫克夏训练：永久+5 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_VICTOR_TRAINED_UNIT_EXP_DESCRIPTION",                       "维克多训练：永久+25% 经验值"),
    ("zh_Hans_CN",  "LOC_ABILITY_VICTOR_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "维克多训练：永久+2 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_KOTOKU_IN_TRAINED_FREE_PROMOTION_DESCRIPTION",              "高德院训练：免费获得1级晋升"),
    ("zh_Hans_CN",  "LOC_ABILITY_TRAINED_LIGHT_CAVALRY_PILLAGE_LESS_MOVEMENT_DESCRIPTION",   "打草谷训练：劫掠只消耗1移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_LIGHT_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "攻击区域时-7 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_HEAVY_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "攻击区域时-5 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_DESCRIPTION",        "在军事学院中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_SEAPORT_TRAINED_UNIT_STRENGTH_DESCRIPTION",                 "在码头中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BARRACKS_TRAINED_UNIT_STRENGTH_DESCRIPTION",                "在兵营中训练获得的+2 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BASILIKOI_TRAINED_UNIT_STRENGTH_DESCRIPTION",               "在皇家学院中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_STABLE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "在马厩中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_ORDU_TRAINED_UNIT_STRENGTH_DESCRIPTION",                    "在斡耳朵中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_MOSQUE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "由清真寺中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_SCHOLASTICISM_BUFF_DESCRIPTION",                            "来自经院哲学信条+7 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_IKANDA_ANTI_CAVALRY_MOVEMENT_BONUS_DESCRIPTION",            "在伊坎达中训练获得的+1 [ICON_MOVEMENT] 移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_RELIGIOUS_ALL_COMBAT_BUFF_DESCRIPTION",            "十字军：同一单元格内的战斗单位+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_STRENGTH_DESCRIPTION",                             "十字军：+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_MONASTIC_ISOLATION_INQUISITOR_CHARGE_DESCRIPTION",          "与世隔绝：审判官+1传教次数。"),
    ("zh_Hans_CN",  "LOC_ABILITY_POLAND_CAVALRY_REDUCTION_DAMAGE_DESCRIPTION",               "受伤后的 [ICON_Strength] 战斗力减益减少50%"),
    ("zh_Hans_CN",  "LOC_ABILITY_TERRITORY_COMBAT_HD_DESCRIPTION",                           "在国境内防御时+4 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_BISHOP_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "来自莫克夏训练"),
    ("zh_Hans_CN",  "LOC_VICTOR_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "来自维克多训练"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_FAITH_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",           "来自主教座堂"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_MILITARY_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",        "来自作战部"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_MILITARY_MOVEMENT_MODIFIER_PREVIEW_TEXT",               "来自作战部"),
    ("zh_Hans_CN",  "LOC_LIGHTNING_WARFARE_CAVALRY_STRENGTH_PREVIEW_TEXT",                   "来自闪电战"),
    ("zh_Hans_CN",  "LOC_CAVALRY_WEAKER_ATTACKING_DISTRICT_PREVIEW_TEXT",                    "攻击区域"),
    ("zh_Hans_CN",  "LOC_GREAT_WALL_REDUCE_COMBAT_PREVIEW_TEXT",                             "相邻长城"),
    ("zh_Hans_CN",  "LOC_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",               "从军事学院中训练获得"),
    ("zh_Hans_CN",  "LOC_SEAPORT_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                        "从码头中训练获得"),
    ("zh_Hans_CN",  "LOC_BARRACKS_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                       "从兵营中训练获得"),
    ("zh_Hans_CN",  "LOC_BASILIKOI_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                      "从皇家学院中训练获得"),
    ("zh_Hans_CN",  "LOC_STABLE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "从马厩中训练获得"),
    ("zh_Hans_CN",  "LOC_ORDU_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                           "从斡耳朵中训练获得"),
    ("zh_Hans_CN",  "LOC_MOSQUE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "从清真寺中训练获得"),
    ("zh_Hans_CN",  "LOC_SCHOLASTICISM_COMBAT_STRENGTH_BUFF_PREVIEW_TEXT",                   "来自经院哲学信条"),
    ("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_STRENGTH_PREVIEW_TEXT",                            "来自十字军"),
    ("zh_Hans_CN",  "LOC_POLAND_ALLY_COMBAT_STRENGTH_PREVIEW_TEXT",                          "+4 来自立陶宛联邦"),
    ("zh_Hans_CN",  "LOC_UNIVERSITY_JUNGLE_SCIENCE",                                         "+{1_num} [ICON_Science] 科技值来自相邻的雨林。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_HALF_PRODUCTION",                                   "+{1_num} [ICON_Production] 生产力来自相邻的采石场。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_CULTURE_DOUBLE_CITY_CENTER",                               "+{1_num} [ICON_CULTURE] 文化值来自相邻的市中心。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_GOLD_CITY_CENTER",                                         "+{1_num} [ICON_Gold] 金币来自相邻的市中心。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_GOLD_HANSA",                                               "+{1_num} [ICON_Gold] 金币来自相邻的商业同业工会。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_GOLD_INDUSTRIAL_ZONE",                                     "+{1_num} [ICON_Gold] 金币来自相邻的工业区。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_COMMERCIAL_GOLD",                                          "+{1_num} [ICON_Gold] 金币来自相邻的商业区。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SUGUBA_GOLD",                                              "+{1_num} [ICON_Gold] 金币来自相邻的曼丁哥市场。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DESERT_SCIENCE",                                           "+{1_num} [ICON_Science] 科技值来自相邻的沙漠单元格。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DESERT_HILLS_SCIENCE",                                     "+{1_num} [ICON_Science] 科技值来自相邻的沙漠（丘陵）单元格。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_HARBOR_INDUSTRIAL_PRODUCTION",                             "+{1_num} [ICON_Production] 生产力来自相邻的港口。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_ROYALDOCK_INDUSTRIAL_PRODUCTION",                          "+{1_num} [ICON_Production] 生产力来自相邻的皇家海军船坞。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_COTHON_INDUSTRIAL_PRODUCTION",                             "+{1_num} [ICON_Production] 生产力来自相邻的U型港。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_RIVER_HANSA_PRODUCTION",                                   "+{1_num} [ICON_Production] 生产力来自相邻河流。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_HARBOR_HANSA_PRODUCTION",                                  "+{1_num} [ICON_Production] 生产力来自相邻的港口。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_ROYALDOCK_HANSA_PRODUCTION",                               "+{1_num} [ICON_Production] 生产力来自相邻的皇家海军船坞。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_COTHON_HANSA_PRODUCTION",                                  "+{1_num} [ICON_Production] 生产力来自相邻的U型港。"),
    ("zh_Hans_CN",  "LOC_PROJECT_BREAD_AND_CIRCUSES_DESCRIPTION",                            "城市项目，可增加此城市对自身和对附近其他城市施加的忠诚度压力。[NEWLINE][NEWLINE]项目启动后，每位 [ICON_Citizen] 公民每回合对此城所施加的忠诚度压力+1。此忠诚度压力还将影响9个单元格以内的其他城市，但每远离1个单元格，效果减弱10%。项目完成后此城立即+20忠诚度。[NEWLINE][NEWLINE]需要先建成“娱乐设施”区域。"),
    ("zh_Hans_CN",  "LOC_ALLIANCE_LV2_RESEARCH_EFFECT_1",                                    "每10回合（标准游戏速度下）解锁1个您盟友已研究或提升，而您尚未研究之科技的 [ICON_TechBoosted] 尤里卡"),
    ("zh_Hans_CN",  "LOC_PEDIA_CONCEPTS_PAGE_ALLIANCES_1_CHAPTER_CONTENT_PARA_1",            "同盟是两个不同文明间相互协商、在某方面进行合作的一种关系。结为同盟之前双方必须首先宣布友谊，且均已完成市政“行政部门”的研究。[NEWLINE][NEWLINE]同盟类型有数种，提供的益处皆有所不同。与其他玩家处于同盟关系时，每回合将获得同盟点数。获得足够的点数后同盟等级将提升，产生更多益处。与盟友进行贸易可提升获得的同盟点数。同盟等级效果叠加计算，如果处于第3级同盟，则也会获得第1级和第2级效果。[NEWLINE][NEWLINE]每种同盟均会使双方开放边界并共同防御。盟友之间无法宣战。[NEWLINE][NEWLINE]您只能和其他文明结成一种同盟。一旦结成一类同盟，则无法与其他文明再次结成此类同盟，但可与之结成其他类型的同盟。举例而言，您与朝鲜结成研究同盟后便无法再与克里结成研究同盟，但却可以与其建立军事、文化、宗教或经济同盟。注意，游戏中最多只能结缔5个同盟。[NEWLINE]研究同盟[NEWLINE][ICON_BULLET] 第1级：盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_Science] 科技值。[NEWLINE][ICON_BULLET] 第2级：盟友每10回合共享1个科技提升（标准速度下）。[NEWLINE][ICON_BULLET] 第3级：与盟友研究相同科技、或研究盟友已研究完成的科技时获得 [ICON_Science] 科技值加成；盟友已研究您完成的科技时也可获得科技值加成。[NEWLINE][NEWLINE]文化同盟[NEWLINE][ICON_BULLET] 第1级：盟友之间不会相互施加忠诚度压力；盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_CULTURE] 文化值。[NEWLINE][ICON_BULLET] 第2级：城市与盟友之间存在 [ICON_TradeRoute] 贸易路线时，将根据起源城市中建造的区域获得更多 [ICON_GreatPerson] 伟人点数。[NEWLINE][ICON_BULLET] 第3级：您将获得盟友城市产出的部分 [ICON_Tourism] 旅游业绩和 [ICON_CULTURE] 文化值。[NEWLINE][NEWLINE]军事同盟[NEWLINE][ICON_BULLET] 第1级：与双方盟友均已宣战的文明作战时将获得 [ICON_Strength] 战斗力加成。[NEWLINE][ICON_BULLET] 第2级：盟友之间共享能见度；其中一个盟友处于战争状态时，双方生产军事单位时都将获得 [ICON_Production] 生产力加成。[NEWLINE][ICON_BULLET] 第3级：单位初始便拥有一次奖励升级。[NEWLINE][NEWLINE]宗教同盟[NEWLINE][ICON_BULLET] 第1级：不会对盟友的城市释放宗教压力；盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_Faith] 信仰值。[NEWLINE][ICON_BULLET] 第2级：与非盟友创建的其他宗教进行宗教战争时获得 [ICON_Religion] 宗教战斗力加成。[NEWLINE][ICON_BULLET] 第3级：基于信仰盟友宗教的 [ICON_Citizen] 公民数量获得信仰值；在没有盟友宗教信徒的城市中获得奖励宗教压力。[NEWLINE][NEWLINE]经济同盟[NEWLINE][ICON_BULLET] 第1级：盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_Gold] 黄金。[NEWLINE][ICON_BULLET] 第2级：每个视盟友为宗主国的城邦将提供一点[ICON_ENVOY]使者点数。[NEWLINE][ICON_BULLET] 第3级：盟友之间共享双方获得的全部城邦宗主国加成。")
    ;

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_RESOURCE_GOLD_NAME",                                            "黄金"),
    ("zh_Hans_CN",  "LOC_PEDIA_RESOURCES_PAGE_RESOURCE_GOLD_CHAPTER_HISTORY_PARA_1",     "黄金是一种柔软、有光泽和延展性的金属，在历史上一直受到人们的珍视。这是一种稀有金属，它的稀有性大大增加了它的价值。尽管黄金有一些工业和医疗用途，但它主要用作铸币或装饰用途，装饰珠宝、杯子、器皿以及超级富豪和权贵的马桶。 ");

--------------------------------------------------------------------------------
-- projects
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                     Text)
values
    ("LOC_PROJECT_CIRCUSES_AND_BREAD_HD_NAME",                                "circuses and bread"),
    ("LOC_PROJECT_CIRCUSES_AND_BREAD_HD_SHORT_NAME",                          "circuses and bread"),
    ("LOC_PROJECT_CIRCUSES_AND_BREAD_HD_DESCRIPTION",                         "City project which increases the Loyalty pressure that this city exerts on itself and other cities nearby.[NEWLINE][NEWLINE]While active, each of your [ICON_Citizen] Citizens here exerts +2 Loyalty pressure to this city. This pressure also affects other cities within 9 tiles, but is 10% less effective per tile. Once completed, instantly gain +20 Loyalty in this city."),
    ("LOC_PROJECT_ENDLESS_MONEY_HD_NAME",                                     "endless money"),
    ("LOC_PROJECT_ENDLESS_MONEY_HD_SHORT_NAME",                               "endless money"),
    ("LOC_PROJECT_ENDLESS_MONEY_HD_DESCRIPTION",                              "City project which provides a huge amount of [ICON_Gold] Gold every turn."),
    ("LOC_PROJECT_GRANT_RESOURCE_HORSES_HD_NAME",                             "breeding good foals"),
    ("LOC_PROJECT_GRANT_RESOURCE_HORSES_HD_SHORT_NAME",                       "breeding good foals"),
    ("LOC_PROJECT_GRANT_RESOURCE_HORSES_HD_DESCRIPTION",                      "Stable project. Once completed, instantly gain +20 [ICON_RESOURCE_HORSES] Horses."),
    ("LOC_PROJECT_GRANT_RESOURCE_IRON_HD_NAME",                               "earthen blast furnace"),
    ("LOC_PROJECT_GRANT_RESOURCE_IRON_HD_SHORT_NAME",                         "earthen blast furnace"),
    ("LOC_PROJECT_GRANT_RESOURCE_IRON_HD_DESCRIPTION",                        "Barracks project. Once completed, instantly gain +20 [ICON_RESOURCE_IRON] Iron."),
    ("LOC_PROJECT_GRANT_RESOURCE_NITER_HD_NAME",                              "high explosives"),
    ("LOC_PROJECT_GRANT_RESOURCE_NITER_HD_SHORT_NAME",                        "high explosives"),
    ("LOC_PROJECT_GRANT_RESOURCE_NITER_HD_DESCRIPTION",                       "Armory project. Once completed, instantly gain +20 [ICON_RESOURCE_NITER] Niter."),
    ("LOC_PROJECT_GRANT_RESOURCE_COAL_HD_NAME",                               "specialty fuels"),
    ("LOC_PROJECT_GRANT_RESOURCE_COAL_HD_SHORT_NAME",                         "specialty fuels"),
    ("LOC_PROJECT_GRANT_RESOURCE_COAL_HD_DESCRIPTION",                        "Armory project. Once completed, instantly gain +20 [ICON_RESOURCE_COAL] Coal."),
    ("LOC_PROJECT_GRANT_RESOURCE_OIL_HD_NAME",                                "shale extraction"),
    ("LOC_PROJECT_GRANT_RESOURCE_OIL_HD_SHORT_NAME",                          "shale extraction"),
    ("LOC_PROJECT_GRANT_RESOURCE_OIL_HD_DESCRIPTION",                         "Military academy project. Once completed, instantly gain +20 [ICON_RESOURCE_OIL] Oil."),
    ("LOC_PROJECT_GRANT_RESOURCE_ALUMINUM_HD_NAME",                           "rare earth research"),
    ("LOC_PROJECT_GRANT_RESOURCE_ALUMINUM_HD_SHORT_NAME",                     "rare earth research"),
    ("LOC_PROJECT_GRANT_RESOURCE_ALUMINUM_HD_DESCRIPTION",                    "Military academy project. Once completed, instantly gain +20 [ICON_RESOURCE_ALUMINUM] Aluminum."),
    ("LOC_PROJECT_GRANT_RESOURCE_URANIUM_HD_NAME",                            "gas centrifugal"),
    ("LOC_PROJECT_GRANT_RESOURCE_URANIUM_HD_SHORT_NAME",                      "gas centrifugal"),
    ("LOC_PROJECT_GRANT_RESOURCE_URANIUM_HD_DESCRIPTION",                     "Military academy project. Once completed, instantly gain +20 [ICON_RESOURCE_URANIUM] Uranium.");

-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                    Text)
values
    ("zh_Hans_CN",  "LOC_PROJECT_CIRCUSES_AND_BREAD_HD_NAME",                                "马戏与面包"),
    ("zh_Hans_CN",  "LOC_PROJECT_CIRCUSES_AND_BREAD_HD_SHORT_NAME",                          "马戏与面包"),
    ("zh_Hans_CN",  "LOC_PROJECT_CIRCUSES_AND_BREAD_HD_DESCRIPTION",                         "城市项目，可增加此城市对自身和对附近其他城市施加的忠诚度压力。[NEWLINE][NEWLINE]项目启动后，每位 [ICON_Citizen] 公民每回合对此城所施加的忠诚度压力+2。此忠诚度压力还将影响9个单元格以内的其他城市，但每远离1个单元格，效果减弱10%。项目完成后此城立即+20忠诚度。"),
    ("zh_Hans_CN",  "LOC_ALLIANCE_LV2_RESEARCH_EFFECT_1",                                    "每10回合（标准游戏速度下）解锁1个您盟友已研究或提升，而您尚未研究之科技的 [ICON_TechBoosted] 尤里卡"),
    ("zh_Hans_CN",  "LOC_PEDIA_CONCEPTS_PAGE_ALLIANCES_1_CHAPTER_CONTENT_PARA_1",            "同盟是两个不同文明间相互协商、在某方面进行合作的一种关系。结为同盟之前双方必须首先宣布友谊，且均已完成市政“行政部门”的研究。[NEWLINE][NEWLINE]同盟类型有数种，提供的益处皆有所不同。与其他玩家处于同盟关系时，每回合将获得同盟点数。获得足够的点数后同盟等级将提升，产生更多益处。与盟友进行贸易可提升获得的同盟点数。同盟等级效果叠加计算，如果处于第3级同盟，则也会获得第1级和第2级效果。[NEWLINE][NEWLINE]每种同盟均会使双方开放边界并共同防御。盟友之间无法宣战。[NEWLINE][NEWLINE]您只能和其他文明结成一种同盟。一旦结成一类同盟，则无法与其他文明再次结成此类同盟，但可与之结成其他类型的同盟。举例而言，您与朝鲜结成研究同盟后便无法再与克里结成研究同盟，但却可以与其建立军事、文化、宗教或经济同盟。注意，游戏中最多只能结缔5个同盟。[NEWLINE]研究同盟[NEWLINE][ICON_BULLET] 第1级：盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_Science] 科技值。[NEWLINE][ICON_BULLET] 第2级：盟友每10回合共享1个科技提升（标准速度下）。[NEWLINE][ICON_BULLET] 第3级：与盟友研究相同科技、或研究盟友已研究完成的科技时获得 [ICON_Science] 科技值加成；盟友已研究您完成的科技时也可获得科技值加成。[NEWLINE][NEWLINE]文化同盟[NEWLINE][ICON_BULLET] 第1级：盟友之间不会相互施加忠诚度压力；盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_CULTURE] 文化值。[NEWLINE][ICON_BULLET] 第2级：城市与盟友之间存在 [ICON_TradeRoute] 贸易路线时，将根据起源城市中建造的区域获得更多 [ICON_GreatPerson] 伟人点数。[NEWLINE][ICON_BULLET] 第3级：您将获得盟友城市产出的部分 [ICON_Tourism] 旅游业绩和 [ICON_CULTURE] 文化值。[NEWLINE][NEWLINE]军事同盟[NEWLINE][ICON_BULLET] 第1级：与双方盟友均已宣战的文明作战时将获得 [ICON_Strength] 战斗力加成。[NEWLINE][ICON_BULLET] 第2级：盟友之间共享能见度；其中一个盟友处于战争状态时，双方生产军事单位时都将获得 [ICON_Production] 生产力加成。[NEWLINE][ICON_BULLET] 第3级：单位初始便拥有一次奖励升级。[NEWLINE][NEWLINE]宗教同盟[NEWLINE][ICON_BULLET] 第1级：不会对盟友的城市释放宗教压力；盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_Faith] 信仰值。[NEWLINE][ICON_BULLET] 第2级：与非盟友创建的其他宗教进行宗教战争时获得 [ICON_Religion] 宗教战斗力加成。[NEWLINE][ICON_BULLET] 第3级：基于信仰盟友宗教的 [ICON_Citizen] 公民数量获得信仰值；在没有盟友宗教信徒的城市中获得奖励宗教压力。[NEWLINE][NEWLINE]经济同盟[NEWLINE][ICON_BULLET] 第1级：盟友之间的 [ICON_TradeRoute] 贸易路线可产出更多 [ICON_Gold] 黄金。[NEWLINE][ICON_BULLET] 第2级：每个视盟友为宗主国的城邦将提供一点[ICON_ENVOY]使者点数。[NEWLINE][ICON_BULLET] 第3级：盟友之间共享双方获得的全部城邦宗主国加成。"),
    ("zh_Hans_CN",  "LOC_PROJECT_ENDLESS_MONEY_HD_NAME",                                     "多钱善贾"),
    ("zh_Hans_CN",  "LOC_PROJECT_ENDLESS_MONEY_HD_SHORT_NAME",                               "多钱善贾"),
    ("zh_Hans_CN",  "LOC_PROJECT_ENDLESS_MONEY_HD_DESCRIPTION",                              "城市项目，每回合提供巨额 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_HORSES_HD_NAME",                             "良驹育种"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_HORSES_HD_SHORT_NAME",                       "良驹育种"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_HORSES_HD_DESCRIPTION",                      "马厩项目，项目完成后提供20点 [ICON_RESOURCE_HORSES] 马。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_IRON_HD_NAME",                               "土制高炉"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_IRON_HD_SHORT_NAME",                         "土制高炉"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_IRON_HD_DESCRIPTION",                        "兵营项目，项目完成后提供20点 [ICON_RESOURCE_IRON] 铁。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_NITER_HD_NAME",                              "烈性炸药"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_NITER_HD_SHORT_NAME",                        "烈性炸药"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_NITER_HD_DESCRIPTION",                       "兵工厂项目，项目完成后提供20点 [ICON_RESOURCE_NITER] 硝石。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_COAL_HD_NAME",                               "特种燃料"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_COAL_HD_SHORT_NAME",                         "特种燃料"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_COAL_HD_DESCRIPTION",                        "兵工厂项目，项目完成后提供20点 [ICON_RESOURCE_COAL] 煤。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_OIL_HD_NAME",                                "页岩提取"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_OIL_HD_SHORT_NAME",                          "页岩提取"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_OIL_HD_DESCRIPTION",                         "军事学院项目，项目完成后提供20点 [ICON_RESOURCE_OIL] 石油。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_ALUMINUM_HD_NAME",                           "稀土研究"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_ALUMINUM_HD_SHORT_NAME",                     "稀土研究"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_ALUMINUM_HD_DESCRIPTION",                    "军事学院项目，项目完成后提供20点 [ICON_RESOURCE_ALUMINUM] 铝。"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_URANIUM_HD_NAME",                            "气体离心"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_URANIUM_HD_SHORT_NAME",                      "气体离心"),
    ("zh_Hans_CN",  "LOC_PROJECT_GRANT_RESOURCE_URANIUM_HD_DESCRIPTION",                     "军事学院项目，项目完成后提供20点 [ICON_RESOURCE_URANIUM] 铀。");

--------------------------------------------------------------------------------   
-- error texts
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                     Text)
values
    ("LOC_CITY_YIELD_MODIFIER_PER_GOVERNOR_TITLE_TOOLTIP",                    "{Value : number +#;-#}% ({ActualValue : number +#.#;-#.#}) from [ICON_Governor] Governor with {1} {1 : plural 1?Promotion; other?Promotions;}");

-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_CITY_YIELD_FROM_TERRAIN_TOOLTIP",                               "{Value : number +#.#;-#.#}来自地形"),
    ("zh_Hans_CN",  "LOC_PLAYER_YIELD_FAITH_FROM_BELIEFS",                               "{Value : number +#.#;-#.#}来自信仰"),
    ("zh_Hans_CN",  "LOC_CITY_YIELD_MODIFIER_PER_GOVERNOR_TITLE_TOOLTIP",                "{Value : number +#;-#}%（{ActualValue : number +#.#;-#.#}）来自拥有{1}次{1 : plural 1?升级; other?升级;}的 [ICON_Governor] 总督");