--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                             Text)
values
    ("LOC_DISTRICT_HOLY_SITE_HD_DESCRIPTION",                         "A district in your city for religious worship. +5% [ICON_Faith] Faith if there exists a third-tier worship building in the district. +1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_LAVRA_HD_DESCRIPTION",                             "A district unique to Russia for religious activity. Replaces the Holy Site district and cheaper to build.[NEWLINE][NEWLINE]The citizen work in this district also yields Great Writer, Artist and Musician points. Your city border grows by one tile each time a Great Person is expended in this city. +5% [ICON_Faith] Faith if there exists a third-tier worship building in the district. +1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_HANSA_HD_DESCRIPTION",                             "A district unique to Germany for industrial activity. Replaces the Industrial Zone district and cheaper to build.[NEWLINE][NEWLINE]+2 [ICON_Production] when adjacent to river. +2 [ICON_Production] Production bonus for each adjacent Harbor, Aqueduct, and Dam districts. +2 [ICON_Production] Production bonus for each adjacent Canal Districts. +1 [ICON_Production] Production bonus for each adjacent Commercial Hub districts and resources (doubles after researching Apprenticeship). +1 [ICON_Production] Production bonus for every two adjacent district tiles. +1 [Icon_Production] Production to adjacent Resources, provide Major adjacency bonus to Commercial Hub Districts. -1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_OPPIDUM_HD_DESCRIPTION",                           "A district unique to Gaul that is cheaper than the district it replaces, the Industrial Zone. The Oppidum district is defensible with a ranged attack. When the first Oppidum is constructed the Metal Casting technology is unlocked.[NEWLINE][NEWLINE]+2 [ICON_Production] Production adjacency bonus from Quarries and strategic resources. -1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_AQUEDUCT_HD_DESCRIPTION",                          "A district that provides this city with a source of fresh water from an adjacent River, Lake, Oasis, or Mountain. Cities that do not yet have existing fresh water receive up to 6 [ICON_Housing] Housing. Cities that already have existing fresh water will instead get +2 [ICON_Housing] Housing. If built adjacent to a Geothermal Fissure +1 [ICON_Amenities] Amenity. Prevents [ICON_Food] Food loss during Drought. All farm adjacent to fresh water or Aqueduct +1 [ICON_FOOD] Food. [NEWLINE] Must be built adjacent to the City Center. Military Engineers can spend a charge to complete 30% of an Aqueduct's production.One per city."),
    ("LOC_DISTRICT_BATH_HD_DESCRIPTION",                              "A district unique to Rome for city growth. Replaces the Aqueduct district and cheaper to build.[NEWLINE][NEWLINE]It provides this city with a source of fresh water from an adjacent River, Lake, Oasis, or Mountain. Cities that do not yet have existing fresh water receive up to 6 [ICON_Housing] Housing. Cities that already have existing fresh water will instead get +2 [ICON_Housing] Housing. If built adjacent to a Geothermal Fissure +1 [ICON_Amenities] Amenity. In all cases the Bath provides an additional bonus of +2 [ICON_Housing] Housing and +1 [ICON_Amenities] Amenity. Prevents [ICON_Food] Food loss during Drought. Must be built adjacent to the City Center. Military Engineers can spend a charge to complete 30% of a Bath's production.All farms adjacent to fresh water or Bath +1 [ICON_FOOD] Food. [NEWLINE] Must be built adjacent to the City Center. Military Engineers can spend a charge to complete 20% of an Aqueduct's production.One per city."),
    ("LOC_DISTRICT_HARBOR_HD_DESCRIPTION",                            "A district for naval activity in your city. Also removes the [ICON_Movement] Movement penalty for embarking and disembarking to and from this tile. Must be built on Coast or Lake Terrain adjacent to land. +2 [ICON_HOUSING] Housing if this city is adjacent to coasts and lakes. Fishing Boats +1 [ICON_FOOD] Food in this city. +25% [ICON_PRODUCTION] production towards all naval units."),
    ("LOC_DISTRICT_COTHON_HD_DESCRIPTION",                            "A district unique to Phoenicia for naval activity in your city. Replaces the Harbor district and cheaper to build. Must be built on Coast or Lake Terrain adjacent to land. +2 [ICON_HOUSING] Housing if this city is adjacent to coasts and lakes. Fishing Boats +1 [ICON_FOOD] Food in this city. +15% growth rate for this city.[NEWLINE][NEWLINE]+50% [ICON_PRODUCTION] Production towards naval units and Settlers in this city. All wounded naval units in this city’s borders heal +100 HP each turn."),
    ("LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_HD_DESCRIPTION",               "A district unique to England for naval activity in your city. Replaces the Harbor district. Also removes the [ICON_Movement] Movement penalty for embarking and disembarking to and from this tile. Must be built on Coast or Lake Terrain adjacent to land. +2 [ICON_HOUSING] Housing if this city is adjacent to coasts and lakes. Fishing Boats +1 [ICON_FOOD] Food in this city. +25% [ICON_PRODUCTION] production towards all naval units.[NEWLINE][NEWLINE]+1 [ICON_Movement] Movement for all naval units built in Dockyard. +2 [ICON_Gold] Gold and +4 Loyalty per turn when built on a foreign continent. +2 [ICON_Gold] Gold bonus for each adjacent Industrial Zone. Accumulating Strategic resources in the city gain an additional +2 per turn."),
    ("LOC_DISTRICT_IKANDA_HD_DESCRIPTION",                            "A district unique to Zulu which replaces the Encampment. Provides +1 [ICON_Housing] Housing. Once the Civic or Technology prerequisite is met, Corps and Armies can be built outright. Buildings in the Ikanda receive +2 [ICON_GOLD] Gold and +1 [ICON_SCIENCE] Science. Faster Corps and Army creation.[NEWLINE] +30% [ICON_PRODUCTION] Production towards Land Military Units. +1 [ICON_PRODUCTION] Production for improved [ICON_RESOURCE_STONE] Stone and [ICON_RESOURCE_COPPER] Copper resource in this city. -1 Appeal to adjacent tiles. Accumulating Strategic resources in the city gain an additional +2 per turn."),
    ("LOC_DISTRICT_THANH_HD_DESCRIPTION",                             "A district unique to Vietnam which replaces the Encampment. +2 [ICON_CULTURE] Culture for each adjacent district. After Flight is researched receive [ICON_TOURISM] Tourism equal to the [ICON_CULTURE] Culture output. This district does not require population, is cheaper to build, cannot be built adjacent to the city center, and is not a specialty district.[NEWLINE]One per city. +15% [ICON_PRODUCTION] Production towards Land Military Units. +1 [ICON_PRODUCTION] Production for improved [ICON_RESOURCE_STONE] Stone and [ICON_RESOURCE_COPPER] Copper resource in this city. Accumulating Strategic resources in the city gain an additional +2 per turn."),
    ("LOC_DISTRICT_ENCAMPMENT_HD_DESCRIPTION",                        "A district in your city for military facilities.[NEWLINE] +15% [ICON_PRODUCTION] Production towards Land Military Units. +1 [ICON_PRODUCTION] Production for improved [ICON_RESOURCE_STONE] Stone and [ICON_RESOURCE_COPPER] Copper resource in this city. Accumulating Strategic resources in the city gain an additional +2 per turn. -1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_MBANZA_HD_DESCRIPTION",                            "A district unique to Kongo that can only be constructed in Rainforest or Woods. Replaces the Neighborhood district but is available earlier and cheaper to build. Provides +5 [ICON_Housing] Housing, +3 [ICON_Food] Food, and +5 [ICON_Gold] Gold, regardless of Appeal. +1 [ICON_FOOD] Food to all adjacent Forest and Rainforest tiles. Allows the purchasing of Settlers and Builders using [ICON_Faith] Faith."),
    ("LOC_DISTRICT_AERODROME_HD_DESCRIPTION",                         "A district that allows you to build and store aircraft. Cannot be built on Hills. Can be built regardless of number of citizens. +25% [Icon_Production] Production towards Air Units. -1 Appeal to adjacent tiles. "),
    ("LOC_DISTRICT_DIPLOMATIC_QUARTER_HD_DESCRIPTION",                "Your civilization receives +1 [ICON_FAVOR] Diplomatic Favor for each Delegation or Embassy from a foreign civilization through diplomacy. Awards 1 [ICON_Envoy] Envoy when completed. Enemy Spies operate at 2 levels below normal targeting this district and adjacent districts. Only 1 can exist in your empire at a time. Grants the ability to construct an additional Spy."), --  if built next to the city center
    ("LOC_DISTRICT_ACROPOLIS_HD_DESCRIPTION",                         "A district unique to Greece for cultural sites. Replaces the Theater Square district and cheaper to build. Awards 1 [ICON_Envoy] Envoy when completed.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture bonus for each adjacent district and an additional +2 [ICON_Culture] Culture bonus for adjacent City Center. +1 [ICON_CULTURE] Culture when built on tiles with Charming Appeal. +3 [ICON_CULTURE] Culture when built on tiles with Breathtaking Appeal. Can only be built on Hills. +1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_THEATER_HD_DESCRIPTION",                           "A district in your city for cultural sites. +1 [ICON_CULTURE] Culture when built on tiles with Charming Appeal. +3 [ICON_CULTURE] Culture when built on tiles with Breathtaking Appeal."),
    ("LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_HD_DESCRIPTION",       "A district placed out on a coastal tile dedicated to keeping your people happy by increasing [ICON_Amenities] Amenities. Cannot be built in a city with an Entertainment Complex."),
    ("LOC_DISTRICT_PRESERVE_HD_DESCRIPTION",                          "+2 [ICON_Housing] Housing when built on tiles with Charming Appeal. +3 [ICON_Housing] Housing when built on tiles with Breathtaking Appeal. Culture bombs adjacent neutral tiles. Can be built on Woods. +1 Appeal to adjacent tiles."),
    ("LOC_DISTRICT_WATER_STREET_CARNIVAL_HD_DESCRIPTION",             "A district unique to Brazil. Replaces the Water Park district, and provides +4 [ICON_Amenities] Amenities. Also unlocks the Carnival project, which grants an additional +1 [ICON_Amenities] Amenity when underway and a variety of [ICON_GreatPerson] Great People points once completed. Cannot be built in a city with a Street Carnival."),
    ("LOC_DISTRICT_STREET_CARNIVAL_HD_DESCRIPTION",                   "A district unique to Brazil. Replaces the Entertainment Complex district, and provides +4 [ICON_Amenities] Amenities. Also unlocks the Carnival project, which grants an additional +1 [ICON_Amenities] Amenity when underway and a variety of [ICON_GreatPerson] Great People points once completed. Cannot be built in a city with a Copacabana."),
    ("LOC_DISTRICT_HIPPODROME_HD_DESCRIPTION",                        "A district unique to Byzantium. Replaces the Entertainment Complex district, provides +4 [ICON_Amenities] Amenities, and is cheaper to build. When the Hippodrome and buildings in this district are constructed, receive a Heavy Cavalry unit. Units granted from this district do not have a resource maintenance cost. Cannot be built in a city with a Water Park."),
    ("LOC_DISTRICT_COMMERCIAL_HUB_HD_DESCRIPTION",                    "A district in your city specializing in finance and trade. +1 [ICON_Food] Food and +1 [ICON_Production] Production from all domestic [ICON_TradeRoute] Trade Routes. +1 [ICON_Culture] Culture and +1 [ICON_Science] Science from all international [ICON_TradeRoute] Trade Routes. +1 [ICON_Food] Food to each improved [ICON_RESOURCE_CATTLE] Cattle and [ICON_RESOURCE_SHEEP] Sheep in this city."),
    ("LOC_DISTRICT_SUGUBA_HD_DESCRIPTION",                            "A district unique to Mali specializing in finance and trade that replaces the Commercial Hub, gains major adjacency bonus when adjacent to Holy Site Districts. Enable purchasing Districts with [ICON_Gold] Gold in this city. Units, Buildings, and Districts are 20% cheaper to purchase with [ICON_GOLD] Gold and [ICON_FAITH] Faith in this City.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture and +1 [ICON_Science] Science from all international [ICON_TradeRoute] Trade Routes. +1 [ICON_Food] Food to each improved [ICON_RESOURCE_CATTLE] Cattle and [ICON_RESOURCE_SHEEP] Sheep in this city."), --[NEWLINE][NEWLINE]+2 [ICON_Gold] Gold bonus for each adjacent Holy Site. +2 [ICON_Gold] Gold bonus for each adjacent Harbor.
    ("LOC_DISTRICT_CANAL_HD_DESCRIPTION",                             "A district built on flat land to connect two bodies of water or a body of water to a City Center. +3 [ICON_Gold] Gold for adjacent tiles. [ICON_TradeRoute] Trade Routes traveling through it can multiply the [ICON_Gold] Gold they get from districts at their destination. Canals may either go straight through the hex or bend by 60 degrees. However three-way Canal junctures are not allowed and Canals must have a full land tile on each side of the waterway they create. Military Engineers can spend a charge to complete 30% of a Canal's production."),
    ("LOC_DISTRICT_DAM_HD_DESCRIPTION",                               "A district built on a Floodplains tile to improve the comfort of living along this river. +2 [ICON_Food] Food for adjacent farms and plantations. Prevents damage from flooding of this river (though yields from flooding drop by 50%). Prevents [ICON_Food] Food loss during Drought. Only one may be built along each river's floodplain (whichever player completes one first) and the river must traverse at least two sides of the Dam hex. Military Engineers can spend a charge to complete 30% of a Dam's production."),
    ("LOC_DISTRICT_SEOWON_HD_DESCRIPTION",                            "A district unique to Korea. Replaces the Campus. +4 [Icon_Science] Science. Have more citizen slots.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                             Text)
values
    ("zh_Hans_CN",  "LOC_DISTRICT_HOLY_SITE_HD_DESCRIPTION",                         "您城市里的宗教祭祀区。若该区域内含有三级宗教建筑，则本城+5% [ICON_Faith] 信仰值。为相邻单元格+1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_LAVRA_HD_DESCRIPTION",                             "俄罗斯特色宗教活动区域，代替圣地，建造费用更低。[NEWLINE][NEWLINE]该区域内的专家也产出大作家、大艺术家、大音乐家点数。此城市每消耗一位伟人，城市边界则扩张一个单元格。若该区域内含有三级宗教建筑，则本城+5% [ICON_Faith] 信仰值。为相邻单元格+1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_HANSA_HD_DESCRIPTION",                             "德国特色工业区域，替代工业区，建造费用更低。[NEWLINE][NEWLINE]相邻河流时获得+2 [ICON_Production] 生产力加成。可从每个相邻的港口、水渠和堤坝区域处获得+2 [ICON_Production] 生产力加成。可从每个相邻的运河区域处获得+3 [ICON_Production] 生产力加成。可从每个相邻的商业中心和资源处获得+1 [ICON_Production] 生产力加成（研究学徒后变为+2）。每两处相邻区域为其提供1点 [ICON_Production] 生产力加成。为相邻的资源+1 [ICON_Production] 生产力，为商业中心提供大量相邻加成。给相邻单元格-1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_OPPIDUM_HD_DESCRIPTION",                           "高卢特色区域，替代“工业区”，建造花费更低。“奥皮杜姆”区域具有防御力且可执行远程攻击。建成此区域后，即可解锁“金属铸造”科技。[NEWLINE][NEWLINE]每与一个采石场改良设施或战略资源相邻，则+2 [ICON_Production] 生产力。为相邻单元格-1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_AQUEDUCT_HD_DESCRIPTION",                          "区域从相邻河流、湖泊、绿洲或山脉引水，为该城市提供淡水资源。没有淡水资源的城市最多获得6个 [ICON_Housing] 住房。相反，已有淡水资源的城市 [ICON_Housing] 住房数量+2；若与地热裂缝相邻，提供+1 [ICON_Amenities] 宜居度。干旱时可防止 [ICON_Food] 食物损失。本城所有淡水或相邻水渠的农田+1 [ICON_FOOD] 食物。[NEWLINE] 必须修建在与市中心相邻的单元格中。军事工程师可消耗1次使用次数来完成水渠30%的修建进度。但1个城市只允许建造1个。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_BATH_HD_DESCRIPTION",                              "促进城市发展的罗马特色区域。取代水渠，建造费用更低。[NEWLINE][NEWLINE]从相邻河流、湖泊、绿洲或山脉引水，为该城市提供淡水资源。尚未拥有淡水资源的城市最多获得6个 [ICON_Housing] 住房。已有淡水资源的城市则+2 [ICON_Housing] 住房。若与地热裂缝相邻，提供+1 [ICON_Amenities] 宜居度。在任何情况下，浴场都能额外提供+2 [ICON_Housing] 住房和+1 [ICON_Amenities] 宜居度。干旱时可防止 [ICON_Food] 食物损失。必须修建在与市中心相邻的单元格中。本城所有淡水或相邻浴场的农田+1 [ICON_FOOD] 食物。[NEWLINE] 军事工程师可消耗1次使用次数来完成浴场30%的修建进度。但1个城市只允许建造1个。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_HARBOR_HD_DESCRIPTION",                            "城市中的海军活动区域。同时取消从该单元格上下船的 [ICON_Movement] 移动力消耗。必须修建在和陆地相邻的海岸或湖泊单元格上。如此城与海岸或湖边相邻，则+2 [ICON_HOUSING] 住房。为本城的渔船 +1 [ICON_FOOD] 食物。对所有海军单位+25% [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_COTHON_HD_DESCRIPTION",                            "腓尼基特色城市海军活动区域，取代港口且建造成本更低。必须修建在海岸或与陆地相邻的湖泊地貌上。如此城与海岸或湖边相邻，则+2 [ICON_HOUSING] 住房。为本城的渔船+1 [ICON_FOOD] 食物，本城余粮+15%。[NEWLINE][NEWLINE]该城市的海军单位与开拓者的 [ICON_PRODUCTION] 生产力+50%。在该城范围内，所有受损海军单位每回合可恢复100点生命值。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_HD_DESCRIPTION",               "城市中的英国特色海军活动区域，取代港口且建造成本更低。同时移除该单元格的上船、下船 [ICON_Movement] 移动力减益。必须建在与陆地相邻的海岸或湖泊地形上。如此城与海岸或湖边相邻，则+2 [ICON_HOUSING] 住房。为本城的渔船 +1 [ICON_FOOD] 食物。对所有海军单位+25% [ICON_PRODUCTION] 生产力。[NEWLINE][NEWLINE]皇家海军船坞中建造的所有海军单位+1 [ICON_Movement] 移动力。修建在外国大陆上时+2 [ICON_Gold] 金币、每回合的忠诚度+4。相邻每个工业区+2 [ICON_Gold] 金币。本城正确改良的战略每回合积累+2。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_IKANDA_HD_DESCRIPTION",                            "祖鲁特色区域，替代军营。+1 [ICON_Housing] 住房。解锁相应的市政或科技后即可生产军团和军队。伊坎达中的建筑+2 [ICON_GOLD] 金币、+1 [ICON_SCIENCE] 科技值。创建军团和军队的速度更快。[NEWLINE] 对陆地军事单位+30% 建造速度。此城中训练的所有抗骑兵单位+1 [ICON_Movement] 移动力。为本城已开发的[ICON_RESOURCE_STONE] 石头、 [ICON_RESOURCE_COPPER] 铜+1 [ICON_PRODUCTION] 生产力。本城正确改良的战略每回合积累+2。为相邻单元格-1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_THANH_HD_DESCRIPTION",                             "越南特色区域，替代“军营”。每与1个区域相邻，则+2 [ICON_CULTURE] 文化值。研究完“飞行”科技后，将获得与 [ICON_CULTURE] 文化值产量相等的 [ICON_TOURISM] 旅游业绩。此区域不需要人口、建造花费更低、无法建在市中心周围，也并非专业化区域。[NEWLINE]每个城市只允许建造1个。对陆地军事单位+15%建造速度。为本城已开发的 [ICON_RESOURCE_STONE] 石头、 [ICON_RESOURCE_COPPER] 铜+1 [ICON_PRODUCTION] 生产力。本城正确改良的战略每回合积累+2。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_ENCAMPMENT_HD_DESCRIPTION",                        "您城市里的军事机构区。[NEWLINE] 对陆地军事单位+15%建造速度。为本城的已开发的 [ICON_RESOURCE_STONE] 石头、 [ICON_RESOURCE_COPPER] 铜+1 [ICON_PRODUCTION] 生产力。本城正确改良的战略每回合积累+2。为相邻单元格-1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_MBANZA_HD_DESCRIPTION",                            "刚果特色区域，只能建在雨林或树林里。代替社区，可更早建造，且建造费用更低。无视魅力值，固定提供+5 [ICON_Housing] 住房、+3 [ICON_Food] 食物和+5 [ICON_Gold] 金币。为相邻的雨林和森林单元格 +1 [ICON_FOOD] 食物。允许使用 [ICON_Faith] 信仰值购买开拓者和建造者。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_AERODROME_HD_DESCRIPTION",                         "可用于建造和存放飞机的区域。不能建在丘陵上。建造不受人口限制。建造空中单位时，+25%建造速度。为相邻单元格-1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DIPLOMATIC_QUARTER_HD_DESCRIPTION",                "通过外交，外国文明的每个代表团或大使馆将为您的文明提供+1 [ICON_FAVOR] 外交支持。建成后奖励1名 [ICON_Envoy] 使者。敌方间谍将此区域和相邻区域当做目标时，其效果将降低2级。文明中一次仅限建造一座此区域。可额外招募一名间谍。"), --如建在市中心旁，则
    ("zh_Hans_CN",  "LOC_DISTRICT_ACROPOLIS_HD_DESCRIPTION",                         "希腊特色文化遗址区域，替代剧院广场，建造费用更低。建成后奖励1名 [ICON_Envoy] 使者。[NEWLINE][NEWLINE]每个相邻区域+1 [ICON_Culture] 文化值，每个相邻市中心额外+2 [ICON_Culture] 文化值。若位于拥有迷人魅力的单元格+1 [ICON_Culture] 文化值，惊艳单元格则+3 [ICON_Culture] 文化值。只能建在丘陵上。为相邻单元格+1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_THEATER_HD_DESCRIPTION",                           "您城市里的文化遗址区。若位于拥有迷人魅力的单元格+1 [ICON_Culture] 文化值，惊艳单元格则+3 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_HD_DESCRIPTION",       "建在海岸单元格上的区域，可增加 [ICON_Amenities] 宜居度，让人民生活幸福。无法建在拥有娱乐设施的城市中。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_PRESERVE_HD_DESCRIPTION",                          "若位于拥有迷人魅力的单元格+2 [ICON_Housing] 住房，惊艳单元格则+3 [ICON_Housing] 住房。对相邻的中立单元格施放文化炸弹。可以建造在森林上。为相邻单元格+1魅力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_WATER_STREET_CARNIVAL_HD_DESCRIPTION",             "巴西特色区域，代替水上乐园，+4 [ICON_Amenities] 宜居度。可解锁“狂欢节”项目，项目启动后即可额外+1 [ICON_Amenities] 宜居度，项目完成后可获得若干 [ICON_GreatPerson] 伟人点数。无法建在拥有“街头狂欢节”的城市中。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_STREET_CARNIVAL_HD_DESCRIPTION",                   "巴西特色区域，代替娱乐设施区域，+4 [ICON_Amenities] 宜居度。可解锁“狂欢节”项目，项目启动后即可额外+1 [ICON_Amenities] 宜居度，项目完成后可获得若干 [ICON_GreatPerson] 伟人点数。无法建在拥有“科帕卡瓦纳”的城市中。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_HIPPODROME_HD_DESCRIPTION",                        "拜占庭特色区域。替代“娱乐设施”区域，提供+4 [ICON_Amenities] 宜居度，且建造花费更低。在此区域中建成跑马场及建筑后，将获得1个重骑兵单位（此单位不消耗资源）。此区域提供的单位不消耗维护资源。无法建在拥有“水上乐园”的城市中。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_COMMERCIAL_HUB_HD_DESCRIPTION",                    "城市中专注于金融和贸易的区域。本城出发的国内 [ICON_TradeRoute] 贸易路线+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力，国际 [ICON_TradeRoute] 贸易路线+1 [ICON_Culture] 文化值和+1 [ICON_Science] 科技值。本城所有已开发的 [ICON_RESOURCE_CATTLE] 牛、 [ICON_RESOURCE_SHEEP] 羊+1 [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SUGUBA_HD_DESCRIPTION",                            "马里特色区域，专精于经济与贸易，取代商业中心，与圣地相邻获得大相邻加成。允许本城使用金币购买区域。使用 [ICON_GOLD] 金币和 [ICON_FAITH] 信仰值在此城中购买单位、建筑和区域时，费用减少20%。[NEWLINE][NEWLINE]本城出发的国内 [ICON_TradeRoute] 贸易路线+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力，国际 [ICON_TradeRoute] 贸易路线+1 [ICON_Culture] 文化值和+1 [ICON_Science] 科技值。本城所有已开发的 [ICON_RESOURCE_CATTLE] 牛、 [ICON_RESOURCE_SHEEP] 羊+1 [ICON_Food] 食物。"), --[NEWLINE][NEWLINE]每相邻一个圣地获得+2 [ICON_Gold] 金币加成。每相邻一个港口获得+2 [ICON_Gold] 金币加成。
    ("zh_Hans_CN",  "LOC_DISTRICT_CANAL_HD_DESCRIPTION",                             "建在平原上的区域，连接两块水域单元格或将一块水域单元格与市中心连接。为相邻的单元格提供+3 [ICON_Gold] 金币。如 [ICON_TradeRoute] 贸易路线途径此处，其将从目的地的区域处获得成倍 [ICON_Gold] 金币。运河可笔直穿过单元格，也可在其中进行60度转向。无法建造三向连接运河，且运河在其所建水路的两侧皆必须含有一个完整的陆地单元格。军事工程师可消耗1次使用次数来完成运河30%的修建进度。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DAM_HD_DESCRIPTION",                               "建造在泛滥平原单元格上的区域，可改善此江河流域旁的民生质量（但来自洪水的产出减半）。为相邻的农田和种植园+2 [ICON_Food] 食物。其可防止江河泛滥带来的损害，还可在干旱时防止 [ICON_Food] 食物损失。每条江河的泛滥平原中仅能建造1个（有文明建成便视为已建造），且江河必须至少穿过堤坝格位的两个面。军事工程师可消耗1次使用次数来完成堤坝30%的修建进度。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SEOWON_HD_DESCRIPTION",                            "朝鲜特色区域，代替学院。+4 [Icon_Science] 科技值。拥有更多的专家槽位。");
