--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                             Text)
values
    ("LOC_TRAIT_LEADER_KUBLAI_DESCRIPTION",                           "One extra Economic policy slot in any government. Receive the civilization traits after conquering another Civilization's Original [ICON_Capital] Capital city."),
    ("LOC_TRAIT_CIVILIZATION_WONDER_TOURISM_DESCRIPTION",             "+20% [ICON_Production] Production toward Medieval, Renaissance, and Industrial era wonders. [ICON_Tourism] Tourism from wonders of any era is +200%. Each wonder provides +1 of all yields to capital city, doubles when the wonder is at least Medieval era."),
    ("LOC_TRAIT_LEADER_SURROUNDED_BY_GLORY_DESCRIPTION",              "+5% [ICON_Culture] Culture per city-state you are the Suzerain of. After building an Acropolis District, the first [ICON_Envoy] Envoy you send to each city-state counts as two [ICON_Envoy] Envoys."),
    ("LOC_TRAIT_LEADER_THERMOPYLAE_DESCRIPTION",                      "Combat victories provide [ICON_Culture] Culture equal to 50% of the [ICON_Strength] Combat Strength of the defeated unit. (on Standard Speed) +1 [ICON_Strength] Combat Strength for every Military Policy slotted. Receive a free anti-cavalry unit when the Acropolis district is constructed."),
    ("LOC_TRAIT_LEADER_THUNDERBOLT_EXPANSION2_DESCRIPTION",           "Allows coastal raiding for all naval melee units and +50% [ICON_PRODUCTION] Production toward all naval melee units. In addition to normal pillage gains, receive [ICON_SCIENCE] Science from pillaging and coastal raiding Farms, Mines and Lumber Mills. Pillaging or coastal raiding Quarries, Pastures, Plantations, and Camps also provide [ICON_CULTURE] Culture. Gain the Viking Longship unique unit with Sailing."),
    ("LOC_TRAIT_LEADER_ROOSEVELT_COROLLARY_ROUGH_RIDER_DESCRIPTION",  "Units receive +5 [ICON_Strength] Combat Strength on their home continent. Envoys sent to City-States you have a [ICON_TradeRoute] Trade Route to count as two [ICON_Envoy] Envoys. Gain the Rough Rider unique unit with Ballistics."),
    ("LOC_TRAIT_CIVILIZATION_EJERCITO_PATRIOTA_DESCRIPTION",          "+1 [ICON_Movement] Movement to all units. Promoting a unit does not end that unit’s turn. Planations provides a Culture Bomb of unowned territory, and receive +1 [ICON_CULTURE] Culture."),
    ("LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_NAME",                    "Chiphyonjon"),
    ("LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_DESCRIPTION",             "Receive +1 [Icon_Governor] Governor Title each time a Seowon district or buildings inside a Seowon District is constructed in your [ICON_Capital] Capital."),
    ("LOC_TRAIT_LEADER_HWARANG_DESCRIPTION",                          "+3 [ICON_Amenities] Amenities, +5 [Icon_Housing] Housing and +20 Loyalty per turn for your Capital and cities with an assigned Governor. -2 [ICON_Amenities] Amenities, -20 Loyalty per turn and -50% to all yields for cities that are not your Capital and do not have an assigned Governors. +25% [ICON_PRODUCTION] Production towards Districts and Buildings for cities that have a Seowon district. +15% [ICON_Production] Production and +15% [ICON_FOOD] Food for Cities have a Library. +100% Districts Adjacency (of corresponding yields) to all Districts for Cities that have a University. Cities with a Research Lab gain +10% to all yields and +1 to all [ICON_CITIZEN] citizen yields."),
    ("LOC_LEADER_POUNDMAKER_ABILITY_DESCRIPTION",                     "All Alliance types provide Shared Visibility.[NEWLINE]Your outgoing [ICON_TradeRoute] Trade Routes grant you +1 [ICON_Food] Food per Fishing Boat, Camp or Pasture improvements at the destination. [ICON_TradeRoute] Trade Routes sent to your cities grant you +1 [ICON_Gold] Gold per Fishing Boat, Camp or Pasture improvements at the destination."),
    ("LOC_TRAIT_CIVILIZATION_MALI_GOLD_DESERT_DESCRIPTION",           "City Centers gain +1 [ICON_FAITH] Faith and +1 [ICON_FOOD] Food for every adjacent Desert and Desert Hills tiles. Mines receive -1 [ICON_PRODUCTION] Production and +4 [ICON_GOLD] Gold. Mines over Luxury resources provide +2 [ICON_Gold] Gold. May purchase Commercial Hub district buildings with [ICON_Faith] Faith. -30% [ICON_PRODUCTION] Production toward constructing buildings or training units."), --Mines over Luxury resources provide +10% [ICON_Gold] Gold. Mines over Luxury resources provide +1 [ICON_FOOD] Food for international [ICON_TradeRoute] Trade Routes from this city. 
    ("LOC_TRAIT_LEADER_SAHEL_MERCHANTS_DESCRIPTION",                  "International [ICON_TradeRoute] Trade Routes gain +1 [ICON_GOLD] Gold for every flat Desert or Desert hills tile in the origin city. Receive +1 [ICON_TradeRoute] Trade Capacity every time you enter a Golden Age. Earn extra 15 [ICON_GOLD] Gold for each era score earned."), -- May initiate the Endless Money Project.
    ("LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_DESCRIPTION",              "Cities with an Established [ICON_Governor] Governor provide +5% [ICON_CULTURE] Culture, +5% [ICON_Production] Production, and +10% experience in combat towards all units trained in this city. These numbers are tripled in cities not founded by the Mapuche. All cities within 9 tiles of a city with your [ICON_Governor] Governor gain +4 Loyalty per turn towards your civilization. Pasture improvements provide additional +1 [ICON_Housing] Housing."),
    ("LOC_TRAIT_LEADER_LAST_BEST_WEST_DESCRIPTION",                   "Allows Farms to be built on Tundra terrain. After Civil Engineering is unlocked Farms can be built on Tundra Hills. In Snow, Tundra, Snow Hills, and Tundra Hills all Mines, Lumber Mills, Pastures and Quarries provide +2 [ICON_PRODUCTION] Production, Farms, Camps and Plantations provide +2 [ICON_FOOD] Food, and strategic resource accumulation rate is +100%. Reduces the purchase cost of tiles in these terrain types by 50%."),
    ("LOC_TRAIT_CIVILIZATION_FACES_OF_PEACE_DESCRIPTION",             "Cannot declare war on City-States or surprise wars. Surprise wars cannot be declared on Canada. Your cities earn +15% [ICON_Culture] Culture and +25% [ICON_Tourism] Tourism across your empire whenever you are not at war with any civilization. When you capture a Barbarian Outpost, receive a builder reward in addition to the usual [ICON_Gold] Gold."),
    ("LOC_TRAIT_LEADER_GRAND_EMBASSY_DESCRIPTION",                    "Can purchase buildings in Industrial Zone with [ICON_FAITH] Faith. -10% [ICON_FAITH] Faith cost when patronizing Great Person."),
    ("LOC_TRAIT_CIVILIZATION_MOTHER_RUSSIA_EXPANSION2_DESCRIPTION",   "+1 [ICON_Food] Food for all Tundra Districts. Extra territory upon founding cities. +1 [ICON_Faith] Faith and +1 [ICON_Production] Production from Tundra. Units do not receive damage from Blizzards. Civilizations that are at war with Russia receive +100% unit damage from Blizzards in Russian territory."),
    ("LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION",        "Begin the game with the Animal Husbandry technology unlocked. +1 [Icon_Production] Production for all Pastures across the Nation. Improved [ICON_RESOURCE_HORSES] Horses accumulate 3 more resources per turn. Receive a second light cavalry unit or Saka Horse Archer each time you train a light cavalry unit or Saka Horse Archer."),
    ("LOC_TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES_DESCRIPTION",       "Each city can build one more district than usual (exceeding the normal limit based on [ICON_Citizen] Population)."), -- +1 [ICON_Science] Science and +1 [ICON_Culture] Culture for cities that have Specialty Districts.
    ("LOC_TRAIT_LEADER_HOLY_ROMAN_EMPEROR_DESCRIPTION",               "Additional Military policy slot. Double Influence Points."),
    ("LOC_TRAIT_CIVILIZATION_INDONESIA_NUSANTARA_DESCRIPTION",        "Coast and Lake tiles provide a standard adjacency bonus for Holy Site, Campus, Industrial Zone, and Theater Square districts. +1 [ICON_AMENITIES] Amenity from entertainment to each Entertainment Complex adjacent to a Coast or Lake tile."),
    ("LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION",             "Temple allows the purchasing and training of Military Engineers. May purchase Military Engineers with [ICON_Faith] Faith. Military Engineers receive +2 charges. Culture Bomb adjacent tiles when completing a Fort inside friendly territory. +1 [ICON_PRODUCTION] Production and +1 [ICON_CULTURE] Culture for every adjacent Fort. [NEWLINE]All Military policy slots in the current government is converted to Wildcard slots."), --Tiles that adjacent to the Fort get +2 [ICON_PRODUCTION] Production and +2 [ICON_CULTURE] Culture.
    ("LOC_TRAIT_LEADER_LITHUANIAN_UNION_DESCRIPTION",                 "+30% [ICON_PRODUCTION] Production and +2 [ICON_FAITH] Faith towards Holy Sites and their buildings. Poland's majority religion becomes the dominant religion in cities that loses a tile to a Polish Culture Bomb. Grant boost [ICON_TechBoosted] to 'Military Engineering' for each completed temple (complete 'Military Engineering' if already boosted)."),
    ("LOC_TRAIT_LEADER_GRAND_EMBASSY_NAME",                           "Pater Patriae"),
    ("LOC_TRAIT_LEADER_ELEANOR_LOYALTY_DESCRIPTION",                  "Great Works in Eleanor’s cities each cause -2 Loyalty per turn in foreign cities within 9 tiles. A city that leaves another civilization due to a loss of Loyalty and is currently receiving the most Loyalty per turn from Eleanor's civilization skips the Free City step to join this civilization. [NEWLINE]May initiate the Judgement of Love project in any city with a Theater Square district. In cities built by Eleanor, Art Museums and Archaeological Museums get 3 extra slots, and are automatically themed when all slots are filled."),
    ("LOC_TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION_DESCRIPTION",      "Improved [ICON_Resource_Iron] Iron and [ICON_Resource_Coal] Coal Mines +1 [ICON_Production] Production and accumulate 2 more resources per turn. +20% building speed towards Industrial Zone buildings. Industrial Zone buildings get extra +4 [ICON_Production] Production with regional effect. Grant boost [ICON_TechBoosted] to 'Industrialization' for each completed shipyard (complete 'Industrialization' if already boosted)."), --Reveal [ICON_Resource_Iron] Iron without the normal technology requirement, 
    ("LOC_TRAIT_CIVILIZATION_NKISI_DESCRIPTION",                      "All land units ignore [ICON_MOVEMENT] movement penalty from Forest and Jungle. +2 [ICON_Food] Food, +2 [ICON_Production] Production, +4 [ICON_Gold] Gold and +1 [ICON_FAITH] from each [ICON_GreatWork_Relic] Relic, [ICON_GreatWork_Artifact] Artifact and [ICON_GreatWork_Sculpture] Sculpture in addition to the usual [ICON_Culture] Culture. Receive 100% more [ICON_GreatWriter] Great Writer, [ICON_GreatArtist] Great Artist, [ICON_GreatMusician] Great Musician, and [ICON_GreatMerchant] Great Merchant points. Palace has slots for 5 Great Works."),
    ("LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",                    "[ICON_TechBoosted] Eurekas provide 94% of the [ICON_SCIENCE] Science for technologies. -50% [ICON_SCIENCE] Science per turn."),
    ("LOC_TRAIT_CIVILIZATION_MAYAB_DESCRIPTION",                      "Settling adjacent to Fresh Water and Coast does not provide extra [ICON_HOUSING] Housing. Instead each Farm provides an additional +1 [ICON_HOUSING] Housing, +1 [ICON_Production] Production for every adjacent Observatory, and +1 [ICON_GOLD] Gold. +1 [ICON_AMENITIES] Amenity for every Luxury resource adjacent to the City Center."),
    ("LOC_TRAIT_LEADER_MUTAL_DESCRIPTION",                            "Reveal plots within 6 tiles of the starting plot. Cities within 6 tiles of the [ICON_Capital] Capital gain +10% to all yields, and when founded receive a builder. Non capital cities within 9 tiles and outside 6 tiles of the [ICON_Capital] Capital yields remain usual. Other non capital cities receive -15% to all yields. +5 [ICON_Strength] Combat Strength to units within 6 tiles of the [ICON_Capital] Capital."),
    ("LOC_TRAIT_LEADER_TRAJANS_COLUMN_DESCRIPTION",                   "All cities start with a Monument building. +50% Construction speed towads builings in the City Center."),
    ("LOC_TRAIT_CIVILIZATION_MAORI_MANA_DESCRIPTION",                 "Begin the game with the Sailing and Shipbuilding technologies unlocked and with the ability to enter Ocean tiles. Embarked units gain +2 [ICON_Movement] Movement. Unimproved Woods and Rainforest gain +1 [ICON_PRODUCTION] Production. Additional +1 [ICON_PRODUCTION] Production from Civil Service, +1 [ICON_PRODUCTION] Production from Mercantilism, +1 [ICON_PRODUCTION] Production from Conservation and +1 [ICON_PRODUCTION] Production from Environmentalism. Fishing Boats provide +1 [ICON_FOOD] Food and a Culture Bomb to adjacent tiles. [ICON_GreatWriter] Great Writers cannot be earned."),
    ("LOC_TRAIT_CIVILIZATION_ITERU_EXPANSION2_DESCRIPTION",           "Major adjacency bonus for Campuses and Theater Squares if next to a River. If placed next to a River, +15% [ICON_Production] Production towards Districts and Wonders. Does not receive damage from Floods. Receive a free Builder unit every time you finish a Wonder."),
    ("LOC_TRAIT_LEADER_MEDITERRANEAN_EXPANSION2_DESCRIPTION",         "Your [ICON_TradeRoute] Trade Routes to other civilizations provide +8 [ICON_Gold] Gold for Egypt. Other civilizations' [ICON_TradeRoute] Trade Routes to Egypt provide +4 [ICON_Food] Food for them and +4 [ICON_Gold] Gold for Egypt. Trading with Allies earns double as many bonus Alliance Points."),
    ("LOC_TRAIT_CIVILIZATION_LAST_PROPHET_DESCRIPTION",               "Automatically receive the final [ICON_GreatProphet] Great Prophet when the next-to-last one is claimed (if you have not earned a [ICON_GreatProphet] Great Prophet already). +4 [ICON_Science] Science for each foreign city following Arabia's Religion."), -- Receive a free apostle when [ICON_GreatProphet] Great Prophet is created or Religion is founded. 
    ("LOC_TRAIT_LEADER_MENELIK_DESCRIPTION",                          "Receive [ICON_SCIENCE] Science and [ICON_CULTURE] Culture equal to 15% of your [ICON_FAITH] Faith generation in cities founded on Hills. Units receive +4 [ICON_STRENGTH] Combat Strength on Hills."),
    ("LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",                    "All Districts (except City Centers) do not remove Forest, Rainforest and Marsh. Receive the following yields for every building and Districts itself on these features: +2 [ICON_Production] Production in Forest, +2 [ICON_Food] Food in Rainforest and +2 [ICON_Science] in Marsh. Woods can be planted with the Medieval Faires civic."),
    ("LOC_TRAIT_CIVILIZATION_GAUL_DESCRIPTION",                       "Mines provide a minor adjacency bonus for all districts, a Culture Bomb of unowned territory, and receive +1 [ICON_CULTURE] Culture. Specialty districts do not receive a minor adjacency bonus for being adjacent to another district."),
    ("LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_ETHIOPIA_DESCRIPTION",        "Can move their original [ICON_Capital] Capital to any city they founded and with a Cothon resource by completing a unique project in that city. +1 [ICON_TradeRoute] Trade Route capacity for each Diplomatic Quarter building, Diplomatic Quarter district, Government Plaza building, and the Government Plaza district. +50% [ICON_Production] Production toward Districts in the city with the Government Plaza or Diplomatic Quarter."),
    ("LOC_TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES_DESCRIPTION",     "Begin the game with the Writing technology [ICON_TechBoosted] Eureka and Foreign Trade [ICON_CivicBoosted] Boost. Coastal cities founded by Phoenicia and located on the same continent as the Phoenician [ICON_Capital] Capital are 100% Loyal. Settlers gain +2 [ICON_Movement] Movement and +2 sight range while embarked. Settlers ignore additional [ICON_Movement] Movement costs from embarking and disembarking. International [ICON_Traderoute] trade routes receive +1 [ICON_Culture] culture and +2 [ICON_Gold] Gold. Triple this bonus when the destination is a City State you are the Suzerain of."),
    ("LOC_TRAIT_LEADER_FIRST_EMPEROR_NAME",                           "The Greatest Emperor Ever"),
    ("LOC_TRAIT_LEADER_FIRST_EMPEROR_EXPANSION2_DESCRIPTION",         "When building Ancient and Classical wonders, you may spend Builder charges to complete 15% of the original wonder cost. Builders receive an additional charge and +1 [ICON_Movement] Movement."),
    ("LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_NAME",                    "Wisdom of Working People"),
    ("LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION",  "+6 [ICON_Science] Science when you use a Builder's charge. [ICON_TechBoosted] Eurekas and [ICON_CivicBoosted] Inspirations provide 10% more of technologies and civics. When completing a wonder, receive a random [ICON_TechBoosted] Eureka and [ICON_CivicBoosted] Inspiration from the era of the wonder, if available. Canals are unlocked with the Masonry technology."),
    ("LOC_TRAIT_LEADER_RAVEN_KING_DESCRIPTION",                       "Levied units gain an ability giving them +2 [ICON_Movement] Movement and +5 [ICON_Strength] Combat Strength. It costs 50% less [ICON_GOLD] Gold and resources to upgrade Levied units. If you Levy troops from a City-State, receive 2 [ICON_ENVOY] Envoys in that City-State. Receive 1 [ICON_ENVOY] Envoy when conquering a city. Gain the Black Army unique unit when the 'Castles' technology is researched."),
    ("LOC_TRAIT_CIVILIZATION_SATRAPIES_DESCRIPTION",                  "'Political Philosophy' civic gives you +1 [ICON_TradeRoute] Trade Route capacity and 1 [ICON_Governor] Governor title. Receive +2 [ICON_Gold] Gold and +2 [ICON_Culture] Culture for routes between your own cities. Roads built in your territory are one level more advanced than usual."),
    ("LOC_TRAIT_LEADER_FALL_BABYLON_EXPANSION2_DESCRIPTION",          "+2 [ICON_Movement] Movement for the first 10 turns after declaring a Surprise War on a major civilization. +5 Loyalty per turn in cities with a garrisoned unit. Declaring a Surprise War only counts as a Formal War for the purposes of [ICON_STAT_GRIEVANCE] Grievances and Warmongering."),
    ("LOC_TRAIT_LEADER_BANNOCKBURN_DESCRIPTION",                      "Military units receive +4 [ICON_Strength] Combat Strength when defending in your territory. Can declare a War of Liberation after gaining the Defensive Tactics Civic. +100% [ICON_Production] Production and +2 [ICON_Movement] Movement for the first 10 turns after declaring a War of Liberation."),
    ("LOC_TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT_DESCRIPTION",     "Happy cities receive an additional +8% [ICON_SCIENCE] Science and +8% [ICON_PRODUCTION] Production. Happy cities generate +2 [ICON_GreatScientist] Great Scientist point per Campus, +2 [ICON_GreatEngineer] Great Engineer point per Industrial Zone. Joyful cities double all these values, Ecstatic cities triple all these values. Campus and Industrial Zone receive +1 [ICON_Amenities] Amenity and standard adjacency (instead of minor adjacency) from other Districts."),
    ("LOC_TRAIT_LEADER_RELIGION_CITY_STATES_DESCRIPTION",             "+100% [ICON_FAITH] Faith for 10 turns after declaring a Protectorate War. Each [ICON_ENVOY] Envoy you send to a city-state of your majority Religion counts as two [ICON_ENVOY] Envoys. (Must have a majority Religion). Combat victories provide [ICON_FAITH] Faith equal to 100% of the Combat Strength of the defeated unit (on Standard Speed). +1 [ICON_CULTURE] Culture and +1 [ICON_Faith] Faith per level of Walls."),
    ("LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION",          "When making Dedications at the beginning of a Golden Age or Heroic Age, receive the Normal Age bonus towards improving Era Score in addition to the other bonus. While in a Golden Age or Heroic Age, may use Dark Age Policies. Gains a permanent extra Wildcard Policy Slot first time in a Golden Age or Heroic Age. +100% [ICON_Production] Production towards defensive buildings."),
    ("LOC_TRAIT_CIVILIZATION_GREAT_MOUNTAINS_DESCRIPTION",            "Citizens may work Mountain tiles. Mountain tiles provide +3 [ICON_PRODUCTION] Production and. +1 [ICON_FOOD] Food to Mountain tiles for every adjacent Terrace Farm. +1 [ICON_PRODUCTION] Production after researching Construntion. Reduces the purchase cost of mountain tiles by 50%."),
    ("LOC_TRAIT_LEADER_PACHACUTI_QHAPAQ_NAN_DESCRIPTION",             "All land units ignore [ICON_MOVEMENT] movement penalty from Hills. Domestic [ICON_TradeRoute] Trade Routes gain +1 [ICON_Food] Food for every Mountain tile in the origin city. Gain the Qhapaq Ñan improvement when Foreign Trade civic is discovered."),
    ("LOC_TRAIT_CIVILIZATION_AMAZON_DESCRIPTION",                     "Rainforest tiles provide +1 adjacency bonus for Campus, Commercial Hub, Holy Site, and Theater Square districts, and grant +1 Appeal to adjacent tiles, instead of the usual -1. Lumber Mill provides +1 adjacency bonus for Industrial Zone. Rainforest tiles receive +1 [ICON_PRODUCTION] Production if is adjacent to Industrial Zone tiles. +2 [ICON_CULTURE] Culture for all Rainforest Lumber Mill. After researching Flight, Lumer Mill will provide [ICON_TOURISM] Tourism equal to its [ICON_CULTURE] Culture yields. All districts (except city centers) will not remove Rainforest. +1 [Icon_Faith] Faith if city is adjacent to Rainforest tiles."),
    ("LOC_TRAIT_LEADER_MAGNANIMOUS_DESCRIPTION",                      "After recruiting or patronizing a [ICON_GreatPerson] Great Person, 20% of its [ICON_GreatPerson] Great Person point cost is refunded. +1 [Icon_Faith] Faith in all Rainforest Tiles across your country for every two [ICON_GreatPerson] Great Person you have recruited."),
    ("LOC_TRAIT_CIVILIZATION_TREASURE_FLEET_EXPANSION2_DESCRIPTION",  "May form Fleets and Armadas with Exploration and Mercantilism, instead of Nationalism and Mobilization. [ICON_TradeRoute] Trade Routes receive +3 [ICON_Gold] Gold, +2 [ICON_Faith] Faith, and +1 [ICON_Production] Production. [ICON_TradeRoute] Trade Routes between multiple continents receive triple these numbers. Cities not on your original Capital’s continent receive +25% [ICON_Production] Production towards districts and a builder when founded."),
    ("LOC_TRAIT_CIVILIZATION_TA_SETI_DESCRIPTION",                    "+30% [ICON_Production] Production toward Ranged units. All Ranged units gain +30% combat experience. Mines over Bonus and Strategic resources provide +1 [ICON_Production] Production, and each kind of mined Bonus or Strategic resources provide +10% [ICON_Production] Production."),
    ("LOC_TRAIT_LEADER_KANDAKE_OF_MEROE_DESCRIPTION",                 "+20% [ICON_Production] Production towards all Districts rising to +30% if there is a Nubian Pyramid adjacent to the City Center."),
    ("LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_NAME",                      "Guerra Florida"),
    ("LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_DESCRIPTION",               "All Melee units have a chance to capture other civilization's military units by turning them into Builders. Enable Sacrificing the builders, which removes the unit and gains +10 [ICON_Culture] Culture and +10 [ICON_Faith] Faith for each builder charge the unit has."),
    ("LOC_TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS_DESCRIPTION",           "Spend Builder charges to complete 20% of the original District cost. Luxury resources provide [ICON_Amenities] Amenity to 2 extra cities. Military units receive +1 [ICON_Strength] Combat Strength when attacking for each different Luxury resource improved in Aztec lands."),
    ("LOC_TRAIT_LEADER_FLYING_SQUADRON_DESCRIPTION",                  "Gain 1 level of [ICON_VisLimited] Diplomatic Visibility greater than normal with every civilization that they've met. Receives a free Spy (and extra spy capacity) with the Castles technology. +2 sight range for spies and traders. All spies start with a free promotion."), -- (if already have, can promote again after the first promotion)
    ("LOC_TRAIT_LEADER_SATYAGRAHA_DESCRIPTION",                       "ALL cities have +15% growth rate, 15% [ICON_Faith] Faith and +1 [ICON_Amenities] Amenity when you are at peace with all other civilizations. +5 [ICON_Faith] Faith for each civilization (including India) they have met that has founded a Religion and is not currently at war. Opposing civilizations receive double the war weariness for fighting against Gandhi."),
    ("LOC_TRAIT_CIVILIZATION_DHARMA_EXPANSION2_DESCRIPTION",          "Receives Follower Belief bonuses in a city from each Religion that has at least 1 Follower. Cities gain an [ICON_Amenities] Amenity for every Religion with at least 1 Follower. Missionaries have +2 spreads. +100% Religious pressure from your [ICON_TradeRoute] Trade Routes. +0.5 [ICON_Food] Food per Population for cities which have stepwell."),
    ("LOC_TRAIT_LEADER_ARTHASHASTRA_DESCRIPTION",                     "After unlocked civic military training, You will get a setter to the capital city, and can declare a war of territorial expansion.After declaring the war of territorial expansion,all your units grant extra 2[ICON_MOVEMENT]movement and 5[ICON_STRENGTH]strength in 10 turns."),
    ("LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_NAME",                  "Manifest Destiny"),
    ("LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION","All Diplomatic policy slots in the current government are converted to Wildcard slots. +1 [ICON_Favor] Diplomatic Favor per turn for every Wildcard slot in their government. Reduces the purchase cost of tiles in Grass, Grass Hills, Plains and Plains Hills by 50%.");

--------------------------------------------------------------------------------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                             Text)
values
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_KUBLAI_DESCRIPTION",                           "任意政体中额外增加一个经济政策槽位。占领其他文明的原始 [ICON_Capital] 首都时，获得该文明的特色能力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_WONDER_TOURISM_DESCRIPTION",             "为中世纪、文艺复兴时期和工业时代的奇观+20% [ICON_Production] 生产力。 所有奇观的 [ICON_Tourism] 旅游业绩+200%。每个奇观为首都+1所有产出，若为中世纪及之后的奇观则该加成翻倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SURROUNDED_BY_GLORY_DESCRIPTION",              "作为宗主国时，每个下辖的城邦使您的 [ICON_Culture] 文化值+5%。建造卫城后，您向每个城邦派遣的第一个 [ICON_Envoy] 使者会被视为2个 [ICON_Envoy] 使者。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_THERMOPYLAE_DESCRIPTION",                      "战斗胜利后，获得等同于被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_Culture] 文化值（标准速度下）。槽位中每有一项军事政策，则+1 [ICON_Strength] 战斗力。建成卫城时获得一个抗骑兵单位。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_THUNDERBOLT_EXPANSION2_DESCRIPTION",           "使所有海军近战单位均能发动海岸扫荡，生产所有海军近战单位时+50% [ICON_PRODUCTION] 生产力。除常规劫掠收益外，对农田、矿山、伐木场发动掠夺或海岸扫荡时还将获得 [ICON_SCIENCE] 科技值，对采石场、牧场、种植园和营地发动掠夺或海岸扫荡时还将获得 [ICON_CULTURE] 文化值。解锁“航海术”科技后即可获得特色单位维京长船。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ROOSEVELT_COROLLARY_ROUGH_RIDER_DESCRIPTION",  "在首都所在大陆上时单位+5 [ICON_Strength] 战斗力。如与城邦之间存在 [ICON_TradeRoute] 贸易路线，派往此处的1位 [ICON_Envoy] 使者将视为2位。解锁“弹道学”科技后获得特色单位“莽骑兵”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_EJERCITO_PATRIOTA_DESCRIPTION",          "所有单位+1 [ICON_Movement] 移动力。升级单位不会结束其回合。种植园对无主领土施放文化炸弹，并+1 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_NAME",                    "集贤殿"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_DESCRIPTION",             "首都每次建造完成书院区域或书院中的建筑时获得一个总督点。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HWARANG_DESCRIPTION",                          "首都或派遣了总督的城市获得+3 [ICON_Amenities] 宜居度，+5 [Icon_Housing] 住房和+20忠诚度。非首都且未派遣总督的城市-2 [ICON_Amenities] 宜居度，-8忠诚度，-50%全部产出。 有书院的城市建造区域和建筑+25% [Icon_Production] 生产力；有图书馆的城市+15% [ICON_Food] 食物和 [Icon_production] 生产力；有大学的城市，所有区域对应产出类型的相邻加成+100%；有实验室的城市所有产出+10%且每个人口额外1点全部产出。"),
    ("zh_Hans_CN",  "LOC_LEADER_POUNDMAKER_ABILITY_DESCRIPTION",                     "所有同盟类型均可以共享视野。[NEWLINE]目的地城市中的每个渔船、营地或牧场可为你的 [ICON_TradeRoute] 贸易路线提供+1 [ICON_Food] 食物。[NEWLINE]你的城市作为 [ICON_TradeRoute] 贸易路线目的地时，此城中的每个渔船、营地或牧场可为你提供+1 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MALI_GOLD_DESERT_DESCRIPTION",           "每个相邻沙漠或沙漠丘陵单元格为市中心提供+1 [ICON_FAITH] 信仰值与+1 [ICON_FOOD] 食物。矿山-1 [ICON_PRODUCTION] 生产力，但+4 [ICON_GOLD] 金币，奢侈品资源矿产提供+2 [ICON_Gold] 金币，可用 [ICON_Faith] 信仰值购买商业中心区域建筑。建造建筑或生产单位时-30% [ICON_PRODUCTION] 生产力。"), --每一种改良的奢侈矿产资源为城市+10% [ICON_Gold] 金币，城市中的每个奢侈品资源矿产为国际 [ICON_TradeRoute] 贸易路线提供+1 [ICON_FOOD] 食物。
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SAHEL_MERCHANTS_DESCRIPTION",                  "起始城市中的每个沙漠或沙漠丘陵单元格为国际 [ICON_TradeRoute] 贸易路线提供+1 [ICON_GOLD] 金币。文明进入黄金时代后可获得+1 [ICON_TradeRoute] 贸易路线容量。每获得1点时代分，额外获得15 [ICON_GOLD] 金币。"), --可在拥有曼丁哥市场的任意城市中开展“多钱善贾”项目。
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_DESCRIPTION",              "[ICON_Governor] 总督就职城市提供的 [ICON_CULTURE] 文化值+5%、 [ICON_Production] 生产力+5%，此城市中生产的所有单位的战斗经验值+10%。在非马普切建立的城市中，这些数值将乘以三倍。[ICON_Governor] 总督就职城市9单元格范围内的所有城市每回合对本方文明的忠诚度+4。牧场提供额外+1 [ICON_Housing] 住房。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LAST_BEST_WEST_DESCRIPTION",                   "允许在冻土地貌上建造农场。解锁“土木工程”后，即可在冻土丘陵上建造农场。在雪地、冻土、雪地丘陵和冻土丘陵上的所有矿山、伐木场、牧场和采石场提供的 [ICON_PRODUCTION] 生产力+2，农场、营地、种植园提供的 [ICON_FOOD] 食物+2，战略资源积累速度+100%。这些地形上的单元格购买费用降低50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_FACES_OF_PEACE_DESCRIPTION",             "无法对城邦宣战或发动突袭战争。无法对加拿大发动突袭战争。与主要文明处于和平时所有城市+15% [ICON_Culture] 文化值，且全境内+25% [ICON_Tourism] 旅游业绩。当您清理一个蛮族哨站时，奖励一个建造者。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GRAND_EMBASSY_DESCRIPTION",                    "可以用 [ICON_FAITH] 信仰购买工业区建筑。用 [ICON_FAITH] 信仰值招募伟人时所需的费用-10%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MOTHER_RUSSIA_EXPANSION2_DESCRIPTION",   "所有位于冻土单元格的区域+1 [ICON_Food] 食物。建立城市可获得额外领土。冻土提供+1 [ICON_Faith] 信仰值与+1 [ICON_Production] 生产力。与俄罗斯交战的文明单位如处于俄罗斯领土中，遭遇暴风雪时受到的伤害+100%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION",        "游戏初始便解锁畜牧业科技。牧场+1 [ICON_PRODUCTION] 生产力。开发 [ICON_RESOURCE_HORSES] 马资源的牧场每回合额外+3 [ICON_RESOURCE_HORSES] 马资源积累。每次您训练一个轻骑兵或萨卡弓骑手，都可以再获得一个轻骑兵或萨卡弓骑手。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES_DESCRIPTION",       "每座城市都能建造比平常多一个区域（无视 [ICON_Citizen] 人口数量限制）。"), -- 拥有专业化区域的城市+1 [ICON_Science] 科技值和 +1 [ICON_Culture] 文化值。
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HOLY_ROMAN_EMPEROR_DESCRIPTION",               "额外的军事政策槽位。获得影响力点数翻倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_INDONESIA_NUSANTARA_DESCRIPTION",        "海岸和湖泊单元格可为圣地、学院、工业区和剧院广场提供标准加成。与海岸或湖泊单元格相邻的娱乐中心额外+1 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LITHUANIAN_UNION_DESCRIPTION",                 "圣地和圣地中建筑+30%建造速度并+2 [ICON_FAITH] 信仰值。如城市在波兰文化炸弹的攻击下失去单元格，则波兰的主流宗教将成为此城的主流宗教。每次完成寺庙后，触发军事工程学尤里卡，若军事工程学尤里卡已触发，则直接完成军事工程学科技。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION",             "当前政体的所有军事政策槽位均转为通配符槽位。在友好领土内建成堡垒后对相邻单元格施放文化炸弹，使相邻的单元格+1 [ICON_Production] 生产力和+1 [ICON_Culture] 文化值。拥有寺庙的城市可以训练或购买军事工程师，军事工程师使用次数+2且可以用 [ICON_FAITH] 信仰值购买。"), --相邻堡垒的单元格+2 [ICON_Production] 生产力和+2 [ICON_Culture] 文化值
    -- ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_PORTUGAL_NAME",                          "东印度公司"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GRAND_EMBASSY_NAME",                           "祖国之父"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ELEANOR_LOYALTY_DESCRIPTION",                  "您的每个巨作使9个单元格内的外国城市-2忠诚度。外国城市转变为自由城市前，如对您的忠诚度最高，则直接加入您的文明。您建立的城市中，考古博物馆和艺术博物馆获得3个额外槽位，填满时自动获得主题化。可在拥有剧院广场区域的任意城市中开展“爱之审判”项目。"), --埃莉诺的城市中每个巨作可使9个单元格内的外国城市每回合减少2点忠诚度。城市因失去忠诚度而离开另一文明后，如其每回合对埃莉诺的忠诚度最高，则会跳过成为自由城市阶段直接加入埃莉诺的文明。[NEWLINE]可在拥有剧院广场区域的任意城市中开展“马戏与面包”项目。埃莉诺建立的城市中，考古博物馆和艺术博物馆获得3个额外槽位，填满时自动获得主题化。
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION_DESCRIPTION",      "已改良的 [ICON_Resource_Iron] 铁与 [ICON_Resource_Coal] 煤+1 [ICON_Production] 生产力且每回合产量额外增加2点。建造工业区建筑时+20%建造速度。工业区的辐射建筑的 [ICON_Production] 生产力辐射额外+4。每次完成造船厂后，触发工业化尤里卡，若工业化尤里卡已触发，则直接完成工业化科技。"), --无视科技需求即揭示 [ICON_Resource_Iron] 铁资源，
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_NKISI_DESCRIPTION",                      "所有陆地单位无视森林和雨林对 [ICON_MOVEMENT] 移动力的减益。除了通常的 [ICON_Culture] 文化值，还会从每个 [ICON_GreatWork_Relic] 遗物、 [ICON_GreatWork_Artifact] 文物和 [ICON_GreatWork_Sculpture] 雕塑中获得+2 [ICON_Food] 食物、+2 [ICON_Production] 生产力、+4 [ICON_Gold] 金币和+1 [ICON_FAITH] 信仰值。获得额外100% [ICON_GreatWriter] 大作家、[ICON_GreatArtist] 大艺术家、[ICON_GreatMusician] 大音乐家和 [ICON_GreatMerchant] 大商人点数。宫殿有5个巨作槽位。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",                    "[ICON_TechBoosted] 尤里卡提供科技的94%的 [ICON_SCIENCE] 科技值。每回合的 [ICON_SCIENCE] 科技值-50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAYAB_DESCRIPTION",                      "在淡水和海岸旁定居时不提供额外 [ICON_HOUSING] 住房。但农场提供额外+1 [ICON_HOUSING] 住房和+1 [ICON_GOLD] 金币，且每与一座天文台相邻则+1 [ICON_Production] 生产力。每有一个奢侈品与市中心相邻，则+1 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MUTAL_DESCRIPTION",                            "揭示出生点6个单元格内的地块。[ICON_Capital] 首都6个单元格范围内城市所有产出+10%，且建成时将获得1名建造者。[ICON_Capital] 首都9个单元格范围内6个单元格外的的非首都城市所有产出不变。其他非首都城市所有产出-15%。[ICON_Capital] 首都6个单元格范围内的单位+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_TRAJANS_COLUMN_DESCRIPTION",                   "所有城市建立时赠送纪念碑。[NEWLINE]建造市中心建筑时加速50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAORI_MANA_DESCRIPTION",                 "游戏初始便解锁“航海术”与“造船术”科技，同时拥有进入海洋单元格的能力。水运单位+2 [ICON_Movement] 移动力。未改良的树林与雨林提供+1 [ICON_PRODUCTION] 生产力。“行政部门”额外提供+1 [ICON_PRODUCTION] 生产力、“重商主义”额外提供+1 [ICON_PRODUCTION] 生产力、“保护地球”额外+1 [ICON_PRODUCTION] 生产力、“环境保护主义”额外提供+1 [ICON_PRODUCTION] 生产力。渔船提供+1 [ICON_FOOD] 食物，并向相邻单元格投放文化炸弹。无法获得 [ICON_GreatWriter] 大作家。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_ITERU_EXPANSION2_DESCRIPTION",           "与河流相邻时，学院和剧院广场将获得大量相邻加成。在河边建造区域与奇观时 [ICON_Production] 生产力+15%。境内不会受到洪水的损害。每次完成一个奇观，获得一个免费的建造者。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MEDITERRANEAN_EXPANSION2_DESCRIPTION",         "您通往其他文明的 [ICON_TradeRoute] 贸易路线为埃及+8 [ICON_Gold] 金币。其他文明通往埃及的 [ICON_TradeRoute] 贸易路线能为其+4 [ICON_Food] 食物、为埃及+4 [ICON_Gold] 金币。与盟友进行贸易可获得双倍同盟点数。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LAST_PROPHET_DESCRIPTION",               "当倒数第二个 [ICON_GreatProphet] 预言家被招募后（如果您尚未获得 [ICON_GreatProphet] 大预言家），自动获得最后一个大预言家。每座信奉阿拉伯宗教的外国城市+4 [ICON_Science] 科技值。"), --获得 [ICON_GreatProphet] 大预言家或创立宗教时获得一个免费的使徒。
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MENELIK_DESCRIPTION",                          "获得等同于建在丘陵上的城市所产生 [ICON_FAITH] 信仰值15%的 [ICON_SCIENCE] 科技值和 [ICON_CULTURE] 文化值。单位在丘陵上时+4 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",                    "所有区域（除市中心外）不移除树林、雨林、沼泽地貌。建在这些区域中的建筑以及区域本体和奇观将获得以下收益：建在树林上提供+2 [ICON_Production] 生产力、建在雨林上提供+2 [ICON_Food] 食物、建在沼泽上提供+2 [ICON_Science] 科技值。拥有“中世纪集市”市政后即可栽种树林。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GAUL_DESCRIPTION",                       "矿山为所有区域提供少量相邻加成、对无主领土施放文化炸弹，并+1 [ICON_CULTURE] 文化值。专业化区域与其他区域相邻时不会获得少量相邻加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_ETHIOPIA_DESCRIPTION",        "在城市中完成特色项目后，可将原始 [ICON_Capital] 首都迁至任意拥有U型港的城市（必须为本方建立）。每个外交区建筑、外交区、市政广场建筑与市政广场区域+1 [ICON_TradeRoute] 贸易路线容量。在拥有市政广场或外交区的城市中建造区域时+50% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES_DESCRIPTION",     "游戏开始便激活“写作”科技 [ICON_TechBoosted] 尤里卡和“对外贸易”市政 [ICON_CivicBoosted] 鼓舞。腓尼基建造的海岸城市若与 [ICON_Capital] 首都在同一大陆，则其忠诚度为100%。开拓者上船后，[ICON_Movement] 移动力与视野范围各+2。开拓者上船和下船无需额外花费 [ICON_Movement] 移动力。国际 [ICON_TradeRoute] 贸易路线+1 [ICON_CULTURE] 文化、+2 [ICON_Gold] 金币，若目的地为你宗主的城邦则该加成变为3倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FIRST_EMPEROR_NAME",                           "千古一帝"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FIRST_EMPEROR_EXPANSION2_DESCRIPTION",         "建造远古和古典奇观时，可消耗建造者次数来加速奇观原始建造进程的15%。建造者获得+1使用次数和+1 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_NAME",                    "劳动人民的智慧"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION",  "每当建造者减少一次使用次数，获得6点 [ICON_Science] 科技值。[ICON_TechBoosted] 尤里卡和 [ICON_CivicBoosted] 鼓舞额外提升（对应科技或人文所需的科技或文化总量的）10%。建成奇观时将获得奇观所处时代的一项随机 [ICON_TechBoosted] 尤里卡和 [ICON_CivicBoosted] 鼓舞（如可用）。解锁“砌砖”科技的同时也解锁“运河”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_RAVEN_KING_DESCRIPTION",                       "征集单位+2 [ICON_Movement] 移动力、+5 [ICON_Strength] 战斗力。升级征集单位所花费的 [ICON_GOLD] 金币和资源减少50%。征集城邦军队时可在该城邦增加2名 [ICON_ENVOY] 使者。占领一座城市后获得1名 [ICON_ENVOY] 使者。研究“城堡”科技后获得特色单位“黑军”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_SATRAPIES_DESCRIPTION",                  "拥有“政治哲学”市政后，[ICON_TradeRoute] 贸易路线容量+1，获得一个 [ICON_Governor] 总督头衔。本国城市之间的路线+2 [ICON_Gold] 金币，+2 [ICON_Culture] 文化值。本国领土中的道路提升一个等级。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FALL_BABYLON_EXPANSION2_DESCRIPTION",          "对主要文明宣布突袭战争后的10回合内+2 [ICON_Movement] 移动力。拥有驻扎单位的城市每回合的忠诚度+5。宣布突袭战争的 [ICON_STAT_GRIEVANCE] 不满和好战性与正式战争相同。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_BANNOCKBURN_DESCRIPTION",                      "国境内的单位防御时+4 [ICON_Strength] 战斗力。解锁防御战术市政后即可宣布解放战争。宣布解放战争后的10回合内+100% [ICON_Production] 生产力、+2 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT_DESCRIPTION",     "幸福度为快乐的城市额外+8% [ICON_SCIENCE] 科技值、+8% [ICON_PRODUCTION] 生产力。快乐的城市中每个学院+2 [ICON_GreatScientist] 大科学家点数、每个工业区+2 [ICON_GreatEngineer] 大工程师点数。喜悦的城市获得的上述加成将加倍，欣喜若狂的城市获得的上述加成将变为三倍。学院和工业+1 [ICON_AMENITIES] 宜居度，且从其他区域获得标准的相邻加成取代少量相邻加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_RELIGION_CITY_STATES_DESCRIPTION",             "宣布保卫城邦战争后的10回合内+100% [ICON_FAITH] 信仰值。如城邦的主流宗教与本方相同，则派遣至其处的每名 [ICON_ENVOY] 使者将视为2名（必须拥有1个主流宗教）。战斗胜利后，获得等同于被击杀单位战斗力100%的 [ICON_FAITH] 信仰值（标准速度下）。每级城墙+1 [ICON_CULTURE] 文化值和+1 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION",          "在黄金或英雄时代初期设置着力点时，除原有加成外还将获得提高时代得分的普通时代加成。进入黄金或英雄时代后，可以使用黑暗时代政策。首次进入黄金或英雄时代时获得一个永久的通配符政策槽位。建造防御性建筑时+100% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GREAT_MOUNTAINS_DESCRIPTION",            "公民可在山脉单元格上工作。山脉单元格提供+3 [ICON_PRODUCTION] 生产力。每个相邻的梯田农场为山脉单元格+1 [ICON_FOOD] 食物。解锁建造科技后，每个相邻的梯田农场为山脉单元格+1 [ICON_PRODUCTION] 生产力。山脉单元格购买费用降低50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_PACHACUTI_QHAPAQ_NAN_DESCRIPTION",             "所有陆地单位无视丘陵对 [ICON_MOVEMENT] 移动力的减益。起始城市中的每座山脉单元格为国内 [ICON_TradeRoute] 贸易路线提供+1 [ICON_Food] 食物。解锁“对外贸易”市政后可获得印加路网改良设施。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_AMAZON_DESCRIPTION",                     "雨林单元格为学院、商业中心、圣地和剧院广场区域提供+1相邻加成，并为相邻的单元格提供+1魅力（而非通常的-1。）伐木场为相邻工业区提供+1相邻加成。若相邻工业区，雨林单元格 +1 [ICON_PRODUCTION] 生产力。建造在雨林的伐木场 +2 [ICON_CULTURE] 文化。研究科技“飞行”后，将产出等同于 [ICON_CULTURE] 文化产出的 [ICON_TOURISM] 旅游业绩。所有区域（除市中心外）不移除雨林。若市中心相邻雨林，+1 [Icon_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MAGNANIMOUS_DESCRIPTION",                      "招募或赞助一位 [ICON_GreatPerson] 伟人后，将返还所消耗 [ICON_GreatPerson] 伟人点数的20%。每招募2名伟人，您国境内的所有雨林单元格+1 [Icon_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_TREASURE_FLEET_EXPANSION2_DESCRIPTION",  "解锁“探索”和“重商主义”后（而非“民族主义”和“动员”）即可组建舰队和无敌舰队。[ICON_TradeRoute] 贸易路线+3 [ICON_Gold] 金币、+2 [ICON_Faith] 信仰值、+1 [ICON_Production] 生产力。如 [ICON_TradeRoute] 贸易路线横跨多个大陆，则这些数值将乘以3倍。如城市处于非原始首都所在大陆，其建成时将获得1名建造者，建造区域时+25% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_TA_SETI_DESCRIPTION",                    "生产远程单位时+30% [ICON_Production] 生产力。所有远程单位战斗经验值+50%。加成和战略资源矿产提供+1 [ICON_Production] 生产力。城市中每一种改良的加成或战略矿产资源为城市+10% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_KANDAKE_OF_MEROE_DESCRIPTION",                 "所有城市建造区域时+20%建造速度，市中心相邻努比亚金字塔时此加成提高至30%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_NAME",                      "荣冠战争"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_DESCRIPTION",               "所有近战类型的单位有几率把其他文明的军事单位转化为建造者并俘获。允许将建造者进行活人献祭，将移除目标单位，且其每有一次剩余劳动力获得10点 [ICON_Culture] 文化值和 10点 [ICON_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS_NAME",                  "太阳纪"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS_DESCRIPTION",           "使用建造者劳动力来推进20%的区域建设进程。其领土中的奢侈品资源为额外2座城市提供1点 [ICON_Amenities] 宜居度。阿兹特克国土内每种改良的奢侈品资源将为军事单位+1 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FLYING_SQUADRON_DESCRIPTION",                  "[ICON_VisLimited] 外交能见度比遇到的其他文明高1级。[NEWLINE]解锁“城堡”科技后免费获得1个间谍（并增加1个间谍容量）。间谍和商人+2视野范围。所有间谍初始便可免费获得一次升级机会。"), -- （若已能升级则可在升级后再升级一次）
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SATYAGRAHA_DESCRIPTION",                       "与主要文明处于和平时所有城市+15%余粮，15% [ICON_Faith]信仰且+1点 [ICON_AMENITIES] 宜居度。所遇到的文明（包括印度）已创建了宗教且不在战争状态，均会+5信仰值 [ICON_Faith] 。与甘地交战的文明获得双倍厌战情绪。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_DHARMA_EXPANSION2_DESCRIPTION",          "从城市中的每个宗教（其须拥有至少1个信徒）获得信徒信仰加成。城市从每个宗教（须有至少1个信徒）获得1点 [ICON_Amenities] 宜居度。传教士的传播次数+2。来自 [ICON_TradeRoute] 贸易路线的宗教压力+100%。拥有梯井的城市每人口+0.5食物 [ICON_Food] 。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ARTHASHASTRA_DESCRIPTION",                     "完成军事训练市政后解锁领土扩张战争借口，并获得一个免费移民到首都。宣布领土扩张战争后的10回合内所有单位+2[ICON_MOVEMENT]移动力，+5[ICON_STRENGTH]战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_NAME",                  "昭昭天命"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION","当前政体的所有外交政策槽均转为通配符槽位。其政体中每个通配符政策槽位每回合提供+1 [ICON_Favor] 外交支持。平原、平原丘陵、草原、草原丘陵单元格的购买费用降低50%。");
--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                             Text)
values
    ("LOC_IMPROVEMENT_POLDER_DESCRIPTION",                            "Unlocks the Builder ability to construct a Polder, unique to Netherlands.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_Production] Production, and +0.5 [ICON_Housing] Housing. +1 [ICON_FOOD] Food if adjacent to a Polder improvement. Additional [ICON_PRODUCTION] Production, [ICON_GOLD] Gold, and [ICON_FOOD] Food  as you advance through the Civics and Technology Tree. Must be placed on a Coast or Lake tile adjacent to 2 or more passable land tiles. Increases [ICON_Movement] Movement Cost of tile to 3."),
    ("LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_NAME",                    "The Country of Windmills"),
    ("LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_EXPANSION2_DESCRIPTION",  "Culture Bomb adjacent tiles when completing a Harbor. +50% construction speed toward the Dam district, Shipyard and Flood Barrier buildings. Shipyard provides +1 [ICON_TradeRoute] Trade Route capacity. When completing naval units (rather than purchasing or gaining them for free) in cities with a Shipyard, gains [ICON_Gold] Gold equal to the unit’s cost (doubles when the city also has a Bank). "),
    ("LOC_TRAIT_RADIO_ORANJE_DESCRIPTION",                            "For each [ICON_TradeRoute] Trade Routes to foreign cities or from foreign cities, Specialty districts provide yields to you as if they were international destination.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                             Text)
values
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC",         "每次获得一位 [ICON_GreatPerson] 伟人可奖励50点 [ICON_Favor] 外交支持（标准速度下）。二级工业区建筑与二级学院建筑分别提供+2 [ICON_GreatEngineer] 大工程师点数与+2 [ICON_GreatScientist] 大科学家点数。若对局中存在该文明，则进入工业时代后将增加3项特色世界议会竞赛。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_POLDER_DESCRIPTION",                            "解锁建造者建造荷兰特色改良设施“圩田”的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物、+1 [ICON_Production] 生产力、+0.5 [ICON_Housing] 住房。如与圩田改良设施相邻，则+1 [ICON_FOOD] 食物。解锁更多市政和科技后即可获得更多 [ICON_PRODUCTION] 生产力、[ICON_GOLD] 金币和 [ICON_FOOD] 食物。必须建在与2个或更多可通行陆地单元格相邻的海岸或湖泊单元格上。单元格的 [ICON_Movement] 移动力消耗增至3点。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_NAME",                    "风车之国"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_EXPANSION2_DESCRIPTION",  "建成港口后可对相邻单元格施放文化炸弹。建造堤坝区域和造船厂、拦洪坝建筑时加速50%。造船厂提供+1 [ICON_TradeRoute] 贸易路线容量。在拥有造船厂的城市生产出海军单位时（而非购买或赠送得到），获得等同于该单位成本的 [ICON_Gold] 金币，若该城市还拥有银行，则该效果翻倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_RADIO_ORANJE_DESCRIPTION",                            "对于每一条 [ICON_TradeRoute] 商路连接，无论您的城市作为国际商路的起点还是终点，您都可从该城内的专业化区域获得其作为国际目的地时的加成。");
