--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                         Text)
values
    ("LOC_BELIEF_ONE_WITH_NATURE_NAME",                           "One with Nature"),
    ("LOC_BELIEF_ONE_WITH_NATURE_DL_DESCRIPTION",                 "+8 [ICON_GreatProphet] Great Prophet points per turn, +10% to all yields, and +2 [ICON_Amenities] Amenity for cities having at least one natural wonder tile."),
    ("LOC_BELIEF_RIVER_GODDESS_DL_DESCRIPTION",                   "Major adjacency bonus for Holy Site if next to a River. +2 [ICON_Amenities] Amenity and +2 [ICON_Housing] Housing to cities if they have a Holy Site district adjacent to a River. +2 [ICON_GreatProphet] Great Prophet points per turn if a city is located adjacent to a River."),
    ("LOC_BELIEF_GOD_OF_WAR_DL_DESCRIPTION",                      "Combat units receive +1 [ICON_Strength] combat strength. Bonus [ICON_Faith] Faith equal to 50% of the base strength of each combat unit killed (on Standard Speed). Receive [ICON_GreatProphet] Great Prophet points equal to 50% of the opposing unit's base strength (on Standard Speed) when a combat unit defeats a major or minor civilization's unit."),
    ("LOC_ABILITY_GOD_OF_WAR_GREAT_PROPHET_NAME",                 "Great Prophet pointss"),
    ("LOC_ABILITY_GOD_OF_WAR_GREAT_PROPHET_DESCRIPTION",          "Receive [ICON_GreatProphet] Great Prophet pointss when a combat unit defeats a major or minor civilization's unit equal to 50% of the opposing unit's strength (Standard Speed). (God of War Belief)"),
    ("LOC_GOD_OF_WAR_GREAT_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT","God of War Belief"),
    ("LOC_BELIEF_MONUMENT_TO_THE_GODS_DL_DESCRIPTION",            "+15% [ICON_Production] Production towards Ancient and Classical era wonders. When chosen, receive a free Monument in your capital. Cities having a Monument yield +10% [ICON_Culture] Culture. May purchase Monument with [ICON_Faith] Faith."), --  Monument are 20% cheaper to purchase with [ICON_FAITH] Faith and [ICON_GOLD] Gold. +50% [ICON_production] Production towards Monument.
    ("LOC_BELIEF_FERTILITY_RITES_DL_DESCRIPTION",                 "When chosen, receive a free Granary in your capital. +10% [ICON_FOOD] Food in cities with a Granary. May purchase Granary with [ICON_Faith] Faith."), --  Granary are 20% cheaper to purchase with [ICON_FAITH] Faith and [ICON_GOLD] Gold. +50% [ICON_production] Production towards Granary.
    ("LOC_BELIEF_CITY_PATRON_GODDESS_DL_DESCRIPTION",             "+75% [ICON_Production] Production towards Districts in cities without a Specialty district."),
    ("LOC_BELIEF_MESSENGER_OF_THE_GODS_NAME",                     "Messenger of the Gods"),
    ("LOC_BELIEF_MESSENGER_OF_THE_GODS_DL_DESCRIPTION",           "When chosen, receive a Recon units with one free promotion in your [ICON_Capital] Capital. +1 [ICON_Movement] Movement for all Recon Units."),
    ("LOC_BELIEF_GOD_OF_THE_OPEN_SKY_DL_DESCRIPTION",             "+1 [ICON_Food] Food and +1 [ICON_Culture] Culture from Pastures."),
    ("LOC_BELIEF_ORAL_TRADITION_DL_DESCRIPTION",                  "+1 [ICON_Culture] Culture and +3 [ICON_Gold] Gold from Plantations."),
    ("LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_DL_DESCRIPTION",   "+2 [ICON_Production] Production from Marsh, Oasis, and Desert Floodplains. +1 [ICON_Science] Science from Marsh."),-- Floodplain tiles no longer lower adjacent tiles' Appeal.
    ("LOC_BELIEF_GODDESS_OF_THE_HUNT_DL_DESCRIPTION",             "Camps over Luxury and Bonus resources provide +1 [ICON_Food] Food and +1 [ICON_Production] Production."),
    ("LOC_BELIEF_DIVINE_SPARK_DL_DESCRIPTION",                    "+2 [ICON_GreatPerson] Great Person Points from Holy Sites (Prophet), Campuses (Scientist), Theater Squares  (Writer), Industial Zones (Engineer) and Commercial Hubs (Merchant)."),
    ("LOC_BELIEF_STONE_CIRCLES_DL_DESCRIPTION",                   "Quarries provide +1 [ICON_Faith] Faith and +1 [ICON_Production] Production. Cities having Quarries provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_RELIGIOUS_IDOLS_DL_DESCRIPTION",                 "+1 [ICON_Faith] Faith and +1 [ICON_CULTURE] Culture from Mines over Luxury and Bonus resources. +2 [ICON_GreatProphet] Great Prophet points per turn for cities having mines over Luxury or Bonus resources."),
    ("LOC_BELIEF_EARTH_GODDESS_DL_DESCRIPTION",                   "+2 [ICON_Faith] Faith from tiles with Breathtaking Appeal. +1 [ICON_Faith] Faith from tiles with Charming Appeal. +2 [ICON_GreatProphet] Great Prophet points per turn if a city is located on a Charming tile, doubles for Breathtaking tile."),
    ("LOC_BELIEF_GODDESS_OF_FIRE_DL_DESCRIPTION",                 "Geothermal Fissures and Volcanic Soil provide +1 [ICON_FAITH] Faith and +1 [ICON_CULTURE] Culture. Cities having Geothermal Fissures, Volcanic Soil or Volcano (Volcanic Wonders included) tiles provide +4 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_THE_PEOPLE_OF_POLAR_NAME",                       "The People of Polar"),
    ("LOC_BELIEF_THE_PEOPLE_OF_POLAR_DL_DESCRIPTION",             "City centers provide +1 [ICON_Food] Food and +1 [ICON_Faith] Faith for every 2 adjacent Tundras and every 2 adjacent Tundra Hills. Cities having Tundra or Tundra Hills tiles provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_GODDESS_OF_THE_DESERT_NAME",                     "Goddess of the Desert"),
    ("LOC_BELIEF_GODDESS_OF_THE_DESERT_DL_DESCRIPTION",           "City centers provide +1 [ICON_Food] Food and +1 [ICON_Faith] Faith for each adjacent Desert or Desert Hills tile. Cities having Desert or Desert Hills tiles provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_RELIGIOUS_SETTLEMENTS_DL_DESCRIPTION",           "Border expansion rate is 15% faster. Extra 4 tiles upon founding cities. +15% [ICON_PRODUCTION] towards Settler. -20% purchase cost when purchasing tiles."),
    ("LOC_BELIEF_DANCE_OF_THE_AURORA_DL_DESCRIPTION",             "Holy Site districts get minor adjacency bonus from Tundra and Tundra Hills. Holy Site provides +1 [ICON_Food] Food to all adjacent Tundra tiles. +2 [ICON_GreatProphet] Great Prophet point per turn if Holy Site is located on Tundra or Tundra Hills tiles."),
    ("LOC_BELIEF_DESERT_FOLKLORE_DL_DESCRIPTION",                 "Holy Site districts get minor adjacency bonus from Desert and Desert Hills. Holy Site provides +1 [ICON_Food] Food and +1 [ICON_Faith] Faith to all adjacent Desert tiles when not pillaged. +2 [ICON_GreatProphet] Great Prophet points per turn if Holy Site is located on Desert or Desert Hills tiles."),
    ("LOC_BELIEF_SACRED_PATH_DL_DESCRIPTION",                     "Holy Site districts get minor adjacency bonus from Rainforest. Holy Site provides +1 [ICON_Culture] Culture to all adjacent Rainforest tiles when not pillaged. +2 [ICON_GreatProphet] Great Prophet points per turn if Holy Site is adjacent to Rainforest tiles."),
    ("LOC_BELIEF_VOODOO_NAME",                                    "Voodoo"),
    ("LOC_BELIEF_VOODOO_DL_DESCRIPTION",                          "City centers provide +1 [ICON_Production] Production for each adjacent Rainforest tile, +1 [ICON_Culture] Culture from every two adjacent Rainforest tiles."),
    ("LOC_BELIEF_GODDESS_OF_FESTIVALS_DL_DESCRIPTION",            "Plantations provide +1 [ICON_Food] Food. Holy Site districts provide +1 [ICON_Faith] Faith for each adjacent Plantation tile. Plantations in your cities with Holy Site district provide +1 [ICON_Faith] Faith. Cities having Plantations provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_TENGRI_NAME",                                    "Tengri"),
    ("LOC_BELIEF_TENGRI_DL_DESCRIPTION",                          "Pastures provide +1 [ICON_Production] Production. Holy Site districts provide +1 [ICON_Faith] Faith for each adjacent Pasture tile. Pastures in your cities with Holy Site district provide +1 [ICON_Faith] Faith. Cities having Pastures provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_GODDESS_OF_THE_HARVEST_DL_DESCRIPTION",          "Farms over resource provide +1 [ICON_Food] Food and +1 [ICON_Production] Production."),
    ("LOC_BELIEF_GOD_OF_THE_SEA_DL_DESCRIPTION",                  "Fishing Boats provide +1 [ICON_Science] Science. Fishing Boats in your cities with Holy Site district provide +1 [ICON_Faith] Faith. Cities having Fishing Boats provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_OCEAN_MOTHER_DL_DESCRIPTION",                    "City center receive +1 [ICON_Food] Food and +1 [ICON_Faith] Faith from each adjacent Coast tile. +1 [ICON_Housing] Housing and +2 [ICON_GreatProphet] Great Prophet point per turn for cities that adjacent to Coasts."),
    ("LOC_BELIEF_OCEAN_MOTHER_NAME",                              "Ocean Mother"),
    ("LOC_BELIEF_HD_DRUID_NAME",                                  "Druid"),
    ("LOC_BELIEF_HD_DRUID_DL_DESCRIPTION",                        "Forest tiles provide +1 [ICON_Food] Food. Rainforest tiles provide +1 [ICON_Production] Production."),
    ("LOC_BELIEF_HD_MAZU_BELIEF_NAME",                            "Mazu Belief"),
    ("LOC_BELIEF_HD_MAZU_BELIEF_DL_DESCRIPTION",                  "City Centers adjacent to Coasts provide +2 [ICON_Production] Production. Fishing Boats provide +2 [ICON_Gold] Gold for each adjacent Specialized Districts."), 
    ("LOC_BELIEF_FISHING_TRADITION_NAME",                         "Fishing Traidition"),
    ("LOC_BELIEF_FISHING_TRADITION_DL_DESCRIPTION",               "Fishing Boats over Bonus resource provide +1 [ICON_FOOD], +1 [ICON_Production] Production."), -- and +2 [ICON_Gold] Gold 
    ("LOC_BELIEF_HD_GOD_KING_NAME",                               "God King"),
    ("LOC_BELIEF_HD_GOD_KING_DL_DESCRIPTION",                     "Palace provides +1 [ICON_Food] Food, +1 [ICON_Production] Production, +1 [ICON_Culture] Culture, +1 [ICON_Science] Scientist, +1 [ICON_Faith] Faith and +1 [ICON_Gold] Gold. When chosen, receive a [ICON_CITIZEN] Citizen, +1 [ICON_Amenities] Amenity and +1 [ICON_HOUSING] Housing in your capital."),
    ("LOC_BELIEF_GOD_OF_CRAFTSMEN_EXPANSION2_DESCRIPTION",        "+1 [ICON_Production] Production and +3 [ICON_Gold] Gold from improved Strategic resources. Properly improved Strategic resources provide an additional +1 per turn."),
    ("LOC_BELIEF_GOD_OF_THE_FORGE_DESCRIPTION",                   "When chosen, receive a free Artisan Plaza in your capital. Mines over Luxury and Bonus resources provide +1 [ICON_Production] Production."),
    ("LOC_BELIEF_HD_HERMES_NAME",                                 "Hermes"),
    ("LOC_BELIEF_HD_HERMES_DL_DESCRIPTION",                       "+1 [ICON_TradeRoute] Trade Route capacity and receive a free Trader in the capital. +1 [ICON_GOLD] Gold to all your Trade Routes."),
    ("LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_NAME",                  "Posterity of Mountain"),
    ("LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_DL_DESCRIPTION",        "Campus and Holy Site districts receive additional standard adjacency bonus from Mountains. Cities having Mountains provide +2 [ICON_GreatProphet] Great Prophet points per turn. Cities adjacent to Mountains receive +1 [ICON_Amenities] Amenity and +1 [ICON_Housing] Housing."),
    ("LOC_BELIEF_HD_SONG_OF_SIREN_NAME",                          "Song of Siren"),
    ("LOC_BELIEF_HD_SONG_OF_SIREN_DL_DESCRIPTION",                "+2 [ICON_Production] Production, +1 [ICON_GOLD] Gold from Reefs."),
    ("LOC_BELIEF_HD_UTAKI_NAME",                                  "Utaki"),
    ("LOC_BELIEF_HD_UTAKI_DL_DESCRIPTION",                        "Cities adjacent to Coasts receive +2 [ICON_Housing] Housing. City Centers provide +1 [ICON_Culture] Culture and +1 [ICON_Production] Production for every two adjacent Lake or Coast tiles."),
    ("LOC_BELIEF_HD_WOLF_GOD_NAME",                               "Lupercal"),
    ("LOC_BELIEF_HD_WOLF_GOD_DL_DESCRIPTION",                     "Camps over Luxury and Bonus resources provide +1 [ICON_CULTURE] Culture. Camps in cities with Holy Site districts provide +1 [ICON_Faith] Faith. Cities having Camps over Luxury or Bonus resources provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_HD_SUN_GOD_NAME",                                "Apollo"),
    ("LOC_BELIEF_HD_SUN_GOD_DL_DESCRIPTION",                      "Farms in cities with Holy Site districts provide +1 [ICON_FAITH] Faith. Plantations and Farms over resources provide +1 [ICON_FOOD] Food. Cities having Plantations or Farms over resources provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_SPARTA_SPIRIT_NAME",                             "Sparta Spirit"),
    ("LOC_BELIEF_SPARTA_SPIRIT_DESCRIPTION",                      "+50% [ICON_PRODUCTION] Production toward Ancient, Classical and Medieval military units. Receive 40% discount on Strategic resource costs for units."),
    ("LOC_BELIEF_TALE_OF_DWALVES_NAME",                           "Tale of Dwalves"),
    ("LOC_BELIEF_TALE_OF_DWALVES_DESCRIPTION",                    "+1 [ICON_FOOD] Food and +1 [ICON_HOUSING] Housing from Mines over Luxury and Bonus resources. +2 [ICON_GOLD] Gold from all Mines."),
    ("LOC_BELIEF_MEGALITHIC_WORSHIP_NAME",                        "Megalithic Worship"),
    ("LOC_BELIEF_MEGALITHIC_WORSHIP_DESCRIPTION",                 "Quarries provide +1 [ICON_CULTURE] Culture and +3 [ICON_GOLD] Gold.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                         Text)
values
    ("zh_Hans_CN",  "LOC_BELIEF_ONE_WITH_NATURE_NAME",                           "天人合一"),
    ("zh_Hans_CN",  "LOC_BELIEF_ONE_WITH_NATURE_DL_DESCRIPTION",                 "拥有自然奇观的城市+2 [ICON_Amenities] 宜居度、+10%所有产出，且每回合+8 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_RIVER_GODDESS_DL_DESCRIPTION",                   "与河流相邻时，圣地获得大量相邻加成。如果拥有与河流相邻的圣地区域，则城市+2 [ICON_Amenities] 宜居度、+2 [ICON_Housing] 住房。如城市市中心坐落在河边，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_WAR_DL_DESCRIPTION",                      "战斗单位+1 [ICON_Strength] 战斗力。每击杀1个战斗单位即可获得等于其战斗力50%的 [ICON_Faith] 信仰值（标准速度下）。战斗单位击杀主要和小型文明的单位时，获得等同于对方单位战斗力50%的 [ICON_GreatProphet] 大预言家点数（标准速度下）。"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOD_OF_WAR_GREAT_PROPHET_NAME",                 "大预言家点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOD_OF_WAR_GREAT_PROPHET_DESCRIPTION",          "战斗单位击杀主要和小型文明的单位时，获得等同于对方单位战斗力50%的 [ICON_GreatProphet] 大预言家点数（标准速度下）。（战争之神）"),
    ("zh_Hans_CN",  "LOC_GOD_OF_WAR_GREAT_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT","战争之神"),
    ("zh_Hans_CN",  "LOC_BELIEF_MONUMENT_TO_THE_GODS_DL_DESCRIPTION",            "远古和古典奇观+15% [ICON_Production] 生产力。选择后即可在首都中获得一个免费的纪念碑。拥有纪念碑的城市增加10% [ICON_Culture] 文化值。可以使用 [ICON_Faith] 信仰值购买纪念碑。"), -- ，用 [ICON_FAITH] 信仰值和 [ICON_GOLD] 金币购买纪念碑的费用降低20%。纪念碑的建造速度+50%。
    ("zh_Hans_CN",  "LOC_BELIEF_FERTILITY_RITES_DL_DESCRIPTION",                 "选择后即可在首都中获得一个免费的粮仓。拥有粮仓的城市总粮增加10%。可以使用 [ICON_Faith] 信仰值购买粮仓。"), -- ，用 [ICON_FAITH] 信仰值和 [ICON_GOLD] 金币购买粮仓的费用降低20%。粮仓的建造速度+50%
    ("zh_Hans_CN",  "LOC_BELIEF_CITY_PATRON_GODDESS_DL_DESCRIPTION",             "没有专业化区域的城市建造区域+75% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_MESSENGER_OF_THE_GODS_NAME",                     "神使"),
    ("zh_Hans_CN",  "LOC_BELIEF_MESSENGER_OF_THE_GODS_DL_DESCRIPTION",           "选择后即可在首都中获得1个有免费晋升的侦察单位。所有侦察类型的单位+1 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_THE_OPEN_SKY_DL_DESCRIPTION",             "牧场+1 [ICON_Food] 食物和 +1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_ORAL_TRADITION_DL_DESCRIPTION",                  "种植园+1 [ICON_Culture] 文化值和 +3 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_DL_DESCRIPTION",   "沼泽、绿洲、沙漠泛滥平原提供+2 [ICON_Production] 生产力。沼泽提供+1 [ICON_Science] 科技值。"),-- 泛滥平原不再为相邻单元格-1魅力。
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_HUNT_DL_DESCRIPTION",             "采集奢侈品资源和加成资源的营地+1 [ICON_Food] 食物和 +1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_DIVINE_SPARK_DL_DESCRIPTION",                    "从圣地（大预言家）、学院（大科学家）、剧院广场（大作家）、工业区（大工程师）以及商业区（大商人）处获得的 [ICON_GreatPerson] 伟人点数+2。"),
    ("zh_Hans_CN",  "LOC_BELIEF_STONE_CIRCLES_DL_DESCRIPTION",                   "采石场+1 [ICON_Faith] 信仰值和+1 [ICON_Production] 生产力。如城市中有采石场，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_RELIGIOUS_IDOLS_DL_DESCRIPTION",                 "采集奢侈和加成矿山+1 [ICON_CULTURE] 文化值和+1 [ICON_FAITH] 信仰值。如城市拥有采集奢侈或加成资源的矿山，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_EARTH_GODDESS_DL_DESCRIPTION",                   "魅力为惊艳的单元格提供的 [ICON_Faith] 信仰值+2。魅力为迷人的单元格提供的 [ICON_Faith] 信仰值+1。如城市市中心坐落在迷人地块上，则每回合+2 [ICON_GreatProphet] 大预言家点数，惊艳则翻倍。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_FIRE_DL_DESCRIPTION",                 "地热裂缝和火山土单元格提供+1 [ICON_CULTURE] 文化值和+1 [ICON_FAITH] 信仰值。每座拥有地热裂缝、火山土或火山（包括火山自然奇观）的城市提供+4 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_THE_PEOPLE_OF_POLAR_NAME",                       "极地子民"),
    ("zh_Hans_CN",  "LOC_BELIEF_THE_PEOPLE_OF_POLAR_DL_DESCRIPTION",             "市中心相邻每2个冻土和每2个冻土丘陵+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。如城市中有冻土或冻土丘陵，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_DESERT_NAME",                     "沙之女神"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_DESERT_DL_DESCRIPTION",           "市中心相邻每个沙漠和沙漠丘陵单元格 +1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值，如城市中有沙漠或沙漠丘陵，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_RELIGIOUS_SETTLEMENTS_DL_DESCRIPTION",           "边界扩张速度提升15%，城市创建时获得额外4个单元格。生产移民时，+15%建造速度。 购买单元格的价格所需的 [ICON_GOLD] 金币-20%。"),
    ("zh_Hans_CN",  "LOC_BELIEF_DANCE_OF_THE_AURORA_DL_DESCRIPTION",             "圣地从冻土和冻土丘陵获得小相邻加成。每个相邻的冻土单元格+1 [ICON_Faith] 信仰值。未被劫掠过的圣地给相邻的冻土单元格+1 [ICON_Food] 食物。若圣地位于冻土或冻土丘陵则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_DESERT_FOLKLORE_DL_DESCRIPTION",                 "圣地从沙漠和沙漠丘陵获得小相邻加成。未被劫掠过的圣地给相邻的沙漠单元格+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。若圣地位于沙漠或沙漠丘陵则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_SACRED_PATH_DL_DESCRIPTION",                     "圣地从雨林获得小相邻加成。未被劫掠过的圣地给相邻的雨林单元格+1 [ICON_Culture] 文化。若圣地相邻雨林则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_VOODOO_NAME",                                    "伏都教"),
    ("zh_Hans_CN",  "LOC_BELIEF_VOODOO_DL_DESCRIPTION",                          "市中心相邻每个雨林单元格+1 [ICON_Production] 生产力。每2个雨林单元格+1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_FESTIVALS_DL_DESCRIPTION",            "种植园+1 [ICON_Food] 食物。圣地区域从每个相邻的种植园获得+1 [ICON_Faith] 信仰值，给本城的种植园 +1 [ICON_Faith] 信仰值。如城市中有种植园，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_TENGRI_NAME",                                    "长生天"),
    ("zh_Hans_CN",  "LOC_BELIEF_TENGRI_DL_DESCRIPTION",                          "牧场+1 [ICON_Production] 生产力。圣地区域从每个相邻的牧场获得+1 [ICON_Faith] 信仰值，给本城的牧场 +1 [ICON_Faith] 信仰值。如城市中有牧场，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_HARVEST_DL_DESCRIPTION",          "改良资源的农场+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_THE_SEA_DL_DESCRIPTION",                  "渔船+1 [ICON_Science] 科技值。有圣地的城市渔船+1 [ICON_FAITH] 信仰值。如城市中有渔船，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_OCEAN_MOTHER_DL_DESCRIPTION",                    "市中心相邻每个海岸单元格+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。相邻海岸的市中心+1 [ICON_Housing] 住房，且城市每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_OCEAN_MOTHER_NAME",                              "海洋母亲"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_DRUID_NAME",                                  "德鲁伊"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_DRUID_DL_DESCRIPTION",                        "森林单元格+1 [ICON_Food] 粮食，雨林单元格+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_MAZU_BELIEF_NAME",                            "妈祖信仰"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_MAZU_BELIEF_DL_DESCRIPTION",                  "位于海边的城市+2 [ICON_Production] 生产力。渔船相邻每个专业化区域获得+2 [ICON_Gold] 金币。"), 
    ("zh_Hans_CN",  "LOC_BELIEF_FISHING_TRADITION_NAME",                         "捕鱼传统"),
    ("zh_Hans_CN",  "LOC_BELIEF_FISHING_TRADITION_DL_DESCRIPTION",               "改良加成资源的渔船+1[ICON_FOOD] 食物和+1 [ICON_Production] 生产力。"), -- 和+2 [ICON_Gold] 金币
    ("zh_Hans_CN",  "LOC_BELIEF_HD_GOD_KING_NAME",                               "神王"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_GOD_KING_DL_DESCRIPTION",                     "宫殿+1 [ICON_Food] 食物、 +1 [ICON_Production] 生产力、 +1 [ICON_Culture] 文化值、 +1 [ICON_Science] 科技值、 +1 [ICON_Faith] 信仰值和 +1 [ICON_Gold] 金币。首都+1 [ICON_CITIZEN] 人口、+1 [ICON_Amenities] 宜居度和+1 [ICON_HOUSING] 住房。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_CRAFTSMEN_EXPANSION2_DESCRIPTION",        "改良后的战略资源+1 [ICON_Production] 生产力和+3 [ICON_Gold] 金币。正确改良的战略资源每回合积累+1。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_THE_FORGE_DESCRIPTION",                   "选择后即可在首都中获得一个免费的工官。采集奢侈品资源和加成资源的矿山+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_HERMES_NAME",                                 "赫尔墨斯"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_HERMES_DL_DESCRIPTION",                       "选择后即可在首都中获得一个商人，+1 [ICON_TradeRoute] 贸易路线容量。所有商路+1 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_NAME",                  "山之苗裔"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_DL_DESCRIPTION",        "学院和圣地靠山获得的加成翻倍，有山脉的城市+2 [ICON_GreatProphet] 大预言家点数，相邻山脉的市中心+1 [ICON_Housing] 住房，+1 [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SONG_OF_SIREN_NAME",                          "塞壬之歌"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SONG_OF_SIREN_DL_DESCRIPTION",                "礁石单元格+2 [ICON_Production] 生产力和+1 [ICON_GOLD]金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_UTAKI_NAME",                                  "御岳"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_UTAKI_DL_DESCRIPTION",                        "沿海市中心+2 [ICON_Housing] 住房；每相邻两块近海或湖泊单元格，市中心额外+1 [ICON_Culture] 文化值，+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_WOLF_GOD_NAME",                               "牧狼神"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_WOLF_GOD_DL_DESCRIPTION",                     "采集奢侈品资源和加成资源的营地+1 [ICON_Culture] 文化值。圣地区域给所在城市的营地+1 [ICON_Faith] 信仰值。如城市拥有采集奢侈或加成资源的营地，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SUN_GOD_NAME",                                "太阳神"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SUN_GOD_DL_DESCRIPTION",                      "种植园和改良资源的农场+1 [ICON_FOOD] 食物。如城市拥有种植园或改良资源的农场，则每回合+2 [ICON_GreatProphet] 大预言家点数。圣地给所在城市的农场+1 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_SPARTA_SPIRIT_NAME",                             "斯巴达精神"),
    ("zh_Hans_CN",  "LOC_BELIEF_SPARTA_SPIRIT_DESCRIPTION",                      "为远古、古典和中世纪军事单位+50% [ICON_PRODUCTION] 生产力。生产单位所需战略资源花费减少40%。"),
    ("zh_Hans_CN",  "LOC_BELIEF_TALE_OF_DWALVES_NAME",                           "矮人传说"),
    ("zh_Hans_CN",  "LOC_BELIEF_TALE_OF_DWALVES_DESCRIPTION",                    "改良奢侈和加成资源的矿山+1 [ICON_FOOD] 食物，+1 [ICON_HOUSING] 住房。所有矿山+2 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_MEGALITHIC_WORSHIP_NAME",                        "巨石崇拜"),
    ("zh_Hans_CN",  "LOC_BELIEF_MEGALITHIC_WORSHIP_DESCRIPTION",                 "采石场+1 [ICON_CULTURE] 文化值，+3 [ICON_GOLD] 金币。");
