--------------------------------------------------------------------------------
-- Language: en_US

insert or replace into EnglishText
    (Tag,                                                                                   Text)
values
    -- New Techs
    ("LOC_TECH_CALENDAR_HD_NAME",                                                           "Calendar"),
    ("LOC_TECH_PAPER_MAKING_HD_NAME",                                                       "Paper Making"),
    ("LOC_TECH_COMPASS_HD_NAME",                                                            "Compass"),
    ("LOC_TECH_PHYSICS_HD_NAME",                                                            "Physics"),
    ("LOC_TECH_BIOLOGY_HD_NAME",                                                            "Biology"),
    ("LOC_TECH_CIVIL_ENGINEERING_HD_NAME",                                                  "Civil Engineering"),
    -- New Techs Boosts
    ("LOC_BOOST_TRIGGER_CALENDAR_HD",                                                       "Build 1 Granary."),
    ("LOC_BOOST_TRIGGER_LONGDESC_CALENDAR_HD",                                              "With the development of agriculture in our empire, we need to plan our production for these years."),
    ("LOC_BOOST_TRIGGER_PAPER_MAKING_HD",                                                   "Build a Plantation."),
    ("LOC_BOOST_TRIGGER_LONGDESC_PAPER_MAKING_HD",                                          "From the stems of the plants in the plantations, we have found some useful fibers."),
    -- ("LOC_BOOST_TRIGGER_COMPASS_HD",                                                        "Have the Naval Tradition Civic."),
    -- ("LOC_BOOST_TRIGGER_LONGDESC_COMPASS_HD",                                               "With the development of navigation technology, magnetic tools have become a necessity for navigators."),
    ("LOC_BOOST_TRIGGER_COMPASS_HD",                                                        "Have the Mathematics Technology."),
    ("LOC_BOOST_TRIGGER_LONGDESC_COMPASS_HD",                                               "With the development of Mathematics, we have learnt to use magnetic tools for navigators."),
    ("LOC_BOOST_TRIGGER_PHYSICS_HD",                                                        "Earn a Great Scientist."),
    ("LOC_BOOST_TRIGGER_LONGDESC_PHYSICS_HD",                                               "Scientists' great theories form our basic understanding of the world."),
    ("LOC_BOOST_TRIGGER_BIOLOGY_HD",                                                        "Build a Zoo."),
    ("LOC_BOOST_TRIGGER_LONGDESC_BIOLOGY_HD",                                               "After collecting animals from all over the world, the zoos in our empire are getting busier and busier. It's time to sort these creatures out."),
    ("LOC_BOOST_TRIGGER_CIVIL_ENGINEERING_HD",                                              "Build 2 Workshops."),
    ("LOC_BOOST_TRIGGER_LONGDESC_CIVIL_ENGINEERING_HD",                                     "The workshop's artisans summed up the basic principles of civil engineering for us."),
    -- Techs
    ("LOC_TECH_MINING_HD_DESCRIPTION",                                                      "Allows chopping of Woods and Rainforest, and harvesting of resources improved by Mines."),
    ("LOC_TECH_ANIMAL_HUSBANDRY_HD_DESCRIPTION",                                            "Allows harvesting of resources improved by Pastures and Camps."),
    ("LOC_TECH_POTTERY_DESCRIPTION",                                                        "Allows harvesting of resources improved by Farms."),
    ("LOC_TECH_SAILING_HD_DESCRIPTION",                                                     "Allows harvesting of resources improved by Fishing Boats. Allows Builders and Traders to embark."),
    ("LOC_TECH_IRRIGATION_DESCRIPTION",                                                     "+2 [ICON_GOLD] Gold from Plantations adjacent to fresh water or Aqueduct.[NEWLINE]Allows clearing of Marsh, and harvesting of resources improved by Plantations. Allows Builders to build Farms on Plains Hills or Grassland Hills adjacent to fresh water or Aqueduct."),
    ("LOC_TECH_ARCHERY_HD_DESCRIPTION",                                                     "Allows Camps to be built on Forests."), -- Camp improvements receive +1 [ICON_GOLD] Gold.
    ("LOC_TECH_CALENDAR_HD_DESCRIPTION",                                                    "+1 [ICON_Food] Food from Farms. [NEWLINE]+1 [ICON_CULTURE] Culture for Monuments.[NEWLINE][ICON_Food] Food consumption of [ICON_Citizen] citizens is reduced by 0.5 in cities with a Granary."),
	("LOC_TECH_COMPASS_HD_DESCRIPTION",														"+1 [ICON_PRODUCTION] Production from Fishing Boats."),
    ("LOC_TECH_THE_WHEEL_HD_DESCRIPTION",                                                   "All improvements inside your territory always obtain roads for free."), -- Pasture improvements receive +1 [ICON_GOLD] Gold.
    ("LOC_TECH_BRONZE_WORKING_DESCRIPTION",                                                 "Reveals [ICON_RESOURCE_IRON] Iron. Allows harvesting of resources improved by Lumber Mills."),
    ("LOC_TECH_MASONRY_HD_DESCRIPTION",                                                     "Allows harvesting of resources improved by Quarries."),
    ("LOC_TECH_CELESTIAL_NAVIGATION_HD_DESCRIPTION",                                        " Allows all land units to embark."),
    ("LOC_TECH_PAPER_MAKING_HD_DESCRIPTION",                                                "+1 [ICON_FOOD] Food from Plantations.[NEWLINE][ICON_Citizen] Citizens in cities with a Library provide +0.3 [ICON_SCIENCE] Science."),
    -- ("LOC_TECH_CURRENCY_HD_DESCRIPTION",                                                    "Provides +3 [ICON_GOLD] Gold to Commercial Hubs."),
    ("LOC_TECH_HORSEBACK_RIDING_HD_DESCRIPTION",                                            "Pasture improvements provide +1 [ICON_Production] Production."),
    ("LOC_TECH_SHIPBUILDING_HD_DESCRIPTION",                                                "Allows all land units to embark. [NEWLINE]Recon units are exempt from [ICON_Strength] Combat Strength penalty when attacking from the water or over a River, and [ICON_Movement] Movement penalty from embarking, disembarking and crossing River."),
    ("LOC_TECH_ENGINEERING_HD_DESCRIPTION",                                                 "Mine and Quarry improvements receive +1 [ICON_PRODUCTION] Production. Mine improvements can be built on Geothermal Fissures."),
    ("LOC_TECH_CONSTRUCTION_HD_DESCRIPTION",                                                "Camp and Lumber Mill improvements provide +1 [ICON_PRODUCTION] Production."), -- 
    ("LOC_TECH_APPRENTICESHIP_HD_DESCRIPTION",                                              "Mine improvements receive +1 [ICON_PRODUCTION] Production."),
    ("LOC_TECH_MACHINERY_HD_DESCRIPTION",                                                   "+50% yields from resource harvests and feature removals. +1 [ICON_Production] Production to Lumber Mills."),
    -- ("LOC_TECH_MACHINERY_HD_ALT_DESCRIPTION",                                               "+50% yields from resource harvests and feature removals. +1 [ICON_Production] Production to Lumber Mills that are not adjacent to rivers."),
    -- ("LOC_TECH_MILITARY_ENGINEERING_HD_DESCRIPTION",                                        "All improved strategic resources yield 3 additional resources per turn."),
    -- ("LOC_TECH_CASTLES_HD_DESCRIPTION",                                                     "Gain a free Spy if playing as Catherine de Medici (Black Queen)."),
    -- ("LOC_TECH_STIRRUPS_HD_DESCRIPTION",                                                    "Pasture improvements receive +1 [ICON_Production] Production."),
    ("LOC_TECH_MASS_PRODUCTION_HD_DESCRIPTION",                                             "Pasture improvements receive +1 [ICON_Food] Food."), 
    -- ("LOC_TECH_ASTRONOMY_HD_DESCRIPTION",                                                    "+3 [ICON_Science] Science to Campus Districts adjacent to Mountains. +5% [ICON_Science] Science for cities with University."),
    -- ("LOC_TECH_MILITARY_TACTICS_HD_DESCRIPTION",                                            "Melee units gain the ability: +3 [ICON_Strength] Combat Strength if there is at least one adjacent friendly melee unit.[NEWLINE]Ranged units gain the ability: +5 [ICON_Strength] Combat Strength when attacking from Hills. [NEWLINE]Light Cavalry units gain the ability: +5 [ICON_Strength] Combat Strength against units."),
    ("LOC_TECH_MILITARY_TACTICS_HD_DESCRIPTION",                                            "Melee units gain the ability: +3 [ICON_Strength] Combat Strength when adjacent to at least one friendly melee unit. [NEWLINE] Ranged units gain ability: +5 [ICON_Strength] Combat Strength when attacking from a hill. [NEWLINE] Light Cavalry units gain the ability: +5 [ICON_Strength] Combat Strength when fighting units. [NEWLINE] Anti-Cavalry units gain the ability to no longer suffer [ICON_Strength] combat strength reductions from the unit's wound level."),
    ("LOC_TECH_GUNPOWDER_HD_DESCRIPTION",                                                   "Quarry improvements provide +1 [ICON_Production] Production. [NEWLINE]Unlocks a [ICON_GOVERNOR] Governor title for Suleiman. [NEWLINE]Heavy Cavalry units gain the ability: +10 [ICON_Damaged] Health after defeating an enemy unit."),
    ("LOC_TECH_SQUARE_RIGGING_HD_DESCRIPTION",                                              "+1 [ICON_Movement] Movement for embarked units.[NEWLINE]Naval melee units can escort units (formation units all inherit escort's [ICON_Movement] Movement speed)."),
    ("LOC_TECH_SCIENTIFIC_THEORY_HD_DESCRIPTION",                                           "+1 [ICON_Housing] Housing from Fisheries."),
    ("LOC_TECH_CIVIL_ENGINEERING_HD_DESCRIPTION",                                           "Allows Farms to be built on Grassland Hills and Plains Hills. Lumber Mill improvements provide +1 [ICON_Production] Production."),
    ("LOC_TECH_STEAM_POWER_HD_DESCRIPTION",                                                 "+2 [ICON_GOLD] Gold from Fishing Boats.[NEWLINE]+2 [ICON_Movement] Movement for embarked units. +15 tiles for water trade route range."),
	("LOC_TECH_CARTOGRAPHY_HD_DESCRIPTION",													"+1 [ICON_FOOD] Food from Fisheries.[NEWLINE]All naval and embarked units can navigate Ocean tiles."),
    -- ("LOC_TECH_SANITATION_HD_DESCRIPTION",                                                  "Stepwell improvements receive +1 [ICON_Housing] Housing."), -- [NEWLINE]Anti-cavalry units gain the ability: Ignore [ICON_Strength] Combat Strength reduction from being injured.
    ("LOC_TECH_RIFLING_HD_DESCRIPTION",                                                     "Siege units gain the ability: +5 [ICON_Strength] Combat Strength when attacking defensible districts."),
    -- ("LOC_TECH_RIFLING_HD_DESCRIPTION",                                                     "Camp improvements receive +1 [ICON_FOOD] Food."),
    ("LOC_TECH_FLIGHT_DESCRIPTION",                                                         "Receive [ICON_Tourism] Tourism from some of the improvements that provide [ICON_Science] Science, [ICON_Culture] Culture, [ICON_Faith] Faith or [ICON_PRODUCTION] Production. Amount of [ICON_Tourism] Tourism generated is equivalent to these yields."),
    ("LOC_TECH_STEEL_HD_DESCRIPTION",                                                       "Unlocks Urban Defenses, giving all of your cities an automatic 400 Fortification HP and the ability to perform a ranged attack. All previous walls become obsolete and siege support units are no longer effective."),
    ("LOC_TECH_BIOLOGY_HD_DESCRIPTION",                                                     "Farms provide +1 [ICON_Food] Food from every adjacent Farms instead of two."),
    ("LOC_TECH_COMPUTERS_DESCRIPTION",                                                      "Grants the ability to construct an additional Spy. +20% [ICON_Tourism] Tourism across your empire."),
    ("LOC_TECH_TELECOMMUNICATIONS_HD_DESCRIPTION",                                          "+50% [ICON_TOURISM] Tourism from all kinds of Great Works except for [ICON_GREATWORK_RELIC] Relic."),
    ("LOC_TECH_SYNTHETIC_MATERIALS_HD_DESCRIPTION",                                         "+2 [ICON_Gold] Gold from Camps."),
    ("LOC_TECH_ROBOTICS_HD_DESCRIPTION",                                                    "+2 [ICON_Food] Food from Pastures."),
    ("LOC_TECH_CYBERNETICS_HD_DESCRIPTION",                                                 "+1 [ICON_Production] production from Lumber Mills.[NEWLINE]{LOC_TECH_CYBERNETICS_DESCRIPTION}"),
    ("LOC_TECH_SMART_MATERIALS_HD_DESCRIPTION",                                             "+1 [ICON_Production] production from Mines.[NEWLINE]{LOC_TECH_SMART_MATERIALS_DESCRIPTION}"),
	("LOC_TECH_PLASTICS_HD_DESCRIPTION",													"+2 [ICON_GOLD] Gold from fisheries.[NEWLINE]{LOC_TECH_PLASTICS_DESCRIPTION}"),
    -- New Civics
    ("LOC_CIVIC_LITERARY_TRADITION_HD_NAME",                                                "Literary Tradition"),
    ("LOC_CIVIC_DEFENSIVE_TACTICS_HD_NAME",                                                 "Supply"),
    ("LOC_CIVIC_NATURAL_HISTORY_HD_NAME",                                                   "Archaeology"),
    ("LOC_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_NAME",                                       "Imperial Examination System"),
    ("LOC_CIVIC_EVOLUTION_THEORY_HD_NAME",                                                  "Evolution Theory"),
    ("LOC_CIVIC_EVOLUTION_THEORY_HD_DESCRIPTION",                                           "Camp improvements provide +1 [ICON_Food] Food."), -- +1 [ICON_Production] Production 
    ("LOC_CIVIC_HISTORICAL_PHILOSOPHY_HD_NAME",                                             "Historical Philosophy"),
    ("LOC_CIVIC_ETHICS_HD_NAME",                                                            "Ethics"),
    ("LOC_CIVIC_SOCIAL_SCIENCE_HD_NAME",                                                    "Social Sciences"),
    -- New Civics Boosts
    ("LOC_BOOST_TRIGGER_LITERARY_TRADITION_HD",                                             "Have the Paper Making Technology."),
    ("LOC_BOOST_TRIGGER_LONGDESC_LITERARY_TRADITION_HD",                                    "The articles writen on paper have become the foundation of our culture."),
    ("LOC_BOOST_TRIGGER_IMPERIAL_EXAMINATION_SYSTEM_HD",                                    "Build 2 Campuses."),
    ("LOC_BOOST_TRIGGER_LONGDESC_IMPERIAL_EXAMINATION_SYSTEM_HD",                           "With the increasing number of intellectuals, we should find a way to utilize their talents."),
    ("LOC_BOOST_TRIGGER_EVOLUTION_THEORY_HD",                                               "Build a Campus on a foreign continent."),
    ("LOC_BOOST_TRIGGER_LONGDESC_EVOLUTION_THEORY_HD",                                      "Scholars on overseas expeditions collected a variety of novel biological resources, which has inspired not only Biology but also social thinking."),
    ("LOC_BOOST_TRIGGER_HISTORICAL_PHILOSOPHY_HD",                                          "Build 3 Theater."),
    ("LOC_BOOST_TRIGGER_LONGDESC_HISTORICAL_PHILOSOPHY_HD",                                 "Generations of statesmen and thinkers inspired writing, leaving us a precious historical legacy."),
    ("LOC_BOOST_TRIGGER_ETHICS_HD",                                                         "Have the Printing Technology."),
    ("LOC_BOOST_TRIGGER_LONGDESC_ETHICS_HD",                                                "When the Bible was printed, truth spreads all over the world."),
    ("LOC_BOOST_TRIGGER_SOCIAL_SCIENCE_HD",                                                 "Build 7 different specialty districts."),
    ("LOC_BOOST_TRIGGER_LONGDESC_SOCIAL_SCIENCE_HD",                                        "Complex cities form complex social relationships, while some geniuses see it through clearly."),
    -- Civics
    ("LOC_CIVIC_NATURAL_HISTORY_NAME",                                                      "Archaeology"),
    ("LOC_CIVIC_FEUDALISM_HD_DESCRIPTION",                                                  "Farms provide +1 [ICON_Food] Food from every 2 adjacent Farms.[NEWLINE]+2 [ICON_GOLD] Gold from Plantations not adjacent to fresh water or Aqueduct.[NEWLINE]+1 [ICON_PRODUCTION] from Pastures.[NEWLINE]Campus districts with university receive an additional standard adjacency bonus from rainforest tiles. [NEWLINE]Melee units gain the ability: +3 [ICON_Strength] Combat Strength when fighting in Rainforest or Woods tiles."),
    ("LOC_CIVIC_DEFENSIVE_TACTICS_HD_DESCRIPTION",                                          "Ranged units gain the ability: +5 [ICON_Strength] Combat Strength when occupying either an improvement that provides [ICON_Strength] Defense Strength or a District. [NEWLINE]Anti-cavalry units gain the ability: +7 [ICON_Strength] Combat Strength when defending from melee attack on Hills."),
    ("LOC_CIVIC_MILITARY_TRAINING_HD_DESCRIPTION",                                          "Heavy Cavalry units gain the ability: +5 [ICON_Strength] Combat Strength when attacking wounded units. [NEWLINE]Siege units gain the ability: Can attack after moving."), -- +5 [ICON_Strength] Combat Strength when fighting on flat tiles without Woods, Jungle, or Marsh.
    -- ("LOC_CIVIC_MERCENARIES_HD_DESCRIPTION",                                             "Light Cavalry units gain the ability: Pillaging Improvements and Districts provides extra 25 [ICON_Faith] Faith."),
    ("LOC_CIVIC_MERCENARIES_HD_DESCRIPTION",                                                "Light Cavalry units gain the ability: +1 [ICON_Movement] Movement if starting in enemy's territory."),
    ("LOC_CIVIC_MERCANTILISM_HD_DESCRIPTION",                                               "Recon units gain the ability: Ignores Zones of Control. [NEWLINE]+2 [ICON_GOLD] Gold from Plantations."),
	("LOC_CIVIC_NAVAL_TRADITION_HD_DESCRIPTION",											"+2 [ICON_GOLD] Gold from Fisheries."),
    ("LOC_CIVIC_CIVIL_SERVICE_HD_DESCRIPTION",                                              "Established [ICON_GOVERNOR] Governors with at least 2 Promotions provide +1 [ICON_Amenities] Amenity and +3 [ICON_Housing] Housing."),
    ("LOC_CIVIC_MEDIEVAL_FAIRES_HD_DESCRIPTION",                                            "+1 [ICON_Production] Production from Camps."),
    ("LOC_CIVIC_COLONIALISM_HD_DESCRIPTION",                                                "+1 [ICON_PRODUCTION] Production from fisheries.[NEWLINE]Gain +1 [ICON_Favor] Favor as Suzerain of a City-State.[NEWLINE]Allows forming two identical units into a Fleet.[NEWLINE]Allows one new Casus Belli that can be used to justify wars: Colonial War."),
    ("LOC_CIVIC_GUILDS_HD_DESCRIPTION",                                                     "Lumber Mills and Camps can be built on Rainforest. [NEWLINE]Allows Builders to plant Woods (second-growth).[NEWLINE]Woods in your territory that have never been removed (old-growth) gain +1 Appeal."),
    ("LOC_CIVIC_ENVIRONMENTALISM_HD_DESCRIPTION",                                           "+20% [ICON_Tourism] Tourism across your empire."),
    ("LOC_CIVIC_GLOBALIZATION_HD_DESCRIPTION",                                              "Plantation improvements provide +2 [ICON_Gold] Gold."),
    ("LOC_CIVIC_NATIONALISM_HD_DESCRIPTION",                                                "Grants the ability to construct an additional Spy.[NEWLINE]Allows forming two identical units into a Corps."),
    ("LOC_CIVIC_CONSERVATION_HD_DESCRIPTION",                                               "Awards 3 [ICON_Envoy] Envoys. Allows the building of National Parks and the purchase of Naturalists with [ICON_Faith] Faith. Receives +1 [ICON_Amenities] Amenity when city center is adjacent to Woods. Receive [ICON_TOURISM] Tourism from Walls."),
    ("LOC_CIVIC_NUCLEAR_PROGRAM_DESCRIPTION",                                               "+50% [ICON_Production] Production to nuclear program projects, Nuclear Devices and Nuclear Power Plant."),
    ("LOC_CIVIC_SCORCHED_EARTH_HD_DESCRIPTION",                                             "Naval Raider units gain ability:  Coastal Raid costs no [ICON_MOVEMENT] Movement."),
    ("LOC_CIVIC_CRAFTSMANSHIP_HD_DESCRIPTION",                                              "Recon units gain the ability: {LOC_ABILITY_SCOUNT_IGNORE_ALL_HD_DESCRIPTION}"),
    ("LOC_CIVIC_COLD_WAR_DESCRIPTION",                                              		"Each [ICON_ENVOY] Envoy you send to a city-state counts as two, if its Suzerain has a different government than you. Grants the ability to construct an additional Spy."),
    -- Boosts
    ("LOC_BOOST_TRIGGER_MASS_PRODUCTION",                                                   "Build 2 Lumber Mills."),
    ("LOC_BOOST_TRIGGER_BRONZE_WORKING",                                                    "Kill 2 Barbarians."),
    -- 
    ("LOC_BOOST_TRIGGER_THE_WHEEL",                                                         "Build a Pasture."),
    ("LOC_BOOST_TRIGGER_LONGDESC_THE_WHEEL",                                                "Domesticated animals are really good helpers for humans, but how to use them more efficiently?"),
    ("LOC_BOOST_TRIGGER_HORSEBACK_RIDING",                                                  "Build a Pasture on Horses."),
    ("LOC_BOOST_TRIGGER_LONGDESC_HORSEBACK_RIDING",                                         "With Horses now domesticated into Pastures, it is time to learn to ride."),
    ("LOC_BOOST_TRIGGER_FOREIGN_TRADE",                                                     "Meet another Major Civilization."),
    ("LOC_BOOST_TRIGGER_LONGDESC_FOREIGN_TRADE",                                            "After meeting with another civilized country, you discover that there are many trade opportunities in this vast world."),
    ("LOC_BOOST_TRIGGER_WRITING",                                                           "Build a Monument."),
    ("LOC_BOOST_TRIGGER_LONGDESC_WRITING",                                                  "Events can no longer be expressed in simple symbols; we need more accurate expressions."),
    ("LOC_BOOST_TRIGGER_GAMES_RECREATION",                                                  "Build 2 Camps."),
    ("LOC_BOOST_TRIGGER_LONGDESC_GAMES_RECREATION",                                         "How is hunting prey not another game?"),
    ("LOC_BOOST_TRIGGER_NAVAL_TRADITION",                                                   "Own 1 Quadrireme."),
    ("LOC_BOOST_TRIGGER_LONGDESC_NAVAL_TRADITION",                                          "The advent of new types of ships inspires your people to strive to make the country a maritime power."),
    ("LOC_BOOST_TRIGGER_MEDIEVAL_FAIRES",                                                   "Maintain 3 Trade Routes."),
    ("LOC_BOOST_TRIGGER_RECORDED_HISTORY",                                                  "Build 1 Library."),
    ("LOC_BOOST_TRIGGER_HUMANISM",                                                          "Build 2 Amphitheaters."),
    ("LOC_BOOST_TRIGGER_LONGDESC_HUMANISM",                                                 "Frequent theatrical performances led to a new wave of thinking among the people."),
    -- ("LOC_BOOST_TRIGGER_MILITARY_TACTICS",                                                  "Have the Defensive Tactics civic."),
    ("LOC_BOOST_TRIGGER_REPLACEABLE_PARTS",                                                 "Own 3 Line Infantries."),
    ("LOC_BOOST_TRIGGER_SIEGE_TACTICS",                                                     "Own 2 Trebuchets."),
    ("LOC_BOOST_TRIGGER_LONGDESC_SIEGE_TACTICS",                                            "After creating Trebuchets you realize that castles are not impregnable – you need a stauncher defense!."),
    ("LOC_BOOST_TRIGGER_COMBUSTION_LEU_MO",                                                 "Build 2 Stations."),
    ("LOC_BOOST_TRIGGER_LONGDESC_COMBUSTION_LEU_MO",                                        "The steam trains shuttles between busy train stations, can we make them go even faster?"),
    ("LOC_BOOST_TRIGGER_ELECTRICITY_HD",                                                    "Build a Dam."),
    ("LOC_BOOST_TRIGGER_LONGDESC_ELECTRICITY_HD",                                           "The fall of water contains a huge potential energy, how can we effectively use it?"),
    ("LOC_BOOST_TRIGGER_FEUDALISM",                                                         "Bulid 5 Farms."),

    -- 
    ("LOC_BOOST_TRIGGER_METAL_CASTING",                                                     "Have the Military Training Civic."),
    ("LOC_BOOST_TRIGGER_LONGDESC_METAL_CASTING",                                            "Weapons evolve along with Military training, more advanced ways of making weapons are emerging."),
    ("LOC_BOOST_TRIGGER_CASTLES",                                                           "Have the Supply Civic."),
    ("LOC_BOOST_TRIGGER_LONGDESC_CASTLES",                                                  "We need impressive defenses to better utilize the defensive tactics to protect our cities."),
    ("LOC_BOOST_TRIGGER_MILITARY_TACTICS",                                                  "Earn a Great General."),
    ("LOC_BOOST_TRIGGER_LONGDESC_MILITARY_TACTICS",                                         "The Great General brings about new military tactics."),
    ("LOC_BOOST_TRIGGER_EDUCATION",                                                         "Have the Imperial Examination System Civic."),
    ("LOC_BOOST_TRIGGER_LONGDESC_EDUCATION",                                                "In view of the need for imperial examinations, the education industry flourishes everywhere."),
    ("LOC_BOOST_TRIGGER_MILITARY_ENGINEERING",                                              "Own 2 Catapults."),
    ("LOC_BOOST_TRIGGER_LONGDESC_MILITARY_ENGINEERING",                                     "The need to make and assemble catapults has spawned a career as a military engineer."),
    ("LOC_BOOST_TRIGGER_DIVINE_RIGHT",                                                      "Own 1 Apostle."),
    ("LOC_BOOST_TRIGGER_LONGDESC_DIVINE_RIGHT",                                             "The apostle extolled your virtues, and the whole nation thought us blessed by the God."),
--    ("LOC_BOOST_TRIGGER_REFORMED_CHURCH",                                                   "Build 2 Temples"),
    ("LOC_BOOST_TRIGGER_LONGDESC_REFORMED_CHURCH",                                          "How the church should waste so much money for religious activities! It is time to reform the corrupt church."),
    ("LOC_BOOST_TRIGGER_DEFENSIVE_TACTICS",                                                 "Have the Wheel Technology."),
    ("LOC_BOOST_TRIGGER_LONGDESC_DEFENSIVE_TACTICS",                                        "Wheeled vehicles have become a kind of powerful tool of imperial logistics."),
    ("LOC_BOOST_TRIGGER_FLIGHT",                                                            "Own 2 Observation Balloons."),
    ("LOC_BOOST_TRIGGER_LONGDESC_FLIGHT",                                                   "Our observation balloons have been destroyed by hostile biplanes. So why can't we find a way to take the high ground?"),
    ("LOC_BOOST_TRIGGER_RADIO",                                                             "Have the Colonialism Civic."),
    ("LOC_BOOST_TRIGGER_LONGDESC_RADIO",                                                    "The colonies have been built around the world, and our governors want to develop a new long-distance communication technology."),
    ("LOC_BOOST_TRIGGER_GUIDANCE_SYSTEMS",                                                  "Own 2 Fighters."),
    ("LOC_BOOST_TRIGGER_LONGDESC_GUIDANCE_SYSTEMS",                                         "Our fighters now need a targeting system like a scalpel and engineers are already working on it."),
    ("LOC_BOOST_TRIGGER_COMPUTERS",                                                         "Build an Aluminum Mine."),
    ("LOC_BOOST_TRIGGER_LONGDESC_COMPUTERS",                                                "The superior corrosion resistance of aluminum makes it an ideal choice for precision equipment."),
    ("LOC_BOOST_TRIGGER_NANOTECHNOLOGY",                                                    "Build an Aluminum Mine and own a helicopter."),
    ("LOC_BOOST_TRIGGER_LONGDESC_NANOTECHNOLOGY",                                           "With the new alloy in action, your scientists are developing new material technologies.  "),
    ("LOC_BOOST_TRIGGER_INDUSTRIALIZATION_XP2",                                             "Build 4 Industrial Zones."),
    ("LOC_BOOST_TRIGGER_LONGDESC_INDUSTRIALIZATION",                                        "The bustling centers of industrial activity hint at the coming of great times. Is this a sign that the industrial revolution is just around the corner?"),
    ("LOC_BOOST_TRIGGER_DIPLOMATIC_SERVICE",                                                "Have a level 2 Alliance."),
    ("LOC_BOOST_TRIGGER_LONGDESC_DIPLOMATIC_SERVICE",                                       "A strong diplomatic alliance has nurtured an elite team of diplomats."),
    ("LOC_BOOST_TRIGGER_SQUARE_RIGGING",                                                    "Build a Niter Mine and own a Caravel."),
    ("LOC_BOOST_TRIGGER_LONGDESC_SQUARE_RIGGING",                                           "Gunpowder weapons proved so powerful that our navy was eager to use them."),
    ("LOC_BOOST_TRIGGER_RIFLING",                                                           "Own 2 Bombards."),
    ("LOC_BOOST_TRIGGER_LONGDESC_RIFLING",                                                  "Our old long-standing mortars were no longer adequate for combat needs in terms of accuracy, and we needed to spin out the shells."),
	("LOC_BOOST_TRIGGER_MOON_LANDING",														"Launch Moon Landing."),
	("LOC_BOOST_TRIGGER_LONGDESC_MOON_LANDING",												"Launch Moon Landing.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN

insert or replace into LocalizedText
    (Language,      Tag,                                                                    Text)
values
    -- New Techs
    ("zh_Hans_CN",  "LOC_TECH_CALENDAR_HD_NAME",                                            "历法"),
    ("zh_Hans_CN",  "LOC_TECH_PAPER_MAKING_HD_NAME",                                        "造纸术"),
    ("zh_Hans_CN",  "LOC_TECH_COMPASS_HD_NAME",                                             "罗盘"),
    ("zh_Hans_CN",  "LOC_TECH_PHYSICS_HD_NAME",                                             "物理"),
    ("zh_Hans_CN",  "LOC_TECH_BIOLOGY_HD_NAME",                                             "生物"),
    ("zh_Hans_CN",  "LOC_TECH_CIVIL_ENGINEERING_HD_NAME",                                   "土木工程"),
    -- New Techs Boosts
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_CALENDAR_HD",                                        "建造1座粮仓。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_CALENDAR_HD",                               "随着文明农业的发展，我们需要去安排一下这些年的生产计划了。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_PAPER_MAKING_HD",                                    "建造1座种植园。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_PAPER_MAKING_HD",                           "从种植园中植物的茎干里，我们发现了一些可以用的纤维。"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_COMPASS_HD",                                         "拥有海军传统市政。"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_COMPASS_HD",                                "随着航海技术的发展，拥有磁性的工具成为了领航员的必需品。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_COMPASS_HD",                                         "拥有数学科技。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_COMPASS_HD",                                "随着数学的发展，我们学会了使用拥有磁性的工具为船只进行导航。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_PHYSICS_HD",                                         "获得1位大科学家。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_PHYSICS_HD",                                "科学家的伟大理论让我们形成了对这个世界基本认知。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_BIOLOGY_HD",                                         "建造1座动物园。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_BIOLOGY_HD",                                "在搜集了世界各地的动物以后，城市中的动物园越来越热闹，我们是时候为这些生物分门别类了。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_CIVIL_ENGINEERING_HD",                               "建造2座工作坊"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_CIVIL_ENGINEERING_HD",                      "工坊的工匠为我们总结了土木工程的基本原理。"),
    -- Techs
    ("zh_Hans_CN",  "LOC_TECH_MINING_HD_DESCRIPTION",                                       "允许砍伐树林、雨林和收获由矿山改良的资源。"),
    ("zh_Hans_CN",  "LOC_TECH_ANIMAL_HUSBANDRY_HD_DESCRIPTION",                             "允许收获由牧场或营地改良的资源。"),
    ("zh_Hans_CN",  "LOC_TECH_POTTERY_DESCRIPTION",                                         "允许收获由农场改良的资源。"),
    ("zh_Hans_CN",  "LOC_TECH_SAILING_HD_DESCRIPTION",                                      "允许收获由渔船改良的资源。允许建造者和商人上船。"),
    ("zh_Hans_CN",  "LOC_TECH_IRRIGATION_DESCRIPTION",                                      "相邻淡水或水渠的种植园+2 [ICON_GOLD] 金币。[NEWLINE]允许清理沼泽和收获由种植园改良的资源。允许在相邻淡水或水渠的平原和草原丘陵上修建农场。"),
    ("zh_Hans_CN",  "LOC_TECH_ARCHERY_HD_DESCRIPTION",                                      "允许在树林上建造营地。"), -- 营地+1 [ICON_gold] 金币。
    ("zh_Hans_CN",  "LOC_TECH_CALENDAR_HD_DESCRIPTION",                                     "农场+1 [ICON_Food] 食物。[NEWLINE]纪念碑额外 +1 [ICON_CULTURE] 文化值。[NEWLINE]拥有粮仓的城市，每 [ICON_Citizen] 市民消耗的 [ICON_Food] 食物减少0.5。"),
	("zh_Hans_CN",  "LOC_TECH_COMPASS_HD_DESCRIPTION",										"渔船+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_TECH_THE_WHEEL_HD_DESCRIPTION",                                    "所有境内改良设施自动获得道路。"), -- 牧场+1 [ICON_GOLD] 金币。
    ("zh_Hans_CN",  "LOC_TECH_BRONZE_WORKING_DESCRIPTION",                                  "显示 [ICON_RESOURCE_IRON] 铁资源。允许收获由伐木场改良的资源。"),
    ("zh_Hans_CN",  "LOC_TECH_MASONRY_HD_DESCRIPTION",                                      "允许收获由采石场改良的资源。"),    
    ("zh_Hans_CN",  "LOC_TECH_CELESTIAL_NAVIGATION_HD_DESCRIPTION",                         "允许所有陆地单位上船。"),
    ("zh_Hans_CN",  "LOC_TECH_PAPER_MAKING_HD_DESCRIPTION",                                 "种植园+1 [ICON_FOOD] 食物。[NEWLINE]拥有图书馆的城市中每位 [ICON_Citizen] 公民 +0.3 [ICON_SCIENCE] 科技值产出。"),
    -- ("zh_Hans_CN",  "LOC_TECH_CURRENCY_HD_DESCRIPTION",                                     "商业中心+3 [ICON_Gold] 金币产出。"),
    ("zh_Hans_CN",  "LOC_TECH_HORSEBACK_RIDING_HD_DESCRIPTION",                             "牧场+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TECH_SHIPBUILDING_HD_DESCRIPTION",                                 "允许所有陆地单位上船。[NEWLINE]侦察单位获得能力：免除单位上下船和跨河时的 [ICON_Movement] 移动力及 [ICON_Strength] 战斗力惩罚。"),
    ("zh_Hans_CN",  "LOC_TECH_ENGINEERING_HD_DESCRIPTION",                                  "矿山和采石场+1 [ICON_Production] 生产力，并且可以建造在地热裂缝上。"),
    ("zh_Hans_CN",  "LOC_TECH_CONSTRUCTION_HD_DESCRIPTION",                                 "营地和伐木场+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_TECH_APPRENTICESHIP_HD_DESCRIPTION",                               "矿山+1 [ICON_Production] 生产力。"), 
    ("zh_Hans_CN",  "LOC_TECH_MACHINERY_HD_DESCRIPTION",                                    "收获和移除地貌的产出+50%。伐木场+1 [ICON_Production] 生产力。"),
    -- ("zh_Hans_CN",  "LOC_TECH_MACHINERY_HD_ALT_DESCRIPTION",                                "收获和移除地貌的产出+50%。非沿河的伐木场改良+1 [ICON_Production] 生产力。"),
    -- ("zh_Hans_CN",  "LOC_TECH_MILITARY_ENGINEERING_HD_DESCRIPTION",                         "所有改良的战略资源每回合额外产出3点资源。"),
    -- ("zh_Hans_CN",  "LOC_TECH_CASTLES_HD_DESCRIPTION",                                      "如果使用凯瑟琳·德·美第奇（黑王后），能免费获得1名间谍。"),
    -- ("zh_Hans_CN",  "LOC_TECH_STIRRUPS_HD_DESCRIPTION",                                     "牧场+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_TECH_MASS_PRODUCTION_HD_DESCRIPTION",                              "牧场+1 [ICON_Food] 食物。"),
    -- ("zh_Hans_CN",  "LOC_TECH_ASTRONOMY_HD_DESCRIPTION",                                    "相邻山脉的学院+3 [ICON_Science] 科技值。"),
    -- ("zh_Hans_CN",  "LOC_TECH_MILITARY_TACTICS_HD_DESCRIPTION",                             "近战单位获得能力：与至少一个友方近战单位相邻时+3 [ICON_Strength] 战斗力。[NEWLINE]远程单位获得能力：从丘陵上发动攻击时+5 [ICON_Strength] 战斗力。[NEWLINE]轻骑兵单位获得能力：与单位作战时+5[ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TECH_MILITARY_TACTICS_HD_DESCRIPTION",                             "近战单位获得能力：与至少一个友方近战单位相邻时+3 [ICON_Strength] 战斗力。[NEWLINE]远程单位获得能力：从丘陵上发动攻击时+5 [ICON_Strength] 战斗力。[NEWLINE]轻骑兵单位获得能力：与单位作战时+5[ICON_Strength] 战斗力。[NEWLINE]抗骑兵单位获得能力：不再受到来自单位受伤程度的 [ICON_Strength] 战斗力减益。"),
    ("zh_Hans_CN",  "LOC_TECH_GUNPOWDER_HD_DESCRIPTION",                                    "采石场+1 [ICON_Production] 生产力。[NEWLINE]重骑兵单位获得能力：击杀敌方单位后+10 [ICON_Damaged] 生命值。"),
    ("zh_Hans_CN",  "LOC_TECH_SQUARE_RIGGING_HD_DESCRIPTION",                               "水运单位+1 [ICON_Movement] 移动力。[NEWLINE]海军近战单位获得能力：所有编队单位将继承护卫队的 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_TECH_SCIENTIFIC_THEORY_HD_DESCRIPTION",                            "渔场+1 [ICON_housing] 住房。"),
    ("zh_Hans_CN",  "LOC_TECH_CIVIL_ENGINEERING_HD_DESCRIPTION",                            "可以在草原丘陵和平原丘陵上建造农场。伐木场+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TECH_STEAM_POWER_HD_DESCRIPTION",                                  "渔船+2 [ICON_GOLD] 金币。[NEWLINE]水运单位+2 [ICON_Movement] 移动力。商人单位在水域单元格的贸易范围增加15个单元格。"),
	("zh_Hans_CN",  "LOC_TECH_CARTOGRAPHY_HD_DESCRIPTION",									"渔场+1 [ICON_FOOD] 食物。[NEWLINE]所有海军和水运单位可在深海单元格上航行。"),
    -- ("zh_Hans_CN",  "LOC_TECH_SANITATION_HD_DESCRIPTION",                                   "梯井+1 [ICON_Housing] 住房。"), -- [NEWLINE]抗骑兵单位获得能力：不再受到来自单位受伤程度的 [ICON_Strength] 战斗力减益。
    ("zh_Hans_CN",  "LOC_TECH_RIFLING_HD_DESCRIPTION",                                      "攻城单位获得能力：攻击区域防御+5 [ICON_Strength] 战斗力。"),
    -- ("zh_Hans_CN",  "LOC_TECH_RIFLING_HD_DESCRIPTION",                                      "营地+1 [ICON_FOOD] 食物。"),
    ("zh_Hans_CN",  "LOC_TECH_FLIGHT_DESCRIPTION",                                          "为部分提供 [ICON_SCIENCE] 科技值， [ICON_Culture] 文化值， [ICON_Faith] 信仰值或 [ICON_Production] 生产力的改良设施提供等于其产出的 [ICON_Tourism] 旅游业绩加成。"),
    ("zh_Hans_CN",  "LOC_TECH_STEEL_HD_DESCRIPTION",                                        "解锁城市防御，为所有城市提供400点自动防御力和发起远程攻击的能力。之前的城墙将全部过时，攻城单位进攻时不再拥有特殊效果。"),
    ("zh_Hans_CN",  "LOC_TECH_BIOLOGY_HD_DESCRIPTION",                                      "每与1个农场相邻，农场+1 [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "LOC_TECH_COMPUTERS_DESCRIPTION",                                       "可以额外招募1个间谍。在帝国全境内+20% [ICON_Tourism] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_TECH_TELECOMMUNICATIONS_HD_DESCRIPTION",                           "所有除 [ICON_GREATWORK_RELIC] 遗物外的巨作+50% [ICON_TOURISM] 旅游业绩。"),
    
    ("zh_Hans_CN",  "LOC_TECH_SYNTHETIC_MATERIALS_HD_DESCRIPTION",                          "营地+2 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_TECH_ROBOTICS_HD_DESCRIPTION",                                     "牧场+1 [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "LOC_TECH_CYBERNETICS_HD_DESCRIPTION",                                  "伐木场+1 [ICON_Production] 生产力。[NEWLINE]{LOC_TECH_CYBERNETICS_DESCRIPTION}"),
    ("zh_Hans_CN",  "LOC_TECH_SMART_MATERIALS_HD_DESCRIPTION",                              "矿山+1 [ICON_Production] 生产力。[NEWLINE]{LOC_TECH_SMART_MATERIALS_DESCRIPTION}"),
	("zh_Hans_CN",	"LOC_TECH_PLASTICS_HD_DESCRIPTION",										"渔场+2 [ICON_GOLD] 金币。[NEWLINE]{LOC_TECH_PLASTICS_DESCRIPTION}"),
    -- New Civics
    ("zh_Hans_CN",  "LOC_CIVIC_LITERARY_TRADITION_HD_NAME",                                 "文学传统"),
    ("zh_Hans_CN",  "LOC_CIVIC_DEFENSIVE_TACTICS_HD_NAME",                                  "后勤补给"),
    ("zh_Hans_CN",  "LOC_CIVIC_NATURAL_HISTORY_HD_NAME",                                    "考古学"),
    ("zh_Hans_CN",  "LOC_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_NAME",                        "科举制"),
    ("zh_Hans_CN",  "LOC_CIVIC_EVOLUTION_THEORY_HD_NAME",                                   "演化论"),
    ("zh_Hans_CN",  "LOC_CIVIC_HISTORICAL_PHILOSOPHY_HD_NAME",                              "历史哲学"),
    ("zh_Hans_CN",  "LOC_CIVIC_ETHICS_HD_NAME",                                             "伦理学"),
    ("zh_Hans_CN",  "LOC_CIVIC_SOCIAL_SCIENCE_HD_NAME",                                     "社会科学"),
    -- New Civics Boosts
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LITERARY_TRADITION_HD",                              "拥有造纸术科技。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_LITERARY_TRADITION_HD",                     "写在纸上的文字成为了我们文化的根基。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_IMPERIAL_EXAMINATION_SYSTEM_HD",                     "建造2个学院。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_IMPERIAL_EXAMINATION_SYSTEM_HD",            "随着文化人越来越多，我们应该想个办法利用他们的才能了。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_EVOLUTION_THEORY_HD",                                "在异大陆建造1座学院。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_EVOLUTION_THEORY_HD",                       "您派遣的学者们从世界各地搜集了多种生物资源，这些琳琅满目的来自新大陆的事物，不仅激励了生物学，也引发了社会思考。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_HISTORICAL_PHILOSOPHY_HD",                           "建造3个剧院。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_HISTORICAL_PHILOSOPHY_HD",                  "一代代政治家和思想家激扬文字，为我们留下了宝贵的历史遗产。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_ETHICS_HD",                                          "拥有印刷术科技。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_ETHICS_HD",                                 "当圣经一本本被印刷出来的时候，真理传遍了大地。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_SOCIAL_SCIENCE_HD",                                  "建造7个不同的专业化区域。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_SOCIAL_SCIENCE_HD",                         "复杂的城市建设构成了复杂的社会关系，而一些天才洞察了这一切。"),
    -- Civics
    ("zh_Hans_CN",  "LOC_DIPLOACTION_ALLIANCE_DESCRIPTION",                                 "宣布友谊后即可缔结同盟。盟友之间无法开战、自动开放边界、自动签署防御协定。如其中一位盟友的城市被占领，则所有盟友都将获得对入侵文明的战争借口。解锁行政部门后，科技、文化、商业同盟间商路获得对应加成。"),
    ("zh_Hans_CN",  "LOC_CIVIC_DEFENSIVE_TACTICS_HD_DESCRIPTION",                           "远程单位获得能力：占领一个区域或一个提供 [ICON_Strength] 防御力的改良设施时+5 [ICON_Strength] 战斗力。[NEWLINE]抗骑兵单位获得能力：在丘陵上防御近距离攻击时+7 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_CIVIC_MILITARY_TRAINING_HD_DESCRIPTION",                           "重骑兵单位获得能力：攻击受伤单位时+5 [ICON_Strength] 战斗力。 [NEWLINE]攻城单位获得能力：可移动后攻击。"), -- 在没有雨林、树林、沼泽地貌的平坦地形作战时+5 [ICON_Strength] 战斗力。
    ("zh_Hans_CN",  "LOC_CIVIC_MEDIEVAL_FAIRES_HD_DESCRIPTION",                             "营地+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_CIVIC_FEUDALISM_HD_DESCRIPTION",                                   "农场每与2个农场相邻+1 [ICON_Food] 食物。[NEWLINE]不相邻淡水或水渠的种植园+2 [ICON_Gold] 金币。[NEWLINE]牧场+1 [ICON_PRODUCTION] 生产力。[NEWLINE]拥有大学的学院从雨林获得额外标准相邻加成。[NEWLINE]近战单位获得能力：在森林或雨林中战斗时+3 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_CIVIC_GUILDS_HD_DESCRIPTION",                                      "允许在雨林上建造伐木场和营地。[NEWLINE]允许建造者植树造林（人造林）。[NEWLINE]您领土上从未被移除的树林（非人造林）获得+1魅力。"),
    ("zh_Hans_CN",  "LOC_CIVIC_MERCENARIES_HD_DESCRIPTION",                                 "轻骑兵单位获得能力：在敌方领土内开始回合时+1 [ICON_Movement] 移动力。"),
    -- ("zh_Hans_CN",  "LOC_CIVIC_MERCENARIES_HD_DESCRIPTION",                                 "轻骑兵单位获得能力：劫掠区域和改良后额外获得25 [ICON_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_CIVIC_CIVIL_SERVICE_HD_DESCRIPTION",                               "拥有至少2项升级的 [ICON_GOVERNOR] 总督就职后将提供+1 [ICON_Amenities] 宜居度、+3 [ICON_Housing] 住房。"),
    ("zh_Hans_CN",  "LOC_CIVIC_MERCANTILISM_HD_DESCRIPTION",                                "侦查单位获得能力：忽略控制区。[NEWLINE]种植园+2 [ICON_GOLD] 金币。"),
	("zh_Hans_CN",  "LOC_CIVIC_NAVAL_TRADITION_HD_DESCRIPTION",								"渔场+2 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_CIVIC_EVOLUTION_THEORY_HD_DESCRIPTION",                            "营地+1 [ICON_Food] 食物。"), -- +1 [ICON_Production] 生产力和
    ("zh_Hans_CN",  "LOC_CIVIC_COLONIALISM_HD_DESCRIPTION",                                 "渔场+1 [ICON_PRODUCTION] 生产力。[NEWLINE]从每个宗主城邦获得+1 [ICON_Favor] 外交支持。[NEWLINE]允许两个完全相同的单位组成一个舰队。[NEWLINE]现在可用一个新的战争借口替战争辩护：殖民战争。"),
    ("zh_Hans_CN",  "LOC_CIVIC_NATIONALISM_HD_DESCRIPTION",                                 "可额外招募一名间谍。[NEWLINE]允许两个完全相同的单位组成一个兵团。"),
    ("zh_Hans_CN",  "LOC_CIVIC_SCORCHED_EARTH_HD_DESCRIPTION",                              "海军袭击者单位获得能力：进行海岸扫荡不消耗 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_CIVIC_CONSERVATION_HD_DESCRIPTION",                                "奖励3位 [ICON_Envoy] 使者。允许使用 [ICON_Faith] 信仰值建造国家公园和购买自然学家。市中心相邻森林的城市+1 [ICON_Amenities] 宜居度。从城墙获得 [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_CIVIC_NUCLEAR_PROGRAM_DESCRIPTION",                                "核计划项目、核装置和核电站的生产力+50%。"),
    ("zh_Hans_CN",  "LOC_CIVIC_ENVIRONMENTALISM_HD_DESCRIPTION",                            "全境内+20% [ICON_Tourism] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_CIVIC_GLOBALIZATION_HD_DESCRIPTION",                               "种植园+2 [ICON_gold] 金币。"),
    ("zh_Hans_CN",  "LOC_CIVIC_CRAFTSMANSHIP_HD_DESCRIPTION",                               "侦察单位获得能力：{LOC_ABILITY_SCOUNT_IGNORE_ALL_HD_DESCRIPTION}"),
    ("zh_Hans_CN",  "LOC_CIVIC_COLD_WAR_DESCRIPTION",                               		"如果城邦的宗主国和您的政体不同，您向城邦派遣的每个 [ICON_ENVOY] 使者都被视为两个使者。可额外招募一名间谍。"),
    -- Boosts
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_FEUDALISM",                                          "建造5个农场。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_MASS_PRODUCTION",                                    "建造2座伐木场。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_BRONZE_WORKING",                                     "击杀2个蛮族单位。"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_BRONZE_WORKING",     ""), -- 和蛮族的战争让你渴望更强大的武器。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_THE_WHEEL",                                          "建造1座牧场。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_THE_WHEEL",                                 "被驯养的动物们真是人类的好助手，但如何更有效率地利用他们呢？"), -- 采矿业让您拥有了建造轮轴的能力。接下来是车轮？
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_HORSEBACK_RIDING",                                   "建造1座改良马的牧场。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_HORSEBACK_RIDING",                          "马匹现在被驯养在牧场里，是时候学习骑乘它们了。"), -- 动物现在被驯养在牧场里，是时候学习骑乘它们了。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_FOREIGN_TRADE",                                      "遇见另一个文明。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_FOREIGN_TRADE",                             "在与另一个文明国家会晤后，您发现这个广阔的世界有很多的贸易机会。"), -- 我们发现了一个新大陆，这个广阔的世界有很多的贸易机会。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_WRITING",                                            "建造一个纪念碑。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_WRITING",                                   "事件已无法用简单的符号表达，我们需要更准确的表达方式。"), -- 在与另一个文明国家会晤后，您意识到了新的交流方式的必要性。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_GAMES_RECREATION",                                   "建造2座营地。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_GAMES_RECREATION",                          "追捕猎物又何尝不是另一种游戏？"), -- 毫无疑问，您在建筑上的新技术对创建游戏和娱乐场所大有裨益。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_NAVAL_TRADITION",                                    "拥有1艘四段帆船。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_NAVAL_TRADITION",                           "新式船只的出现激励您的人民努力让国家成为海上强国。"), -- 您在海上取得的胜利激励您的人民努力让国家成为海上强国。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_MEDIEVAL_FAIRES",                                    "经营3条贸易线。"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_MEDIEVAL_FAIRES",    ""), -- 您领土上的贸易正在蓬勃发展，这将很快促使商品交易会的产生。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_RECORDED_HISTORY",                                   "建造1个图书馆"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_RECORDED_HISTORY",   ""), -- 您的国民打算把更多卷轴放在您的学院图书馆里，他们开始记录文明的历史了。
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_HUMANISM",                                           "建造2个古罗马剧场。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_HUMANISM",                                  "频繁戏剧的演出引领了人民的新思潮。"), -- 您新获得的大艺术家带来的启示使我们的人民意识到了个体的力量。
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_MILITARY_TACTICS",            "拥有防御战术市政。"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_MILITARY_TACTICS",   "初步的防御战术是不足以抵御强大的敌人的，我们需要更丰富的战术"), -- 您的枪兵很厉害，但如今您的对手实力变强了，行动也更快了。您或许需要一个更长的武器？
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_REPLACEABLE_PARTS",                                  "拥有3个线列步兵。"),
    -- ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_REPLACEABLE_PARTS",  ""), -- 您的武器制造商已厌倦了手工制作数量如此庞大的步枪。或许建立标准化对此有帮助？
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_SIEGE_TACTICS",                                      "拥有2个配重投石机。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_SIEGE_TACTICS",                             "在配重投石机出现后，您意识到城堡并非固若金汤——您需要更坚固的防御措施！"), -- 在射石炮出现后，您意识到城堡并非固若金汤——您需要更坚固的防御措施！
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_COMBUSTION_LEU_MO",                                  "建造2座火车站。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_COMBUSTION_LEU_MO",                         "蒸汽机车穿梭于忙碌的火车站之间，我们还能让他跑得更快吗？"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_ELECTRICITY_HD",                                     "建造1座堤坝。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_ELECTRICITY_HD",                            "水的落差蕴含着巨大的势能，如何才能有效地利用呢？"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_METAL_CASTING",                                      "拥有军事训练市政。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_METAL_CASTING",                             "军事训练推进着武器不断的革新，新式的武器铸造方式也孕育而生。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_CASTLES",                                            "拥有后勤补给市政。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_CASTLES",                                   "我们需要更牢靠的防御来更好地发挥防御战术保护我们的城市。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_MILITARY_TACTICS",                                   "获得1位大将军。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_MILITARY_TACTICS",                          "大将军带来了全新的军事战术的思考。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_EDUCATION",                                          "拥有科举制市政。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_EDUCATION",                                 "出于科举考试的需要，各地的教育行业都蓬勃发展起来。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_MILITARY_ENGINEERING",                               "拥有2个石弩。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_MILITARY_ENGINEERING",                      "石弩的制作和组装需求催生了军事工程师这一职业。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_DIVINE_RIGHT",                                       "拥有1个使徒。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_DIVINE_RIGHT",                              "这位使徒极力颂扬您的德行，全国上下都认为我们受到了神的保佑。"),
--    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_REFORMED_CHURCH",                                    "建造2座寺庙。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_REFORMED_CHURCH",                           "教会为了宗教活动竟如此劳民伤财！是时候改革腐败的教会了。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_DEFENSIVE_TACTICS",                                  "拥有轮子科技。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_DEFENSIVE_TACTICS",                         "有轮子的载具成为了军队后勤工作的有力工具。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_FLIGHT",                                             "拥有2个观测气球。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_FLIGHT",                                    "我们的观测气球在敌方双翼机的枪林弹雨之下毁坏殆尽，我们为什么就不能想办法占据战场制高点呢？"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_RADIO",                                              "拥有殖民主义市政。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_RADIO",                                     "世界各地都在兴建殖民地，因此总督们希望能够开发一种新的长距离通讯技术。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_GUIDANCE_SYSTEMS",                                   "拥有2个战斗机。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_GUIDANCE_SYSTEMS",                          "我们的战斗机现在需要手术刀一样的瞄准系统，工程师已经开始了工作。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_COMPUTERS",                                          "建造一座铝矿。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_COMPUTERS",                                 "铝材料优越的抗腐蚀性质为精密设备的材料提供了理想选择。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_NANOTECHNOLOGY",                                     "建造一座铝矿，拥有一个直升飞机。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_NANOTECHNOLOGY",                            "新型合金投入实战后，您的科学家们开始研发新的材料技术。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_INDUSTRIALIZATION_XP2",                              "建造4座工业区。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_INDUSTRIALIZATION",                         "繁忙的工业活动中心暗示着伟大时代的到来。这预示着工业革命就近在眼前吗？"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_DIPLOMATIC_SERVICE",                                 "拥有第2级同盟。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_DIPLOMATIC_SERVICE",                        "牢固的外交联盟为您培养了一支精英外交官团队。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_SQUARE_RIGGING",                                     "建造一座硝石矿，拥有一个轻快帆船。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_SQUARE_RIGGING",                            "火药武器展现出了非凡威力，我们的海军迫不及待的想要运用它们。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_RIFLING",                                            "拥有2个射石炮。"),
    ("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_RIFLING",                                   "我们老久的臼炮在精度方面已经无法满足战斗需求，我们需要旋转出膛的炮弹。"),
	("zh_Hans_CN",  "LOC_BOOST_TRIGGER_MOON_LANDING",										"启动登月计划。"),
	("zh_Hans_CN",  "LOC_BOOST_TRIGGER_LONGDESC_MOON_LANDING",								"启动登月计划。");

--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                   Text)
values
    -- TODO: LOC_TECH_CALENDAR_HD_QUOTE_2 change to English
    ("LOC_TECH_CALENDAR_HD_QUOTE_1",                                        "There was nothing brought together, nothing which could make a noise, nor anything which might move, or tremble, or could make noise in the sky. -- Popul Vuh"),
    ("LOC_TECH_CALENDAR_HD_QUOTE_2",                                        "太初元年，岁名“焉逢摄提格”，月名“毕聚”，日得甲子，夜半朔旦冬至。——司马迁《史记》"),
    ("LOC_TECH_PAPER_MAKING_HD_QUOTE_1",                                    "The beauty of the paper is precious, the integrity of the formula, the purity of the body and the chastity of the nature. -- Fu Xian, Paper Fugue "),
    ("LOC_TECH_PAPER_MAKING_HD_QUOTE_2",                                    "The experienced man reads with two eyes, one seeing the words on the page and the other seeing the back of the paper. -- Goethe"),
    ("LOC_TECH_COMPASS_HD_QUOTE_1",                                         "A navigator knows geography; at night he watches the stars, at day he watches the sun, and at cloudy days he watches the compass. -- Pingzhou Ketan"),
    ("LOC_TECH_COMPASS_HD_QUOTE_2",                                         "Foreigners use compasses for navigation, but China uses them for feng shui. -- Lu Xun"),
    ("LOC_TECH_PHYSICS_HD_QUOTE_1",                                         "The most incomprehensible thing about the world is that it is comprehensible.-- Albert Einstein"),
    ("LOC_TECH_PHYSICS_HD_QUOTE_2",                                         "Give me a fulcrum and I can lift the whole earth. -- Archimedes"),
    ("LOC_TECH_BIOLOGY_HD_QUOTE_1",                                         "All life comes from life. -- Louis Pasteur"),
    ("LOC_TECH_BIOLOGY_HD_QUOTE_2",                                         "Nüwa has a body, who makes it? -- Qu Yuan, Heavenly Questions"),
    ("LOC_CIVIC_SUPPLY_HD_QUOTE_1",                                         "A horse! A horse! My kingdom for a horse! -- Shakespeare, Richard III"),
    ("LOC_CIVIC_SUPPLY_HD_QUOTE_2",                                         "As the old saying goes, before the armies move, food and fodder go first, and when the army is well fed, the battle is invincible. -- The Storys of the Qin King of the Great Tang Dynasty"),
    ("LOC_CIVIC_ARCHAEOLOGY_HD_QUOTE_1",                                    "This is the reason for this study, which is intended to be used by the doctors and counsellors, and to make the world aware of the usefulness of the relics of Yin to scholars of history and scripture. --Wang Guowei, A Study of the First Kings and First Gentlemen as Found in the Divination of Yin"),
    ("LOC_CIVIC_ARCHAEOLOGY_HD_QUOTE_2",                                    "The French Empire has appropriated half its treasures, and now it has the impudence to go to such lengths as to bring out for public exhibition, as owner, these beautiful ancient relics from the Yuanmingyuan. --Victor Hugo"),
    ("LOC_CIVIC_LITERARY_TRADITION_HD_QUOTE_1",                             "The essay is a great and immortal event. --Cao Pi,  A Treatise on the Canon"),
    ("LOC_CIVIC_LITERARY_TRADITION_HD_QUOTE_2",                             "I think tendencies should flow naturally from the sections and episodes, and not be specifically pointed out. --Frederic Engels"),
    ("LOC_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_QUOTE_1",                    "The spring breeze is so fast that you can see all the flowers in Chang'an in one day. --Meng Jiao,  After the Examination"),
    ("LOC_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_QUOTE_2",                    "It is all but impossible to conceive of a better government than that in which only those who have passed a rigorous examination are admitted to the government offices. -- Voltaire"),
    ("LOC_CIVIC_EVOLUTION_THEORY_HD_QUOTE_1",                               "Ah, how magical! How many wonderful characters here; how beautiful are the human beings! O wondrous new world, to have such wonderful people! -- William Shakespeare, The Tempest"),
    ("LOC_CIVIC_EVOLUTION_THEORY_HD_QUOTE_2",                               "We don't want change. Every change endangers stability. --Aldous Huxley, Brave New World"),
    ("LOC_CIVIC_HISTORICAL_PHILOSOPHY_HD_QUOTE_1",                          "The book is called a factual record because it is good at ordering things, discriminating without being flashy, qualitative without being slang, straight in its text, and checkable in its matter, without false beauty or hidden evil. --- Ban Gu, The Book of Han"),
    ("LOC_CIVIC_HISTORICAL_PHILOSOPHY_HD_QUOTE_2",                          "The only lesson that history teaches is that one never learns anything in history. --Georg Hegel, The Philosophy of History"),
    ("LOC_CIVIC_ETHICS_HD_QUOTE_1",                                         "What gentleman was there when Adam and Eve laboured! --Florian Geyer"),
    ("LOC_CIVIC_ETHICS_HD_QUOTE_2",                                         "The kind of career that requires people to work non-stop and becomes an integral part of their lives. In fact, it is the only possible motivation. -- Max Weber, The Protestant Ethic and the Spirit of Capitalism"),
    ("LOC_CIVIC_SOCIAL_SCIENCE_HD_QUOTE_1",                                 "A science can only reach the point of true perfection when it applies mathematics successfully. -- Karl Marx"),
    ("LOC_CIVIC_SOCIAL_SCIENCE_HD_QUOTE_2",                                 "Only society can make a general assessment of the value of life, and the individual can do nothing about it ...... -- Émile Durkheim, On Suicide");

-- Quotes
--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                    Text)
values
    ("zh_Hans_CN",  "LOC_TECH_CALENDAR_HD_QUOTE_1",                                         "此处记述了如何：一切处于悬止，一切平静，处于静默；一切静止，寂静，而天穹的领域是空洞的。——《波波武经》"),
    ("zh_Hans_CN",  "LOC_TECH_CALENDAR_HD_QUOTE_2",                                         "太初元年，岁名“焉逢摄提格”，月名“毕聚”，日得甲子，夜半朔旦冬至。——司马迁《史记》"),
    ("zh_Hans_CN",  "LOC_TECH_PAPER_MAKING_HD_QUOTE_1",                                     "夫其为物，厥美可珍，廉方有则，体洁性贞。——傅咸《纸赋》"),
    ("zh_Hans_CN",  "LOC_TECH_PAPER_MAKING_HD_QUOTE_2",                                     "经验丰富的人读书用两只眼睛，一只眼睛看到纸面上的话，另一眼睛看到纸的背面。——约翰·沃尔夫冈·冯·歌德"),
    ("zh_Hans_CN",  "LOC_TECH_COMPASS_HD_QUOTE_1",                                          "舟师识地理，夜则观星，昼则观日，阴晦观指南针。——《萍洲可谈》"),
    ("zh_Hans_CN",  "LOC_TECH_COMPASS_HD_QUOTE_2",                                          "外国用罗盘针航海，中国却用它看风水。——鲁迅"),
    ("zh_Hans_CN",  "LOC_TECH_PHYSICS_HD_QUOTE_1",                                          "这个世界最不可理解的就是它竟然是可以理解的。——阿尔伯特·爱因斯坦"),
    ("zh_Hans_CN",  "LOC_TECH_PHYSICS_HD_QUOTE_2",                                          "给我一个支点，我可以翘起整个地球——阿基米德"),
    ("zh_Hans_CN",  "LOC_TECH_BIOLOGY_HD_QUOTE_1",                                          "所有生命都来自生命——路易斯·巴斯德"),
    ("zh_Hans_CN",  "LOC_TECH_BIOLOGY_HD_QUOTE_2",                                          "女娲有体，孰制匠之？——屈原《天问》"),
    ("zh_Hans_CN",  "LOC_CIVIC_SUPPLY_HD_QUOTE_1",                                          "一匹马！一匹马！我用王国换一匹马！——莎士比亚《理查三世》"),
    ("zh_Hans_CN",  "LOC_CIVIC_SUPPLY_HD_QUOTE_2",                                          "自古道三军未动，粮草先行，兵精粮足，战无不胜。——《大唐秦王词话》"),
    ("zh_Hans_CN",  "LOC_CIVIC_ARCHAEOLOGY_HD_QUOTE_1",                                     "由是有商一代，先公先王之名不见于卜辞者殆鲜。乃为此考，以质诸博士及参事,并使世人知殷虚遗物之有裨于经史二学者有如斯也。——王国维《殷卜辞中所见先公先王考》"),
    ("zh_Hans_CN",  "LOC_CIVIC_ARCHAEOLOGY_HD_QUOTE_2",                                     "法兰西帝国侵吞了一半宝物，现在，它居然无耻到这样的地步，还以所有者的身份把圆明园的这些美轮美奂的古代文物拿出来公开展览。——维克多·雨果"),
    ("zh_Hans_CN",  "LOC_CIVIC_LITERARY_TRADITION_HD_QUOTE_1",                              "盖文章经国之大业，不朽之盛事。——曹丕《典论》"),
    ("zh_Hans_CN",  "LOC_CIVIC_LITERARY_TRADITION_HD_QUOTE_2",                              "我认为倾向应当从断面和情节中自然而然地流露出来,而不应当特地把它指点出来。——弗雷德里克·恩格斯"),
    ("zh_Hans_CN",  "LOC_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_QUOTE_1",                     "春风得意马蹄疾，一日看尽长安花。——孟郊《登科后》"),
    ("zh_Hans_CN",  "LOC_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_QUOTE_2",                     "通过层层严格考试的人才能进入衙门任职，人们全然不可能设想一个比这更好的政府。——伏尔泰"),
    ("zh_Hans_CN",  "LOC_CIVIC_EVOLUTION_THEORY_HD_QUOTE_1",                                "啊，多么神奇！这里有多少美妙的人物；人类多么美丽！奇妙的新世界啊，竟有这样美好的人！——威廉·莎士比亚《暴风雨》"),
    ("zh_Hans_CN",  "LOC_CIVIC_EVOLUTION_THEORY_HD_QUOTE_2",                                "我们不要变化。每一个变化都会危及安定。 ——阿道司·赫胥黎《美丽新世界》"),
    ("zh_Hans_CN",  "LOC_CIVIC_HISTORICAL_PHILOSOPHY_HD_QUOTE_1",                           "服其善序事理，辨而不华，质而不俚，其文直，其事核，不虚美，不隐恶，故谓之实录。——班固《汉书》"),
    ("zh_Hans_CN",  "LOC_CIVIC_HISTORICAL_PHILOSOPHY_HD_QUOTE_2",                           "历史给人的唯一教训，就是人们从未在历史中吸取过任何教训。——格奥尔格·黑格尔《历史哲学》"),
    ("zh_Hans_CN",  "LOC_CIVIC_ETHICS_HD_QUOTE_1",                                          "亚当夏娃劳作之时，哪有什么绅士！——弗洛里安·盖耶"),
    ("zh_Hans_CN",  "LOC_CIVIC_ETHICS_HD_QUOTE_2",                                          "这种需要人们不停地工作的事业，成为他们生活中不可或缺的组成部分。事实上，这是唯一可能的动机。——马克斯·韦伯《新教伦理与资本主义精神》"),
    ("zh_Hans_CN",  "LOC_CIVIC_SOCIAL_SCIENCE_HD_QUOTE_1",                                  "一门科学，只有当它成功地运用数学时，才能达到真正完善的地步。——卡尔·马克思"),
    ("zh_Hans_CN",  "LOC_CIVIC_SOCIAL_SCIENCE_HD_QUOTE_2",                                  "只有社会才能对人生的价值做出总的评价，而个人对此是无能为力的……——埃米尔·涂尔干《自杀论》");

update LocalizedText set Text = replace(Text, '改良设施', '') where Tag = 'LOC_TECH_CARTOGRAPHY_DESCRIPTION' and Language = 'zh_Hans_CN';
update LocalizedText set Text = replace(Text, '改良设施', '') where Tag = 'LOC_TECH_INDUSTRIALIZATION_DESCRIPTION' and Language = 'zh_Hans_CN';
update LocalizedText set Text = replace(Text, '改良设施', '') where Tag = 'LOC_TECH_ROBOTICS_DESCRIPTION' and Language = 'zh_Hans_CN';
update LocalizedText set Text = replace(Text, '石油钻机改良设施提供的 [ICON_Production] 生产力+1', '海上石油钻机+1 [ICON_Production] 生产力') where Tag = 'LOC_TECH_PREDICTIVE_SYSTEMS_DESCRIPTION' and Language = 'zh_Hans_CN';
