--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                             Text)
values
    ("LOC_TRAIT_LEADER_KUBLAI_DESCRIPTION",                           "One extra Economic policy slot in any government. Upon conquering another Civilization's Original [ICON_Capital] Capital city, receive its Civilization Trait."),
    ("LOC_TRAIT_CIVILIZATION_WONDER_TOURISM_DESCRIPTION",             "+20% [ICON_Production] Production toward Medieval, Renaissance, and Industrial era wonders. [ICON_Tourism] Tourism from wonders of any era is +200%. Each time you complete a Wonder, gain [ICON_GREATWRITER] Great Writer, [ICON_GREATARTIST] Great Artist and [ICON_GREATMUSICIAN] Great Musician Points each equals to 20% of its production cost. Each time you active a Great Work in a city, complete 20% of the original Wonder cost towards the Wonder that is currently building."),
    ("LOC_TRAIT_LEADER_SURROUNDED_BY_GLORY_DESCRIPTION",              "+5% [ICON_Culture] Culture per city-state you are the Suzerain of. After building an Acropolis District, the first [ICON_Envoy] Envoy you send to each city-state counts as two [ICON_Envoy] Envoys."),
    ("LOC_TRAIT_LEADER_THERMOPYLAE_DESCRIPTION",                      "Combat victories provide [ICON_Culture] Culture equal to 50% of the [ICON_Strength] Combat Strength of the defeated unit. (on Standard Speed) +1 [ICON_Strength] Combat Strength for every Military Policy slotted. Receive a free anti-cavalry unit when the Acropolis district is constructed."),
    ("LOC_TRAIT_CIVILIZATION_EARLY_OCEAN_NAVIGATION_DESCRIPTION",     "+1 [ICON_Production] Production and +1 [ICON_Housing] Housing to Lumber Mills. Units gain the ability to enter Ocean tiles after researching the Shipbuilding technology. Naval melee units heal in neutral territory. Units ignore additional [ICON_Movement] Movement costs from embarking and disembarking."),
    ("LOC_TRAIT_LEADER_THUNDERBOLT_EXPANSION2_DESCRIPTION",           "Allows coastal raiding for all naval melee units and +50% [ICON_PRODUCTION] Production toward all naval melee units. In addition to normal pillage gains, receive [ICON_SCIENCE] Science from pillaging and coastal raiding Farms, Mines and Lumber Mills, receive [ICON_CULTURE] Culture from pillaging and coastal raiding Quarries, Pastures, Plantations, and Camps. Gain the Viking Longship unique unit with Sailing."),
    ("LOC_TRAIT_LEADER_ROOSEVELT_COROLLARY_ROUGH_RIDER_DESCRIPTION",  "Units receive +5 [ICON_Strength] Combat Strength on their home continent. Envoys sent to City-States you have a [ICON_TradeRoute] Trade Route to count as two [ICON_Envoy] Envoys. Gain the Rough Rider unique unit with Ballistics."),
    ("LOC_TRAIT_CIVILIZATION_EJERCITO_PATRIOTA_DESCRIPTION",          "+1 [ICON_Movement] Movement to all units. Promoting a unit does not end that unit’s turn. Planations Culture Bomb nearby neutral territory, and receive +1 [ICON_CULTURE] Culture."),
    ("LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_NAME",                    "Chiphyonjon"),
    ("LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_DESCRIPTION",             "Receive +1 [Icon_Governor] Governor Title each time a Seowon district or buildings inside a Seowon District is constructed in your [ICON_Capital] Capital."),
    ("LOC_TRAIT_LEADER_HWARANG_DESCRIPTION",                          "+3 [ICON_Amenities] Amenities, +5 [Icon_Housing] Housing and +20 Loyalty per turn for your Capital and cities with an assigned Governor. -2 [ICON_Amenities] Amenities, -20 Loyalty per turn and -50% to all yields for cities that are not your Capital and do not have an assigned Governors. +25% [ICON_PRODUCTION] Production towards Districts and Buildings for cities that have a Seowon district. +15% [ICON_Production] Production and +15% [ICON_FOOD] Food for Cities have a Library. +100% Districts Adjacency (of corresponding yields) to all Districts for Cities that have a University. Cities with a Research Lab gain +10% to all yields and +1 to all [ICON_CITIZEN] citizen yields."),
    ("LOC_LEADER_POUNDMAKER_ABILITY_DESCRIPTION",                     "All Alliance types provide Shared Visibility.[NEWLINE]Your outgoing [ICON_TradeRoute] Trade Routes grant you +1 [ICON_Food] Food per Fishing Boat, Camp or Pasture improvements at the destination. [ICON_TradeRoute] Trade Routes sent to your cities grant you +1 [ICON_Gold] Gold per Fishing Boat, Camp or Pasture improvements at the destination."),
    ("LOC_TRAIT_CIVILIZATION_MALI_GOLD_DESERT_DESCRIPTION",           "City Centers gain +1 [ICON_FAITH] Faith and +1 [ICON_FOOD] Food for every adjacent Desert and Desert Hills tiles. Mines receive -1 [ICON_PRODUCTION] Production and +4 [ICON_GOLD] Gold. May purchase Commercial Hub district buildings with [ICON_Faith] Faith. -30% [ICON_PRODUCTION] Production toward constructing buildings or training units."), --Mines over Luxury resources provide +10% [ICON_Gold] Gold. Mines over Luxury resources provide +1 [ICON_FOOD] Food for international [ICON_TradeRoute] Trade Routes from this city. 
    ("LOC_TRAIT_LEADER_SAHEL_MERCHANTS_DESCRIPTION",                  "International [ICON_TradeRoute] Trade Routes gain +1 [ICON_GOLD] Gold for every flat Desert or Desert hills tile in the origin city. Receive +1 [ICON_TradeRoute] Trade Capacity every time you enter a Golden Age. Earn extra 15 [ICON_GOLD] Gold for each era score earned."), -- May initiate the Endless Money Project.
    ("LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_DESCRIPTION",              "Cities with an Established [ICON_Governor] Governor provide +5% [ICON_CULTURE] Culture, +5% [ICON_Production] Production, and +10% experience in combat towards all units trained in this city. These numbers are tripled in cities not founded by the Mapuche. All cities within 9 tiles of a city with your [ICON_Governor] Governor gain +4 Loyalty per turn towards your civilization. Pasture improvements provide additional +1 [ICON_Housing] Housing."),
    ("LOC_TRAIT_LEADER_LAST_BEST_WEST_DESCRIPTION",                   "Allows Farms to be built on Tundra terrain. After Civil Engineering is unlocked Farms can be built on Tundra Hills. In Snow, Tundra, Snow Hills, and Tundra Hills all Mines, Lumber Mills, Pastures and Quarries provide +2 [ICON_PRODUCTION] Production, Farms, Camps and Plantations provide +2 [ICON_FOOD] Food, and strategic resource accumulation rate is +100%. Reduces the purchase cost of tiles in these terrain types by 50%."),
    ("LOC_TRAIT_CIVILIZATION_FACES_OF_PEACE_DESCRIPTION",             "Cannot declare war on City-States or surprise wars. Surprise wars cannot be declared on Canada. Your cities earn +15% [ICON_Culture] Culture and +25% [ICON_Tourism] Tourism across your empire whenever you are not at war with any major civilization. When you dispersed a Barbarian Outpost, receive a builder reward in addition."),
    ("LOC_TRAIT_LEADER_GRAND_EMBASSY_DESCRIPTION",                    "Can purchase buildings in Industrial Zone with [ICON_FAITH] Faith. -10% [ICON_FAITH] Faith cost when patronizing Great Person."),
    ("LOC_TRAIT_CIVILIZATION_MOTHER_RUSSIA_EXPANSION2_DESCRIPTION",   "+1 [ICON_Food] Food for all Tundra Districts. Extra territory upon founding cities. +1 [ICON_Faith] Faith and +1 [ICON_Production] Production from Tundra. Units do not receive damage from Blizzards. Civilizations that are at war with Russia receive +100% unit damage from Blizzards in Russian territory."),
    ("LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION",        "Begin the game with the Animal Husbandry technology unlocked. +1 [Icon_Production] Production for all Pastures across the Nation. Improved [ICON_RESOURCE_HORSES] Horses accumulate 3 more resources per turn. Receive a second light cavalry unit or Saka Horse Archer each time you train a light cavalry unit or Saka Horse Archer."),
    ("LOC_TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES_DESCRIPTION",       "Each city can build one more district than usual (exceeding the normal limit based on [ICON_Citizen] Population)."), -- +1 [ICON_Science] Science and +1 [ICON_Culture] Culture for cities that have Specialty Districts.
    ("LOC_TRAIT_LEADER_HOLY_ROMAN_EMPEROR_DESCRIPTION",               "Additional Military policy slot. Double Influence Points."),
    ("LOC_TRAIT_CIVILIZATION_INDONESIA_NUSANTARA_DESCRIPTION",        "Coast and Lake tiles provide a standard adjacency bonus for Holy Site, Campus, Industrial Zone, and Theater Square districts. +1 [ICON_AMENITIES] Amenity from entertainment to each Entertainment Complex adjacent to a Coast or Lake tile."),
    ("LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION",             "Can purchase and train Military Engineers in cities with Temple. May purchase Military Engineers with [ICON_Faith] Faith. Military Engineers receive +2 charges. Culture Bomb adjacent tiles when completing a Fort inside friendly territory. Fort provides +1 [ICON_PRODUCTION] Production and +1 [ICON_CULTURE] Culture to adjacent tiles. [NEWLINE]All Military policy slots in the current government are converted to Wildcard slots."), --Tiles that adjacent to the Fort get +2 [ICON_PRODUCTION] Production and +2 [ICON_CULTURE] Culture.
    ("LOC_TRAIT_LEADER_LITHUANIAN_UNION_DESCRIPTION",                 "Holy Sites and their buildings are built 30% faster, and yield +2 [ICON_FAITH] Faith. Poland's majority religion becomes the dominant religion in cities that loses a tile to a Polish Culture Bomb. Grant boost [ICON_TechBoosted] to 'Military Engineering' for each completed temple (complete 'Military Engineering' if already boosted)."),
    ("LOC_TRAIT_LEADER_GRAND_EMBASSY_NAME",                           "Pater Patriae"),
    ("LOC_TRAIT_LEADER_ELEANOR_LOYALTY_DESCRIPTION",                  "In cities built by Eleanor, Art Museums and Archaeological Museums get 3 extra slots, and are automatically themed when all slots are filled. Great Works in Eleanor’s cities each cause -2 Loyalty per turn in foreign cities within 9 tiles. A city that leaves another civilization due to a loss of Loyalty and is currently receiving the most Loyalty per turn from Eleanor's civilization skips the Free City step to join this civilization.May initiate the Judgement of Love project in any city with a Theater Square district."),
    ("LOC_TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION_DESCRIPTION",      "[ICON_Resource_Iron] Iron and [ICON_Resource_Coal] Coal Mines +1 [ICON_Production] Production and accumulate 2 more resources per turn. +25% building speed towards Industrial Zone and its buildings. Regional effects from Industrial Zone buildings provide extra +4 [ICON_Production] Production. Grant boost [ICON_TechBoosted] to 'Industrialization' each time a Shipyard is built (complete 'Industrialization' if already boosted)."), --Reveal [ICON_Resource_Iron] Iron without the normal technology requirement, 
    ("LOC_TRAIT_CIVILIZATION_PAX_BRITANNICA_EXPANSION2_DESCRIPTION",      "Each time you found your first city on a continent other than your home continent receive a free melee unit and a [ICON_TRADEROUTE] Trade Route capacity. Constructing any Royal Navy Dockyard grants you a copy of the strongest naval unit you can build. Whenever you recruit a [ICON_GREATGENERAL] Great General, grant a random [ICON_TECHBOOSTED] Eureka of the corresponding era. Gain the Redcoat unique unit when the Military Science technology is researched."),
    ("LOC_TRAIT_LEADER_RELIGIOUS_CONVERT_DESCRIPTION",                "May not gain Great Prophets, or found Religions. Receive Theology [ICON_CivicBoosted] Inspiration, Divine Right [ICON_CivicBoosted] Inspiration and Reformed Church [ICON_CivicBoosted] Inspiration when Mbanza is first built. Receive 50% more [ICON_GREATWRITER] Great Writer, [ICON_GREATARTIST] Great Artist, [ICON_GREATMUSICIAN] Great Musician, and [ICON_GREATMERCHANT] Great Merchant points. Palace has slots for 5 Great Works."),
    ("LOC_TRAIT_CIVILIZATION_NKISI_DESCRIPTION",                      "All land units ignore [ICON_MOVEMENT] movement penalty from Forest and Jungle. +4 [ICON_Food] Food, +4 [ICON_Production] Production from each [ICON_GreatWork_Relic] Relic, [ICON_GreatWork_Artifact] Artifact, [ICON_GreatWork_Portrait] Portrait, [ICON_GreatWork_Landscape] Landscape, [ICON_GreatWork_Religious] Religious, [ICON_GreatWork_Sculpture] Sculpture and [ICON_GREATWORK_MUSIC] Music. +2 [ICON_Food] Food, +2 [ICON_Production] Production from each [ICON_GreatWork_Writing] Writing. Palace has slots for 5 Great Works."),
    ("LOC_TRAIT_CIVILIZATION_BABYLON_NAME",                    		  "Fertile Crescent"),
	("LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",                    "Your Specialty districts provide +1 of the corresponding yield (Harbor provides [ICON_FOOD] Food, Government Plaza provides [ICON_CULTURE] Culture, Entertainment Complex and Water Park provides [ICON_GOLD] Gold) to every Specialty district in cities without the corresponding district."),
    ("LOC_TRAIT_LEADER_HAMMURABI_NAME",                    	  		  "The Code of Hammurabi"),
    ("LOC_TRAIT_LEADER_FLYING_SQUADRON_NAME",                         "Château de Chenonceau"),
	("LOC_TRAIT_LEADER_HAMMURABI_XP1_DESCRIPTION",                    "[ICON_TECHBOOSTED] Eurekas provide 94% of the [ICON_SCIENCE] Science for technologies. -50% [ICON_SCIENCE] Science per turn."),
    ("LOC_TRAIT_CIVILIZATION_MAYAB_DESCRIPTION",                      "Settling adjacent to Fresh Water and Coast does not provide extra [ICON_HOUSING] Housing. Instead each Farm provides an additional +1 [ICON_HOUSING] Housing, +1 [ICON_Production] Production for every adjacent Observatory, and +1 [ICON_GOLD] Gold. +1 [ICON_AMENITIES] Amenity for every Luxury resource adjacent to the City Center."),
    ("LOC_TRAIT_LEADER_MUTAL_DESCRIPTION",                            "Reveal plots within 6 tiles of the starting plot. Cities within 6 tiles of the [ICON_Capital] Capital gain +10% to all yields, and when founded receive a builder. Non capital cities within 9 tiles and outside 6 tiles of the [ICON_Capital] Capital yields remain usual. Other non capital cities receive -15% to all yields. +5 [ICON_Strength] Combat Strength to units within 6 tiles of the [ICON_Capital] Capital."),
    ("LOC_TRAIT_LEADER_TRAJANS_COLUMN_DESCRIPTION",                   "All cities start with a Monument building. +100% construction speed towads builings in City Center."),
    ("LOC_TRAIT_CIVILIZATION_MAORI_MANA_DESCRIPTION",                 "Begin the game with the Sailing and Shipbuilding technologies unlocked and with the ability to enter Ocean tiles. Embarked units gain +2 [ICON_Movement] Movement. Unimproved Woods and Rainforest gain +1 [ICON_PRODUCTION] Production. Additional +1 [ICON_PRODUCTION] Production from Civil Service, +1 [ICON_PRODUCTION] Production from Mercantilism, +1 [ICON_PRODUCTION] Production from Conservation and +1 [ICON_PRODUCTION] Production from Environmentalism. Fishing Boats provide +1 [ICON_FOOD] Food and a Culture Bomb to adjacent tiles. [ICON_GreatWriter] Great Writers cannot be earned."),
    ("LOC_TRAIT_CIVILIZATION_ITERU_EXPANSION2_DESCRIPTION",           "Campus and Theater Square districts recieve major adjacency bonus from being adjacent to River. +15% construction speed towards Districts and Wonders if placed next to a River. Does not receive damage from Floods. Receive a free Builder every time you finish a Wonder."),
    ("LOC_TRAIT_LEADER_MEDITERRANEAN_EXPANSION2_DESCRIPTION",         "Your [ICON_TradeRoute] Trade Routes to other civilizations provide +8 [ICON_Gold] Gold for Egypt. Other civilizations' [ICON_TradeRoute] Trade Routes to Egypt provide +4 [ICON_Food] Food for them and +4 [ICON_Gold] Gold for Egypt. Trading with Allies earns double as many bonus Alliance Points."),
    ("LOC_TRAIT_CIVILIZATION_LAST_PROPHET_DESCRIPTION",               "Automatically receive the final [ICON_GreatProphet] Great Prophet when the next-to-last one is claimed (if you have not earned a [ICON_GreatProphet] Great Prophet already). +4 [ICON_Science] Science for each foreign city following Arabia's Religion."), -- Receive a free apostle when [ICON_GreatProphet] Great Prophet is created or Religion is founded. 
    ("LOC_TRAIT_LEADER_MENELIK_DESCRIPTION",                          "Receive [ICON_SCIENCE] Science and [ICON_CULTURE] Culture equal to 15% of your [ICON_FAITH] Faith generation in cities founded on Hills. Units receive +4 [ICON_STRENGTH] Combat Strength on Hills."),
    ("LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",                    "All Districts (except City Centers) do not remove Forest, Rainforest and Marsh. Receive the following yields for every building and Districts itself on these features: +2 [ICON_Production] Production in Forest, +2 [ICON_Food] Food in Rainforest and +2 [ICON_Science] Science in Marsh. Woods can be planted with the Mysticism civic."),
    ("LOC_TRAIT_CIVILIZATION_GAUL_DESCRIPTION",                       "Mines provide a minor adjacency bonus for all districts, a Culture Bomb of unowned territory, and receive +1 [ICON_CULTURE] Culture. Specialty districts do not receive a minor adjacency bonus for being adjacent to another district."),
    ("LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_DESCRIPTION",                 "Cities (founded by you) with a Cothon gain the unique Move Capital project, which moves the Phoenician [ICON_Capital] Capital to that city. Coastal cities founded by Phoenicia and located on the same continent as the Phoenician [ICON_Capital] Capital are 100% Loyal.Gains +1 [ICON_TradeRoute] Trade Route capacity after building the Government Plaza or any Government Plaza building, Diplomatic Quarter or any Diplomatic Quarter building. +50% [ICON_Production] Production towards [ICON_District] Districts in the city with Government Plaza or Diplomatic Quarter."),
    ("LOC_TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES_DESCRIPTION",     "Begin the game with the Writing technology [ICON_TechBoosted] Eureka and Foreign Trade [ICON_CivicBoosted] Inspiration.  Settlers gain +2 [ICON_Movement] Movement and +2 sight range while embarked. Settlers ignore additional [ICON_Movement] Movement costs from embarking and disembarking. International [ICON_Traderoute] Trade Routes provide +2 [ICON_Culture] culture; this bonus is tripled when the destination is a City-State you are the Suzerain of."),
    ("LOC_TRAIT_LEADER_FIRST_EMPEROR_NAME",                           "The Greatest Emperor Ever"),
    ("LOC_TRAIT_LEADER_FIRST_EMPEROR_EXPANSION2_DESCRIPTION",         "When building Ancient and Classical wonders, you may spend Builder charges to complete 15% of the original wonder cost. Builders receive an additional charge and +1 [ICON_Movement] Movement."),
    ("LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_NAME",                    "Wisdom of Working People"),
    ("LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION",  "+6 [ICON_Science] Science when you use a Builder's charge. [ICON_TechBoosted] Eurekas and [ICON_CivicBoosted] Inspirations provide 10% more of technologies and civics. When completing a wonder, receive a random [ICON_TechBoosted] Eureka and [ICON_CivicBoosted] Inspiration from the era of the wonder, if available. Canals are unlocked with the Masonry technology."),
    ("LOC_TRAIT_LEADER_RAVEN_KING_DESCRIPTION",                       "Levied units gain an ability giving them +2 [ICON_Movement] Movement and +5 [ICON_Strength] Combat Strength. It costs 50% less [ICON_GOLD] Gold and resources to upgrade Levied units. If you Levy troops from a City-State, receive 2 [ICON_ENVOY] Envoys in that City-State. Gain the Black Army unique unit when the 'Castles' technology is researched."),
    ("LOC_TRAIT_CIVILIZATION_SATRAPIES_DESCRIPTION",                  "+1 [ICON_TradeRoute] Trade Route capacity and receive 1 [ICON_Governor] Governor title with Political Philosophy civic. Receive +2 [ICON_Gold] Gold and +2 [ICON_Culture] Culture for routes between your own cities. Roads built in your territory are one level more advanced than usual."),
    ("LOC_TRAIT_LEADER_FALL_BABYLON_EXPANSION2_DESCRIPTION",          "+2 [ICON_Movement] Movement for the first 10 turns after declaring a Surprise War on a major civilization. +5 Loyalty per turn in cities with a garrisoned unit. Declaring a Surprise War only counts as a Formal War for the purposes of [ICON_STAT_GRIEVANCE] Grievances and Warmongering."),
    ("LOC_TRAIT_LEADER_BANNOCKBURN_DESCRIPTION",                      "Military units receive +4 [ICON_Strength] Combat Strength when defending in your territory. Can declare a War of Liberation after gaining the Supply Civic. +100% [ICON_Production] Production and +2 [ICON_Movement] Movement for the first 10 turns after declaring a War of Liberation."),
    ("LOC_TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT_DESCRIPTION",     "Happy cities receive an additional +6% [ICON_SCIENCE] Science and +6% [ICON_PRODUCTION] Production. Happy cities generate +2 [ICON_GreatScientist] Great Scientist point per Campus, +2 [ICON_GreatEngineer] Great Engineer point per Industrial Zone. Joyful cities double all these values, Ecstatic cities triple all these values. Campus and Industrial Zone receive +1 [ICON_Amenities] Amenity and standard adjacency (instead of minor adjacency) from other Districts."),
    ("LOC_TRAIT_LEADER_RELIGION_CITY_STATES_DESCRIPTION",             "Each [ICON_ENVOY] Envoy you send to a city-state following your majority Religion counts as two [ICON_ENVOY] Envoys (if you have a majority Religion). Combat victories provide [ICON_FAITH] Faith equal to 100% of the Combat Strength of the defeated unit. +100% [ICON_FAITH] Faith for 10 turns after declaring a Protectorate War."),
    ("LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION",          "Receives a permanent extra Wildcard Policy Slot once if enters a Golden Age or Heroic Age for the first time. May use Dark Age Policies during a Golden Age or Heroic Age. After enters a Golden Age or Heroic Age, receive the Normal Age bonus towards improving Era Score in addition to the other bonus. +100% construction speed towards defensive buildings. +1 [ICON_CULTURE] Culture and +1 [ICON_Faith] Faith per level of Walls."),
    ("LOC_TRAIT_CIVILIZATION_GREAT_MOUNTAINS_DESCRIPTION",            "Citizens may work Mountain tiles. Mountain tiles provide +3 [ICON_PRODUCTION] Production. Reduces the purchase cost of mountain tiles by 50%. Aqueduct provides +1 [ICON_PRODCUTION] for Terrace Farms in the city."),
    ("LOC_TRAIT_LEADER_PACHACUTI_QHAPAQ_NAN_DESCRIPTION",             "All land units ignore [ICON_MOVEMENT] movement penalty from Hills. Domestic [ICON_TradeRoute] Trade Routes gain +1 [ICON_Food] Food for every Mountain tile in the origin city. Gain the Qhapaq Ñan improvement when Foreign Trade civic is discovered."),
    ("LOC_TRAIT_CIVILIZATION_AMAZON_DESCRIPTION",                     "Rainforest tiles provide +1 adjacency bonus for Campus, Commercial Hub, Holy Site, and Theater Square districts, and grant +1 Appeal to adjacent tiles, instead of the usual -1. Lumber Mill provides +1 adjacency bonus for Industrial Zone. Rainforest tiles receive +1 [ICON_PRODUCTION] Production if is adjacent to Industrial Zone tiles. +2 [ICON_CULTURE] Culture for all Rainforest Lumber Mill. All districts (except city centers) will not remove Rainforest. +1 [Icon_Faith] Faith if city is adjacent to Rainforest tiles."),
    ("LOC_TRAIT_LEADER_MAGNANIMOUS_DESCRIPTION",                      "After recruiting or patronizing a [ICON_GreatPerson] Great Person, 20% of its [ICON_GreatPerson] Great Person point cost is refunded. +1 [Icon_Faith] Faith in all Rainforest Tiles across your country for every two [ICON_GreatPerson] Great Person you have recruited."),
    ("LOC_TRAIT_CIVILIZATION_TREASURE_FLEET_EXPANSION2_DESCRIPTION",  "May form Fleets and Armadas with Exploration and Mercantilism, instead of Colonialism and Mobilization. [ICON_TradeRoute] Trade Routes provide +3 [ICON_Gold] Gold, +2 [ICON_Faith] Faith, and +1 [ICON_Production] Production; this bonus is tripled for [ICON_TradeRoute] Trade Routes across multiple continents. Cities not on your original Capital’s continent receive a Builder when founded, and has +25% [ICON_Production] Production towards districts."),
    ("LOC_TRAIT_CIVILIZATION_TA_SETI_DESCRIPTION",                    "+30% [ICON_Production] Production toward Ranged units. All Ranged units gain +30% combat experience. Mines over Bonus and Luxury resources provide +2 [ICON_GOLD] Gold, and Mines over Strategic resources provide +1 [ICON_Production] Production. Each kind of mined Bonus or Luxury resources provide +10% [ICON_GOLD] Gold, and each kind of mined Strategic resources provide +10% [ICON_Production] Production."),
    ("LOC_TRAIT_LEADER_KANDAKE_OF_MEROE_DESCRIPTION",                 "+20% [ICON_Production] Production towards all Districts; rising to +40% if there is a Nubian Pyramid adjacent to the City Center."),
    ("LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_NAME",                      "Guerra Florida"),
    ("LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_DESCRIPTION",               "All Melee units have a chance to capture other civilization's military units by turning them into Builders. Enable Sacrificing the builders, which removes the unit and gains +10 [ICON_Culture] Culture and +10 [ICON_Faith] Faith for each builder charge the unit has."),
    ("LOC_TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS_DESCRIPTION",           "Spend Builder charges to complete 20% of the original District cost. Luxury resources provide [ICON_Amenities] Amenity to 2 extra cities. When attacking, military units receive +1 [ICON_Strength] Combat Strength for each different Luxury resource improved across the Nation."),
    ("LOC_TRAIT_LEADER_FLYING_SQUADRON_DESCRIPTION",                  "Receives a free Spy (and extra spy capacity) upon unlocking the Castles technology, Political Philosophy civic, or Supply civic. +1 sight range for Trader, Settler, Builder units and Recon units, +3 sight range for spies. All spies start with a free promotion. Gain 1 level of [ICON_VISLIMITED] Diplomatic Visibility greater than normal with every civilization that they've met."), -- (if already have, can promote again after the first promotion)
    ("LOC_TRAIT_LEADER_SATYAGRAHA_DESCRIPTION",                       "ALL cities have +15% growth rate, 15% [ICON_Faith] Faith and +1 [ICON_Amenities] Amenity when you are at peace with all other major civilizations. +5 [ICON_Faith] Faith for each civilization (including India) they have met that has founded a Religion and is not currently at war. Opposing civilizations receive double the war weariness for fighting against Gandhi."),
    ("LOC_TRAIT_CIVILIZATION_DHARMA_EXPANSION2_DESCRIPTION",          "Receives Follower Belief bonuses in a city from each Religion that has at least 1 Follower. Cities gain an [ICON_Amenities] Amenity for every Religion with at least 1 Follower. Missionaries have +2 spreads. +100% Religious pressure from your [ICON_TradeRoute] Trade Routes. +0.5 [ICON_Food] Food per Population for cities with Stepwell."),
    ("LOC_TRAIT_LEADER_ARTHASHASTRA_DESCRIPTION",                     "Can declare a War of Territorial Expansion after progressing the 'Military Tradition' Civic. Receive a Setter in your capital after progressing the 'Military Training' Civic. +2 [ICON_Movement] Movement and +5 [ICON_Strength] Combat Strength for the first 10 turns after declaring a War of Territorial Expansion."),
    ("LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_NAME",                  "Manifest Destiny"),
    ("LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION","All Diplomatic policy slots in the current government are converted to Wildcard slots. +1 [ICON_Favor] Diplomatic Favor per turn for every Wildcard slot in their government. Reduces the purchase cost of tiles in Grass, Grass Hills, Plains and Plains Hills by 50%."),
    ("LOC_TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME_DESCRIPTION",          "All cities you found or conquer start with a Trading Post. If in [ICON_TradeRoute] Trade Route range of your [ICON_Capital] Capital, they also start with a road to it. Your domestic [ICON_TradeRoute] Trade Routes earn extra +1 [ICON_Gold] Gold for passing through Trading Posts in your own cities."),
    ("LOC_TRAIT_CIVILIZATION_CREE_TRADE_GAIN_TILES_DESCRIPTION",      "+1 [ICON_TradeRoute] Trade Route capacity and a free Trader with the Pottery technology. +1 [ICON_TradeRoute] Trade Route capacity and a free Trader with the State Workforce civic. Unclaimed tiles within 3 tiles of a Cree city come under Cree control when a Trader first moves into them."),
    ("LOC_TRAIT_LEADER_DIVINE_WIND_EXPANSION2_DESCRIPTION",           "Land units receive +5 [ICON_Strength] Combat Strength in land tiles adjacent to Coast; naval units receive +5 [ICON_Strength] Combat Strength in shallow water tiles. +50% [ICON_PRODUCTION] Production towards Harbor, Holy Site and Theater Square districts."),
    ("LOC_TRAIT_CIVILIZATION_ADJACENT_DISTRICTS_DESCRIPTION",         "All districts receive an additional standard adjacency bonus for being adjacent to another district."),
    ("LOC_TRAIT_CIVILIZATION_MONGOLIAN_ORTOO_DESCRIPTION",            "Starting a [ICON_TRADEROUTE] Trade Route immediately creates a [ICON_TRADINGPOST] Trading Post in the destination city. Your [ICON_TRADEROUTE] Trade Routes provide additional +1 [ICON_SCIENCE] Science for passing through each [ICON_TRADINGPOST] Trading Post owned by you. Receive 1 extra level of [ICON_VISLIMITED] Diplomatic Visibility on corresponding Civilization for possessing each [ICON_TRADINGPOST] Trading Post in its Cities. All Mongolian units double the usual [ICON_STRENGTH] Combat Bonus for having a higher level of [ICON_VISLIMITED] Diplomatic Visibility than their opponent."),
    ("LOC_TRAIT_LEADER_GENGHIS_KHAN_ABILITY_DESCRIPTION",             "Pasture tiles provide standard adjacency bonus to Holy Site and Commercial Hub districts. All cavalry class units gain +3 [ICON_STRENGTH] Combat Strength and a chance to capture defeated enemy cavalry class units."),
    ("LOC_GENGHIS_KHAN_PASTURE_HOLY_SITE",                            "+{1_num} [ICON_FAITH] Faith from the adjacent Pasture {1_Num : plural 1?tile; other?tiles;}."),
    ("LOC_GENGHIS_KHAN_PASTURE_COMMERCIAL_HUB",                       "+{1_num} [ICON_GOLD] Gold from the adjacent Pasture {1_Num : plural 1?tile; other?tiles;}."),
    ("LOC_TRAIT_CIVILIZATION_ZULU_ISIBONGO_DESCRIPTION",              "+1 [ICON_CULTURE] Culture in cities with a garrisoned unit. Cities with a garrisoned unit get +3 Loyalty per turn, or +5 if it is a Corps or Army. Conquering a city with a unit will upgrade it into a Corps or Army, if the proper Civics are unlocked."),
    ("LOC_TRAIT_LEADER_CAESAR_DESCRIPTION",              			  "+200 [ICON_GOLD] Gold when you build or conquer a city. +100 [ICON_GOLD] Gold when you clear a Barbarian Outpost. When you conquer a city, all units within 3 tiles permanetly gets +1 [ICON_STRENGTH] Combat Strength."),
    ("LOC_CAESAR_STRENGTH_MODIFIER",              			  		  "+{1_Amount} Strength from conquered city."),
    ("LOC_TRAIT_LEADER_LINCOLN_EXPANSION_DESCRIPTION",                "Industrial Zones give +2 [ICON_Amenities] Amenities. Receive a free Builder every time you finish a Industrial Zone. Enable Liberating the builders, which removes the unit and gives +2 [ICON_PRODUCTION] Production adjacency bonus to this Industrial Zone, and gains 1 [ICON_CITIZEN] citizen if you first do it in a city."),
    ("LOC_TRAIT_LEADER_SALADIN_ALT_DESCRIPTION",                      "+100% Flanking and Support Bonus to all Combat and Religious units. Unit gains 1 bonus [ICON_MOVEMENT] Movement if it begins a turn within the borders of cities that follow your Religion. Religious units can ignore Zone of Control."),
    ("LOC_UNITCOMMAND_LIBERATION_LINCOLN_NAME",                       "Liberate"),
    ("LOC_UNITCOMMAND_LIBERATION_LINCOLN_DESCRIPTION",                "Liberate this unit to give +2 [ICON_PRODUCTION] Production adjacency bonus to this Industrial Zone, and gain 1 [ICON_CITIZEN] citizen if you first do it in a city."),
    ("LOC_UNITCOMMAND_LIBERATION_LINCOLN_DISABLED_TT",                "Must be located in the Industrial Zone, and have [ICON_MOVEMENT] Movement left."),
    ("LOC_TRAIT_LEADER_SULEIMAN_ALT_DESCRIPTION",                     "Gain a copy of all available commemoration effects in each Era."),
    ("LOC_TRAIT_LEADER_NADER_SHAH_DESCRIPTION",                       "+7 [ICON_STRENGTH] Combat Strength when attacking units or cities with full Health. Upon conquering a city, destroy all its Districts and Buildings and grant yield based on the District type or the required District Type equal to the base [ICON_PRODUCTION] Production cost: Campus, Encampment and Industrial Zone provide [ICON_SCIENCE] Science, Holy Site, Theater Square, Entertainment Complex and Water Park provide [ICON_CULTURE] Culture, others provide 4 times [ICON_GOLD] Gold."),
    ("LOC_ABILITY_NADER_SHAH_COMBAT_DESCRIPTION",                       "+7 [ICON_Strength] Combat Strength when attacking units or cities with full Health. (Nader Shah)"),
    ("LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_NAME",                     "People of the Earth"),
    ("LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_DESCRIPTION",              "All Districts (Wonders not included) adjacent to Mountain tiles provide +1 [ICON_FOOD] Food and +1 [ICON_FAITH] Faith, and Improved tiles adjacent to Mountain tiles provide +1 [ICON_FOOD] Food and +1 [ICON_FAITH] Faith. Gains 1 bonus [ICON_MOVEMENT] Movement if it begins a turn adjacent to Mountain tiles."),
    ("LOC_TRAIT_LEADER_LAUTARO_ABILITY_DESCRIPTION_ALT",              "+5 [ICON_STRENGTH] Combat Strength when fighting Free Cities or civilizations that are in a Golden or Heroic Age. Cities with an Established [ICON_GOVERNOR] Governor provide +50% experience in combat towards all units trained in this city."),
    ("LOC_ABILITY_TOQUI_XP_FROM_GOVERNOR_DESCRIPTION",                "Gains +50% experience in combat.(Swift Hawk)"),
    ("LOC_PEDIA_LEADERS_PAGE_LEADER_TOKUGAWA_CHAPTER_DETAILED_BODY",  "The Taika Era Reforms ability gives large adjacency bonuses to Japan’s districts. Tokugawa’s ability also greatly increases Domestic [ICON_TradeRoute] Trade Route’s yields for every district. But be aware that International [ICON_TradeRoute] Trade Routes are much weaker. The Electronics Factory will help him towards a Culture or Science Victory."),
    ("LOC_TRAIT_CIVILIZATION_ADJACENT_DISTRICTS_NAME",                "Taika Era Reforms"),
    ("LOC_TRAIT_LEADER_DIVINE_WIND_NAME",                             "Kamakura Bakufu"),
    ("LOC_TRAIT_LEADER_TOKUGAWA_XP_DESCRIPTION",                      "International [ICON_TradeRoute] Trade Routes receive -25% Yield and [ICON_Tourism] Tourism, but Domestic [ICON_TradeRoute] Trade Routes provide +1 [ICON_Culture] Culture, +1  [ICON_Science] Science, and +2  [ICON_Gold] Gold for every Specialty District at the Destination.");
--------------------------------------------------------------------------------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                             Text)
values
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_KUBLAI_DESCRIPTION",                           "任意政体中额外增加一个经济政策槽位。占领其他文明的原始 [ICON_Capital] 首都时，获得该文明的特色能力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_WONDER_TOURISM_DESCRIPTION",             "为中世纪、文艺复兴时期和工业时代的奇观+20%建造速度。 所有奇观的 [ICON_Tourism] 旅游业绩+200%。完成奇观时，获得各等同于其 [ICON_PRODUCTION] 生产力花费20%的 [ICON_GREATWRITER] 大作家、 [ICON_GREATARTIST] 大艺术家、 [ICON_GREATMUSICIAN] 大音乐家点数。在城市中激活巨作，可为该城市正在建造的奇观推进10%的建造进程。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SURROUNDED_BY_GLORY_DESCRIPTION",              "作为宗主国时，每个下辖的城邦使您的 [ICON_Culture] 文化值+5%。建造卫城后，您向每个城邦派遣的第一个 [ICON_Envoy] 使者会被视为2个 [ICON_Envoy] 使者。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_THERMOPYLAE_DESCRIPTION",                      "战斗胜利后，获得等同于被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_Culture] 文化值（标准速度下）。槽位中每有一项军事政策，则+1 [ICON_Strength] 战斗力。建成卫城时获得一个抗骑兵单位。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_EARLY_OCEAN_NAVIGATION_DESCRIPTION",     "伐木场提供额外+1 [ICON_Production] 生产力和+1 [Icon_Housing] 住房。在研究造船术后，单位获得进入海洋单元格的能力。海军近战单位可在中立领土上回复。单位忽略来自上船和下船的额外 [ICON_Movement] 移动力消耗。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_THUNDERBOLT_EXPANSION2_DESCRIPTION",           "使所有海军近战单位均能发动海岸扫荡，生产所有海军近战单位时+50% [ICON_PRODUCTION] 生产力。除常规劫掠收益外，对农田、矿山、伐木场发动掠夺或海岸扫荡时还将获得 [ICON_SCIENCE] 科技值，对采石场、牧场、种植园和营地发动掠夺或海岸扫荡时还将获得 [ICON_CULTURE] 文化值。解锁“航海术”科技后即可获得特色单位维京长船。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ROOSEVELT_COROLLARY_ROUGH_RIDER_DESCRIPTION",  "在首都所在大陆上时单位+5 [ICON_Strength] 战斗力。如与城邦之间存在 [ICON_TradeRoute] 贸易路线，派往此处的1位 [ICON_Envoy] 使者将视为2位。解锁“弹道学”科技后获得特色单位“莽骑兵”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_EJERCITO_PATRIOTA_DESCRIPTION",          "所有单位+1 [ICON_Movement] 移动力。升级单位不会结束其回合。种植园对无主领土施放文化炸弹，并+1 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_NAME",                    "集贤殿"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_THREE_KINGDOMS_DESCRIPTION",             "首都每次建造完成书院区域或书院中的建筑时获得一个总督点。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HWARANG_DESCRIPTION",                          "首都或派遣了总督的城市获得+3 [ICON_Amenities] 宜居度，+5 [Icon_Housing] 住房和+20忠诚度。非首都且未派遣总督的城市-2 [ICON_Amenities] 宜居度，-8忠诚度，-50%全部产出。 有书院的城市建造区域和建筑+25% [Icon_Production] 生产力；有图书馆的城市+15% [ICON_Food] 食物和 [Icon_production] 生产力；有大学的城市，所有区域对应产出类型的相邻加成+100%；有实验室的城市所有产出+10%且每个人口额外1点全部产出。"),
    ("zh_Hans_CN",  "LOC_LEADER_POUNDMAKER_ABILITY_NAME",                            "最惠条款"),
    ("zh_Hans_CN",  "LOC_LEADER_POUNDMAKER_ABILITY_DESCRIPTION",                     "所有同盟类型均可以共享视野。[NEWLINE]目的地城市中的每个渔船、营地或牧场可为你的 [ICON_TradeRoute] 贸易路线提供+1 [ICON_Food] 食物。[NEWLINE]你的城市作为 [ICON_TradeRoute] 贸易路线目的地时，此城中的每个渔船、营地或牧场可为你提供+1 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MALI_GOLD_DESERT_DESCRIPTION",           "每个相邻沙漠或沙漠丘陵单元格为市中心提供+1 [ICON_FAITH] 信仰值与+1 [ICON_FOOD] 食物。矿山-1 [ICON_PRODUCTION] 生产力，但+4 [ICON_GOLD] 金币，可用 [ICON_Faith] 信仰值购买商业中心区域建筑。建造建筑或生产单位时-30% [ICON_PRODUCTION] 生产力。"), --每一种改良的奢侈矿产资源为城市+10% [ICON_Gold] 金币，城市中的每个奢侈品资源矿产为国际 [ICON_TradeRoute] 贸易路线提供+1 [ICON_FOOD] 食物。
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SAHEL_MERCHANTS_DESCRIPTION",                  "起始城市中的每个沙漠或沙漠丘陵单元格为国际 [ICON_TradeRoute] 贸易路线提供+1 [ICON_GOLD] 金币。文明进入黄金时代后可获得+1 [ICON_TradeRoute] 贸易路线容量。每获得1点时代分，额外获得15 [ICON_GOLD] 金币。"), --可在拥有曼丁哥市场的任意城市中开展“多钱善贾”项目。
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_DESCRIPTION",              "[ICON_Governor] 总督就职城市提供的 [ICON_CULTURE] 文化值+5%、 [ICON_Production] 生产力+5%，此城市中生产的所有单位的战斗经验值+10%。在非马普切建立的城市中，这些数值将乘以三倍。[ICON_Governor] 总督就职城市9单元格范围内的所有城市每回合对本方文明的忠诚度+4。牧场提供额外+1 [ICON_Housing] 住房。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LAST_BEST_WEST_DESCRIPTION",                   "允许在冻土地貌上建造农场。解锁“土木工程”后，即可在冻土丘陵上建造农场。在雪地、冻土、雪地丘陵和冻土丘陵上的所有矿山、伐木场、牧场和采石场提供的 [ICON_PRODUCTION] 生产力+2，农场、营地、种植园提供的 [ICON_FOOD] 食物+2，战略资源积累速度+100%。这些地形上的单元格购买费用降低50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_FACES_OF_PEACE_DESCRIPTION",             "无法对城邦宣战或发动突袭战争。无法对加拿大发动突袭战争。与主要文明处于和平时所有城市+15% [ICON_Culture] 文化值，且全境内+25% [ICON_Tourism] 旅游业绩。当您清理一个蛮族哨站时，奖励一个建造者。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GRAND_EMBASSY_DESCRIPTION",                    "可以用 [ICON_FAITH] 信仰购买工业区建筑。用 [ICON_FAITH] 信仰值招募伟人时所需的费用-10%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MOTHER_RUSSIA_EXPANSION2_DESCRIPTION",   "所有位于冻土单元格的区域+1 [ICON_Food] 食物。建立城市可获得额外领土。冻土提供+1 [ICON_Faith] 信仰值与+1 [ICON_Production] 生产力。与俄罗斯交战的文明单位如处于俄罗斯领土中，遭遇暴风雪时受到的伤害+100%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION",        "游戏初始便解锁畜牧业科技。牧场+1 [ICON_PRODUCTION] 生产力。开发 [ICON_RESOURCE_HORSES] 马资源的牧场每回合额外+3 [ICON_RESOURCE_HORSES] 马资源积累。每次您训练一个轻骑兵或萨卡弓骑手，都可以再获得一个轻骑兵或萨卡弓骑手。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES_DESCRIPTION",       "每座城市都能建造比平常多一个区域（无视 [ICON_Citizen] 人口数量限制）。"), -- 拥有专业化区域的城市+1 [ICON_Science] 科技值和 +1 [ICON_Culture] 文化值。
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HOLY_ROMAN_EMPEROR_DESCRIPTION",               "额外的军事政策槽位。获得影响力点数翻倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_INDONESIA_NUSANTARA_DESCRIPTION",        "海岸和湖泊单元格可为圣地、学院、工业区和剧院广场提供标准相邻加成。与海岸或湖泊单元格相邻的娱乐中心额外+1 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LITHUANIAN_UNION_DESCRIPTION",                 "圣地和圣地中建筑+30%建造速度并+2 [ICON_FAITH] 信仰值。如城市遭到波兰文化炸弹攻击失去单元格，此城将自动信仰你的主流宗教。每次完成寺庙后，触发军事工程学尤里卡，若军事工程学尤里卡已触发，则完成该科技。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION",             "当前政体的所有军事政策槽位均转为通配符槽位。堡垒对相邻单元格施放文化炸弹，并使相邻单元格+1 [ICON_Production] 生产力和+1 [ICON_Culture] 文化值。拥有寺庙的城市可训练军事工程师。军事工程师+2劳动力且可以用 [ICON_FAITH] 信仰值购买。"), --相邻堡垒的单元格+2 [ICON_Production] 生产力和+2 [ICON_Culture] 文化值
    -- ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_PORTUGAL_NAME",                          "东印度公司"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_NAME",                    "贵族联盟制"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GRAND_EMBASSY_NAME",                           "祖国之父"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ELEANOR_LOYALTY_DESCRIPTION",                  "您建立的城市中，考古博物馆和艺术博物馆获得3个额外槽位，填满时自动获得主题化。每个已放置的巨作使9个单元格内的外国城市-2忠诚度。外国城市转变为自由城市前，若对您的忠诚度最高，可直接效忠您。拥有剧院广场的城市可开展“爱之审判”项目。"), 
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION_DESCRIPTION",      "已改良的 [ICON_Resource_Iron] 铁与 [ICON_Resource_Coal] 煤+1 [ICON_Production] 生产力且每回合产量额外增加2点。建造工业区和这个区域中的建筑时+25%建造速度。工业区的辐射建筑的 [ICON_Production] 生产力辐射额外+4，[ICON_SCIENCE] 科技值辐射额外+2。每次完成造船厂后，触发工业化尤里卡，若工业化尤里卡已触发，则直接完成工业化科技。"), --无视科技需求即揭示 [ICON_Resource_Iron] 铁资源，
	("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_PAX_BRITANNICA_EXPANSION2_DESCRIPTION",      "在新大陆（非首都所在大陆）建造首座城市时免费获得1个近战单位与1条 [ICON_TRADEROUTE] 贸易路线容量。建造“皇家海军船坞”后，获得可生产的最强海军单位。招募 [ICON_GREATGENERAL] 海军统帅时，获得一个对应时代的 [ICON_TECHBOOSTED] 尤里卡。研究“军事学”科技后，获得特色单位“红衫军”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_RELIGIOUS_CONVERT_DESCRIPTION",                "无法获得大预言家，或创建宗教。首次建成姆班赞后，激活“神学”、“王权神授”和“归正会”市政 [ICON_CivicBoosted] 鼓舞。获得额外50% [ICON_GREATWRITER] 大作家、[ICON_GREATARTIST] 大艺术家、[ICON_GREATMUSICIAN] 大音乐家和 [ICON_GREATMERCHANT] 大商人点数。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_NKISI_DESCRIPTION",                      "所有陆地单位无视森林和雨林对 [ICON_MOVEMENT] 移动力的减益。每个 [ICON_GreatWork_Relic] 遗物、[ICON_GreatWork_Artifact] 文物、[ICON_GreatWork_Portrait] 肖像、[ICON_GreatWork_Landscape] 风景、[ICON_GreatWork_Religious] 宗教、 [ICON_GreatWork_Sculpture] 雕塑艺术和 [ICON_GREATWORK_MUSIC] 音乐巨作中获得+4 [ICON_Food] 食物、+4 [ICON_Production] 生产力；每个 [ICON_GreatWork_Writing] 巨著提供+2 [ICON_Food] 食物、+2 [ICON_Production] 生产力。宫殿有5个巨作槽位。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_BABYLON_NAME",                    		 "新月沃土"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",                    "每个专业化区域给没有该区域的城市提供对应产出（港口提供 [ICON_FOOD] 食物，市政广场提供 [ICON_CULTURE] 文化值，娱乐中心和水上乐园提供 [ICON_GOLD] 金币）：这些城市每有一个专业化区域+1点。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HAMMURABI_NAME",                    	 		 "汉谟拉比法典"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FLYING_SQUADRON_NAME",                         "舍农索城堡"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_HAMMURABI_XP1_DESCRIPTION",                    "[ICON_TECHBOOSTED] 尤里卡提供科技的94%的 [ICON_SCIENCE] 科技值。每回合的 [ICON_SCIENCE] 科技值-50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAYAB_DESCRIPTION",                      "在淡水和海岸旁定居时不提供额外 [ICON_HOUSING] 住房。但农场提供额外+1 [ICON_HOUSING] 住房和+1 [ICON_GOLD] 金币，且每与一座天文台相邻则+1 [ICON_Production] 生产力。每有一个奢侈品与市中心相邻，则+1 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MUTAL_DESCRIPTION",                            "揭示出生点6个单元格内的单元格。[ICON_Capital] 首都6个单元格范围内城市所有产出+10%，且建成时将获得1名建造者。[ICON_Capital] 首都9个单元格范围内6个单元格外的非首都城市所有产出不变。其他非首都城市所有产出-15%。[ICON_Capital] 首都6个单元格范围内的单位+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_TRAJANS_COLUMN_DESCRIPTION",                   "所有城市建立时赠送纪念碑。[NEWLINE]建造市中心建筑时+100%建造速度。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAORI_MANA_DESCRIPTION",                 "游戏初始便解锁“航海术”与“造船术”科技，同时拥有进入海洋单元格的能力。水运单位+2 [ICON_Movement] 移动力。未改良的树林与雨林提供+1 [ICON_PRODUCTION] 生产力。“行政部门”额外提供+1 [ICON_PRODUCTION] 生产力、“重商主义”额外提供+1 [ICON_PRODUCTION] 生产力、“保护地球”额外+1 [ICON_PRODUCTION] 生产力、“环境保护主义”额外提供+1 [ICON_PRODUCTION] 生产力。渔船提供+1 [ICON_FOOD] 食物，并向相邻单元格投放文化炸弹。无法获得 [ICON_GreatWriter] 大作家。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_ITERU_EXPANSION2_DESCRIPTION",           "学院和剧院广场与河流相邻获得大量相邻加成。在相邻河流单元格建造区域与奇观时+15%建造速度。境内不会受到洪水的损害。每完成一个奇观，获得一个免费的建造者。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MEDITERRANEAN_EXPANSION2_DESCRIPTION",         "您通往其他文明的 [ICON_TradeRoute] 贸易路线为埃及+8 [ICON_Gold] 金币。其他文明通往埃及的 [ICON_TradeRoute] 贸易路线能为其+4 [ICON_Food] 食物、为埃及+4 [ICON_Gold] 金币。与盟友进行贸易可获得双倍同盟点数。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LAST_PROPHET_DESCRIPTION",               "当倒数第二个 [ICON_GreatProphet] 预言家被招募后（如果您尚未获得 [ICON_GreatProphet] 大预言家），自动获得最后一个大预言家。每座信奉阿拉伯宗教的外国城市+4 [ICON_Science] 科技值。"), --获得 [ICON_GreatProphet] 大预言家或创立宗教时获得一个免费的使徒。
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MENELIK_DESCRIPTION",                          "获得等同于建在丘陵上的城市所产生 [ICON_FAITH] 信仰值15%的 [ICON_SCIENCE] 科技值和 [ICON_CULTURE] 文化值。单位在丘陵上时+4 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",                    "所有区域（除市中心外）不移除树林、雨林、沼泽地貌。建在这些区域中的建筑以及区域本体和奇观将获得以下收益：建在树林上提供+2 [ICON_Production] 生产力、建在雨林上提供+2 [ICON_Food] 食物、建在沼泽上提供+2 [ICON_Science] 科技值。拥有“神秘主义”市政后即可栽种树林。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GAUL_DESCRIPTION",                       "矿山为所有区域提供少量相邻加成、对无主领土施放文化炸弹，并+1 [ICON_CULTURE] 文化值。专业化区域与其他区域相邻时不会获得少量相邻加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_DESCRIPTION",                 "由你建立的拥有U型港的城市，可进行“迁都”项目将原始 [ICON_Capital] 首都更改。与 [ICON_Capital] 首都在同一大陆的海岸城市忠诚度固定为100。建成市政广场或市政广场建筑、外交区或外交区建筑时皆+1 [ICON_TradeRoute] 贸易路线容量。拥有市政广场或外交区的城市建造区域时+50% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES_DESCRIPTION",     "游戏开始时获得“写作”科技 [ICON_TechBoosted] 的尤里卡和“对外贸易”市政 [ICON_CivicBoosted] 的鼓舞。开拓者上船和下船无需额外花费 [ICON_Movement] 移动力，上船后+2[ICON_Movement] 移动力和视野。国际 [ICON_TradeRoute] 贸易路线+2 [ICON_CULTURE] 文化，若目的地为你宗主的城邦则该加成变为3倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FIRST_EMPEROR_NAME",                           "千古一帝"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FIRST_EMPEROR_EXPANSION2_DESCRIPTION",         "建造远古和古典奇观时，可消耗建造者次数来加速奇观原始建造进程的15%。建造者获得+1使用次数和+1 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_NAME",                    "劳动人民的智慧"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION",  "每当建造者减少一次使用次数，获得6点 [ICON_Science] 科技值。[ICON_TechBoosted] 尤里卡和 [ICON_CivicBoosted] 鼓舞额外提升（对应科技或人文所需的科技或文化总量的）10%。建成奇观时将获得奇观所处时代的一项随机 [ICON_TechBoosted] 尤里卡和 [ICON_CivicBoosted] 鼓舞（如可用）。解锁“砌砖”科技的同时也解锁“运河”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_RAVEN_KING_DESCRIPTION",                       "征集单位+2 [ICON_Movement] 移动力、+5 [ICON_Strength] 战斗力。升级征集单位所花费的 [ICON_GOLD] 金币和资源减少50%。征集城邦军队时可在该城邦增加2名 [ICON_ENVOY] 使者。研究“城堡”科技后获得特色单位“黑军”。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_SATRAPIES_DESCRIPTION",                  "拥有“政治哲学”市政后，+1 [ICON_TradeRoute] 贸易路线容量，获得一个 [ICON_Governor] 总督头衔。国内 [ICON_TRADEROUTE] 贸易路线+2 [ICON_Gold] 金币、+2 [ICON_Culture] 文化值。本国领土中的道路提升一个等级。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FALL_BABYLON_EXPANSION2_DESCRIPTION",          "对主要文明宣布突袭战争后的10回合内+2 [ICON_Movement] 移动力。拥有驻扎单位的城市每回合的忠诚度+5。宣布突袭战争的 [ICON_STAT_GRIEVANCE] 不满和好战性与正式战争相同。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_BANNOCKBURN_DESCRIPTION",                      "国境内的单位防御时+4 [ICON_Strength] 战斗力。解锁后勤补给市政后即可宣布解放战争。宣布解放战争后的10回合内+100% [ICON_Production] 生产力、+2 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT_DESCRIPTION",     "幸福度为快乐的城市额外+6% [ICON_SCIENCE] 科技值、+6% [ICON_PRODUCTION] 生产力。快乐的城市中每个学院+2 [ICON_GreatScientist] 大科学家点数、每个工业区+2 [ICON_GreatEngineer] 大工程师点数。喜悦的城市获得的上述加成将加倍，欣喜若狂的城市获得的上述加成将变为三倍。学院和工业区+1 [ICON_AMENITIES] 宜居度，且从其他区域获得标准的相邻加成取代少量相邻加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_RELIGION_CITY_STATES_DESCRIPTION",             "派遣使者到主流宗教与你相同的城邦时，每名 [ICON_ENVOY] 使者将视为2名。战斗胜利时，获得被击杀单位战斗力100%的 [ICON_FAITH] 信仰值。宣布保卫城邦战争后的10回合内+100% [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION",          "首次进入黄金或英雄时代时获得一个永久的通配符政策槽位。进入黄金或英雄时代后，可以使用黑暗时代政策。黄金和英雄时代着力点额外获得普通时代的得分加成。所有城墙+100%建造速度。每级城墙+1 [ICON_CULTURE] 文化值和+1 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GREAT_MOUNTAINS_DESCRIPTION",            "公民可在山脉单元格上工作。山脉单元格提供+3 [ICON_PRODUCTION] 生产力。山脉单元格购买费用降低50%。水渠给所在城市的梯田农场+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_PACHACUTI_QHAPAQ_NAN_DESCRIPTION",             "所有陆地单位无视丘陵对 [ICON_MOVEMENT] 移动力的减益。起始城市中的每座山脉单元格为国内 [ICON_TradeRoute] 贸易路线提供+1 [ICON_Food] 食物。解锁“对外贸易”市政后可获得印加路网改良设施。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_AMAZON_DESCRIPTION",                     "雨林单元格为学院、商业中心、圣地和剧院广场区域提供+1相邻加成，并为相邻的单元格提供+1魅力（而非通常的-1。）伐木场为相邻工业区提供+1相邻加成。若相邻工业区，雨林单元格 +1 [ICON_PRODUCTION] 生产力。建造在雨林的伐木场 +2 [ICON_CULTURE] 文化。所有区域（除市中心外）不移除雨林。若市中心相邻雨林，+1 [Icon_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MAGNANIMOUS_DESCRIPTION",                      "招募或赞助一位 [ICON_GreatPerson] 伟人后，将返还所消耗 [ICON_GreatPerson] 伟人点数的20%。每招募2名伟人，您国境内的所有雨林单元格+1 [Icon_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_TREASURE_FLEET_EXPANSION2_DESCRIPTION",  "解锁“探索”和“重商主义”后（而非“民族主义”和“殖民主义”）即可组建舰队和无敌舰队。[ICON_TradeRoute] 贸易路线+3 [ICON_Gold] 金币、+2 [ICON_Faith] 信仰值、+1 [ICON_Production] 生产力。如 [ICON_TradeRoute] 贸易路线横跨多个大陆，则这些数值将乘以3倍。如城市处于非原始首都所在大陆，其建成时将获得1名建造者，建造区域时+25% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_TA_SETI_DESCRIPTION",                    "生产远程单位时+30% [ICON_Production] 生产力。所有远程单位战斗经验值+50%。加成和奢侈资源矿产提供+2 [ICON_gold] 金币，战略资源矿产提供+1 [ICON_Production] 生产力。城市中每一种改良的加成和奢侈矿产资源为城市+10% [ICON_gold] 金币。城市中每一种改良的战略矿产资源为城市+10% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_KANDAKE_OF_MEROE_DESCRIPTION",                 "所有城市建造区域时+20%建造速度，市中心相邻努比亚金字塔时此加成提高至40%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_NAME",                      "鲜花战争"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GIFTS_FOR_TLATOANI_DESCRIPTION",               "所有近战类型的单位有几率把其他文明的军事单位转化为建造者并俘获。允许将建造者进行活人献祭，将移除目标单位，且其每有一次剩余劳动力获得10点 [ICON_Culture] 文化值和 10点 [ICON_Faith] 信仰值。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS_NAME",                  "太阳纪"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS_DESCRIPTION",           "使用建造者劳动力来推进20%的区域建设进程。其领土中的奢侈品资源为额外2座城市提供1点 [ICON_Amenities] 宜居度。阿兹特克国土内每种改良的奢侈品资源将为军事单位+1 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_FLYING_SQUADRON_DESCRIPTION",                  "解锁“城堡”科技、“政治哲学”和“后勤补给”市政各获得1个免费间谍容量和1个免费间谍。所有间谍初始便拥有1次免费升级。平民单位和侦察单位+1视野范围，间谍+3视野范围。[ICON_VISLIMITED] 外交能见度比遇到的其他文明高1级。"), -- （若已能升级则可在升级后再升级一次）
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MAGNIFICENCES_DESCRIPTION",                    "与剧院广场区域或城堡庄园相邻的改良奢侈品资源提供的 [ICON_CULTURE] 文化值+2。可在拥有剧院广场区域的任意城市中开展“宫廷盛会”项目。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SATYAGRAHA_DESCRIPTION",                       "与主要文明处于和平时所有城市+15%余粮，15% [ICON_Faith]信仰且+1点 [ICON_AMENITIES] 宜居度。所遇到的文明（包括印度）已创建了宗教且不在战争状态，均会+5信仰值 [ICON_Faith] 。与甘地交战的文明获得双倍厌战情绪。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_DHARMA_EXPANSION2_DESCRIPTION",          "从城市中的每个宗教（其须拥有至少1个信徒）获得信徒信仰加成。城市从每个宗教（须有至少1个信徒）获得1点 [ICON_Amenities] 宜居度。传教士的传播次数+2。来自 [ICON_TradeRoute] 贸易路线的宗教压力+100%。拥有梯井的城市每人口+0.5食物 [ICON_Food] 。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_ARTHASHASTRA_DESCRIPTION",                     "完成“军事传统”市政后解锁领土扩张战争借口。完成“军事训练”市政后在首都获得一个免费开拓者。宣布领土扩张战争后的10回合内所有单位+2[ICON_MOVEMENT]移动力，+5[ICON_STRENGTH]战斗力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_NAME",                  "昭昭天命"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION","当前政体的所有外交政策槽均转为通配符槽位。其政体中每个通配符政策槽位每回合提供+1 [ICON_Favor] 外交支持。平原、平原丘陵、草原、草原丘陵单元格的购买费用降低50%。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME_DESCRIPTION",          "所有您创建或攻占的城市一开始便拥有贸易站。如果位于您 [ICON_Capital] 首都的 [ICON_TradeRoute] 贸易路线范围内，城市自动建立一条通至罗马的路。您的国内 [ICON_TradeRoute] 贸易路线经过您的城市贸易站时额外+1 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_CREE_TRADE_GAIN_TILES_DESCRIPTION",      "拥有制陶术科技后，+1 [ICON_TradeRoute] 贸易路线容量，获得1个免费商人。拥有国家劳动力市政后，+1 [ICON_TradeRoute] 贸易路线容量，获得1个免费商人。商人首次进入克里城市3个单元格内的无主单元格后，这些单元格将划入克里领土中。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_DIVINE_WIND_EXPANSION2_DESCRIPTION",           "陆地单位处于相邻海岸的陆地单元格时+5 [ICON_Strength] 战斗力；浅水单元格上的海军单位+5 [ICON_Strength] 战斗力。建造港口、圣地和剧院广场+50% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_ADJACENT_DISTRICTS_DESCRIPTION",         "区域与区域相邻时额外获得标准相邻加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MONGOLIAN_ORTOO_DESCRIPTION",           "创建 [ICON_TRADEROUTE] 贸易路线后， [ICON_TRADINGPOST] 贸易站将立刻出现在目标城市。您的 [ICON_TRADEROUTE] 贸易路线每经过一个您的 [ICON_TRADINGPOST] 贸易站便+1 [ICON_SCIENCE] 科技值。每在一个文明的任意城市中拥有1座您的 [ICON_TRADINGPOST] 贸易站后，您对其的 [ICON_VISLIMITED] 外交能见度则上升1级。您从 [ICON_VISLIMITED] 外交能见度获得的 [ICON_STRENGTH] 战斗力加成翻倍。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_GENGHIS_KHAN_ABILITY_DESCRIPTION",            "牧场给圣地和商业中心提供标准相邻加成。所有骑兵类单位 [ICON_STRENGTH] 战斗力+3，击败敌方骑兵类单位后有几率将其俘获。"),
    ("zh_Hans_CN",  "LOC_GENGHIS_KHAN_PASTURE_HOLY_SITE",                           "+{1_num} [ICON_FAITH] 信仰来自相邻牧场{1_Num : plural 1?单元格; other?单元格;}。"),
    ("zh_Hans_CN",  "LOC_GENGHIS_KHAN_PASTURE_COMMERCIAL_HUB",                      "+{1_num} [ICON_GOLD] 金币来自相邻牧场{1_Num : plural 1?单元格; other?单元格;}。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_ZULU_ISIBONGO_DESCRIPTION",             "拥有驻军单位的城市 +1 [ICON_CULTURE] 文化值。拥有驻军单位的城市每回合忠诚度+3；如驻扎有军团或军队，则+5。解锁相应的市政或科技后，用单位占领城市则可将其升级为军团或军队。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_CAESAR_DESCRIPTION",      			       "建立或征服城市时+200 [ICON_GOLD] 金币。清除蛮族哨站时+100 [ICON_GOLD] 金币。征服一个城市后，所有3个单元格内的单位永久获得+1 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_CAESAR_STRENGTH_MODIFIER",      			     		  "+{1_Amount}力来自已征服的城市。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LINCOLN_EXPANSION_DESCRIPTION",               "工业区+2 [ICON_Amenities] 宜居度。建造工业区后获得一个免费的建造者。允许在工业区解放建造者，为该工业区提供+2 [ICON_PRODUCTION] 生产力相邻加成，如果在本城第一次进行解放，+1 [ICON_CITIZEN] 人口。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SALADIN_ALT_DESCRIPTION",                     "为所有战斗和宗教单位+100%夹击和支援加成。所有单位在信仰你宗教的城市开始一个回合，会获得1 [ICON_MOVEMENT] 移动力加成。宗教单位无视区域控制效果。"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_LIBERATION_LINCOLN_NAME",                      "解放"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_LIBERATION_LINCOLN_DESCRIPTION",               "解放此单位，为该工业区提供+2 [ICON_PRODUCTION] 生产力相邻加成，如果在本城第一次进行解放，+1 [ICON_CITIZEN] 人口。"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_LIBERATION_LINCOLN_DISABLED_TT",               "必须位于工业区，且有剩余 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_SULEIMAN_ALT_DESCRIPTION",                    "在每个时代额外获得所有着力点加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_NADER_SHAH_DESCRIPTION",                      "进攻满生命值的单位或城市时+7 [ICON_STRENGTH] 战斗力。占领城市时摧毁其所有区域和建筑，并根据区域类型或建筑的前置区域类型获得等同于其基础 [ICON_PRODUCTION] 生产力消耗的产出：学院、军营和工业区提供 [ICON_SCIENCE] 科技值，圣地，剧院广场，娱乐中心和水上乐园提供 [ICON_CULTURE] 文化值，其余区域提供4倍 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_ABILITY_NADER_SHAH_COMBAT_DESCRIPTION",                      "进攻满生命值的单位或城市时+7 [ICON_Strength] 战斗力。（纳迪尔沙阿）"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_NAME",                    "大地的子民"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAPUCHE_TOQUI_DESCRIPTION",             "所有靠山的区域（不包含奇观）+1 [ICON_FOOD] 食物和+1 [ICON_FAITH] 信仰值，相邻山脉单元格的改良设施+1 [ICON_FOOD] 食物和+1 [ICON_FAITH] 信仰值。单位如果相邻山脉单元格开始一个回合，会获得1 [ICON_MOVEMENT] 移动力加成。"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_LAUTARO_ABILITY_DESCRIPTION_ALT",             "与自由城市或处在黄金/英雄时代中的文明作战时+5 [ICON_STRENGTH] 战斗力。[ICON_GOVERNOR] 总督就职城市中生产的所有单位的战斗经验值+50%。"),
    ("zh_Hans_CN",  "LOC_ABILITY_TOQUI_XP_FROM_GOVERNOR_DESCRIPTION",               "获得的战斗经验值+50%。（迅捷之鹰）"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_PORTUGAL_NAME",                         "东印度之家"),
    ("zh_Hans_CN",  "LOC_PEDIA_LEADERS_PAGE_LEADER_TOKUGAWA_CHAPTER_DETAILED_BODY", "“大化改新”能力可以为日本区域带来大量相邻加成。德川家康的特色能力是提高了每个区域从国内 [ICON_TradeRoute] 贸易路线获得的收益。但要注意，国际 [ICON_TradeRoute] 贸易路线较为孱弱。“电子厂”将帮助他迈向文化或科技胜利。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_ADJACENT_DISTRICTS_NAME",               "大化改新"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_DIVINE_WIND_NAME",                            "镰仓幕府"),
    ("zh_Hans_CN",  "LOC_TRAIT_LEADER_TOKUGAWA_XP_DESCRIPTION",                     "国际 [ICON_TradeRoute] 贸易路线的产出和旅游业绩-25%；目的地城市中每有一个特色区域，国内 [ICON_TradeRoute] 贸易路线便提供+1 [ICON_Culture] 文化值、+1 [ICON_Science] 科技值和+2 [ICON_Gold] 金币。");
--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                             Text)
values
    ("LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC",         "Sweden gains 50 [ICON_Favor] Diplomatic Favor when earning a Great Person (on Standard Speed). Sweden receives +2 [ICON_GreatEngineer] Great Engineer point from Level 2 Industrial Zone buildings and +2 [ICON_GreatScientist] Great Scientist point from Level 2 Campus buildings. Having Sweden in the game adds three unique World Congress competitions starting in the Industrial Era."),
    ("LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_NAME",                    "The Country of Windmills"),
    ("LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_EXPANSION2_DESCRIPTION",  "Culture Bomb adjacent tiles when completing a Harbor. +20% [ICON_Production] Production toward Districts in cities with a Harbor district. +50% construction speed toward the Dam district, Shipyard and Seawall buildings. Tiles next to a River provide +1 [ICON_PRODUCTION] Production for each Dam district owned by the City."),--When completing naval units (rather than purchasing or gaining them for free) in cities with a Shipyard, gains [ICON_Gold] Gold equal to the unit’s cost (doubles when the city also has a Bank).
    ("LOC_TRAIT_RADIO_ORANJE_DESCRIPTION",                            "Shipyard provides +1 [ICON_TradeRoute] Trade Route capacity. Each international [ICON_TradeRoute] Trade Route to or from your city provide +2 [ICON_SCIENCE] Science for you, doubled if you are in Dark Ages.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                             Text)
values
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC",         "每次获得一位 [ICON_GreatPerson] 伟人可奖励50点 [ICON_Favor] 外交支持（标准速度下）。二级工业区建筑与二级学院建筑分别提供+2 [ICON_GreatEngineer] 大工程师点数与+2 [ICON_GreatScientist] 大科学家点数。若对局中存在该文明，则进入工业时代后将增加3项特色世界议会竞赛。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_NAME",                    "风车之国"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_EXPANSION2_DESCRIPTION",  "建成港口后可对相邻单元格施放文化炸弹。在拥有港口的城市中建造区域时+20% [ICON_Production] 生产力。建造堤坝区域和拦海堤建筑时加速50%。堤坝为所在城市的沿河单元格+1 [ICON_Production] 生产力。"),--在拥有造船厂的城市生产出海军单位时（而非购买或赠送得到），获得等同于该单位成本的 [ICON_Gold] 金币，若该城市还拥有银行，则该效果翻倍。
    ("zh_Hans_CN",  "LOC_TRAIT_RADIO_ORANJE_DESCRIPTION",                            "造船厂提供+1 [ICON_TradeRoute] 贸易路线容量。您通往其他文明的 [ICON_TRADEROUTE] 贸易路线为荷兰+2 [ICON_SCIENCE] 科技值。其他文明通往荷兰的 [ICON_TRADEROUTE] 贸易路线能为荷兰+2 [ICON_SCIENCE] 科技值。如您处于黑暗时代，则这些数值将乘以2倍。");

--腓尼基文本更改
insert or replace into LocalizedText
    (Language,      Tag,                                                    Text)
select
    "zh_Hans_CN",   "LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_DESCRIPTION",        "由你建立的拥有U型港的城市，可进行“迁都”项目将原始 [ICON_Capital] 首都更改。与 [ICON_Capital] 首都在同一大陆的海岸城市忠诚度固定为100。建成市政广场或市政广场建筑、外交区或外交区建筑时皆+1 [ICON_TradeRoute] 贸易路线容量。拥有市政广场或外交区的城市建造区域时+50% [ICON_Production] 生产力。"
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');
insert or replace into EnglishText
    (Tag,                                                  Text)
select
    "LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_DESCRIPTION",       "Cities (founded by you) with a Cothon gain the unique Move Capital project, which moves the Phoenician [ICON_Capital] Capital to that city. Coastal cities founded by Phoenicia and located on the same continent as the Phoenician [ICON_Capital] Capital are 100% Loyal.Gains +1 [ICON_TradeRoute] Trade Route capacity after building the Government Plaza or any Government Plaza building, Diplomatic Quarter or any Diplomatic Quarter building. +50% [ICON_Production] Production towards [ICON_District] Districts in the city with Government Plaza or Diplomatic Quarter."
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');
--------------------------------------------------------------------------------

--美国文本更改
insert or replace into LocalizedText
    (Language,      Tag,                                                                     Text)
select
    "zh_Hans_CN",   "LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION",        "当前政体的所有外交政策槽均转为通配符槽位。其政体中每个通配符政策槽位每回合提供+1 [ICON_Favor] 外交支持。平原、平原丘陵、草原、草原丘陵单元格的购买费用降低50%。建成外交区或外交区建筑时皆+1间谍容量。"
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');
insert or replace into EnglishText
    (Tag,                                                                   Text)
select
    "LOC_TRAIT_CIVILIZATION_FOUNDING_FATHERS_EXPANSION2_DESCRIPTION",       "All Diplomatic policy slots in the current government are converted to Wildcard slots. +1 [ICON_Favor] Diplomatic Favor per turn for every Wildcard slot in their government. Reduces the purchase cost of tiles in Grass, Grass Hills, Plains and Plains Hills by 50%.Gains +1 spy capacity after building Diplomatic Quarter or any Diplomatic Quarter building."),
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');
--------------------------------------------------------------------------------
insert or replace into EnglishText
    (Tag,                                                  		Text)
select
	"LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",				"Your Specialty districts provide +1 of the corresponding yield (Harbor provides [ICON_FOOD] Food, Government Plaza provides [ICON_CULTURE] Culture, Dipomatic Quater provides Influence Point, Entertainment Complex and Water Park provides [ICON_GOLD] Gold) to every Specialty district in cities without the same district."
where exists (select Tag from LocalizedText where Tag = 'LOC_DISTRICT_DIPLOMATIC_QUARTER_NAME');

insert or replace into LocalizedText
    (Language,		Tag,                                            	Text)
select
	"zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION",		"每个专业化区域给没有该区域的城市提供对应产出（港口提供 [ICON_FOOD] 食物，市政广场提供 [ICON_CULTURE] 文化值，外交区提供影响力点数，娱乐中心和水上乐园提供 [ICON_GOLD] 金币）：这些城市每有一个专业化区域+1点。"
where exists (select Tag from LocalizedText where Tag = 'LOC_DISTRICT_DIPLOMATIC_QUARTER_NAME');