--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                     Text)
values
    ("LOC_BUILDING_MEENAKSHI_TEMPLE_DESCRIPTION",             "Grants 2 Gurus. Holy Site districts provide +2 [ICON_FOOD] Food. Buildings in Holy Site district provide +4 [ICON_FOOD] Food. Allows your Cities to purchase Builders and Settlers using [ICON_Faith] Faith. Must be built adjacent to a Holy Site and you must have founded a Religion."), --Holy Site provides +1 [ICON_Food] Food 
    ("LOC_BUILDING_PANAMA_CANAL_DESCRIPTION",                 "1 free [Icon_GreatMerchant] Great Merchant appears near the city where the wonder was built. Upon completion 1 or 2 adjacent Canal districts are automatically constructed. The Canal wonder tile can now be crossed by naval units. [ICON_TradeRoute] Trade Routes traveling through it can multiply the [ICON_Gold] Gold they get from districts at their destination.[NEWLINE][NEWLINE]Must be built on a flat land tile where there are two adjacent tiles directly across the build tile from one another that meet the following criteria: one adjacent tile must be able to legally hold a Canal district connecting into the Panama Canal construction tile; the other must be either a city, a water tile, or be another tile that can hold a connecting Canal."),
    ("LOC_BUILDING_OXFORD_UNIVERSITY_DESCRIPTION",            "+20% [ICON_Science] Science in this city, and awards 2 randomly-chosen free technologies when completed. Themed when displaying [ICON_GreatWork_Writing] Great Work of Writing from different Writers. Must be built on Grassland or Plains adjacent to a Campus district with a University."),
    ("LOC_BUILDING_KILWA_KISIWANI_DESCRIPTION",               "+3 [ICON_ENVOY] Envoys when built. When you are the Suzerain of a City-State this city receives a +15% boost to the Type bonuses provided by that City-State. If you are the Suzerain to 2 or more City-States of that type this city receives an additional +15% boost to the Type bonuses provided by those City-States. Must be built on a flat tile adjacent to Coast."),
    ("LOC_BUILDING_TERRACOTTA_ARMY_DESCRIPTION",              "All current units gain +30 experience. All Archaeologists from the owner may enter foreign lands without Open Borders, and ignore [ICON_MOVEMENT] movement penalty from Hills, Woods and Rainforest. Must be built on flat Grassland or Plains adjacent to an Encampment district with a Barracks or Stable."),
    ("LOC_BUILDING_RUHR_VALLEY_DESCRIPTION",                  "+20% [ICON_Production] Production in this city, and Mines and Quarries in this City provide +2 [ICON_Production] Production. International [ICON_TradeRoute] Trade Route to this city provides +3 [ICON_Production] Production for both sides. Domestic [ICON_TradeRoute] Trade Route to this City provides +5 [ICON_Production] Production. Must be built adjacent to an Industrial Zone district with a Factory, and next to a River."),
    ("LOC_BUILDING_SYDNEY_OPERA_HOUSE_DESCRIPTION",           "Must be built on the Coast, adjacent to land and a Harbor district. Great works and Wonders provide +100% [Icon_Tourism] Tourism (extra 100% [Icon_Tourism] Tourism for [ICON_GreatWork_MUSIC] Music) if this city has [ICON_Governor] Governor established and is founded by you. Themed when displaying [ICON_GreatWork_MUSIC] Great Works of Music from the same Era."),
    ("LOC_BUILDING_HERMITAGE_DESCRIPTION",                    "+50% Production speed towards all buildings in Theater Square. Themed when displaying Great Works of the same Era, with doubled theming bonus. Artifacts in cities within 9 tiles provide +200% [ICON_TOURISM] Tourism."),
    ("LOC_BUILDING_FORBIDDEN_CITY_DESCRIPTION",               "+1 Wildcard policy slot. Themed when displaying Great Works of the same type.[NEWLINE][NEWLINE]Must be built on flat land adjacent to the City Center."),
    ("LOC_BUILDING_THEMINGBONUS_FORBIDDEN_CITY",              "Theming bonus doubling output when displaying objects of the same kind."),
    ("LOC_BUILDING_PETRA_DESCRIPTION",                        "+3 [ICON_Food] Food, +2 [ICON_Gold] Gold, and +1 [ICON_Production] Production to all non-Floodplains Desert tiles for this City. Must be built on flat Desert, Desert (Mountain), or Desert Floodplains."),
    ("LOC_BUILDING_ST_BASILS_CATHEDRAL_DESCRIPTION",          "+100% [ICON_Tourism] Religious Tourism from this city. +2 [ICON_Food] Food, +1 [ICON_Production] Production, and +1 [ICON_Culture] Culture on all Tundra tiles for this city. Must be built adjacent to a City Center."),
    ("LOC_BUILDING_CHICHEN_ITZA_DESCRIPTION",                 "+1 [ICON_Food] Food, +2 [ICON_Culture] Culture, +1 [ICON_Production] Production to all Rainforest tiles for this city. Your Cities yield +10% [ICON_Faith] Faith in [ICON_GLORY_GOLDEN_AGE] Golden Age, and +10% [ICON_Production] Production otherwise. Must be built on Rainforest."),
    ("LOC_BUILDING_ORACLE_DESCRIPTION",                       "Patronage of Great People costs 25% less [ICON_Faith] Faith. Districts in this city provide +6 [ICON_GreatPerson] Great Person points of their type (for example, [ICON_GreatWriter] Great Writer points from the Theater Square district). Must be built on Hills or Mountains."),
    ("LOC_BUILDING_TEMPLE_ARTEMIS_DESCRIPTION",               "Each Camp over Resource, Pasture, and Plantation improvements within 4 tiles of this Wonder provides +1 [ICON_AMENITIES] Amenity. Must be placed adjacent to a Camp improvement."),
    ("LOC_BUILDING_MAHABODHI_TEMPLE_EXPANSION2_DESCRIPTION",  "Grants 2 Apostles when built. -10% [ICON_FAITH] Faith cost when purchasing Apostle in this city.[NEWLINE][NEWLINE]Must be built on Woods adjacent to a Holy Site district with a Temple, and you must have founded a Religion."),
    ("LOC_BUILDING_ORSZAGHAZ_DESCRIPTION",                    "+2 Diplomatic Victory Points and +4 [ICON_ENVOY] Envoys when built. Doubles the effect of each Wildcard Policy in your government. Receive +100% [ICON_Favor] Diplomatic Favor per turn from starting a turn as Suzerain of a City-State.[NEWLINE][NEWLINE]Must be built next to a River."),
    ("LOC_BUILDING_STATUE_OF_ZEUS_DESCRIPTION",               "Monuments provide +1 Influence point per turn. Must be built adjacent to a Theater district. Must be built next to a River."),
    ("LOC_BUILDING_GREAT_LIBRARY_DESCRIPTION",                "Receive boosts to all Ancient and Classical era technologies. [ICON_TechBoosted] Eurekas provide +3% [ICON_SCIENCE] Science after finishing this Wonder (Ancient and Classical Techs excluded). Receive a random tech boost after another player recruits a [ICON_GreatScientist] Great Scientist. [NEWLINE][NEWLINE]Must be built on flat land adjacent to a Campus district with a Library."),
    ("LOC_BUILDING_GREAT_LIGHTHOUSE_DESCRIPTION",             "+1 [ICON_Movement] Movement for all Naval and Embarked units. Grants a free Great Admiral. [NEWLINE][NEWLINE]Must be built on the Coast, and adjacent to land and a Harbor district with a Lighthouse."),
    ("LOC_BUILDING_GREAT_ZIMBABWE_DESCRIPTION",               "+1 [ICON_TradeRoute] Trade Route capacity[NEWLINE][NEWLINE]Your [ICON_TradeRoute] Trade Routes from this city get +3 [ICON_Gold] Gold for every Bonus resource within 3 tiles of the city and in this city's territory. [NEWLINE][NEWLINE] Must be built adjacent to a Commercial Hub district with a Market and adjacent to [ICON_RESOURCE_CATTLE] Cattle."),
    ("LOC_BUILDING_BROADWAY_DESCRIPTION",                     "+30% [ICON_Culture] Culture in this city. 1 free random Atomic era civic boost. Grants 1 free [ICON_GreatMusician] Great Musician. Citizens in Cities within 6 tiles provide +1 [ICON_Culture] Culture. +50% [ICON_GreatMusician] Great Musician points you generate.[NEWLINE][NEWLINE]Must be built on flat land adjacent to a Theater Square district."),
    ("LOC_BUILDING_UNIVERSITY_SANKORE_DESCRIPTION",           "+5 [ICON_SCIENCE] Science and +1 [ICON_Faith] Faith to all your Cities within 6 tiles. +1 [ICON_SCIENCE] to all Desert tiles (Desert Floodplains excluded) in this City. Campus gain standard adjacency bonus from Desert and Desert Hill Tiles.[NEWLINE][NEWLINE]Must be built on Desert or Desert Hills adjacent to a Campus district with a University."),
    ("LOC_BUILDING_HAGIA_SOPHIA_DESCRIPTION",                 "Missionaries and Apostles can spread Religion 1 extra time. When you use a religious unit to convert a city for the first time, earn +10 [ICON_FAITH] Faith per [ICON_Citizen] Population of that city (on Standard Speed).[NEWLINE][NEWLINE]Must be built on flat land adjacent to a Holy Site district, and you must have founded a Religion."),
    ("LOC_BUILDING_BIOSPHERE_EXPANSION2_DESCRIPTION",         "Offshore Windfarms, Solar Farms, Wind Farms, Geothermal Plants, and Hydroelectric Dams provide +400% [ICON_POWER] Power. This building and these improvements provide [ICON_TOURISM] Tourism equal to their [ICON_POWER] Power. Rainforest and Marsh in your empire now provide +1 Appeal to adjacent tiles (rather than -1).[NEWLINE][NEWLINE]Must be built along a River adjacent to a Neighborhood district."),
    ("LOC_BUILDING_KOTOKU_IN_DESCRIPTION",                    "+20% [ICON_Faith] Faith in this city. Grants 4 Warrior Monks with 1 free promotion. All Warrior Monks trained in this city receive 1 free promotion. [NEWLINE][NEWLINE]Must be built adjacent to a Holy Site district with a Temple. Warrior Monks can only be received if player has founded a religion or if there is a majority religion for this player or city."),
    ("LOC_BUILDING_POTALA_PALACE_EXPANSION2_DESCRIPTION",     "+1 Diplomatic policy slot. +1 Diplomatic Victory point. Immediately after construction, increase accumulated [ICON_FAITH] Faith by 50%. [NEWLINE][NEWLINE]Must be built on a Hill or a Mountain tile that adjacent to a Mountain."),
    ("LOC_BUILDING_HANGING_GARDENS_DESCRIPTION",              "+10% [ICON_FOOD] Food in all cities. Must be built next to a River."),
    ("LOC_BUILDING_JEBEL_BARKAL_EXPANSION2_DESCRIPTION",      "Awards 6 [ICON_RESOURCE_IRON] Iron per turn. Provides +4 [ICON_Faith] Faith to all your cities that are within 9 tiles.[NEWLINE][NEWLINE]Must be built on Desert (Hills) terrain."),
    ("LOC_BUILDING_CRISTO_REDENTOR_DESCRIPTION",              "[ICON_Tourism] Tourism output from [ICON_GreatWork_Relic] Relics and Holy Cities is not diminished by other civilizations who have researched The Enlightenment civic. +100% [ICON_Tourism] Tourism from Seaside Resorts across your civilization. Patronage of Great People costs 25% less [ICON_Faith] Faith. [NEWLINE][NEWLINE] Must be built on Hills."),
    ("LOC_BUILDING_HUEY_TEOCALLI_DESCRIPTION",                "+1 [ICON_Amenities] Amenity from entertainment for each Lake tile within one tile of Huey Teocalli. +1 [ICON_Food] Food, +1 [ICON_Production] Production and +1 [ICON_Gold] Gold for each Lake tile in your empire. Must be built on a Lake tile adjacent to land."),
    ("LOC_BUILDING_MACHU_PICCHU_DESCRIPTION",                 "Mountain tiles provide a standard adjacency bonus to Commercial Hub, Theater Square, and Industrial Zone districts in all cities. All Districts (Wonders not included) adjacent to Mountain tiles provide +2 [ICON_FOOD] Food.[NEWLINE][NEWLINE]Must be built on a Mountain tile that does not contain a Volcano."),
    ("LOC_BUILDING_COLOSSUS_DESCRIPTION",                     "+1 [ICON_TradeRoute] Trade Route capacity. Grants a Trader unit. International trade routes from this City provide +2 [ICON_GOLD] Gold for each Fishing Boat owned by this City. [NEWLINE][NEWLINE]Must be built on the Coast, adjacent to land and a Harbor district."),
    ("LOC_BUILDING_TAJ_MAHAL_DESCRIPTION",                    "+1 Era Score from Historic Moment earned after this wonder is complete if that Moment is usually worth 2 or more Era Score. +8 [ICON_GOLD] Gold for all world wonders in your empire. Each time you complete a wonder, gain [ICON_GOLD] Gold equal to 80% of its production cost.[NEWLINE][NEWLINE]Must be built next to a River."),
    ("LOC_BUILDING_TORRE_DE_BELEM_DESCRIPTION",               "International [ICON_TradeRoute] Trade Routes from this city receive +2 [ICON_GOLD] Gold for every Luxury resource at the destination. Grants two Settlers when built. Settlers have +2 [ICON_Movement] Movement. +2 starting [ICON_Citizen] Population for Cities settled on a different continent than your first City. [NEWLINE][NEWLINE]Must be built on a Coast tile adjacent to a Harbor district."),
    ("LOC_BUILDING_THEMINGBONUS_OXFORD_UNIVERSITY",           "Theming bonus doubling output when displaying objects from different writers."),
    ("LOC_BUILDING_THEMINGBONUS_SYDNEY_OPERA_HOUSE",          "Theming bonus doubling output when displaying objects of musicians from the same era."),
    ("LOC_BUILDING_THEMINGBONUS_HERMITAGE",                   "Theming bonus doubling output when displaying objects from the same era."),
    ("LOC_BUILDING_THEMINGBONUS_GOV_CULTURE",                 "Theming bonus doubling output when displaying objects from the same era."),
    ("LOC_BUILDING_THEMINGBONUS_NEUSCHWANSTEIN",              "Theming bonus doubling output when displaying objects from different musicians."),
    ("LOC_BUILDING_THEMINGBONUS_NOTRE_DAME",                  "Theming bonus doubling output when displaying objects from the same era."),
    ("LOC_BUILDING_THEMINGBONUS_UFFIZI",                      "Theming bonus doubling output when displaying objects of the same kind."),
    ("LOC_BUILDING_THEMINGBONUS_DL_STPETERSBASILICA",         "Theming bonus doubling output when all slots are filled."),
    ("LOC_BUILDING_VENETIAN_ARSENAL_DESCRIPTION",             "Receive a second naval unit each time you train a naval unit. +1 [ICON_Production] Production and +1 [ICON_Gold] Gold to Coast tiles in this city. Provide +6 [ICON_RESOURCE_Niter] Niter per turn. Must be built on a Coast tile that is adjacent to an Industrial Zone district."),
    -- ("LOC_BUILDING_APADANA_DESCRIPTION",                      "+2 [ICON_ENVOY] Envoys when you build a wonder, including Apadana, in this city. Each City-State you are Suzerain of provides +2 [ICON_CULTURE] Culture. Must be built adjacent to your [ICON_CAPITAL] Capital."),
    ("LOC_BUILDING_ALHAMBRA_DESCRIPTION",                     "+1 Military policy slot[NEWLINE][NEWLINE]Provides the same defensive bonuses as the Fort improvement. Encampment districts provide +2 Influence points per turn. Must be built on Hills adjacent to an Encampment district."),
    -- ("LOC_BUILDING_CASA_DE_CONTRATACION_DESCRIPTION",         "Gain 2 [ICON_Governor] Governor titles. All your cities not on your original [ICON_Capital] Capital's continent with a [ICON_Governor] Governor gain +15% [ICON_Production] Production, +15% [ICON_Faith] Faith and +15% [ICON_Gold] Gold. Must be built adjacent to a Government Plaza."),
    ("LOC_BUILDING_ESTADIO_DO_MARACANA_DESCRIPTION",          "Citizens working in districts within 9 tiles provide +3 yield of the district's type (+3 [ICON_PRODUCTION] Production for citizens in Encampment districts, +3 [ICON_FOOD] Food for citizens in Harbor districts). +50% [ICON_GREATPERSON] Great Person points in Cities within 9 tiles if this City is fully [ICON_POWER] Powered."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_HOLY_SITE_NAME",                 "[COLOR:ResFaithLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_HOLY_SITE_DESCRIPTION",          "The Holy Site is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [Icon_Faith] Faith."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_CAMPUS_NAME",                    "[COLOR:ResScienceLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_CAMPUS_DESCRIPTION",             "The Campus is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [ICON_Science] Science."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_HARBOR_NAME",                    "[COLOR:ResFoodLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_HARBOR_DESCRIPTION",             "The Harbor is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [ICON_Food] Food."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_ENCAMPMENT_NAME",                "[COLOR:ResProductionLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_ENCAMPMENT_DESCRIPTION",         "The Encampment is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [ICON_Production] Production."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_COMMERCIAL_HUB_NAME",            "[COLOR:ResGoldLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_COMMERCIAL_HUB_DESCRIPTION",     "The Commercial Hub is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [ICON_Gold] Gold."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_THEATER_NAME",                   "[COLOR:ResCultureLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_THEATER_DESCRIPTION",            "The Theater is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [ICON_Culture] Culture."),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_INDUSTRIAL_ZONE_NAME",           "[COLOR:ResProductionLabelCS]Receive extra yields[ENDCOLOR]"),
    ("BUILDING_MARACANA_DUMMY_DISTRICT_INDUSTRIAL_ZONE_DESCRIPTION",    "The Industrial Zone is built in 9 tiles of the Estádio do Maracanã, citizens working in this district provide +3 [ICON_Production] Production."),
    ("LOC_BUILDING_STATUE_LIBERTY_EXPANSION2_DESCRIPTION",              "+4 Diplomatic Victory point. Coastal Cities within 9 tiles receive +4 [ICON_CULTURE] Culture and +4 [ICON_AMENITIES] Amenities. [NEWLINE][NEWLINE]Must be built on a Coast tile, adjacent to land and a Harbor district.");--+1 influence point, for every 100 military strength points you have.

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                                            Text)
values
    ("zh_Hans_CN",  "LOC_BUILDING_MEENAKSHI_TEMPLE_DESCRIPTION",             "获得2名上师。圣地提供 +2 [ICON_FOOD] 食物，每个圣地建筑提供 +4 [ICON_FOOD] 食物。允许您的城市使用 [ICON_Faith] 信仰值购买建造者和开拓者。必须建在圣地旁，同时必须已创立宗教。"), --圣地区域+2 [ICON_Food] 食物。
    ("zh_Hans_CN",  "LOC_BUILDING_PANAMA_CANAL_DESCRIPTION",                 "建成时市中心出现一位 [Icon_GreatMerchant] 大商人。开始修建巴拿马运河时，将在满足条件的相邻单元格自动开始建造1或2个运河，完成巴拿马运河的同时运河也将完成。建成的巴拿马运河将同样被视为运河。[NEWLINE]将巴拿马运河视为水域单元格时，必须有两个相邻巴拿马运河的且关于其对称的单元格满足：两个单元格均可以修建运河；或是一个单元格可以修建运河，一个单元格是城市/水域。如想使用巴拿马运河连接两座城市，那么这两座城市必须有至少一座相邻水域单元格或已经被运河连接至水域单元格。[NEWLINE]必须修建在平坦地形单元格之上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_OXFORD_UNIVERSITY_DESCRIPTION",            "当前城市+20% [ICON_Science] 科技值，完成时，随机奖励2项免费科技。当展示来自不同作家的作品时获得主题化加成。必须建在靠近带有大学的学院区域的草原或平原上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_KILWA_KISIWANI_DESCRIPTION",               "建成后+3 [ICON_ENVOY] 使者。对于每一类城邦，若你是其中至少1个的宗主国，本城中此类城邦对应的产出+15%；若你是其中至少2个的宗主国，本城中此类城邦对应的产出额外+15%。必须建造在与海岸相邻的平坦地形上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TERRACOTTA_ARMY_DESCRIPTION",              "目前所有单位获得30点经验值。所拥有的考古学家无视丘陵、森林和雨林带来的 [ICON_Movement] 移动力减益，且可在没有开放边界的情况下进入外国。必须建在平坦的草原或平原上，且靠近带有兵营或马厩的军营区域。"),
    ("zh_Hans_CN",  "LOC_BUILDING_RUHR_VALLEY_DESCRIPTION",                  "该城市+20% [ICON_Production] 生产力，此城中每个矿山和采石场+2 [ICON_Production] 生产力。通往此城的国际 [ICON_TradeRoute] 商路为双方+3 [ICON_PRODUCTION] 生产力。通往此城的国内 [ICON_TradeRoute] 商路+5 [ICON_PRODUCTION] 生产力。必须沿河而建，且与拥有工厂的工业区区域相邻。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SYDNEY_OPERA_HOUSE_DESCRIPTION",           "必须建在海岸上，且需要靠近陆地和一个港口。所有由玩家创立且有总督就职的城市中，奇观和所有巨作 [Icon_Tourism] 旅游业绩+100%（音乐巨作 [Icon_Tourism] 旅游业绩额外+100%）。当展示来自相同时代音乐家的作品时获得主题化加成。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HERMITAGE_DESCRIPTION",                    "建造剧院建筑时加速50%。当展示来自相同时代的作品时获得主题加成，且主题化的收益翻倍。9个单元格内的城市来自 [ICON_GREATWORK_ARTIFACT] 文物的 [ICON_TOURISM] 旅游业绩+200%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FORBIDDEN_CITY_DESCRIPTION",               "+1 通配符政策槽位。当展示来自相同类型的作品时获得主题加成。[NEWLINE][NEWLINE]必须建在靠近市中心的平地上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_FORBIDDEN_CITY",              "当展示来自相同类型的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_PETRA_DESCRIPTION",                        "为该城市所有沙漠单元格（非泛滥平原）+3 [ICON_Food] 食物，+2 [ICON_Gold] 金币，+1 [ICON_Production] 生产力。必须建在平坦的沙漠，或沙漠泛滥平原，或是沙漠山脉上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ST_BASILS_CATHEDRAL_DESCRIPTION",          "此城市产出的 [ICON_Tourism] 宗教旅游业绩+100%。此城市所有冻土单元格产出的 [ICON_Food] 食物+2、[ICON_Production] 生产力+1、[ICON_Culture] 文化值+1。必须建在市中心旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_CHICHEN_ITZA_DESCRIPTION",                 "该城市所有雨林单元格+1 [ICON_Food] 食物，+2 [ICON_Culture] 文化值，+1 [ICON_Production] 生产力。处于 [ICON_GLORY_GOLDEN_AGE] 黄金时代时，所有城市+10% [ICON_Faith] 信仰，处于 [ICON_GLORY_NORMAL_AGE] 非黄金时代时，所有城市+10% [ICON_Production] 生产力。必须建在雨林。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ORACLE_DESCRIPTION",                       "伟人赞助消耗的 [ICON_Faith] 信仰值减少25%。该城市区域为它们类型的 [ICON_GreatPerson] 伟人点数+6（比如，来自剧院广场区的 [ICON_GreatWriter] 大作家点数）。必须建在丘陵或山脉单元格上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TEMPLE_ARTEMIS_DESCRIPTION",               "此奇观4个单元格内的每个资源营地、牧场和种植园改良设施+1 [ICON_AMENITIES] 宜居度。必须放置在营地改良设施旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MAHABODHI_TEMPLE_EXPANSION2_DESCRIPTION",  "建成后提供2个使徒。本城购买使徒的 [ICON_FAITH] 信仰花费-10%。[NEWLINE][NEWLINE]必须建在与圣地区域（此区域中须建有寺庙）相邻的树林中，前提还须已创立宗教。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ORSZAGHAZ_DESCRIPTION",                    "建成时+2外交胜利点数，+4 [ICON_ENVOY] 使者。政体中每张生效中的通配政策卡效果翻倍。成为一座城邦的宗主国后，每回合从此城邦获得的 [ICON_Favor] 外交支持+100%。[NEWLINE][NEWLINE]必须修建在河边。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STATUE_OF_ZEUS_DESCRIPTION",               "每座纪念碑提供+1影响力点数。必须建造在与剧院广场区域相邻且临近河流的单元格上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GREAT_LIBRARY_DESCRIPTION",                "所有远古和古典时代的科技均获得 [ICON_TechBoosted] 尤里卡。建成后，[ICON_TechBoosted] 尤里卡提供的 [ICON_SCIENCE] 科技值+3%（不包括建成时触发的远古古典 [ICON_TechBoosted] 尤里卡）。其他玩家招募 [ICON_GreatScientist] 大科学家时将随机获得1个 [ICON_TechBoosted] 尤里卡。[NEWLINE][NEWLINE]必须建在与学院区域（其中须建有图书馆）相邻的平坦地面上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GREAT_LIGHTHOUSE_DESCRIPTION",             "所有海军单位和海运单位+1 [ICON_Movement] 移动力。建成时市中心出现一位大提督。[NEWLINE][NEWLINE]必须建在海岸上，且必须与陆地和已有灯塔的港口相邻。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GREAT_ZIMBABWE_DESCRIPTION",               "[ICON_TradeRoute] 贸易路线容量+1。[NEWLINE][NEWLINE]城市领土中3个单元格以内的每个加成资源将为从此城市发源的 [ICON_TradeRoute] 贸易路线+3 [ICON_Gold] 金币。[NEWLINE][NEWLINE]必须建在与商业中心区域（要求拥有市场）和 [ICON_RESOURCE_CATTLE] 牛资源相邻的单元格上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_BROADWAY_DESCRIPTION",                     "为此城+30% [ICON_Culture] 文化值。免费随机获得1个原子能时代市政的鼓舞。建成时市中心出现一位 [ICON_GreatMusician] 大音乐家。6环内的城市每位 [ICON_Citizen] 市民+1 [ICON_Culture] 文化值。玩家 [Icon_GreatMusician] 大音乐家点数的积累速度+50%。[NEWLINE][NEWLINE]必须建在邻近剧院广场区域的平地上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_UNIVERSITY_SANKORE_DESCRIPTION",           "为6个单元格内的所有城市提供+5 [ICON_SCIENCE] 科技值和 +1 [ICON_Faith] 信仰值。本城所有的除沙漠泛滥外的沙漠单元格+1 [ICON_SCIENCE] 科技值。 学院从沙漠和沙漠丘陵单元格获得标准相邻加成。[NEWLINE][NEWLINE]必须修建在沙漠或沙漠丘陵之上，同时必须与学院区域（其中须建有大学）相邻。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HAGIA_SOPHIA_DESCRIPTION",                 "传教士和使徒可以额外传播一次宗教。利用宗教单位使城市首次改变信仰时，该城市每拥有1点 [ICON_Citizen] 人口，则提供10点 [ICON_FAITH] 信仰值（标准速度下）。[NEWLINE][NEWLINE]您必须已经创立了一个宗教，此外，还必须建在靠近圣地的平原上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_BIOSPHERE_EXPANSION2_DESCRIPTION",         "所有离岸风力发电厂、太阳能农场、风力发电厂、地热发电厂和水电站坝产出的 [ICON_POWER] 电力+400%。此建筑和这些改良设置将提供等同于其 [ICON_POWER] 电力的 [ICON_TOURISM] 旅游业绩。帝国中与雨林和沼泽相邻的单元格+1魅力（而不是-1）。[NEWLINE][NEWLINE]必须建在与“社区”区域相邻的河流旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_KOTOKU_IN_DESCRIPTION",                    "此城+20% [ICON_Faith] 信仰值。赠送4名有免费晋升的武僧。本城生产的武僧获得额外1级免费晋升。[NEWLINE][NEWLINE]必须建在拥有寺庙的圣地区域旁。获得武僧的前提条件是玩家创立了宗教，或此玩家/城市拥有主流宗教。"),
    ("zh_Hans_CN",  "LOC_BUILDING_POTALA_PALACE_EXPANSION2_DESCRIPTION",     "+1外交政策槽位。+1外交胜利点数。建成时+50%当前累积的 [ICON_FAITH] 信仰值。[NEWLINE][NEWLINE]必须建在丘陵或山脉单元格上，且相邻山脉。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HANGING_GARDENS_DESCRIPTION",              "所有城市+10% [ICON_FOOD] 食物。必须建在河流旁边。"),
    ("zh_Hans_CN",  "LOC_BUILDING_JEBEL_BARKAL_EXPANSION2_DESCRIPTION",      "每回合奖励6点 [ICON_RESOURCE_IRON] 铁。为9个单元格内的所有城市提供+4 [ICON_Faith] 信仰值。[NEWLINE][NEWLINE]必须建在沙漠（丘陵）地貌上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_CRISTO_REDENTOR_DESCRIPTION",              "[ICON_GreatWork_Relic] 遗物和圣城的 [ICON_Tourism] 旅游业绩产值不会被其他研究了“启蒙运动”市政的文明削弱。您文明中“海滨度假区”产出的 [ICON_Tourism] 旅游业绩+100%。伟人赞助消耗的 [ICON_Faith] 信仰值减少25%。[NEWLINE][NEWLINE] 必须建在丘陵上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HUEY_TEOCALLI_DESCRIPTION",                "在休伊神庙一个单元格以内的每个湖泊单元格为城市+1 [ICON_Amenities] 宜居度。为您帝国内的每个湖泊单元格+1 [ICON_Food] 食物、+1 [ICON_Production] 生产力和+1 [ICON_Gold] 金币。必须建在靠近陆地的湖泊单元格上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MACHU_PICCHU_DESCRIPTION",                 "山脉单元格为所有城市的商业中心、剧院广场及工业区提供标准的相邻加成。所有靠山的区域（不包含奇观）+2 [ICON_FOOD] 食物。[NEWLINE][NEWLINE]必须修建在无火山的山脉单元格中。"),
    ("zh_Hans_CN",  "LOC_BUILDING_COLOSSUS_DESCRIPTION",                     "+1 [ICON_TradeRoute] 贸易路线容量。获得1个商人单位。 本城拥有的每个渔船为从该城出发的国际商路+2 [ICON_GOLD] 金币[NEWLINE][NEWLINE]必须建在邻近陆地和港口的海岸上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TAJ_MAHAL_DESCRIPTION",                    "此奇观建成后，提供2点或以上时代得分的历史时刻所提供的时代得分+1。所有世界奇观+8 [ICON_GOLD] 金币。完成世界奇观后返还等同于奇观所需产能80%的 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]必须建在河流旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TORRE_DE_BELEM_DESCRIPTION",               "目的地城市每有1处奢侈品资源，从此城起源的国际 [ICON_TradeRoute] 贸易路线便+2 [ICON_GOLD] 金币。建成时获得2个开拓者，所有开拓者+2 [ICON_Movement] 移动力。和首座城市不在同一个大陆上的城市+2初始 [ICON_Citizen] 人口。[NEWLINE][NEWLINE]必须建造在与港口区域相邻的海岸单元格上。"),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_OXFORD_UNIVERSITY",           "当展示来自不同作家的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_SYDNEY_OPERA_HOUSE",          "当展示来自相同时代音乐家的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_HERMITAGE",                   "当展示来自相同时代的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_GOV_CULTURE",                 "当展示来自相同时代的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_NEUSCHWANSTEIN",              "当展示来自不同音乐家的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_NOTRE_DAME",                  "当展示来自相同时代的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_UFFIZI",                      "当展示来自相同类型的作品时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_THEMINGBONUS_DL_STPETERSBASILICA",         "当所有槽位填满时，主题加成翻倍。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_VENETIAN_ARSENAL_DESCRIPTION",             "每训练一个海军单位，便会获得第二个海军单位。为本城每个近海单元格+1 [ICON_Production] 生产力和+1 [ICON_Gold] 金币，每回合提供6点 [ICON_RESOURCE_Niter] 硝石。必须建在靠近工业区的海岸单元格上。"),
    -- ("zh_Hans_CN",  "LOC_BUILDING_APADANA_DESCRIPTION",                      "在此城市中建造奇观（包括阿帕达纳宫）时+2 [ICON_ENVOY] 使者。每个宗主的城邦提供+2 [ICON_CULTURE] 文化。必须建造在 [ICON_CAPITAL] 首都旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ALHAMBRA_DESCRIPTION",                     "+1 军事政策槽位[NEWLINE][NEWLINE]提供同堡垒改良设施一样的防御加成。每座军营提供+2影响力点数。必须建立在邻近军营区的丘陵上。"),
    -- ("zh_Hans_CN",  "LOC_BUILDING_CASA_DE_CONTRATACION_DESCRIPTION",         "获得2次 [ICON_Governor] 总督升级。所有与原始 [ICON_Capital] 首都不在同一大陆、且拥有 [ICON_Governor] 总督的城市 [ICON_Production] 生产力+15%、[ICON_Faith] 信仰值+15%、[ICON_Gold] 金币+15%。必须建造在市政广场旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ESTADIO_DO_MARACANA_DESCRIPTION",          "9个单元格内的所有区域专家额外+3对应产出（军营专家提供 +3 [ICON_Production] 生产力；港口专家提供 +3 [ICON_Food] 食物）。若此城 [ICON_POWER] 供电充足，则9个单元格内的所有城市+50% [ICON_GreatPerson] 伟人点。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_HOLY_SITE_NAME",                 "[COLOR:ResFaithLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_HOLY_SITE_DESCRIPTION",          "该圣地建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [Icon_Faith] 信仰值。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_CAMPUS_NAME",                    "[COLOR:ResScienceLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_CAMPUS_DESCRIPTION",             "该学院建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_HARBOR_NAME",                    "[COLOR:ResFoodLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_HARBOR_DESCRIPTION",             "该港口建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_ENCAMPMENT_NAME",                "[COLOR:ResProductionLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_ENCAMPMENT_DESCRIPTION",         "该军营建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_COMMERCIAL_HUB_NAME",            "[COLOR:ResGoldLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_COMMERCIAL_HUB_DESCRIPTION",     "该商业中心建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_THEATER_NAME",                   "[COLOR:ResCultureLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_THEATER_DESCRIPTION",            "该剧院建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_INDUSTRIAL_ZONE_NAME",           "[COLOR:ResProductionLabelCS]专家产出已提升[ENDCOLOR]"),
    ("zh_Hans_CN",  "BUILDING_MARACANA_DUMMY_DISTRICT_INDUSTRIAL_ZONE_DESCRIPTION",    "该工业区建造于“马拉卡纳体育场”奇观9个单元格内，专家额外+3 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STATUE_LIBERTY_EXPANSION2_DESCRIPTION",              "+4外交胜利点数。为9个单元格以内的所有海岸城市市中心提供：+4 [ICON_CULTURE] 文化值和+4 [ICON_AMENITIES] 宜居度。当前所有拥有港口的城市获得当前可在该区域中建造的、所需 [ICON_PRODUCTION] 生产力最低的建筑。[NEWLINE][NEWLINE]必须建造在与港口相邻且靠近陆地的海岸单元格上。");--每拥有100点军评，获得1点影响力。

-- National Wonders
--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                     Text)
values
    ("LOC_NAT_WONDER_CL_COLLEGE_DESCRIPTION",                 "National Wonder. Can only be built once in your empire. Must be built on flat land adjacent to a Campus district with a Library.[NEWLINE][NEWLINE]+100% Campus district adjacency bonuses in this City. Established [ICON_Governor] Governor in this city provide +4% [ICON_Science] Science for each Promotion earned, including the first."),
    ("LOC_NAT_WONDER_CL_COLLEGE_DESCRIPTION_INTERNAL",        "National Wonder. Can only be built once in your empire. Must be built on flat land adjacent to a Campus district with a Library.[NEWLINE][NEWLINE]+100% Campus district adjacency bonuses in this City. Established [ICON_Governor] Governor in this city provide +4% [ICON_Science] Science for each Promotion earned, including the first."),
    
    ("LOC_NAT_WONDER_CL_NATIONALEPIC_DESCRIPTION",            "National Wonder. Can only be built once in your empire. Must be built adjacent to a Theater Square with an Art Museum or an Archaeological Museum.[NEWLINE][NEWLINE]+20% [ICON_GreatPerson] Great Person points in this city. For every [ICON_GreatPerson] Great Person earned, provide +4 yield equal to that [ICON_GreatPerson] Great Person's district type.([ICON_Greatgeneral] Great Generals earned provide +4 [ICON_Production] Production. [ICON_Greatadmiral] Great Admirals earned provide +4 [ICON_Food] Food.)"),
    ("LOC_NAT_WONDER_CL_NATIONALEPIC_DESCRIPTION_INTERNAL",   "National Wonder. Can only be built once in your empire. Must be built adjacent to a Theater Square with an Art Museum or an Archaeological Museum.[NEWLINE][NEWLINE]+20% [ICON_GreatPerson] Great Person points in this city. For every [ICON_GreatPerson] Great Person earned, provide +4 yield equal to that [ICON_GreatPerson] Great Person's district type.([ICON_Greatgeneral] Great Generals earned provide +4 [ICON_Production] Production. [ICON_Greatadmiral] Great Admirals earned provide +4 [ICON_Food] Food.)"),
    
    ("LOC_NAT_WONDER_CL_CITADEL_DESCRIPTION",                 "National Wonder. Can only be built once in your empire. To unlock: Requires that you are at War with other Civilizations. Must be built adjacent to an Encampment district.[NEWLINE][NEWLINE]Provides the same defensive bonuses as the Fort improvement. Grant Walls and Medieval Walls in this City. Promoting a unit does not end that unit's turn. +4 [ICON_STRENGTH] Combat Strength for all military units in your territory. All Encampment districts, buildings in Encampment districts and Fort improvements provide +2 [ICON_Production] Production and +2 [ICON_Culture] Culture. Fort improvements provide [ICON_TOURISM] Tourism from [ICON_CULTURE] Culture after researching Flight."),
    ("LOC_NAT_WONDER_CL_CITADEL_DESCRIPTION_INTERNAL",        "National Wonder. Can only be built once in your empire. [COLOR:Red]To unlock: Requires that you are at War with other Civilizations[ENDCOLOR]. Must be built adjacent to an Encampment district.[NEWLINE][NEWLINE]Provides the same defensive bonuses as the Fort improvement. Grant Walls and Medieval Walls in this City. Promoting a unit does not end that unit's turn. +4 [ICON_STRENGTH] Combat Strength for all military units in your territory. All Encampment districts, buildings in Encampment districts and Fort improvements provide +2 [ICON_Production] Production and +2 [ICON_Culture] Culture. Fort improvements provide [ICON_TOURISM] Tourism from [ICON_CULTURE] Culture after researching Flight."),
    
    ("LOC_NAT_WONDER_CL_TEMPLE_DESCRIPTION",                  "National Wonder. Can only be built once in your empire. To unlock: Requires that you must have founded a Religion with at least 5 Cities following it. Must be built adjacent to a Holy Site district.[NEWLINE][NEWLINE]For each Worship building constructed, all your Cities spread Religion with +20% pressure and +10% range. These effects can stack up to 5 times. +1 [ICON_SCIENCE] Science and +1 [ICON_CULTURE] Culture from each city following your Religion."),
    ("LOC_NAT_WONDER_CL_TEMPLE_DESCRIPTION_INTERNAL",         "National Wonder. Can only be built once in your empire. [COLOR:Red]To unlock: Requires that you must have founded a Religion with at least 5 Cities following it.[ENDCOLOR] Must be built adjacent to a Holy Site district.[NEWLINE][NEWLINE]For each Worship building constructed, all your Cities spread Religion with +20% pressure and +10% range. These effects can stack up to 5 times. +1 [ICON_SCIENCE] Science and +1 [ICON_CULTURE] Culture from each city following your Religion."),
    
    ("LOC_NAT_WONDER_CL_THEMEPARK_DESCRIPTION",               "National Wonder. Can only be built once in your empire. To unlock: Requires 4 Entertainment Complex or Waterpark districts to have been built in your empire. Must be built on a flat tile adjacent to an Entertainment Complex district. District built on Breathtaking tiles provide [ICON_TOURISM] Tourism from adjacency bonuses. Wonders provide +300% [ICON_TOURISM] Tourism in Cities having Entertainment Complex or Water Park.  Pastures and Camps provide +50% [ICON_TOURISM] Tourism in Cities having Zoo. Fishing Boats provide +50% [ICON_TOURISM] Tourism in Cities having Aquarium."),
    ("LOC_NAT_WONDER_CL_THEMEPARK_DESCRIPTION_INTERNAL",      "National Wonder. Can only be built once in your empire. [COLOR:Red]To unlock: Requires 4 Entertainment Complex or Waterpark districts to have been built in your empire.[ENDCOLOR] Must be built on a flat tile adjacent to an Entertainment Complex district. District built on Breathtaking tiles provide [ICON_TOURISM] Tourism from adjacency bonuses. Wonders provide +300% [ICON_TOURISM] Tourism in Cities having Entertainment Complex or Water Park.  Pastures and Camps provide +50% [ICON_TOURISM] Tourism in Cities having Zoo. Fishing Boats provide +50% [ICON_TOURISM] Tourism in Cities having Aquarium."),

    ("LOC_NAT_WONDER_CL_IRONWORKS_DESCRIPTION",               "National Wonder. Can only be built once in your empire. To unlock: Improve 4 Strategic Resources in your empire. Must be built on a land tile next to an Industrial Zone district and an [ICON_IRON] Iron resource. All Cities within 8 tiles of the Ironworks receive +3 [ICON_PRODUCTION] production for every type of Strategic Resource properly improved in this City."),
    ("LOC_NAT_WONDER_CL_IRONWORKS_DESCRIPTION_INTERNAL",      "National Wonder. Can only be built once in your empire. [COLOR:Red]To unlock: Improve 4 Strategic Resources in your empire.[ENDCOLOR] Must be built on a land tile next to an Industrial Zone district and an [ICON_IRON] Iron resource. All Cities within 8 tiles of the Ironworks receive +3 [ICON_PRODUCTION] production for every type of Strategic Resource properly improved in this City."),

    ("LOC_NAT_WON_CL_FINANCE_DESCRIPTION",                    "National Wonder. Can only be built once in your empire. To unlock: Maintain 8 [ICON_TradeRoute] Trade Routes. Must be built on land tile adjacent to an Commercial Hub. Commercial Hub of this city receive +100% adjacency bonus.
    Banks provide +2 [ICON_Gold] Gold to [ICON_TradeRoute] International Trade Routes originated from the city. Stock Exchanges provide +4 [ICON_Gold] Gold to [ICON_TradeRoute] International Trade Routes originated from the city. [ICON_GreatPerson] Great People patronage cost -50% [ICON_Gold] Gold."),
    ("LOC_NAT_WON_CL_FINANCE_DESCRIPTION_INTERNAL",           "National Wonder. Can only be built once in your empire. [COLOR:Red]To unlock: Maintain 8 [ICON_TradeRoute] Trade Routes.[ENDCOLOR] Must be built on land tile adjacent to an Commercial Hub. Commercial Hub of this city receive +100% adjacency bonus. Banks provide +2 [ICON_Gold] Gold to [ICON_TradeRoute] International Trade Routes originated from the city. Stock Exchanges provide +4 [ICON_Gold] Gold to [ICON_TradeRoute] International Trade Routes originated from the city. [ICON_GreatPerson] Great People patronage cost -50% [ICON_Gold] Gold."),
    ("LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION",               "National Wonder. Can only be built once in your empire. To unlock: Maintain 8 [ICON_TradeRoute] Trade Routes. Must be built on land tile adjacent to an Commercial Hub. [NEWLINE][NEWLINE]Your Corporations provide +200% [ICON_TOURISM] Tourism. [ICON_GreatWork_Product] Products provide double yields in Cities with a Stock Exchange. [ICON_GreatPerson] Great People patronage cost -50% [ICON_Gold] Gold."),
    ("LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION_INTERNAL",      "National Wonder. Can only be built once in your empire. [COLOR:Red]To unlock: Maintain 8 [ICON_TradeRoute] Trade Routes.[ENDCOLOR] Must be built on land tile adjacent to an Commercial Hub. [NEWLINE][NEWLINE]Your Corporations provide +200% [ICON_TOURISM] Tourism. [ICON_GreatWork_Product] Products provide double yields in Cities with a Stock Exchange. [ICON_GreatPerson] Great People patronage cost -50% [ICON_Gold] Gold."),

    ("LOC_GOSSIP_SOURCE_NAT_AIRPORT",                         "Stewardesses at the International Airport learn that "),
    ("LOC_VIZSOURCE_NAT_AIRPORT",                             "The International Airport is complete"),
    ("LOC_VIZSOURCE_ACTION_NAT_AIRPORT",                      "Construct the International Airport"),

    ("LOC_HD_NAT_AIRPORT_CORP_ADD",                           ""),
    ("LOC_NAT_WON_CL_AIRPORT_DESCRIPTION",                    "National Wonder. Can only be built once in your empire. Must be built on flat terrain.[NEWLINE][NEWLINE]{LOC_HD_NAT_AIRPORT_CORP_ADD}+3 [ICON_TradeRoute] Trade Route capacity. Plantations and Lumber Mills in Cities with Airport districts and/or the International Airport wonder provide +50% [ICON_TOURISM] Tourism. International [ICON_TradeRoute] Trade Routes to or from this City provide you with Specialty Districts yields as if this City is the destination; this bonus is doubled if the City has an Airport district and/or the International Airport wonder. Provides an additional level of [ICON_VISLIMITED] Diplomatic Visibility to all Civilizations."),
    ("LOC_NAT_WON_CL_AIRPORT_DESCRIPTION_INTERNAL",           "National Wonder. Can only be built once in your empire. Must be built on flat terrain.[NEWLINE][NEWLINE]{LOC_HD_NAT_AIRPORT_CORP_ADD}+3 [ICON_TradeRoute] Trade Route capacity. Plantations and Lumber Mills in Cities with Airport districts and/or the International Airport wonder provide +50% [ICON_TOURISM] Tourism. International [ICON_TradeRoute] Trade Routes to or from this City provide you with Specialty Districts yields as if this City is the destination; this bonus is doubled if the City has an Airport district and/or the International Airport wonder. Provides an additional level of [ICON_VISLIMITED] Diplomatic Visibility to all Civilizations.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                     Text)
values
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_COLLEGE_NAME",                        "国立学院"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_COLLEGE_DESCRIPTION",                 "国家奇观，国家境内只能建造一座。必须建在与学院区域（其中须建有图书馆）相邻的平坦地形上。[NEWLINE][NEWLINE]本城+100%学院相邻加成。 [ICON_Governor] 总督在本城就职后，每次升级（包括首次升级）都将提供 +4% [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_COLLEGE_DESCRIPTION_INTERNAL",        "国家奇观，国家境内只能建造一座。必须建在与学院区域（其中须建有图书馆）相邻的平坦地形上。[NEWLINE][NEWLINE]本城+100%学院相邻加成。 [ICON_Governor] 总督在本城就职后，每次升级（包括首次升级）都将提供 +4% [ICON_Science] 科技值。"),
    
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_NATIONALEPIC_NAME",                   "民族史诗"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_NATIONALEPIC_DESCRIPTION",            "国家奇观，国家境内只能建造一座。必须建在与剧院区域（其中须建有艺术博物馆或考古博物馆）相邻的陆地上。[NEWLINE][NEWLINE]此城+20% [ICON_GreatPerson] 伟人点。您的文明每获得1位 [ICON_GreatPerson] 伟人，此城便获得等同于此 [ICON_GreatPerson] 伟人区域类型的+4产出（大将军 [ICON_Greatgeneral] 提供 +4 [ICON_Production] 生产力；海军提督 [ICON_Greatadmiral] 提供 +4 [ICON_Food] 食物）。"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_NATIONALEPIC_DESCRIPTION_INTERNAL",   "国家奇观，国家境内只能建造一座。必须建在与剧院区域（其中须建有艺术博物馆或考古博物馆）相邻的陆地上。[NEWLINE][NEWLINE]此城+20% [ICON_GreatPerson] 伟人点。您的文明每获得1位 [ICON_GreatPerson] 伟人，此城便获得等同于此 [ICON_GreatPerson] 伟人区域类型的+4产出（大将军 [ICON_Greatgeneral] 提供 +4 [ICON_Production] 生产力；海军提督 [ICON_Greatadmiral] 提供 +4 [ICON_Food] 食物）。"),
    
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_CITADEL_NAME",                        "大本营"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_CITADEL_DESCRIPTION",                 "国家奇观，国家境内只能建造一座。解锁条件：与其他文明交战。必须建在与军营相邻的陆地上。[NEWLINE][NEWLINE]获得和堡垒相同的防御加成。本城中立刻建造远古城墙和中世纪城墙。升级单位不会结束其回合，位于国境内的单位+4 [ICON_Strength] 战斗力。所有军营、军营建筑和堡垒+2 [ICON_Production] 生产力、+2 [ICON_Culture] 文化值。研究完“飞行”科技后，堡垒将获得与 [ICON_CULTURE] 文化值产量相等的 [ICON_TOURISM]。"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_CITADEL_DESCRIPTION_INTERNAL",        "国家奇观，国家境内只能建造一座。[COLOR:Red]解锁条件：与其他文明交战。[ENDCOLOR]必须建在与军营相邻的陆地上。[NEWLINE][NEWLINE]获得和堡垒相同的防御加成。本城中立刻建造远古城墙和中世纪城墙。升级单位不会结束其回合，位于国境内的单位+4 [ICON_Strength] 战斗力。所有军营、军营建筑和堡垒+2 [ICON_Production] 生产力、+2 [ICON_Culture] 文化值。研究完“飞行”科技后，堡垒将获得与 [ICON_CULTURE] 文化值产量相等的 [ICON_TOURISM]。"),
    
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_TEMPLE_NAME",                         "圣殿"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_TEMPLE_DESCRIPTION",                  "国家奇观，国家境内只能建造一座。解锁条件：已创立一个宗教，且至少有5座城市皈依您文明的宗教。必须建在与圣地相邻的陆地上。[NEWLINE][NEWLINE]每拥有一座祭祀建筑，国家境内所有城市向相邻城市施加的宗教传播压力+20%，且宗教传播范围+10%，该效果最多叠加5次。从每个信奉该宗教的城市获得+1 [ICON_SCIENCE] 科技值和 +1 [ICON_CULTURE] 文化。"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_TEMPLE_DESCRIPTION_INTERNAL",         "国家奇观，国家境内只能建造一座。[COLOR:Red]解锁条件：已创立一个宗教，且至少有5座城市皈依您文明的宗教。[ENDCOLOR]必须建在与圣地相邻的陆地上。[NEWLINE][NEWLINE]每拥有一座祭祀建筑，国家境内所有城市向相邻城市施加的宗教传播压力+20%，且宗教传播范围+10%，该效果最多叠加5次。从每个信奉该宗教的城市获得+1 [ICON_SCIENCE] 科技值和 +1 [ICON_CULTURE] 文化。"),
    
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_THEMEPARK_NAME",                      "国家主题公园"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_THEMEPARK_DESCRIPTION",               "国家奇观，国家境内只能建造一座。解锁条件：国家境内拥有4座娱乐中心或水上乐园。必须建在与娱乐中心相邻的陆地上。[NEWLINE][NEWLINE]拥有惊艳魅力的单元格中的区域，相邻加成也提供相等的 [ICON_TOURISM] 旅游业绩。拥有娱乐中心或者水上乐园的城市，奇观的 [ICON_Tourism] 旅游业绩+300%。拥有动物园的城市“牧场”和“营地”改良设施产出的 [ICON_Tourism] 旅游业绩+50%；拥有水族馆的城市“渔船”改良设施产出的 [ICON_Tourism] 旅游业绩+50%。"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_THEMEPARK_DESCRIPTION_INTERNAL",      "国家奇观，国家境内只能建造一座。[COLOR:Red]解锁条件：国家境内拥有4座娱乐中心或水上乐园。[ENDCOLOR]必须建在与娱乐中心相邻的平坦地形上。[NEWLINE][NEWLINE]拥有惊艳魅力的单元格中的区域，相邻加成也提供相等的 [ICON_TOURISM] 旅游业绩。拥有娱乐中心或者水上乐园的城市，奇观的 [ICON_Tourism] 旅游业绩+300%。拥有动物园的城市“牧场”和“营地”改良设施产出的 [ICON_Tourism] 旅游业绩+50%；拥有水族馆的城市“渔船”改良设施产出的 [ICON_Tourism] 旅游业绩+50%。"),

    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_IRONWORKS_NAME",                      "大铁厂"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_IRONWORKS_DESCRIPTION",               "国家奇观，国家境内只能建造一座。解锁条件：国家境内拥有至少4个战略资源的改良设施。必须建在与工业区和 [ICON_RESOURCE_IRON] 铁资源相邻的陆地上。[NEWLINE][NEWLINE]本城每拥有一种被改良的战略资源，为8个单元格之内的城市提供+3 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_NAT_WONDER_CL_IRONWORKS_DESCRIPTION_INTERNAL",      "国家奇观，国家境内只能建造一座。[COLOR:Red]解锁条件：国家境内拥有至少4个战略资源的改良设施。[ENDCOLOR]必须建在与工业区和 [ICON_RESOURCE_IRON] 铁资源相邻的陆地上。[NEWLINE][NEWLINE]本城每拥有一种被改良的战略资源，为8个单元格之内的城市提供+3 [ICON_Production] 生产力。"),
    
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_NAME",                           "金融中心"),
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_DESCRIPTION",                    "国家奇观，国家境内只能建造一座。解锁条件：经营8条贸易路线。必须建在与商业中心相邻的陆地上。[NEWLINE][NEWLINE]本城+100%商业中心相邻加成。从拥有银行的城市出发的国际 [ICON_TradeRoute] 贸易路线+2 [ICON_Gold] 金币，从拥有证券交易所的城市出发的国际 [ICON_TradeRoute] 贸易路线+4 [ICON_Gold] 金币。 [ICON_GreatPerson] 伟人赞助消耗的 [ICON_Gold] 金币减少50%。"),
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_DESCRIPTION_INTERNAL",           "国家奇观，国家境内只能建造一座。[COLOR:Red]解锁条件：经营8条贸易路线。[ENDCOLOR]必须建在与商业中心相邻的陆地上。[NEWLINE][NEWLINE]本城+100%商业中心相邻加成。从拥有银行的城市出发的国际 [ICON_TradeRoute] 贸易路线+2 [ICON_Gold] 金币，从拥有证券交易所的城市出发的国际 [ICON_TradeRoute] 贸易路线+4 [ICON_Gold] 金币。 [ICON_GreatPerson] 伟人赞助消耗的 [ICON_Gold] 金币减少50%。"),
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION",               "国家奇观，国家境内只能建造一座。解锁条件：经营8条贸易路线。必须建在与商业中心相邻的陆地上。[NEWLINE][NEWLINE][ICON_GreatPerson] 伟人赞助消耗的 [ICON_Gold] 金币减少50%。国家境内的“公司”改良设施产出的 [ICON_Tourism] 旅游业绩+200%。拥有证券交易所的城市 [ICON_GreatWork_Product] 产品的产出翻倍。"),
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION_INTERNAL",      "国家奇观，国家境内只能建造一座。[COLOR:Red]解锁条件：经营8条贸易路线。[ENDCOLOR]必须建在与商业中心相邻的陆地上。[NEWLINE][NEWLINE][ICON_GreatPerson] 伟人赞助消耗的 [ICON_Gold] 金币减少50%。国家境内的“公司”改良设施产出的 [ICON_Tourism] 旅游业绩+200%。拥有证券交易所的城市 [ICON_GreatWork_Product] 产品的产出翻倍。"),

    ("zh_Hans_CN",  "LOC_GOSSIP_SOURCE_NAT_AIRPORT",                         "国际机场的空姐获悉"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_NAT_AIRPORT",                             "建造了国际机场"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_ACTION_NAT_AIRPORT",                      "建造国际机场"),

    ("zh_Hans_CN",  "LOC_NAT_WON_CL_AIRPORT_NAME",                           "国际机场"),
    ("zh_Hans_CN",  "LOC_HD_NAT_AIRPORT_CORP_ADD",                           ""),
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_AIRPORT_DESCRIPTION",                    "国家奇观，国家境内只能建造一座。必须建在平坦地形上。[NEWLINE][NEWLINE]{LOC_HD_NAT_AIRPORT_CORP_ADD}+3 [ICON_TradeRoute] 贸易路线容量。对所有文明+1 [ICON_VISLIMITED] 外交能见度。拥有机场（包括国际机场）的城市“种植园”和“伐木场”改良设施产出的 [ICON_Tourism] 旅游业绩+50%。对于每一条 [ICON_TradeRoute] 贸易路线连接，无论您的城市作为国际 [ICON_TradeRoute] 贸易路线的起点还是终点，您都可从该城内的专业化区域获得其作为国际目的地时的加成；若城市拥有机场（包括国际机场），则该效果翻倍。"),
    ("zh_Hans_CN",  "LOC_NAT_WON_CL_AIRPORT_DESCRIPTION_INTERNAL",           "国家奇观，国家境内只能建造一座。必须建在平坦地形上。[NEWLINE][NEWLINE]{LOC_HD_NAT_AIRPORT_CORP_ADD}+3 [ICON_TradeRoute] 贸易路线容量。对所有文明+1 [ICON_VISLIMITED] 外交能见度。拥有机场（包括国际机场）的城市“种植园”和“伐木场”改良设施产出的 [ICON_Tourism] 旅游业绩+50%。对于每一条 [ICON_TradeRoute] 贸易路线连接，无论您的城市作为国际 [ICON_TradeRoute] 贸易路线的起点还是终点，您都可从该城内的专业化区域获得其作为国际目的地时的加成；若城市拥有机场（包括国际机场），则该效果翻倍。");