--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                 Text)
values
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_CLASSICAL",       "Religious art of classical era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INDUSTRIAL",      "Religious art of industrial era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MODERN",          "Religious art of modern era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_RENAISSANCE",     "Religious art of renaissance era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INFORMATION",     "Religious art of information era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MEDIEVAL",        "Religious art of medieval era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_ATOMIC",          "Religious art of atomic era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_CLASSICAL",        "Portrait of classical era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_INDUSTRIAL",       "Portrait of industrial era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_MODERN",           "Portrait of modern era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_RENAISSANCE",      "Portrait of renaissance era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_INFORMATION",      "Portrait of information era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_MEDIEVAL",         "Portrait of medieval era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_ATOMIC",           "Portrait of atomic era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_CLASSICAL",       "Sculpture of classical era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_INDUSTRIAL",      "Sculpture of industrial era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_MODERN",          "Sculpture of modern era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_RENAISSANCE",     "Sculpture of renaissance era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_INFORMATION",     "Sculpture of information era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_MEDIEVAL",        "Sculpture of medieval era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_ATOMIC",          "Sculpture of atomic era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_CLASSICAL",       "Landscape of classical era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INDUSTRIAL",      "Landscape of industrial era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MODERN",          "Landscape of modern era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_RENAISSANCE",     "Landscape of renaissance era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INFORMATION",     "Landscape of information era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MEDIEVAL",        "Landscape of medieval era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_ATOMIC",          "Landscape of atomic era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_CLASSICAL",         "Writing of classical era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_INDUSTRIAL",        "Writing of industrial era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_MODERN",            "Writing of modern era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_RENAISSANCE",       "Writing of renaissance era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_INFORMATION",       "Writing of information era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_MEDIEVAL",          "Writing of medieval era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_ATOMIC",            "Writing of atomic era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_CLASSICAL",           "Music of classical era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_INDUSTRIAL",          "Music of industrial era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_MODERN",              "Music of modern era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_RENAISSANCE",         "Music of renaissance era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_INFORMATION",         "Music of information era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_MEDIEVAL",            "Music of medieval era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_ATOMIC",              "Music of atomic era");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_CLASSICAL",       "古典时期的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INDUSTRIAL",      "工业时期的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MODERN",          "现代的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_RENAISSANCE",     "文艺复兴时期的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INFORMATION",     "信息时代的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MEDIEVAL",        "中世纪的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_ATOMIC",          "原子能时代的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_CLASSICAL",        "古典时期的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_INDUSTRIAL",       "工业时期的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_MODERN",           "现代的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_RENAISSANCE",      "文艺复兴时期的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_INFORMATION",      "信息时代的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_MEDIEVAL",         "中世纪的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_ATOMIC",           "原子能时代的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_CLASSICAL",       "古典时期的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_INDUSTRIAL",      "工业时期的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_MODERN",          "现代的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_RENAISSANCE",     "文艺复兴时期的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_INFORMATION",     "信息时代的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_MEDIEVAL",        "中世纪的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_ATOMIC",          "原子能时代的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_CLASSICAL",       "古典时期的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INDUSTRIAL",      "工业时期的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MODERN",          "现代的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_RENAISSANCE",     "文艺复兴时期的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INFORMATION",     "信息时代的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MEDIEVAL",        "中世纪的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_ATOMIC",          "原子能时代的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_CLASSICAL",         "古典时期的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_INDUSTRIAL",        "工业时期的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_MODERN",            "现代的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_RENAISSANCE",       "文艺复兴时期的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_INFORMATION",       "信息时代的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_MEDIEVAL",          "中世纪的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_ATOMIC",            "原子能时代的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_CLASSICAL",           "古典时期的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_INDUSTRIAL",          "工业时期的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_MODERN",              "现代的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_RENAISSANCE",         "文艺复兴时期的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_INFORMATION",         "信息时代的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_MEDIEVAL",            "中世纪的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_ATOMIC",              "原子能时代的音乐");

