--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                 Text)
values
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_CLASSICAL",       "Religious Art of Classical era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INDUSTRIAL",      "Religious Art of Industrial era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MODERN",          "Religious Art of Modern era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_RENAISSANCE",     "Religious Art of Renaissance era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INFORMATION",     "Religious Art of Information era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MEDIEVAL",        "Religious Art of Medieval era"),
    ("LOC_GREATWORKOBJECT_RELIGIOUS_ERA_ATOMIC",          "Religious Art of Atomic era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_CLASSICAL",        "Portrait of Classical era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_INDUSTRIAL",       "Portrait of Industrial era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_MODERN",           "Portrait of Modern era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_RENAISSANCE",      "Portrait of Renaissance era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_INFORMATION",      "Portrait of Information era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_MEDIEVAL",         "Portrait of Medieval era"),
    ("LOC_GREATWORKOBJECT_PORTRAIT_ERA_ATOMIC",           "Portrait of Atomic era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_CLASSICAL",       "Sculpture of Classical era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_INDUSTRIAL",      "Sculpture of Industrial era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_MODERN",          "Sculpture of Modern era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_RENAISSANCE",     "Sculpture of Renaissance era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_INFORMATION",     "Sculpture of Information era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_MEDIEVAL",        "Sculpture of Medieval era"),
    ("LOC_GREATWORKOBJECT_SCULPTURE_ERA_ATOMIC",          "Sculpture of Atomic era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_CLASSICAL",       "Landscape of Classical era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INDUSTRIAL",      "Landscape of Industrial era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MODERN",          "Landscape of Modern era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_RENAISSANCE",     "Landscape of Renaissance era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INFORMATION",     "Landscape of Information era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MEDIEVAL",        "Landscape of Medieval era"),
    ("LOC_GREATWORKOBJECT_LANDSCAPE_ERA_ATOMIC",          "Landscape of Atomic era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_CLASSICAL",         "Writing of Classical era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_INDUSTRIAL",        "Writing of Industrial era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_MODERN",            "Writing of Modern era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_RENAISSANCE",       "Writing of Renaissance era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_INFORMATION",       "Writing of Information era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_MEDIEVAL",          "Writing of Medieval era"),
    ("LOC_GREATWORKOBJECT_WRITING_ERA_ATOMIC",            "Writing of Atomic era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_CLASSICAL",           "Music of Classical era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_INDUSTRIAL",          "Music of Industrial era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_MODERN",              "Music of Modern era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_RENAISSANCE",         "Music of Renaissance era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_INFORMATION",         "Music of Information era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_MEDIEVAL",            "Music of Medieval era"),
    ("LOC_GREATWORKOBJECT_MUSIC_ERA_ATOMIC",              "Music of Atomic era"),
    ("LOC_GREATWORK_SUN_TZU_NAME",                        "The Art of War[NEWLINE]All combat units gain +25% experience when attacking.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_CLASSICAL",       "古典时期的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INDUSTRIAL",      "工业时期的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MODERN",          "现代的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_RENAISSANCE",     "文艺复兴时期的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_INFORMATION",     "信息时代的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_MEDIEVAL",        "中世纪的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_RELIGIOUS_ERA_ATOMIC",          "原子能时代的宗教画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_CLASSICAL",        "古典时期的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_INDUSTRIAL",       "工业时期的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_MODERN",           "现代的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_RENAISSANCE",      "文艺复兴时期的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_INFORMATION",      "信息时代的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_MEDIEVAL",         "中世纪的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_PORTRAIT_ERA_ATOMIC",           "原子能时代的肖像画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_CLASSICAL",       "古典时期的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_INDUSTRIAL",      "工业时期的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_MODERN",          "现代的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_RENAISSANCE",     "文艺复兴时期的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_INFORMATION",     "信息时代的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_MEDIEVAL",        "中世纪的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_SCULPTURE_ERA_ATOMIC",          "原子能时代的雕塑"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_CLASSICAL",       "古典时期的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INDUSTRIAL",      "工业时期的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MODERN",          "现代的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_RENAISSANCE",     "文艺复兴时期的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_INFORMATION",     "信息时代的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_MEDIEVAL",        "中世纪的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_LANDSCAPE_ERA_ATOMIC",          "原子能时代的风景画"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_CLASSICAL",         "古典时期的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_INDUSTRIAL",        "工业时期的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_MODERN",            "现代的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_RENAISSANCE",       "文艺复兴时期的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_INFORMATION",       "信息时代的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_MEDIEVAL",          "中世纪的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_WRITING_ERA_ATOMIC",            "原子能时代的书"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_CLASSICAL",           "古典时期的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_INDUSTRIAL",          "工业时期的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_MODERN",              "现代的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_RENAISSANCE",         "文艺复兴时期的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_INFORMATION",         "信息时代的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_MEDIEVAL",            "中世纪的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORKOBJECT_MUSIC_ERA_ATOMIC",              "原子能时代的音乐"),
    ("zh_Hans_CN",  "LOC_GREATWORK_SUN_TZU_NAME",                        "《 孙子兵法 》[NEWLINE]所有战斗单位的攻击经验+25%。");

