--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                 Text)
values
    -- Base Improvements
    ("LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",               "Unlocks the Builder ability to construct Mines.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Production] Production if adjacent to Mountain tiles (obsolete with Apprenticeship Technology). +1 [ICON_Production] Production for each adjacent Industrial Zone District (except Hansa District). Extra +1 [ICON_Production] Production if the city owns a Workshop. -1 Appeal to all adjacent tiles. [NEWLINE][NEWLINE]Can be built on Hills or valid Resources. If built on Luxury or Strategic resources, the city will gain use of that Resource."),
    ("LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",             "Unlocks the Builder ability to construct Quarries.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. +1 [ICON_Production] Production for each adjacent Industrial Zone District (except Hansa District). -1 Appeal to all adjacent tiles. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on a Luxury resource, the city will gain use of that resource. [NEWLINE][NEWLINE]For each city that owns a Quarry, +10% Production when building ancient and classical Wonders and 5% when building medieval era or renaissance era Wonders. Doubles when the city owns a second Quarry."),
    ("LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",      "Unlocks the Builder ability to construct Fishing Boats.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Food] Food if the city owns a Harbor. +2 [ICON_Gold] Gold for each adjacent Harbor District.[NEWLINE][NEWLINE]Can only be built on valid Resources. If built on Luxury resources, the city will gain use of that Resource."),
    ("LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",         "Unlocks the Builder ability to construct Plantations.[NEWLINE][NEWLINE]+2 [ICON_Gold] Gold. Extra +1 [ICON_Food] Food if adjacent to fresh water or Aqueduct District (obsolete with Feudalism Civic). +2 [ICON_Gold] Gold for each adjacent Commercial Hub District. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on Luxury resources, the city will gain use of that resource."),
    ("LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",            "Unlocks the Builder ability to construct Pastures.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. [NEWLINE][NEWLINE]Can only be built on valid Resources. If built on Strategic resources, the city will gain use of that Resource."),
    ("LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",               "Unlocks the Builder ability to construct Farms.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. If the city owns a Aqueduct District, farms that are adjacent to fresh water or Aqueduct District yield +1 [ICON_Food] Food.[NEWLINE][NEWLINE]Can only be built on Grassland or Plains. Once Civil Engineering is unlocked it can also be built on Grassland Hills or Plains Hills."),
    ("LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",               "Unlocks the Builder ability to construct Camps.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. +2 [ICON_Gold] Gold for each adjacent Commercial Hub District. [NEWLINE][NEWLINE]Can only be built on valid Resources. Once Archery is unlocked it can also be built on Forests. Once Guilds is unlocked it can also be built on Rainforest. [NEWLINE][NEWLINE]If built on Luxury resources, the city will gain use of that Resource."),
    ("LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",        "Unlocks the Builder ability to construct a Lumber Mill.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Production] Production if adjacent to a River.[NEWLINE][NEWLINE]Can only be built on Woods. +1 [ICON_Production] Production for each adjacent Industrial Zone District (except Hansa District). Once Guilds is unlocked it can also be built on Rainforest."),
    ("LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",            "Unlocks the Builder ability to construct a Fishery.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +0.5 [ICON_Housing] Housing; +1 additional [ICON_Food] Food for each adjacent sea resource. Must be built on a coastal tile."),
    -- UI of Majors
    ("LOC_IMPROVEMENT_OUTBACK_STATION_DESCRIPTION",       "Unlocks the Builder ability to construct an Outback Station, unique to Australia.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production and +0.5 [ICON_Housing] Housing. +1 [ICON_Food] Food for each adjacent Pasture. Pastures and Outback Stations receive +1 [ICON_Food] Food for every two adjacent Outback Stations (also receive +1 [ICON_Production] Production with the 'Steam Power' technology). Can only be built in Desert, Desert Hills, Grassland, and Plains tiles."),
    ("LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",          "Unlocks the Builder ability to construct a Terrace Farm, unique to the Inca.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food. Provides +1 [ICON_Housing] Housing for every Terrace Farms. +1 [ICON_FOOD] Food for each adjacent Mountain Tile ,+1 [ICON_FOOD] Food after researching Engineeing. Gain +2 [ICON_PRODUCTION] Production for each adjacent Aqueduct district. Receive +1 [ICON_PRODUCTION] Production if adjacent to Fresh Water and not an Aqueduct district. Additional [ICON_FOOD] Food as you advance through the Civics and Technology Tree for adjacency with other Terrace Farms. Can be placed on Grassland Hills, Plains Hills, and Desert Hills."),
    ("LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",             "Unlocks the Builder ability to construct a Chemamull, unique to Mapuche.[NEWLINE][NEWLINE]+1 [Icon_Production] Production. Provides [ICON_CULTURE] Culture equal to 100% of the tile's Appeal. Additional [ICON_TOURISM] Tourism after researching Flight. Minimum Appeal of Charming. Can be built on Woods."),
    ("LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",     "Unlocks the Builder ability to construct a Sphinx, unique to Egypt.[NEWLINE][NEWLINE]+1 [ICON_Faith] Faith and +1 [ICON_Culture] Culture. +2 Appeal. +2 [ICON_Faith] Faith if next to a Wonder. +1 [ICON_CULTURE] Culture if built on Floodplains. Each Sphinx +1 [Icon_food] Food to adjacent Farm if the Farm is built on Floodplains. [NEWLINE] Additional [ICON_CULTURE] Culture once Natural History is discovered. Provides [ICON_TOURISM] Tourism after researching Flight. Cannot be built next to another Sphinx. Cannot be built on Snow or Snow Hills."),
    ("LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",               "Unlocks the Builder ability to construct a Mekewap, unique to Cree.[NEWLINE][NEWLINE]Provides +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing. Extra +1 [ICON_Housing] Housing after completing Civil Service. +1 [ICON_PRODUCTION] Production if adjacent to a Luxury resource. Yields +1 [ICON_FOOD] Food for every adjacent Bonus resource. Additional [ICON_PRODUCTION] Production and [ICON_GOLD] Gold as you advance through the Civics and Technology Tree. Must be placed adjacent to a Bonus or Luxury resource. Cannot be built adjacent to another Mekewap."),
    ("LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",              "Unlocks the Builder ability to construct a Hacienda, unique to Gran Colombia.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold, +1 [ICON_PRODUCTION] Production, and +0.5 [Icon_Housing] Housing. +1 [ICON_Food] Food for every adjacent Plantation. Plantations and Haciendas receive +1 [ICON_Production] Production for every two adjacent Haciendas (increased to every Hacienda with Mercantilism). Can only be built on Jungles, Plains, Plains Hills, Grassland and Grassland Hills."), -- (increased to +2 [ICON_Food] Food for every Plantation with Replaceable Parts)
    ("LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",            "Unlocks the Builder ability to construct a Pairidaeza, unique to Persia.[NEWLINE][NEWLINE]+1 [ICON_CULTURE] Culture and +2 [ICON_GOLD] Gold. +2 Appeal. +1 [ICON_CULTURE] Culture for each adjacent Holy Site and Theater Square. +1 [ICON_GOLD] Gold for each adjacent Commercial Hub and City Center. Additional [ICON_Culture] Culture and [ICON_Tourism] Tourism as you advance through the Technology and Civics Tree. Cannot be built on Snow, Tundra, Snow Hills, or Tundra Hills or adjacent to another Pairidaeza."),
    ("LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",               "Improvement that unlocks with Masonry and can be built on Desert Floodplains, Desert, Plains, Grass (including Hills). +2 [ICON_Faith] Faith and +1 [ICON_Food] Food. +1 [ICON_FOOD] Food after researching Theology. Receives additional yields from adjacent districts. +1 [ICON_Food] Food if adjacent to a city center. For all other Districts that award adjacency bonuses: +1 of the appropriate yield if that district is adjacent. If build on Desert, Desert Hills extra +2 [ICON_Faith] Faith and +2 [ICON_Food] Food."),
    ("LOC_IMPROVEMENT_ZIGGURAT_DESCRIPTION",              "Unlocks the Builder ability to construct a Ziggurat, unique to Sumeria.[NEWLINE][NEWLINE]+2 [ICON_Science] Science. +1 [ICON_Food] Food and +1 [ICON_Culture] Culture if next to River. +1 additional [ICON_Science] Science for each era since classial era. Cannot be built on Hills but may be built on Floodplains."),
    ("LOC_IMPROVEMENT_CHATEAU_EXPANSION2_DESCRIPTION",    "Unlocks the Builder ability to construct a Chateau, unique to France.[NEWLINE][NEWLINE]+2 [ICON_Culture] Culture. +1 Appeal. +2 [ICON_Culture] Culture for every adjacent Wonder. +1 [ICON_Culture] Culture for every adjacent Luxury resource. +2 [ICON_Gold] Gold for every adjacent Bonus resource. Provides [ICON_TOURISM] Tourism after researching Flight. Must be placed adjacent to a Bonus or Luxury resource. Cannot be built adjacent to another Château."),
    ("LOC_IMPROVEMENT_STEPWELL_EXPANSION2_DESCRIPTION",   "Unlocks the Builder ability to construct a Stepwell, unique to India.[NEWLINE][NEWLINE]+1 [ICON_Food] Food and +1 [ICON_Housing] Housing. +1 [ICON_Faith] Faith if adjacent to a Holy Site district. +1 [ICON_Food] Food if adjacent to a Farm. City receive +1 [ICON_AMENITIES] Amenity from their first Stepwell improvement. Additional [ICON_Housing] Housing, [ICON_Faith] Faith, and [ICON_Food] Food as you advance through the Technology and Civics Tree. Prevents [ICON_Food] Food loss during Drought. Cannot be built on Hills or adjacent to another Stepwell."),
    ("LOC_IMPROVEMENT_KAMPUNG_DESCRIPTION",               "Unlocks the Builder ability to construct a Kampung, unique to Indonesia.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing. +1 [ICON_PRODUCTION] Production for adjacent City Center district. +1 [ICON_PRODUCTION] Production for each adjacent Fishing Boat. Once Civil Engineering is unlocked, +1 [ICON_PRODUCTION] Production, +1 [ICON_Housing] Housing, and Fishing Boats +1 [ICON_PRODUCTION] Production for every 2 adjacent Kampungs. Provides [ICON_TOURISM] Tourism acording to [ICON_PRODUCTION] Production yield after researching Flight. Must be placed on a Coast, Lake or Reef tile adjacent to a sea Resource."),
    ("LOC_IMPROVEMENT_GOLF_COURSE_XP2_DESCRIPTION",       "Unlocks the Builder ability to construct a Golf Course, unique to Scotland.[NEWLINE][NEWLINE]+2 [ICON_AMENITIES] Amenities and +2 [ICON_GOLD] Gold. +1 [ICON_CULTURE] Culture if adjacent to a City Center district and +1 [ICON_CULTURE] Culture if adjacent to an Entertainment Complex district. +1 [ICON_CULTURE] Culture for every adjacent Districts after complete the Humanism Civic. +1 [ICON_Housing] after complete Globalization Civic. Cannot be placed on Desert or Desert Hills. One per city. Tiles with Golf Courses cannot be swapped. +1 Appeal."),
    ("LOC_IMPROVEMENT_GREAT_WALL_EXPANSION2_DESCRIPTION", "Unlocks the Builder ability to construct the Great Wall, unique to China.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +2 [ICON_GOLD] Gold. Provides an increase to [ICON_Strength] Defense. Enemy military units -2 [ICON_Strength] for each adjacent the Great Wall. Bonus to [ICON_Culture] Culture if adjacent to other segments. Additional [ICON_Gold] Gold and [ICON_Tourism] Tourism as you advance through the Technology Tree for adjacent segments. Must be built in a line along the borders of your empire. Can be built on mountains and forest. Can only be pillaged (never destroyed) by natural disasters."),
    -- UI of Minors
    ("LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",            "Your Builders can now make Mahavihara improvements.[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] Science and +1 [Icon_Housing] Housing. +1 [ICON_Science] Science for every adjacent Campus district or Holy Site district. After researching Scientific Theory, receive an additional +1 [Icon_Science] Science for every adjacent Campus. Must be built on flat terrain not adjacent to another Mahavihara."),
    ("LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",          "Your Builders can now make Trading Dome improvements.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold. extra +2 [ICON_Gold] after Medieval Faires is discovered. Provide +2 [ICON_Gold] to adjacent Luxury resources. Your outgoing international [ICON_TradeRoute] Trade Routes grant +2 [ICON_GOLD] Gold per Trading Dome at the origin. Cannot be built next to another Trading Dome."), -- +2 [ICON_Gold] Gold for every adjacent Luxury resource. 
    ("LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",  "Your Builders can now make Monastery improvements.[NEWLINE][NEWLINE]Monasteries provide +2 [ICON_Faith] Faith. +15 HP healing for friendly religious unit on this tile that has not attacked this turn. +1 [ICON_FAITH] Faith for every adjacent District. +2 [ICON_FAITH] Faith for every adjacent District once Divine Right is discovered. Provides +1 [ICON_HOUSING] Housing. Receive an additional [ICON_HOUSING] Housing once Colonialism is discovered. Cannot be built next to another Monastery."),
    ("LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",    "Unlocks the Builder ability to construct an Alcázar.[NEWLINE][NEWLINE]+2 [ICON_Culture] Culture. Provides [ICON_SCIENCE] Science equal to 75% of the tile's Appeal. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification. Provides [ICON_TOURISM] Tourism after researching Flight. Cannot be built next to another Alcázar."),
    ("LOC_IMPROVEMENT_BATEY_DESCRIPTION",                 "Unlocks the Builder ability to construct a Batey.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every adjacent Bonus Resource and Entertainment Complex (increased to +2 [Icon_Culture] Culture when Humanism is discovered). Provides [Icon_Tourism] Tourism after researching Flight. Cannot be built adjacent to another Batey or on Hills."),
    ("LOC_IMPROVEMENT_COLOSSAL_HEAD_EXPANSION2_DESCRIPTION", "Unlocks the Builder ability to construct a Colossal Head.[NEWLINE][NEWLINE]+2 [ICON_Faith] Faith. +1 [ICON_Faith] Faith for every 2 adjacent Rainforest or for every adjacent Rainforest once Humanism is discovered. +1 [ICON_Faith] Faith for every 2 adjacent Woods or for every adjacent Woods once Humanism is discovered. [ICON_TOURISM] Tourism from [ICON_FAITH] Faith once Flight is researched. Can only be built on Forest or Jungles."),
    ("LOC_IMPROVEMENT_MOUND_DESCRIPTION",                 "Unlocks the Builder ability to construct a Cahokia Mounds.[NEWLINE][NEWLINE]+3 [ICON_GOLD] Gold. Cities receive +1 [ICON_AMENITIES] Amenity from their first and second Cahokia Mound improvement.  +1 [ICON_FOOD] Food for every adjacent Districts. +2 [ICON_FOOD] Food for every adjacent Districts once Historical Philosophy is discovered. Provides +1 [ICON_HOUSING] Housing. Cannot be built adjacent to other Cahokia Mounds."),
    ("LOC_IMPROVEMENT_NAZCA_LINE_DESCRIPTION",            "Unlocks the Builder ability to construct a Nazca Line.[NEWLINE][NEWLINE]+2 [ICON_Faith] Faith to adjacent tiles. +1 [ICON_Faith] Faith to adjacent tiles with a resource. +1 [ICON_FOOD] Food to adjacent Desert and Desert Hill tiles after discovering Feudalism. +1 [ICON_PRODUCTION] Production to adjacent flat tiles after researching Mass Production. +1 Appeal. Can only be built on flat Desert. This tile cannot be worked."),
    -- UI of Governor
    ("LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",             "+2 Appeal to adjacent tiles and +1 [ICON_Culture] Culture. Cannot be adjacent to another City Park. If the city park is in a city with a Surveyor Governor with the Parks and Recreation promotion, it provides +1 of all yields to all adjacent tiles.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    -- 基础改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",               "解锁建造者建造矿山的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若靠近山脉单元格，额外+1 [ICON_Production] 生产力（学徒后失效）。 每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。若本城有工作坊，额外+1 [ICON_Production] 生产力。 相邻单元格-1魅力。[NEWLINE][NEWLINE]只能在丘陵或有效资源上建造。如果建在奢侈品资源或战略资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",             "解锁建造者建造采石场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。相邻单元格-1魅力。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。[NEWLINE][NEWLINE]城市若拥有采石场，则建造远古和古典奇观加速10%，建造中古和文艺复兴的奇观加速5%。若该城市还拥有第二个采石场，则该加成加倍。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",      "解锁建造者建造渔船的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若城市有港口区域，则+1 [ICON_Food] 食物。每相邻1个港口区域则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",         "解锁建造者建造种植园的能力。[NEWLINE][NEWLINE]+2 [ICON_Gold] 金币。拥有淡水或相邻水渠的种植园+1 [ICON_Food] 食物（封建后失效）。每相邻1个商业中心单元格则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",            "解锁建造者建造牧场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在战略资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",               "解锁建造者建造农场的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物。若本城有水渠，则相邻淡水或水渠的农场+1 [ICON_Food] 食物。[NEWLINE][NEWLINE]只能建在草原或平原上。解锁“土木工程”市政后也能建造在草原丘陵或平原丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",               "解锁建造者建造营地的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物。每相邻1个商业中心单元格则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。解锁“弓箭”科技后也可建造在森林上。解锁“公会”市政后也可建造在雨林上。[NEWLINE][NEWLINE]如建在奢侈品资源上，城市则能利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",        "解锁建造者建造伐木场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若沿河，额外+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]只能建在树林上。每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。解锁“公会”市政后也能建造在雨林上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",            "解锁建造者建造渔场的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物，+0.5 [ICON_Housing] 住房。每与1个海洋资源相邻，则额外+1 [ICON_Food] 食物；必须建在海岸格位上。"),
    -- 文明特色改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_OUTBACK_STATION_DESCRIPTION",       "解锁建造者修建澳大利亚特色改良设施内陆牧场的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物和+1 [ICON_PRODUCTION] 生产力并+0.5 [Icon_Housing] 住房。每相邻一个牧场+1 [ICON_Food] 食物。每相邻两个“内陆牧场”，牧场与“内陆牧场”便+1 [ICON_Food] 食物（完成科技“蒸汽动力”后，也获得+1 [ICON_Production] 生产力）。只能建在沙漠、沙漠丘陵、草原和平原单元格上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",          "解锁建造者建造印加特色设施印加梯田的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物；每块印加梯田+1 [ICON_Housing] 住房。每个相邻的山脉单元格+1 [ICON_FOOD] 食物，解锁工程科技后，每个相邻的山脉单元格额外+1 [ICON_FOOD] 食物。每个相邻的水渠区域+2 [ICON_PRODUCTION] 生产力。与淡水资源（非水渠区域）相邻时，+1 [ICON_PRODUCTION] 生产力（无法相互叠加）。随着市政与科技的发展，与其他印加梯田相邻时还可额外获得 [ICON_FOOD] 食物加成。可建在草原丘陵、平原丘陵与沙漠丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",             "解锁建造者建造马普切木人（马普切特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [Icon_Production] 生产力。提供等同于所在单元格魅力100%的 [ICON_CULTURE] 文化值。研究完“飞行”后可获得额外 [ICON_TOURISM] 旅游业绩。要求单元格至少达到迷人魅力。可以建造在森林上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",     "解锁建造者建造狮身人面像（埃及特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [ICON_Faith] 信仰值、+1 [ICON_Culture] 文化值。+2魅力。如果与奇观相邻，+2 [ICON_Faith] 信仰值。如建在泛滥平原上，+1 [ICON_CULTURE] 文化值。每个相邻的狮身人面像为相邻的建造在泛滥平原上的农场+1 [ICON_FOOD]食物。获得“自然历史”市政后将产出更多 [ICON_CULTURE] 文化值。[NEWLINE] 研究完“飞行”后其将提供 [ICON_TOURISM] 旅游业绩。无法建在另一个狮身人面像旁。无法建在雪地或雪地丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",               "解锁建造者建造棚屋（克里特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房。完成行政部门后额外+1 [ICON_HOUSING] 住房。如与奢侈品资源相邻，则+1 [ICON_PRODUCTION] 生产力。相邻的每个加成资源可使其+1 [ICON_FOOD] 食物。解锁更多市政和科技后即可获得更多 [ICON_PRODUCTION] 生产力和 [ICON_GOLD] 金币。必须建在与加成或奢侈品资源相邻的单元格上。无法建在另一个棚屋旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",              "解锁建造者建造大庄园（大哥伦比亚特色改良设施）的能力。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币、+1 [ICON_PRODUCTION] 生产力并+0.5 [Icon_Housing] 住房。每相邻一个种植园则+1 [ICON_Food] 食物。每与2座大庄园相邻，种植园与大庄园便+1 [ICON_Production] 生产力（获得市政“重商主义”后，每与1座大庄园相邻便能获得加成）。只能建造在雨林、平原、平原丘陵、草原和草原丘陵上。"), -- （解锁科技“零件规格化”后，每与1座种植园相邻便能获得+2 [ICON_Food] 食物）
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",            "解锁建造者建造波斯庭院（波斯特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [ICON_CULTURE] 文化值并+2 [ICON_GOLD] 金币。+2魅力。每个相邻圣地和剧院广场+1 [ICON_CULTURE] 文化值。每个相邻商业中心和市中心+1 [ICON_GOLD] 金币。解锁更多科技和市政树后可提供更多 [ICON_Culture] 文化值和 [ICON_Tourism] 旅游业绩。无法建在雪地、冻土、雪地丘陵或冻土丘陵上，也无法建在另一座波斯庭院旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_KURGAN_DESCRIPTION",                "解锁建造者建造斯基泰特色坟墩的能力。[NEWLINE][NEWLINE]+1 [ICON_Faith] 信仰值、+3 [ICON_Gold] 金币。每与一座牧场相邻便+1 [ICON_Faith] 信仰值（研究完“马镫”后提升为+2）。研究完“飞行”之后将根据 [ICON_FAITH] 信仰值提供 [ICON_TOURISM] 旅游业绩。不能建在丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CHATEAU_DESCRIPTION",               "解锁建造者建造法国特色建筑城堡庄园的能力。[NEWLINE][NEWLINE]+2 [ICON_Culture] 文化值、+1 [ICON_Gold] 金币。+1魅力。每与一座奇观相邻便+1 [ICON_Culture] 文化值（研究“飞行”科技后提升为+2）。如处在包含河岸的单元格上，则+2 [ICON_Gold] 金币。研究完“飞行”之后，将根据 [ICON_CULTURE] 文化值提供 [ICON_TOURISM] 旅游业绩。必须建在加成或奢侈品资源旁。无法建在另一座城堡庄园旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",               "随“砌砖”科技解锁的改良设施。可以建造在沙漠泛滥平原，沙漠、草原、平原（包括对应丘陵）上。+2 [ICON_Faith] 信仰值、+1 [ICON_Food] 食物，解锁神学后，+1 [ICON_Food] 食物。可从相邻区域获得额外产出。与市中心相邻则+1 [ICON_Food] 食物。如与提供相邻加成的其他任意区域相邻，则相应产出+1。建造在沙漠或者沙漠丘陵上时，额外+2 [ICON_Faith] 信仰值、+2 [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_ZIGGURAT_DESCRIPTION",              "解锁建造者建造苏美尔特色金字形神塔的能力。[NEWLINE][NEWLINE]+2 [ICON_Science] 科技值。如果紧挨着河流，+1 [ICON_Food] 食物并+1 [ICON_Culture] 文化值。从远古时代起，每经过一个时代额外+1 [ICON_Science] 科技值。不能建在丘陵上，但可建在泛滥平原上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CHATEAU_EXPANSION2_DESCRIPTION",    "解锁建造者建造法国特色城堡的能力。[NEWLINE][NEWLINE]+2 [ICON_Culture] 文化值。+1魅力。每有1处相邻奇观便+2 [ICON_Culture] 文化值。每有1处相邻奢侈品资源便+1 [ICON_Culture] 文化值。每有1处相邻加成资源便+2 [ICON_Gold] 金币。研究完“飞行”科技后可提供 [ICON_TOURISM] 旅游业绩。必须建在加成或奢侈品资源旁。无法建在另一座法国城堡旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_STEPWELL_EXPANSION2_DESCRIPTION",   "解锁建造者建造印度特色改良设施梯井的能力。[NEWLINE][NEWLINE]提供+1点 [ICON_Food] 食物并+1 [ICON_Housing] 住房。如与圣地区域相邻，+1 [ICON_Faith] 信仰值。如与农场相邻，+1 [ICON_Food] 食物。城市建造首座梯井改良设施可提供+1点 [ICON_AMENITIES] 宜居度。随着科技和市政的发展，其将提供更多 [ICON_Housing] 住房、[ICON_Faith] 信仰值和 [ICON_Food] 食物。干旱期间可防止 [ICON_Food] 食物损失。不能建在丘陵上，不能建在另一个梯井旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_KAMPUNG_DESCRIPTION",               "解锁建造者建造印度尼西亚特色改良设施“甘榜屋”的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物、+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房。相邻市中心+1 [ICON_PRODUCTION] 生产力。每个相邻渔船+1 [ICON_PRODUCTION] 生产力。解锁“土木工程”后+1 [ICON_PRODUCTION] 生产力和+1 [ICON_Housing] 住房，渔船每相邻2个甘榜屋+1 [ICON_PRODUCTION] 生产力。研究完“飞行”科技后将根据 [ICON_PRODUCTION] 生产力提供 [ICON_TOURISM] 旅游业绩。必须建造在靠近海洋资源的海岸、湖泊或礁石单元格上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_GOLF_COURSE_XP2_DESCRIPTION",       "解锁建造者建造高尔夫球场（苏格兰特色改良设施）的能力。[NEWLINE][NEWLINE]+2 [ICON_AMENITIES] 宜居度、+2 [ICON_GOLD] 金币、+1 [ICON_Housing] 住房。如与市中心区域相邻，则+1 [ICON_CULTURE] 文化值；如与娱乐设施区域相邻，则+1 [ICON_CULTURE] 文化值。解锁人文主义后，每相邻一个区域+1 [ICON_CULTURE] 文化值。解锁全球化后+1 [ICON_Housing] 住房。无法建在沙漠或沙漠丘陵地貌上。每座城市仅限建造一座。拥有高尔夫球场的单元格无法切换。为相邻单元格提供+1魅力。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_GREAT_WALL_EXPANSION2_DESCRIPTION", "解锁建造者建造中国特色改良设施长城的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物，+2 [ICON_GOLD] 金币。提升 [ICON_Strength] 防御力。敌方军事单位每相邻一段长城-2 [ICON_Strength] 战斗力。如果和其他分段相邻，将获得 [ICON_Culture] 文化值加成。随着科技进步，与长城分段相邻将获得额外的 [ICON_Gold] 金币和 [ICON_Tourism] 旅游业绩。必须沿着帝国的边界线建造。可以修建在山脉和树林上。仅能被自然灾害掠夺（不会遭到破坏）。"),
    -- 城邦改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",            "您的建造者现在能够建造大寺改良设施。[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] 科技值、+1 [Icon_Housing] 住房。每与1座学院或圣地区域相邻，则+1 [ICON_Science] 科技值。研究完“科学理论”之后，每与1座学院相邻则额外+1 [Icon_Science] 科技值。必须建在平坦地貌上，不能与其他大寺相邻。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",          "您的建造者现在能够建造圆顶市集改良设施。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币。解锁“中世纪集市”后+2 [ICON_GOLD] 金币。每与一个奢侈品资源相邻则+2 [ICON_Gold] 金币。起源城市每有一座圆顶市集，对外国际贸易 [ICON_TradeRoute] 路线提供的 [ICON_GOLD] 金币便+2。无法建在另一座圆顶市集旁。"), -- 为相邻的奢侈品资源+2 [ICON_GOLD] 金币。
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",  "您的建造者现在能够建造修道院改良设施。[NEWLINE][NEWLINE]修道院提供+2 [ICON_Faith] 信仰值。此单元格上的友方宗教单位生命值恢复+15（前提是其当前回合未发动攻击）。每1个相邻的区域使其+1 [ICON_FAITH] 信仰值。解锁“王权神授”市政后每1个相邻的区域使其+2 [ICON_FAITH] 信仰值。提供+1 [ICON_HOUSING] 住房。解锁“殖民主义”市政后获得额外1点 [ICON_HOUSING] 住房。无法建在另一座修道院旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",    "您的建造者现在能够建造阿卡萨城堡改良设施。[NEWLINE][NEWLINE]阿卡萨城堡提供+2 [ICON_Culture] 文化值。提供等于单元格魅力75%的 [ICON_SCIENCE] 科技值。占领单位 [ICON_Strength] 防御力+4，并自动获得2回合防御工事。研究“飞行”科技后可提供 [ICON_TOURISM] 旅游业绩。无法建在另一座阿卡萨城堡旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_BATEY_DESCRIPTION",                 "您的建造者现在能够建造改良设施巴特依。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值。每与1座加成资源和娱乐设施相邻，则+1 [ICON_Culture] 文化值（拥有“人文主义”市政后+2 [Icon_Culture] 文化值）。研究完“飞行”后将产出 [Icon_Tourism] 旅游业绩。无法建造在另一座巴特依旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_COLOSSAL_HEAD_EXPANSION2_DESCRIPTION", "解锁建造者建造巨神头像的能力。[NEWLINE][NEWLINE]+2 [ICON_Faith] 信仰值。与每2个雨林相邻+1信仰值，而解锁“人文主义”市政后与每1个雨林相邻便能+1信仰值。与每2个树林相邻+1信仰值，而解锁“人文主义”市政后与每1个树林相邻便能+1信仰值。研究“飞行”科技后可通过 [ICON_FAITH] 信仰值获得 [ICON_TOURISM] 旅游业绩。仅可建造在森林或雨林上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MOUND_DESCRIPTION",                 "解锁建造者建造“卡霍基亚土墩”的能力。[NEWLINE][NEWLINE]+3 [ICON_GOLD] 金币。城市建造首座卡霍基亚土墩改良设施可提供+1点 [ICON_AMENITIES] 宜居度。发现“自然历史”后，城市建造的第二座卡霍基亚土墩改良设施可提供+1点 [ICON_AMENITIES] 宜居度。每个相邻区域+1 [ICON_FOOD] 食物；完成“历史哲学”后，变更为每个相邻区域+2 [ICON_FOOD] 食物。提供+1 [ICON_HOUSING] 住房。无法建造在另一个卡霍基亚土墩旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_NAZCA_LINE_DESCRIPTION",            "解锁建造者建造纳斯卡巨画的能力。[NEWLINE][NEWLINE]相邻的单元格+2 [ICON_Faith] 信仰值；拥有资源的相邻单元格+1 [ICON_Faith] 信仰值。发现“封建主义”后，相邻的沙漠、沙漠丘陵单元格+1 [ICON_FOOD] 食物。研究“批量生产”后，相邻的平坦的单元格+1 [ICON_PRODUCTION] 生产力；同时+1魅力。仅能建在平坦的沙漠上。此单元格无法进行改良。"),
    -- 总督改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",             "产出1 [ICON_Culture] 文化值，为相邻单元格+2魅力。无法建在另一个市立公园旁。当“测量师”总督梁（必须拥有“公园与休憩”升级）在城市就职时，市立公园为相邻单元格提供+1所有产出。");
