--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                     Text)
values
    ("LOC_ABILITY_ENABLE_WALL_ATTACK_DESCRIPTION",                            "When adjacent to an enemy city, units do full damage to the city's Walls."),
    ("LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",                                     "{1_num}-tile regional effects: Its basic yields extend to each city center within {1_num} tiles. Multiple copies of this effect from the same type of building do not provide additional bonuses."),
    ("LOC_HAPPINESS_DELIGHTED_NAME",                                          "Delighted"),
    ("LOC_VIZSOURCE_CHANCERY",                                                "Built Building Chancery"),
    ("LOC_VIZSOURCE_ACTION_CHANCERY",                                         "Build Building Chancery"),
    ("LOC_GOSSIP_SOURCE_CHANCERY",                                            "Your officier from Chancery informed that "),
    ("LOC_GOSSIP_SOURCE_GOV_SPIES",                                           "Your officier from GOV SPIES informed that "),
    ("LOC_VIZSOURCE_GOV_SPIES",                                               "Built Building GOV SPIES"),
    ("LOC_VIZSOURCE_ACTION_GOV_SPIES",                                        "Build Building GOV SPIES"),
    ("LOC_DISTRICT_LUXURY_GOLD",                                              "+{1_num} [ICON_Gold] Gold from the adjacent luxury resource."),
    ("LOC_PEDIA_CONCEPTS_PAGE_CITIES_12_CHAPTER_CONTENT_PARA_1",              "Your city will grow, or add more [ICON_Citizen] Citizens, with surplus [ICON_Food] Food. Any amount of [ICON_Food] Food over the total consumption of a city's [ICON_Citizen] Citizens, 3 per, is considered surplus, and is added as progress towards a new [ICON_Citizen] Citizen."),
    ("LOC_PEDIA_CONCEPTS_PAGE_CITIES_13_CHAPTER_CONTENT_PARA_1",              "A city requires 3 [ICON_Food] Food per [ICON_Citizen] Citizen (another term for ""[ICON_Citizen] Population"") per turn to avoid starvation. A city acquires [ICON_Food] Food (as well as other yields) by assigning its [ICON_Citizen] Citizens to ""work"" the land around the city. The city can work any tile within 3 spaces of the city that is also within the civilization's borders, provided as well that it is not being worked by another city. Cities cannot work tiles occupied by wonders."),
    ("LOC_DISTRICT_CANAL_GOLD",                                               "+{1_num} [ICON_Gold] Gold from the adjacent Canal."),
    ("LOC_DISTRICT_AERODROME_INDUSTRIAL_PRODUCTION",                          "+{1_num} [ICON_Production] Production from the adjacent Aerodrome."),
    ("LOC_DISTRICT_OIL_INDUSTRIAL_PRODUCTION",                                "+{1_num} [ICON_Production] Production from the adjacent Oil Well."),
    ("LOC_DISTRICT_SEAOIL_INDUSTRIAL_PRODUCTION",                             "+{1_num} [ICON_Production] Production from the adjacent Offshore Oil Rig."),
    ("LOC_DISTRICT_LUMBER_MILL_1_PRODUCTION",                                 "+{1_num} [ICON_Production] Production from the adjacent Lumber Mill."),
    ("LOC_PEDIA_CONCEPTS_PAGE_COMBAT_9_CHAPTER_CONTENT_PARA_2",               "Walls add extra protection to a city or Encampment, making it even more difficult to conquer. This protection is like armor, shielding the city from attacks. Melee units deal only 15% of their normal damage to walls, and ranged units deal only 75% of their normal damage. Only Bombard units deal 100% of their normal damage to walls, making them necessary to capture a fortified city. If the walls are damaged, they stop being as effective and the district's health will start taking a little bit of damage with every attack. Walls can only recover health with a Project found in the city's Production Queue, like repairing district buildings, that becomes available if the district has not taken any damage for 3 consecutive turns. Once a city has walls, it can make ranged attacks against enemy units using a ""City Ranged Strength"" stat.[NEWLINE][NEWLINE]The City Combat Strength is based on the [ICON_Strength] Combat Strength of the strongest melee unit built by your civilization, minus 10, or by the [ICON_Strength] Combat Strength of a garrisoned military unit.[NEWLINE][NEWLINE]The City Ranged Strength is based on the [ICON_Ranged] Ranged Strength of the strongest ranged unit built by your civilization.[NEWLINE][NEWLINE]The city gets additional bonuses to its City Combat Strength for each non-pillaged district it has, making big cities harder to capture, and from terrain and a few other modifiers sources."),
    ("LOC_ABILITY_KILL_GIVE_GREAT_GENERAL_POINTS_DESCRIPTION",                "Receive [ICON_GreatGeneral] Great General points when defeat a major or minor civilization's unit equal to 20% of the opposing unit's strength (Standard Speed)."),
    ("LOC_ABILITY_KILL_GIVE_GREAT_ADMIRAL_POINTS_DESCRIPTION",                "Receive [ICON_GreatAdmiral] Great Admiral points when defeat a major or minor civilization's unit equal to 20% of the opposing unit's strength (Standard Speed)."),
    ("LOC_ABILITY_INCA_IGNORE_HILLS_DESCRIPTION",                             "Qhapaq Ñan: ignore [ICON_MOVEMENT] movement penalty from Hills. "),
    ("LOC_ABILITY_KONGO_IGNORE_WOODS_DESCRIPTION",                            "Nkisi: Ignore [ICON_MOVEMENT] movement penalty from Forest and Jungle. "),
    ("LOC_ABILITY_AMANI_FERR_PROMOTION_DESCRIPTION",                          "1 free promotion from Amani "),
    ("LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_TERRAIN_DESCRIPTION",             "Ignore terrain's extra movement penalty"),
    ("LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_RIVER_DESCRIPTION",               "Ignore river's extra movement penalty"),
    ("LOC_ABILITY_GUILDMASTER_TRAINED_BUILDER_MOVEMENT_DESCRIPTION",          "+1 [ICON_MOVEMENT] Movement from Liang's Training"),
    ("LOC_ABILITY_BISHOP_EXTRA_MOVEMENT_DESCRIPTION",                         "+1 [ICON_MOVEMENT] Movement from Bishop's Training"),
    ("LOC_ABILITY_BISHOP_TRAINED_UNIT_EXP_DESCRIPTION",                       "+100% EXP from Bishop's training"),
    ("LOC_ABILITY_BISHOP_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+5 [ICON_Strength] Combat Strength from Bishop's training"),
    ("LOC_ABILITY_VICTOR_TRAINED_UNIT_EXP_DESCRIPTION",                       "+25% EXP from Victor's training"),
    ("LOC_ABILITY_VICTOR_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+2 [ICON_Strength] Combat Strength from Victor's training "),
    ("LOC_ABILITY_KOTOKU_IN_TRAINED_FREE_PROMOTION_DESCRIPTION",              "1 free promotion from Kotoku In "),
    ("LOC_ABILITY_TRAINED_LIGHT_CAVALRY_PILLAGE_LESS_MOVEMENT_DESCRIPTION",   "Pillage costs 1 movement from Pillage Preparing city policy"),
    ("LOC_ABILITY_LIGHT_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "-7 [ICON_Strength] Combat Strength when attacking Districts"),
    ("LOC_ABILITY_HEAVY_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "-5 [ICON_Strength] Combat Strength when attacking Districts"),
    ("LOC_ABILITY_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_DESCRIPTION",        "+3 [ICON_Strength] Combat Strength from training in Military Academy"),
    ("LOC_ABILITY_SEAPORT_TRAINED_UNIT_STRENGTH_DESCRIPTION",                 "+3 [ICON_Strength] Combat Strength from training in Seaport"),
    ("LOC_ABILITY_BARRACKS_TRAINED_UNIT_STRENGTH_DESCRIPTION",                "+2 [ICON_Strength] Combat Strength from training in Barracks"),
    ("LOC_ABILITY_BASILIKOI_TRAINED_UNIT_STRENGTH_DESCRIPTION",               "+3 [ICON_Strength] Combat Strength from training in Basilikoi Paides"),
    ("LOC_ABILITY_STABLE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+3 [ICON_Strength] Combat Strength from training in Stable"),
    ("LOC_ABILITY_ORDU_TRAINED_UNIT_STRENGTH_DESCRIPTION",                    "+3 [ICON_Strength] Combat Strength from training in Ordu"),
    ("LOC_ABILITY_MOSQUE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "+3 [ICON_Strength] Combat Strength from training in Mosque"),
    ("LOC_ABILITY_SCHOLASTICISM_BUFF_DESCRIPTION",                            "+7 [ICON_Strength] Combat Strength from Scholasticism Belief"),
    ("LOC_ABILITY_IKANDA_ANTI_CAVALRY_MOVEMENT_BONUS_DESCRIPTION",            "+1 [ICON_MOVEMENT] Movement from training in Ikanda"),
    ("LOC_ABILITY_JUST_WAR_RELIGIOUS_ALL_COMBAT_BUFF_DESCRIPTION",            "Just War : Combat units gain +5 [ICON_Strength] Combat Strength when plot has religious unit."),
    ("LOC_ABILITY_JUST_WAR_STRENGTH_DESCRIPTION",                             "Just War : +5 [ICON_Strength] Combat Strength"),
    ("LOC_ABILITY_MONASTIC_ISOLATION_INQUISITOR_CHARGE_DESCRIPTION",          "Isolation Inquisitor : inquisitors can spread Religion 1 extra time"),
    ("LOC_BISHOP_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from Bishop's training"),
    ("LOC_VICTOR_TRAINED_UNIT_EXP_PREVIEW_TEXT",                              "from Victor's training"),
    ("LOC_VICTOR_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from Victor's training"),
    ("LOC_ABILITY_GOV_FAITH_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",           "from Episcopal Church"),
    ("LOC_ABILITY_GOV_MILITARY_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",        "from War Department"),
    ("LOC_ABILITY_GOV_MILITARY_MOVEMENT_MODIFIER_PREVIEW_TEXT",               "from War Department"),
    ("LOC_CAVALRY_WEAKER_ATTACKING_DISTRICT_PREVIEW_TEXT",                    "Attacking Districts"),
    ("LOC_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",               "from training in Military Academy"),
    ("LOC_SEAPORT_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                        "from training in Seaport"),
    ("LOC_BARRACKS_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                       "from training in Barracks"),
    ("LOC_BASILIKOI_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                      "from training in Basilikoi Paides"),
    ("LOC_STABLE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from training in Stable"),
    ("LOC_ORDU_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                           "from training in Ordu"),
    ("LOC_MOSQUE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "from training in Mosque"),
    ("LOC_SCHOLASTICISM_COMBAT_STRENGTH_BUFF_PREVIEW_TEXT",                   "from Scholasticism Belief"),
    ("LOC_ABILITY_JUST_WAR_STRENGTH_PREVIEW_TEXT",                            "Combat Strength from Just War"),
    ("LOC_UNIVERSITY_JUNGLE_SCIENCE",                                         "+{1_num} [ICON_Science] Science from the adjacent {1_num : plural 1?Jungle; other?Jungles;}."),
    ("LOC_DISTRICT_QUARRY_HALF_PRODUCTION",                                   "+{1_num} [ICON_Production] Production from the adjacent Quarries."),
    ("LOC_District_Culture_Double_City_Center",                               "+{1_num} [ICON_CULTURE] Culture from adjacent City {1_Num : plural 2?Center; other?Centers;}."),
    ("LOC_District_Gold_City_Center",                                         "+{1_num} [ICON_Gold] Gold from adjacent City {1_Num : plural 1?Center; other?Centers;}."),
    ("LOC_District_Gold_Hansa",                                               "+{1_num} [ICON_Gold] Gold from adjacent Hansa {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_DESERT_SCIENCE",                                           "+{1_num} [ICON_Science] Science from adjacent Desert {1_Num : plural 1?Tile; other?Tiles;}."),
    ("LOC_DISTRICT_DESERT_HILLS_SCIENCE",                                     "+{1_num} [ICON_Science] Science from adjacent Desert hill {1_Num : plural 1?Tile; other?Tiles;}."),
    ("LOC_DISTRICT_Harbor_INDUSTRIAL_Production",                             "+{1_num} [ICON_Production] Production from adjacent Harbor {1_Num : plural 1?district; other?districts;}."),
    ("LOC_DISTRICT_RoyalDock_INDUSTRIAL_Production",                          "+{1_num} [ICON_Production] Production from adjacent RoyalDock {1_Num : plural 1?district; other?districts;}."),
    ("LOC_DISTRICT_Cothon_INDUSTRIAL_Production",                             "+{1_num} [ICON_Production] Production from adjacent Cothon {1_Num : plural 1?district; other?districts;}."),
    ("LOC_DISTRICT_River_HANSA_Production",                                   "+{1_num} [ICON_Production] Production from adjacent river."),
    ("LOC_DISTRICT_Harbor_HANSA_Production",                                  "+{1_num} [ICON_Production] Production from adjacent Harbor {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_RoyalDock_HANSA_Production",                               "+{1_num} [ICON_Production] Production from adjacent RoyalDock {1_Num : plural 2?district; other?districts;}."),
    ("LOC_DISTRICT_Cothon_HANSA_Production",                                  "+{1_num} [ICON_Production] Production from adjacent Cothon {1_Num : plural 2?district; other?districts;}."),
    ("LOC_PROJECT_CIRCUSES_AND_BREAD_HD_NAME",                                "circuses and bread"),
    ("LOC_PROJECT_CIRCUSES_AND_BREAD_HD_SHORT_NAME",                          "circuses and bread"),
    ("LOC_PROJECT_CIRCUSES_AND_BREAD_HD_DESCRIPTION",                         "City project which increases the Loyalty pressure that this city exerts on itself and other cities nearby.[NEWLINE][NEWLINE]While active, each of your [ICON_Citizen] Citizens here exerts +2 Loyalty pressure to this city. This pressure also affects other cities within 9 tiles, but is 10% less effective per tile. Once completed, instantly gain +20 Loyalty in this city.")
    ;

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                     Text)
values
    ("zh_Hans_CN",  "LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",                                     "靠近敌人城市时，对城市城墙造成全额伤害。"),
    ("zh_Hans_CN",  "LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",                                     "{1_num}环辐射：其基础产出延伸到{1_num}个单元格内的市中心，但多个同种建筑的辐射不叠加。"),
    ("zh_Hans_CN",  "LOC_TYPE_TRAIT_CITIZENSLOTS",                                           "{1_Amount: number +#,###;-#,###} [ICON_Citizen] 公民{1_Amount : plural 1?槽位; other?槽位;}"),
    ("zh_Hans_CN",  "LOC_HAPPINESS_DELIGHTED_NAME",                                          "愉悦"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_CHANCERY",                                                "建造了外交办"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_ACTION_CHANCERY",                                         "建造外交办"),
    ("zh_Hans_CN",  "LOC_GOSSIP_SOURCE_CHANCERY",                                            "外交办的官员获悉"),
    ("zh_Hans_CN",  "LOC_GOSSIP_SOURCE_GOV_SPIES",                                           "情报局的官员获悉"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_GOV_SPIES",                                               "建造了情报局"),
    ("zh_Hans_CN",  "LOC_VIZSOURCE_ACTION_GOV_SPIES",                                        "建造情报局"),
    ("zh_Hans_CN",  "LOC_DISTRICT_LUXURY_GOLD",                                              "相邻奢侈品资源提供+{1_num} [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_PEDIA_CONCEPTS_PAGE_CITIES_13_CHAPTER_CONTENT_PARA_1",              "城市里的每位 [ICON_Citizen] 公民（这是“ [ICON_Citizen] 人口”的另一种表达方式）每回合需要3份 [ICON_Food] 食物来避免饥饿。通过派遣其 [ICON_Citizen] 公民“改良”周围土地，城市能获得 [ICON_Food] 食物（以及其他收益）。城市能改良3个距离以内的任意单元格（位于文明境内且没被其他城市改良过）。城市无法改良被奇观占领的单元格。"),
    ("zh_Hans_CN",  "LOC_PROMOTION_SHELLS_DESCRIPTION",                                      "与区域防御战斗时+10 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_UNIT_GAUL_GAESATAE_DESCRIPTION",                                    "高卢特色远古时代单位，替代勇士。此单位拥有更高花费。与基础战斗力更高的单位作战时+10 [ICON_Strength] 战斗力。与区域防御战斗时+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_CANAL_GOLD",                                               "相邻运河提供+{1_num} [ICON_Gold] 金币。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_AERODROME_INDUSTRIAL_PRODUCTION",                          "相邻航空港提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_OIL_INDUSTRIAL_PRODUCTION",                                "相邻油井提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SEAOIL_INDUSTRIAL_PRODUCTION",                             "相邻海上钻机平台提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_LUMBER_MILL_1_PRODUCTION",                                 "相邻伐木场提供+{1_num} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_PEDIA_CONCEPTS_PAGE_COMBAT_9_CHAPTER_CONTENT_PARA_2",               "城墙为城市或军营增加额外保护，让其更难被占领。这种保护如同护甲一般，使城市免受攻击。近战单位仅对城墙造成它通常伤害的15%，远程单位仅对城墙造成它通常伤害的75%。只有轰炸单位才能对城墙造成它100%的伤害，因此，轰炸单位是占领坚固城市的必需之物。如果城墙遭受损害，其会不再有效，同时，每一次攻击都会让区域生命值受到少量伤害。只有使用在城市生产队列中找到的项目才能回复城墙生命值，比如修理区域建筑，如果区域连续3回合没有遭受任何伤害，则可以进行修复。城市一旦拥有城墙，便可使用“城市远程攻击”对敌方单位发动远程攻击。[NEWLINE][NEWLINE]城市战斗力取决于您文明里最强近战单位的 [ICON_Strength] 战斗力大小，最小为10，或取决于驻军军事单位的战斗力。[NEWLINE][NEWLINE]城市远程攻击力取决于您文明里最强 [ICON_Ranged] 远程单位的远程攻击力大小。[NEWLINE][NEWLINE]城市所拥有的每个没被掠夺的区域会为其城市战斗力提供额外加成，使大城市更难被占领，城市也能从地形和一些其他改造者来源中获得额外加成。"),
    ("zh_Hans_CN",  "LOC_ABILITY_INCA_IGNORE_HILLS_DESCRIPTION",                             "印加路网：无视丘陵对 [ICON_MOVEMENT] 移动力的减益。"),
    ("zh_Hans_CN",  "LOC_ABILITY_KILL_GIVE_GREAT_GENERAL_POINTS_DESCRIPTION",                "击杀文明和城邦的单位时，获得等同于对方单位战斗力的20%（标准速度下）的 [ICON_GreatGeneral] 大将军点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_KILL_GIVE_GREAT_ADMIRAL_POINTS_DESCRIPTION",                "击杀文明和城邦的单位时，获得等同于对方单位战斗力的20%（标准速度下）的 [ICON_GreatAdmiral] 海军统帅点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_KONGO_IGNORE_WOODS_DESCRIPTION",                            "精神实体：无视森林和雨林对 [ICON_MOVEMENT] 移动力的减益。"),
    ("zh_Hans_CN",  "LOC_ABILITY_AMANI_FERR_PROMOTION_DESCRIPTION",                          "阿玛尼训练：免费晋升1级"),
    ("zh_Hans_CN",  "LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_TERRAIN_DESCRIPTION",             "无视地形造成的移动力损益"),
    ("zh_Hans_CN",  "LOC_ABILITY_MILLITARY_ENGINEER_IGNORE_RIVER_DESCRIPTION",               "无视河流造成的移动力损益"),
    ("zh_Hans_CN",  "LOC_ABILITY_GUILDMASTER_TRAINED_BUILDER_MOVEMENT_DESCRIPTION",          "梁训练：永久+1 [ICON_MOVEMENT] 移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BISHOP_EXTRA_MOVEMENT_DESCRIPTION",                         "莫克夏训练：永久+1 [ICON_MOVEMENT] 移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BISHOP_TRAINED_UNIT_EXP_DESCRIPTION",                       "莫克夏训练：永久+100% 经验值"),
    ("zh_Hans_CN",  "LOC_ABILITY_BISHOP_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "莫克夏训练：永久+5 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_VICTOR_TRAINED_UNIT_EXP_DESCRIPTION",                       "维克多训练：永久+25% 经验值"),
    ("zh_Hans_CN",  "LOC_ABILITY_VICTOR_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "维克多训练：永久+2 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_KOTOKU_IN_TRAINED_FREE_PROMOTION_DESCRIPTION",              "高德院训练：免费获得1级晋升"),
    ("zh_Hans_CN",  "LOC_ABILITY_TRAINED_LIGHT_CAVALRY_PILLAGE_LESS_MOVEMENT_DESCRIPTION",   "打草谷训练：劫掠只消耗1移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_LIGHT_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "攻击区域时-7 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_HEAVY_CAVALRY_WEAKER_ATTACKING_DISTRICT_DESCRIPTION",       "攻击区域时-5 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_DESCRIPTION",        "在军事学院中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_SEAPORT_TRAINED_UNIT_STRENGTH_DESCRIPTION",                 "在码头中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BARRACKS_TRAINED_UNIT_STRENGTH_DESCRIPTION",                "在兵营中训练获得的+2 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_BASILIKOI_TRAINED_UNIT_STRENGTH_DESCRIPTION",               "在皇家学院中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_STABLE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "在马厩中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_ORDU_TRAINED_UNIT_STRENGTH_DESCRIPTION",                    "在斡耳朵中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_MOSQUE_TRAINED_UNIT_STRENGTH_DESCRIPTION",                  "由清真寺中训练获得的+3 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_SCHOLASTICISM_BUFF_DESCRIPTION",                            "来自经院哲学信条+7 [ICON_Strength] 战斗力"),
    ("zh_Hans_CN",  "LOC_ABILITY_IKANDA_ANTI_CAVALRY_MOVEMENT_BONUS_DESCRIPTION",            "在伊坎达中训练获得的+1 [ICON_MOVEMENT] 移动力"),
    ("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_RELIGIOUS_ALL_COMBAT_BUFF_DESCRIPTION",            "十字军：同一单元格内的战斗单位+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_STRENGTH_DESCRIPTION",                             "十字军：+5 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_MONASTIC_ISOLATION_INQUISITOR_CHARGE_DESCRIPTION",          "与世隔绝：审判官+1传教次数。"),
    ("zh_Hans_CN",  "LOC_BISHOP_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "来自莫克夏训练"),
    ("zh_Hans_CN",  "LOC_VICTOR_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "来自维克多训练"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_FAITH_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",           "来自主教座堂"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_MILITARY_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT",        "来自作战部"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_MILITARY_MOVEMENT_MODIFIER_PREVIEW_TEXT",               "来自作战部"),
    ("zh_Hans_CN",  "LOC_CAVALRY_WEAKER_ATTACKING_DISTRICT_PREVIEW_TEXT",                    "攻击区域"),
    ("zh_Hans_CN",  "LOC_MILITARY_ACADEMY_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",               "从军事学院中训练获得"),
    ("zh_Hans_CN",  "LOC_SEAPORT_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                        "从码头中训练获得"),
    ("zh_Hans_CN",  "LOC_BARRACKS_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                       "从兵营中训练获得"),
    ("zh_Hans_CN",  "LOC_BASILIKOI_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                      "从皇家学院中训练获得"),
    ("zh_Hans_CN",  "LOC_STABLE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "从马厩中训练获得"),
    ("zh_Hans_CN",  "LOC_ORDU_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                           "从斡耳朵中训练获得"),
    ("zh_Hans_CN",  "LOC_MOSQUE_TRAINED_UNIT_STRENGTH_PREVIEW_TEXT",                         "从清真寺中训练获得"),
    ("zh_Hans_CN",  "LOC_SCHOLASTICISM_COMBAT_STRENGTH_BUFF_PREVIEW_TEXT",                   "来自经院哲学信条"),
    ("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_STRENGTH_PREVIEW_TEXT",                            "来自十字军"),
    ("zh_Hans_CN",  "LOC_UNIVERSITY_JUNGLE_SCIENCE",                                         "+{1_num} [ICON_Science] 科技值来自相邻的雨林。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_HALF_PRODUCTION",                                   "+{1_num} [ICON_Production] 生产力来自相邻的采石场。"),
    ("zh_Hans_CN",  "LOC_District_Culture_Double_City_Center",                               "+{1_num} [ICON_CULTURE] 文化值来自相邻的市中心。"),
    ("zh_Hans_CN",  "LOC_District_Gold_City_Center",                                         "+{1_num} [ICON_Gold] 金币来自相邻的市中心。"),
    ("zh_Hans_CN",  "LOC_District_Gold_Hansa",                                               "+{1_num} [ICON_Gold] 金币来自相邻的商业同业工会。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DESERT_SCIENCE",                                           "+{1_num} [ICON_Science] 科技值来自相邻的沙漠单元格。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DESERT_HILLS_SCIENCE",                                     "+{1_num} [ICON_Science] 科技值来自相邻的沙漠（丘陵）单元格。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_Harbor_INDUSTRIAL_Production",                             "+{1_num} [ICON_Production] 生产力来自相邻的港口。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_RoyalDock_INDUSTRIAL_Production",                          "+{1_num} [ICON_Production] 生产力来自相邻的皇家海军船坞。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_Cothon_INDUSTRIAL_Production",                             "+{1_num} [ICON_Production] 生产力来自相邻的U型港。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_River_HANSA_Production",                                   "+{1_num} [ICON_Production] 生产力来自相邻河流。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_Harbor_HANSA_Production",                                  "+{1_num} [ICON_Production] 生产力来自相邻的港口。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_RoyalDock_HANSA_Production",                               "+{1_num} [ICON_Production] 生产力来自相邻的皇家海军船坞。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_Cothon_HANSA_Production",                                  "+{1_num} [ICON_Production] 生产力来自相邻的U型港。"),
    ("zh_Hans_CN",  "LOC_PROJECT_CIRCUSES_AND_BREAD_HD_NAME",                                "马戏与面包"),
    ("zh_Hans_CN",  "LOC_PROJECT_CIRCUSES_AND_BREAD_HD_SHORT_NAME",                          "马戏与面包"),
    ("zh_Hans_CN",  "LOC_PROJECT_CIRCUSES_AND_BREAD_HD_DESCRIPTION",                         "城市项目，可增加此城市对自身和对附近其他城市施加的忠诚度压力。[NEWLINE][NEWLINE]项目启动后，每位 [ICON_Citizen] 公民每回合对此城所施加的忠诚度压力+2。此忠诚度压力还将影响9个单元格以内的其他城市，但每远离1个单元格，效果减弱10%。项目完成后此城立即+20忠诚度。")
    ;

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_RESOURCE_GOLD_NAME",                                            "黄金"),
    ("zh_Hans_CN",  "LOC_PEDIA_RESOURCES_PAGE_RESOURCE_GOLD_CHAPTER_HISTORY_PARA_1",     "黄金是一种柔软、有光泽和延展性的金属，在历史上一直受到人们的珍视。这是一种稀有金属，它的稀有性大大增加了它的价值。尽管黄金有一些工业和医疗用途，但它主要用作铸币或装饰用途，装饰珠宝、杯子、器皿以及超级富豪和权贵的马桶。 ");

