--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
	(Tag,														Text)
values
	("LOC_IMPROVEMENT_BUTTRESS_ON_FLOODLANDS",					"[NEWLINE][NEWLINE]Once Buttress is unlocked it can also be built on Floodplains."),
	-- Base Improvements
	("LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",						"Unlocks the Builder ability to construct a Mine.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Production] Production if adjacent to Mountain tiles (obsolete with Apprenticeship Technology). Additional +1 [ICON_Production] Production from each adjacent Industrial Zone District (except Hansa District). -1 Appeal to all adjacent tiles. [NEWLINE][NEWLINE]Can be built on Hills or valid Resources. Once Engineering is unlocked it can also be built on Geothermal Fissures. If built on Luxury or Strategic resources, the city will gain use of that Resource."),
	("LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",					"Unlocks the Builder ability to construct a Quarry.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Additional +1 [ICON_Production] Production from each adjacent Industrial Zone District (except Hansa District). -1 Appeal to all adjacent tiles. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on a Luxury resource, the city will gain use of that resource. [NEWLINE][NEWLINE]For each city that owns a Quarry, +10% Production when building ancient and classical Wonders and 5% when building medieval era or renaissance era Wonders. Doubles when the city owns a second Quarry."),
	("LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",			"Unlocks the Builder ability to construct a Fishing Boat.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Food] Food if the city owns a Harbor. +2 [ICON_Gold] Gold for each adjacent Harbor District.[NEWLINE][NEWLINE]Can only be built on valid Resources. If built on Luxury resources, the city will gain use of that Resource."),
	("LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",				"Unlocks the Builder ability to construct a Plantation.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food. +2 [ICON_GOLD] Gold if adjacent to fresh water or Aqueduct after researching Irrigation Technology (obsolete with Feudalism Civic). +2 [ICON_Gold] Gold from each adjacent Commercial Hub District. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on Luxury resources, the city will gain use of that resource."),
	("LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",					"Unlocks the Builder ability to construct a Pasture.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. [NEWLINE][NEWLINE]Can only be built on valid Resources. If built on Strategic resources, the city will gain use of that Resource."),
	("LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",						"Unlocks the Builder ability to construct a Farm.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. If the city owns a Aqueduct District, farms that are adjacent to fresh water or Aqueduct District yield +1 [ICON_Food] Food.[NEWLINE][NEWLINE]Can only be built on Grassland or Plains. Once Civil Engineering is unlocked it can also be built on Grassland Hills or Plains Hills."),
	("LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",						"Unlocks the Builder ability to construct a Camp.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. +2 [ICON_Gold] Gold for each adjacent Commercial Hub District. [NEWLINE][NEWLINE]Can only be built on valid Resources. Once Archery is unlocked it can also be built on Forests. Once Guilds is unlocked it can also be built on Rainforest. [NEWLINE][NEWLINE]If built on Luxury resources, the city will gain use of that Resource."),
	("LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",				"Unlocks the Builder ability to construct a Lumber Mill.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. [NEWLINE][NEWLINE]Can only be built on Woods. +1 [ICON_Production] Production for each adjacent Industrial Zone District (except Hansa District). Once Guilds is unlocked it can also be built on Rainforest."), -- Once Bronze Working is unlocked, Extra +1 [ICON_Production] Production if adjacent to a River.
	("LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",					"Unlocks the Builder ability to construct a Fishery.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +0.5 [ICON_Housing] Housing; +1 additional [ICON_Food] Food for each adjacent sea resource. Must be built on a Coast tile."),
	-- UI of Majors	
	("LOC_IMPROVEMENT_OUTBACK_STATION_DESCRIPTION",				"Unlocks the Builder ability to construct an Outback Station, unique to Australia.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production and +0.5 [ICON_Housing] Housing. +1 [ICON_Food] Food for each adjacent Pasture. Pastures and Outback Stations receive +1 [ICON_Food] Food for every two adjacent Outback Stations (also receive +1 [ICON_Production] Production with the 'Banking' technology). Can only be built in Desert, Desert Hills, Grassland, and Plains tiles."),
	("LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",				"Unlocks the Builder ability to construct a Terrace Farm, unique to the Inca.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_Housing] Housing. +1 [ICON_PRODUCTION] Production if adjacent to Fresh Water. +1 [ICON_FOOD] Food for every adjacent Mountain Tile, which becomes +2 [ICON_FOOD] Food after researching 'Engineeing' Technology. +1 [ICON_FOOD] Food for every 2 adjacent Terrace Farm tiles after progressing 'Feudalism' Civic, or for every adjacent Terrace Farm tile after researching 'Biology' Technology. +1 [ICON_PRODUCTION] Production for every 2 adjacent Terrace Farm tiles after researching 'Construction' Technology. Triggers the [ICON_TECHBOOSTED] Eureka of 'Irrigation' Technology and the [ICON_CIVICBOOSTED] Inspiration of 'Feudalism' Civic if built on resource. Must be built on Hills or Mountain tiles in Grassland, Plains or Desert (including Volacanos)."),
	("LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",					"Unlocks the Builder ability to construct a Chemamull, unique to Mapuche.[NEWLINE][NEWLINE]+1 [Icon_Production] Production. Provides [ICON_CULTURE] Culture equal to 100% of the tile's Appeal. Can only be built on Charming or Breathtaking tiles. Can be built on Woods."),
	("LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",			"Unlocks the Builder ability to construct a Sphinx, unique to Egypt.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture. Provides the basic yield of all adjacent Wonders. +1 [Icon_food] Food to adjacent Farms. +2 Appeal to adjacent tiles. In cities with a Sphinx on Floodplains and adjacent to City Center, +15% additional construction speed towards Districts and Wonders that are placed next to a River. Cannot be built next to another Sphinx. Cannot be built on Snow or Snow Hills."),
	("LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",						"Unlocks the Builder ability to construct a Mekewap, unique to Cree.[NEWLINE][NEWLINE]Provides +2 [ICON_GOLD] Gold and +1 [ICON_Housing] Housing. Extra +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing after progressing 'Civil Service' Civic. +1 [ICON_FOOD] Food for every adjacent Bonus resource. +1 [ICON_PRODUCTION] Production for every adjacent Luxury or Strategic resource. +2 [ICON_GOLD] Gold for every adjacent Luxury resource after researching 'Cartography' Technology. Must be built adjacent to a Bonus or Luxury resource. Can be built on Woods after researching 'Mining' Technology. Cannot be built adjacent to another Mekewap."),
	("LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",					"Unlocks the Builder ability to construct a Hacienda, unique to Gran Colombia.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold, +1 [ICON_PRODUCTION] Production, and +0.5 [Icon_Housing] Housing. +1 [ICON_Food] Food for every adjacent Plantation. Plantations and Haciendas receive +1 [ICON_Production] Production for every two adjacent Haciendas (increased to every Hacienda with Mercantilism civic). Can only be built on Rainforests, Plains, Plains Hills, Grassland and Grassland Hills."),
	("LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",					"Unlocks the Builder ability to construct a Pairidaeza, unique to Persia.[NEWLINE][NEWLINE]+1 [ICON_CULTURE] Culture, +2 [ICON_GOLD] Gold. +1 [ICON_CULTURE] Culture for each adjacent Holy Site or Theater Square. +1 [ICON_GOLD] Gold for each adjacent Commercial Hub or City Center. +1 [ICON_FOOD] Food for each adjacent City Center. Recieves +1 [ICON_CULTURE] Culture for each Government Plaza or Government Plaza building in your civilization. +1 [ICON_CULTURE] Culture after progressing 'Civil Service' Civic. +2 Appeal to adjacent tiles. Cannot be built on Snow, Tundra, Snow Hills, or Tundra Hills or adjacent to another Pairidaeza."),
	("LOC_IMPROVEMENT_PAIRIDAEZA_ETHIOPIA_DESCRIPTION",			"Unlocks the Builder ability to construct a Pairidaeza, unique to Persia.[NEWLINE][NEWLINE]+1 [ICON_CULTURE] Culture, +2 [ICON_GOLD] Gold. +1 [ICON_CULTURE] Culture for each adjacent Holy Site or Theater Square. +1 [ICON_GOLD] Gold for each adjacent Commercial Hub or City Center. +1 [ICON_FOOD] Food for each adjacent City Center. Recieves +1 [ICON_CULTURE] Culture for each Government Plaza or Government Plaza building in your civilization, +2 [ICON_GOLD] Gold for each Diplomatic Quater or Diplomatic Quater building in your civilization. +1 [ICON_CULTURE] Culture after progressing 'Civil Service' Civic. +2 Appeal to adjacent tiles. Cannot be built on Snow, Tundra, Snow Hills, or Tundra Hills or adjacent to another Pairidaeza."),
	("LOC_IMPROVEMENT_KURGAN_DESCRIPTION",						"Unlocks the Builder ability to construct a Kurgan, unique to Scythia. +1 [ICON_Faith] Faith and +3 [ICON_Gold] Gold. +1 [ICON_Faith] Faith for each adjacent Pasture, which becomes +2 [ICON_Faith] Faith after researching 'Stirrups' Technology. +2 [ICON_FAITH] Faith for each retired [ICON_GREATGENERAL] Great General. Provides +1 [ICON_Faith] Faith to adjacent Pasture. Allow the purchase of Cavalry units using [ICON_FAITH] Faith in this city. Cannot be built on Hills."),
	("LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",						"Unlocks the Builder ability to construct a Nubian Pyramid, unique to Nubia. +2 [ICON_Faith] Faith and +1 [ICON_Food] Food. Extra +2 [ICON_Faith] Faith and +1 [ICON_Food] Food if built on non-Floodplains Desert tiles. For every adjacent district with adjacency bonus, Nubian Pyramid receives +1 of the corresponding yield (+2 [ICON_GOLD] Gold in case of Commercial Hub and Harbor). +1 [ICON_Food] Food for every adjacent City Center, +1 [ICON_CULTURE] Culture for every adjacent Government Plaza. Yields from being adjacent to these districts are doubled after progressing 'Feudalism' Civic. Can only be built on Plains, Grass and Desert (including Hills and Floodplains)."),
	("LOC_IMPROVEMENT_ZIGGURAT_DESCRIPTION",					"Unlocks the Builder ability to construct a Ziggurat, unique to Sumeria.[NEWLINE][NEWLINE]+2 [ICON_Science] Science. +1 [ICON_Food] Food and +1 [ICON_Culture] Culture if adjacent to River. +1 extra [ICON_Science] Science for each era after ancient era. Cannot be built on Hills but can be built on Floodplains."),
	("LOC_IMPROVEMENT_CHATEAU_EXPANSION2_DESCRIPTION",			"Unlocks the Builder ability to construct a Château, unique to France.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture, +2 [ICON_GOLD] Gold and +1 [ICON_HOUSING] Housing. +1 [ICON_CULTURE] Culture for every adjacent Luxury resource after researching 'Castles' Technology. +2 [ICON_GOLD] Gold for every adjacent Luxury resource after progressing 'Guilds' Civic. +1 Appeal to adjacent tiles. Must be placed adjacent to a Bonus or Luxury resource.[NEWLINE][NEWLINE]If 'Industries and Corporations' Mode is enabled, can only be built one per city, and for each type of adjacent Luxury resource improved by Plantation, Château recieves its Industry bonus. If 'Industries and Corporations' Mode is not enabled, cannot be built adjacent to another Château, +2 [ICON_GOLD] for every adjacent Bonus resource and +2 [ICON_Culture] Culture for every adjacent Wonder."),
	("LOC_IMPROVEMENT_STEPWELL_EXPANSION2_DESCRIPTION",			"Unlocks the Builder ability to construct a Stepwell, unique to India.[NEWLINE][NEWLINE]+1 [ICON_Food] Food and +1 [ICON_Housing] Housing. +1 [ICON_Faith] Faith if adjacent to a Holy Site district. +1 [ICON_Food] Food to adjacent Farm and Plantation tiles. Cities with a Stepwell receive +1 [ICON_AMENITIES] Amenity, [ICON_CITYZEN] citizens in these cities provide +0.5 [ICON_FOOD]. +1 [ICON_FAITH] Faith after progressing 'Feudalism' Civic, +1 [ICON_Food] Food and +1 [ICON_Housing] Housing after researching 'Sanitation' Technology. Prevents [ICON_Food] Food loss during Drought. Cannot be built on Hills or adjacent to another Stepwell."),
	("LOC_IMPROVEMENT_KAMPUNG_DESCRIPTION",						"Unlocks the Builder ability to construct a Kampung, unique to Indonesia.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing. +1 [ICON_PRODUCTION] Production for every adjacent City Center. +1 [ICON_PRODUCTION] Production for every adjacent Fishing Boat. After researching 'Civil Engineering' Technology, +1 [ICON_PRODUCTION] Production, +1 [ICON_Housing] Housing, and Fishing Boats recieves +1 [ICON_PRODUCTION] Production for every 2 adjacent Kampungs. Must be placed on a Coast, Lake or Reef tile adjacent to a sea Resource."),
	("LOC_IMPROVEMENT_KAMPUNG_KELP_DESCRIPTION",				"Unlocks the Builder ability to construct a Kampung, unique to Indonesia.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing. +1 [ICON_PRODUCTION] Production for every adjacent City Center. +1 [ICON_PRODUCTION] Production for every adjacent Fishing Boat. After researching 'Civil Engineering' Technology, +1 [ICON_PRODUCTION] Production, +1 [ICON_Housing] Housing, and Fishing Boats recieves +1 [ICON_PRODUCTION] Production for every 2 adjacent Kampungs. Must be placed on a Coast, Lake, Reef or Kelp Forest tile adjacent to a sea Resource. "),
	("LOC_IMPROVEMENT_GOLF_COURSE_XP2_DESCRIPTION",				"Unlocks the Builder ability to construct a Golf Course, unique to Scotland.[NEWLINE][NEWLINE]+2 [ICON_AMENITIES] Amenities, +2 [ICON_GOLD] Gold, +1 [ICON_Housing] Housing. +1 [ICON_CULTURE] Culture if adjacent to a City Center district and +1 [ICON_CULTURE] Culture if adjacent to an Entertainment Complex district. +1 [ICON_CULTURE] Culture for every adjacent Districts after complete the Humanism Civic. +1 [ICON_Housing] after complete Globalization Civic. Cannot be placed on Desert or Desert Hills. One per city. Tiles with Golf Courses cannot be swapped. +1 Appeal to adjacent tiles."),
	("LOC_IMPROVEMENT_GREAT_WALL_EXPANSION2_DESCRIPTION",		"Unlocks the Builder ability to construct the Great Wall, unique to China.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +2 [ICON_GOLD] Gold. Provides an increase to [ICON_Strength] Defense. Enemy military units recieve -2 [ICON_Strength] Strength for each adjacent Great Wall. +2 [ICON_Culture] Culture for each adjacent Great Wall. +2 [ICON_Gold] Gold for each adjacent Great Wall after researching 'Castles' Technology. Must be built in a line along the borders of your empire. Can be built on Mountain or Forest tiles. Can only be pillaged (never destroyed) by natural disasters."),
	("LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION",				"Unlocks the Builder ability to construct an Ice Hockey Rink, unique to Canada.[NEWLINE][NEWLINE]+1 [ICON_AMENITIES] Amenity. +1 [ICON_CULTURE] Culture for each adjacent Tundra, Tundra Hills, Snow, and Snow Hills tile. +2 [ICON_FOOD] Food and [ICON_PRODUCTION] Production once the Professional Sports civic is unlocked. +4 [ICON_CULTURE] Culture if adjacent to a Stadium building. Can be built on Tundra, Tundra Hills, Snow, and Snow Hills. Cannot be built adjacent to another Ice Hockey Rink. +2 Appeal."),
	("LOC_IMPROVEMENT_ROCK_HEWN_CHURCH_EXPANSION2_DESCRIPTION",	"Unlocks the Builder ability to construct a Rock-Hewn Church, unique to Ethiopia. [NEWLINE][NEWLINE]+1 [ICON_FAITH] Faith and +1 [ICON_FOOD] Food. +1 [ICON_FAITH] Faith for every adjacent Hills and Mountain tile. May purchase Builders and Settlers with [ICON_FAITH] Faith in this city. Can only be built on Hills."),
	("LOC_IMPROVEMENT_MISSION_EXPANSION2_DESCRIPTION",			"Unlocks the Builder ability to construct a Mission, unique to Spain.[NEWLINE][NEWLINE]+2 [ICON_Faith] Faith. +2 [ICON_SCIENCE] Science after progressing 'Exploration' Civic. +1 [ICON_Science] Science for every adjacent Campus or Holy Site. In cities with a Mission adjacent to Holy Site, [ICON_CITIZEN] Citizens provide +0.2 [ICON_FAITH] Faith. In cities with a Mission adjacent to Campus, [ICON_CITIZEN] Citizens provide +0.2 [ICON_SCIENCE] Science. These bonuses for [ICON_CITIZEN] citizens are doubled if the city is not on your [ICON_CAPITAL] Capital's continent or is captured by you. "),
	("LOC_IMPROVEMENT_POLDER_NAME",								"Coastal Polder"),
	("LOC_IMPROVEMENT_POLDER_DESCRIPTION",						"Unlocks the Builder ability to construct a Coastal Polder, unique to Netherlands.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_Production] Production and +0.5 [ICON_Housing] Housing. +1 [ICON_FOOD] Food for every 2 adjacent Coastal Polder or Floodplain Polder tiles, or for every adjacent Coastal Polder or Floodplain Polder after progressing 'Naval Tradition' Civic. Extra +1 [ICON_FOOD] Food for every adjacent Coastal Polder or Floodplain Polder after researching 'Steam Power' Technology. +1 [ICON_PRODUCTION] Production for every 2 adjacent Coastal Polder or Floodplain Polder tiles, or for every adjacent Coastal Polder or Floodplain Polder after researching 'Mass Production' Technology. +2 [ICON_GOLD] for every adjacent Coastal Polder or Floodplain Polder after researching 'Civil Engineering' Technology. Must be placed on a Lake or Coast tile adjacent to passable land tile. Increases [ICON_Movement] Movement Cost by 2."),
	("LOC_IMPROVEMENT_LAND_POLDER_NAME",						"Floodplain Polder"),
	("LOC_IMPROVEMENT_LAND_POLDER_DESCRIPTION",					"Unlocks the Builder ability to construct a Floodplain Polder, unique to Netherlands.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food, +1 [ICON_Production] Production and +0.5 [ICON_Housing] Housing. +1 [ICON_FOOD] Food for every 2 adjacent Coastal Polder or Floodplain Polder tiles, or for every adjacent Coastal Polder or Floodplain Polder after researching 'Buttress' Technology. Extra +1 [ICON_FOOD] Food for every adjacent Coastal Polder or Floodplain Polder after researching 'Steam Power' Technology. +1 [ICON_PRODUCTION] Production for every 2 adjacent Coastal Polder or Floodplain Polder tiles, or for every adjacent Coastal Polder or Floodplain Polder after researching 'Mass Production' Technology. +2 [ICON_GOLD] for every adjacent Coastal Polder or Floodplain Polder after researching 'Civil Engineering' Technology. Must be placed on a Lake or Coast tile adjacent to passable land tile. Increases [ICON_Movement] Movement Cost by 2."),
	-- UI of Minors	
	("LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",					"Unlocks the Builder ability to construct a Mahavihara.[NEWLINE][NEWLINE]+2 [ICON_SCIENCE] Science, +1 [Icon_Housing] Housing. +1 [ICON_Science] Science for every adjacent Campus or Holy Site district, which becomes +2 [ICON_Science] Science after progressing 'Divine Right' Civic. +1 [ICON_Science] Science for every adjacent Neighborhood. Must be built on flat terrain. Cannot be built adjacent to another Mahavihara."),
	("LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",				"Unlocks the Builder ability to construct a Trading Dome.[NEWLINE][NEWLINE]Provides the basic yield of all Luxury resource types improved by your Trading Dome. After researching 'Currency' Technology, your [ICON_TradeRoute] Trade Routes start from this city provide the same yield, which is doubled after researching 'Economics' Technology. +2 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] if built on non-Floodplains Desert tile. Can only be built on land Luxury resource, and the city will gain use of that Resource. One per city."),
	("LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",		"Unlocks the Builder ability to construct a Monastery.[NEWLINE][NEWLINE]+2 [ICON_Faith] Faith, +1 [ICON_HOUSING] Housing. +15 HP healing for friendly religious unit on this tile that has not attacked this turn. +2 [ICON_FAITH] Faith for every adjacent District, which becomes +3 [ICON_FAITH] Faith after progressing 'Reformed Church' Civic. Extra +1 [ICON_HOUSING] Housing after progressing 'Colonialism' Civic. One per city."),
	("LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",			"Unlocks the Builder ability to construct an Alcázar.[NEWLINE][NEWLINE]+2 [ICON_Culture] Culture. Provides [ICON_SCIENCE] Science equal to the tile's Appeal. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification. Cannot be built next to another Alcázar."),
	("LOC_IMPROVEMENT_BATEY_DESCRIPTION",						"Unlocks the Builder ability to construct a Batey.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every adjacent Bonus Resource, Luxury Resource, Entertainment Complex or Neighborhood, which becomes +2 after progressing 'Humanism' Civic. Cannot be built adjacent to another Batey."),
	("LOC_IMPROVEMENT_COLOSSAL_HEAD_EXPANSION2_DESCRIPTION",	"Unlocks the Builder ability to construct a Colossal Head.[NEWLINE][NEWLINE]+1 [ICON_Faith] Faith. +1 [ICON_Faith] Faith for every 2 adjacent Rainforest tiles or for every adjacent Rainforest tile after progressing 'Humanism' Civic. +1 [ICON_Faith] Faith for every 2 adjacent Woods tiles or for every adjacent Woods tile after progressing 'Humanism' Civic. Can be built on Rainforest and Woods tiles."),
	("LOC_IMPROVEMENT_MOUND_DESCRIPTION",						"Unlocks the Builder ability to construct a Cahokia Mounds.[NEWLINE][NEWLINE]+3 [ICON_GOLD] Gold, +1 [ICON_HOUSING] Housing. Cities with Cahokia Mounds receive +1 [ICON_AMENITIES] Amenity, extra +1 for cities with at least 2 Cahokia Mounds. +1 [ICON_FOOD] Food for every adjacent District, which becomes +2 [ICON_FOOD] Food after progressing 'Historical Philosophy' Civic. Cannot be built adjacent to another Cahokia Mounds."),
	("LOC_IMPROVEMENT_NAZCA_LINE_DESCRIPTION",					"Unlocks the Builder ability to construct a Nazca Line.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food to adjacent tiles. Extra +1 [ICON_FOOD] after researching 'Engineering' Technology, +1 [ICON_PRODUCTION] Production after researching 'Mass Production' Technology. Cities Adjacent to Nazca Line recieve +2 [ICON_HOUSING] Housing. Provides standard adjacency bonus for Campus, Holy Site and Theater Square districts, which becomes major adjacency bonus after progressing 'Archaeology' Civic. Can only be built on flat Desert. Cannot be built adjacent to another Nazca Line. This tile cannot be worked."),
	("LOC_NAZCA_LINE_HOLY_SITE_ADJACENCY_DESCRIPTION",			"+{1_num} [ICON_FAITH] Faith from adjacent Nazca Line {1_Num : plural 2?Tiles; other?Tile;}."),
	("LOC_NAZCA_LINE_CAMPUS_ADJACENCY_DESCRIPTION",				"+{1_num} [ICON_SCIENCE] Science from adjacent Nazca Line {1_Num : plural 2?Tiles; other?Tile;}."),
	("LOC_NAZCA_LINE_THEATER_ADJACENCY_DESCRIPTION",			"+{1_num} [ICON_CULTURE] Culture from adjacent Nazca Line {1_Num : plural 2?Tiles; other?Tile;}."),
	("LOC_IMPROVEMENT_MOAI_DESCRIPTION",						"Unlocks the Builder ability to construct a Moai.[NEWLINE][NEWLINE]+2 [ICON_Culture] Culture. +2 [ICON_Culture] Culture if on or adjacent to a Volcanic Soil. +1 [ICON_Culture] Culture if adjacent to Coast or Lake. +1 [ICON_Culture] Culture for every 2 adjacent Moai or for every adjacent Moai after progress 'Medieval Faires' Civic. Can be built on Plains, Plains Hills, Grassland, Grassland Hills, or Volcanic Soil. Cannot be built adjacent to Woods or Rainforest tile."),
	-- UI of Governor
	("LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",					"+2 Appeal to adjacent tiles and +1 [ICON_Culture] Culture. Cannot be adjacent to another City Park. If the city park is in a city with a Surveyor Governor with the Parks and Recreation promotion, it provides +1 of all yields to all adjacent tiles."),

	-- To be moved
	("LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",				"All Districts (except City Centers) do not remove Forest, Rainforest and Marsh. Receive the following yields for every building and Districts itself on these features: +2 [ICON_Production] Production in Forest, +2 [ICON_Food] Food in Rainforest and +2 [ICON_Science] in Marsh. Woods can be planted with the Mysticism civic.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
	(Language,		Tag,														Text)
values
	("zh_Hans_CN",	"LOC_IMPROVEMENT_BUTTRESS_ON_FLOODLANDS",					"[NEWLINE][NEWLINE]解锁“扶壁”科技后，可以建造在泛滥平原上。"),
	-- 基础改良
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",						"解锁建造者建造矿山的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。研究“铸铜术”科技后，若靠近山脉单元格，额外+1 [ICON_Production] 生产力（学徒后失效）。 每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。相邻单元格-1魅力。[NEWLINE][NEWLINE]只能在丘陵或有效资源上建造，研究“工程”科技后也可以建造在地热裂缝上。如果建在奢侈品资源或战略资源上，城市则可以利用该资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",					"解锁建造者建造采石场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。相邻单元格-1魅力。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。[NEWLINE][NEWLINE]城市若拥有采石场，则建造远古和古典奇观加速10%，建造中古和文艺复兴的奇观加速5%。若该城市还拥有第二个采石场，则该加成加倍。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",				"解锁建造者建造渔船的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若城市有港口区域，则+1 [ICON_Food] 食物。每相邻1个港口区域则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",				"解锁建造者建造种植园的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物。研究“灌溉”科技后，相邻淡水或水渠的种植园+2 [ICON_GOLD] 金币（封建后失效）。每相邻1个商业中心单元格则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",					"解锁建造者建造牧场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在战略资源上，城市则可以利用该资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",						"解锁建造者建造农场的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物。若本城有水渠，则相邻淡水或水渠的农场+1 [ICON_Food] 食物。[NEWLINE][NEWLINE]只能建在草原或平原上。解锁“土木工程”市政后也能建造在草原丘陵或平原丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",						"解锁建造者建造营地的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物。每相邻1个商业中心单元格则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。解锁“弓箭”科技后也可建造在森林上。解锁“公会”市政后也可建造在雨林上。[NEWLINE][NEWLINE]如建在奢侈品资源上，城市则能利用该资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",				"解锁建造者建造伐木场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]只能建在树林上。每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。解锁“公会”市政后也能建造在雨林上。"), -- 研究“铸铜术”科技后，若沿河，额外+1 [ICON_Production] 生产力。
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",					"解锁建造者建造渔场的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物，+0.5 [ICON_Housing] 住房。每相邻1个海洋资源，则额外+1 [ICON_Food] 食物；必须建在海岸格位上。研究“科学理论”科技后，+1 [ICON_Housing] 住房。无法建在另一个渔场旁。"),
	-- 文明特色改良
	("zh_Hans_CN",	"LOC_IMPROVEMENT_OUTBACK_STATION_DESCRIPTION",				"解锁建造者修建澳大利亚特色改良设施内陆牧场的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物和+1 [ICON_PRODUCTION] 生产力并+0.5 [Icon_Housing] 住房。每相邻一个牧场+1 [ICON_Food] 食物。每相邻两个“内陆牧场”，牧场与“内陆牧场”便+1 [ICON_Food] 食物（完成科技“银行业”后，也获得+1 [ICON_Production] 生产力）。只能建在沙漠、沙漠丘陵、草原和平原单元格上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",					"解锁建造者建造印加特色改良梯田农场的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物, +1 [ICON_Housing] 住房。如果相邻淡水则+1 [ICON_PRODUCTION] 生产力。每相邻1个山脉单元格+1 [ICON_FOOD] 食物，解锁“工程”科技后变为+2 [ICON_FOOD] 食物。解锁“封建主义”市政后每相邻2个梯田农场+1 [ICON_FOOD] 食物，解锁“生物”科技后变为每1个。解锁“建造”科技后每相邻2个梯田农场+1 [ICON_PRODUCTION] 生产力。如果建造在资源上，触发“灌溉”科技的 [ICON_TECHBOOSTED] 尤里卡和“封建主义”市政的 [ICON_CIVICBOOSTED] 鼓舞。只能建在草原、平原或沙漠的丘陵或山脉上（包括火山）。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",					"解锁建造者建造马普切特色改良马普切木人的能力。[NEWLINE][NEWLINE]+1 [Icon_Production] 生产力。提供等同于所在单元格魅力100%的 [ICON_CULTURE] 文化值。只能建造在迷人或惊艳魅力的单元格上。可以建造在森林上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",			"解锁建造者建造埃及特色改良狮身人面像的能力。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值。提供所有相邻奇观的基础产出。为相邻农场+1 [ICON_FOOD]食物。为相邻单元格+2魅力。如果一个城市拥有位于泛滥平原且相邻市中心的狮身人面像，该城市在河边建造区域与奇观时额外+15%建造速度。无法建在另一个狮身人面像旁。无法建在雪地或雪地丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",						"解锁建造者建造克里特色改良棚屋的能力。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币、+1 [ICON_Housing] 住房。完成“行政部门”市政后额外+1 [ICON_PRODUCTION]和+1 [ICON_HOUSING] 住房。每相邻1个加成资源+1 [ICON_FOOD] 食物。每相邻1个奢侈或战略资源+1 [ICON_PRODUCTION] 生产力。解锁“制图学”科技后，每相邻1个奢侈资源+2 [ICON_GOLD]金币。必须建在与加成或奢侈资源相邻的单元格上。解锁“采矿”科技后可以建造在森林上。无法建在另一个棚屋旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",						"解锁建造者建造大庄园（大哥伦比亚特色改良设施）的能力。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币、+1 [ICON_PRODUCTION] 生产力并+0.5 [Icon_Housing] 住房。每相邻一个种植园则+1 [ICON_Food] 食物。每相邻2座大庄园，种植园与大庄园便+1 [ICON_Production] 生产力（获得市政“重商主义”后，每相邻1座大庄园便能获得加成）。只能建造在雨林、平原、平原丘陵、草原和草原丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",					"解锁建造者建造波斯特色改良波斯庭院的能力。[NEWLINE][NEWLINE]+1 [ICON_CULTURE] 文化值、+2 [ICON_GOLD] 金币。每相邻1个圣地或剧院广场+1 [ICON_CULTURE] 文化值。每相邻1个商业中心或市中心+1 [ICON_GOLD] 金币。每相邻1个市中心+1 [ICON_FOOD] 食物。您每拥有1个市政广场和市政广场建筑+1 [ICON_CULTURE] 文化值。解锁“行政部门”市政后+1 [ICON_Culture] 文化值。为相邻单元格+2魅力。无法建在雪地、冻土、雪地丘陵或冻土丘陵上，也无法建在另一座波斯庭院旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PAIRIDAEZA_ETHIOPIA_DESCRIPTION",			"解锁建造者建造波斯特色改良波斯庭院的能力。[NEWLINE][NEWLINE]+1 [ICON_CULTURE] 文化值、+2 [ICON_GOLD] 金币。每相邻1个圣地或剧院广场+1 [ICON_CULTURE] 文化值。每相邻1个商业中心或市中心+1 [ICON_GOLD] 金币。每相邻1个市中心+1 [ICON_FOOD] 食物。您每拥有1个市政广场和市政广场建筑+1 [ICON_CULTURE] 文化值，每拥有一个外交区和外交区建筑+2 [ICON_GOLD] 金币。解锁“行政部门”市政后+1 [ICON_Culture] 文化值。为相邻单元格+2魅力。无法建在雪地、冻土、雪地丘陵或冻土丘陵上，也无法建在另一座波斯庭院旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_KURGAN_DESCRIPTION",						"解锁建造者建造斯基泰特色改良坟墩的能力。[NEWLINE][NEWLINE]+1 [ICON_Faith] 信仰值、+3 [ICON_Gold] 金币。每相邻1个牧场+1 [ICON_Faith] 信仰值，解锁“马镫”科技后变为+2 [ICON_Faith] 信仰值。每隐退一个 [ICON_GREATGENERAL] 大将军+2 [ICON_FAITH] 信仰值。为相邻的牧场+1 [ICON_Faith] 信仰值。允许城市用 [ICON_FAITH] 信仰购买骑兵单位。不能建在丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",						"解锁建造者建造努比亚特色改良努比亚金字塔的能力。+2 [ICON_Faith] 信仰值、+1 [ICON_Food] 食物。如果建造在沙漠单元格（非泛滥平原），额外+2 [ICON_Faith] 信仰值、+1 [ICON_Food] 食物。对于每个相邻的提供相邻加成的区域，努比亚金字塔获得+1对应产出（对于商业中心和港口则是+2 [ICON_GOLD] 金币）。每相邻1个市中心+1 [ICON_Food] 食物。每相邻1个市政广场+1 [ICON_CULTURE] 文化值。解锁“封建主义”市政后，相邻区域得到的产出翻倍。只能建造在沙漠、草原或平原（包括丘陵或泛滥平原）上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ZIGGURAT_DESCRIPTION",						"解锁建造者建造苏美尔特色改良金字形神塔的能力。[NEWLINE][NEWLINE]+2 [ICON_Science] 科技值。如果相邻河流，+1 [ICON_Food] 食物和+1 [ICON_Culture] 文化值。从远古时代起，每经过一个时代额外+1 [ICON_Science] 科技值。不能建在丘陵上，但可建在泛滥平原上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CHATEAU_EXPANSION2_DESCRIPTION",			"解锁建造者建造法国特色改良城堡庄园的能力。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值、+2 [ICON_Gold] 金币、+1 [ICON_HOUSING] 住房。解锁“城堡”科技后，每相邻1个奢侈资源+1 [ICON_CULTURE] 文化值。解锁“公会”市政后，每相邻1个奢侈资源+2 [ICON_GOLD] 金币。为相邻单元格+1魅力。必须建在加成或奢侈品资源旁。[NEWLINE][NEWLINE]若开启了“行业与公司模式”，对于每种相邻的已被种植园改良的奢侈资源，城堡庄园获得其行业效果，每个城市仅限建造一座。[NEWLINE][NEWLINE]若未开启“行业与公司模式”，每相邻1个加成资源+2 [ICON_GOLD] 金币，每相邻1个奇观+2 [ICON_Culture] 文化值，无法建在另一座城堡庄园旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_STEPWELL_EXPANSION2_DESCRIPTION",			"解锁建造者建造印度特色改良设施梯井的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物、+1 [ICON_Housing] 住房。如与圣地区域相邻，+1 [ICON_Faith] 信仰值。给相邻的农场和种植园+1 [ICON_FOOD] 食物。有梯井的城市+1 [ICON_AMENITIES] 宜居度，每位 [ICON_CITYZEN] 公民+0.5 [ICON_FOOD] 食物。解锁“封建主义”市政后+1 [ICON_Faith] 信仰。解锁“卫生设备”科技后+1 [ICON_Food] 食物、+1 [ICON_Housing] 住房。干旱期间可防止 [ICON_Food] 食物损失。不能建在丘陵上，不能建在另一个梯井旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_KAMPUNG_DESCRIPTION",						"解锁建造者建造印度尼西亚特色改良甘榜屋的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物、+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房。每相邻1个市中心+1 [ICON_PRODUCTION] 生产力。每相邻1个渔船+1 [ICON_PRODUCTION] 生产力。解锁“土木工程”科技后，+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房，渔船每相邻2个甘榜屋+1 [ICON_PRODUCTION] 生产力。必须建造在靠近海洋资源的海岸、湖泊或礁石单元格上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_KAMPUNG_KELP_DESCRIPTION",					"解锁建造者建造印度尼西亚特色改良甘榜屋的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物、+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房。相邻市中心+1 [ICON_PRODUCTION] 生产力。每相邻1个渔船+1 [ICON_PRODUCTION] 生产力。解锁“土木工程”科技后，+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房，渔船每相邻2个甘榜屋+1 [ICON_PRODUCTION] 生产力。必须建造在靠近海洋资源的海岸、湖泊、礁石或海藻森林单元格上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_GOLF_COURSE_XP2_DESCRIPTION",				"解锁建造者建造高尔夫球场（苏格兰特色改良设施）的能力。[NEWLINE][NEWLINE]+2 [ICON_AMENITIES] 宜居度、+2 [ICON_GOLD] 金币、+1 [ICON_Housing] 住房。如与市中心区域相邻，则+1 [ICON_CULTURE] 文化值；如与娱乐设施区域相邻，则+1 [ICON_CULTURE] 文化值。解锁人文主义后，每相邻一个区域+1 [ICON_CULTURE] 文化值。解锁全球化后+1 [ICON_Housing] 住房。无法建在沙漠或沙漠丘陵地貌上。每座城市仅限建造一座。拥有高尔夫球场的单元格无法切换。为相邻单元格提供+1魅力。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_GREAT_WALL_EXPANSION2_DESCRIPTION", 		"解锁建造者建造中国特色改良设施长城的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物，+2 [ICON_GOLD] 金币。提升 [ICON_Strength] 防御力。敌方军事单位每相邻一段长城-2 [ICON_Strength] 战斗力。每相邻1个长城+2 [ICON_Culture] 文化值。解锁“城堡”科技后，每相邻1个长城+2 [ICON_GOLD] 金币。必须沿着帝国的边界线建造。可以修建在山脉和树林上。仅能被自然灾害掠夺（不会遭到破坏）。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION",				"解锁建造者建造加拿大特色改良设施冰球场的能力。[NEWLINE][NEWLINE]+1 [ICON_AMENITIES] 宜居度；每个相邻的冻土、冻土丘陵、雪地、雪地丘陵单元格提供+1 [ICON_CULTURE] 文化值。解锁“职业体育”市政后，+2 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力。若与建筑“体育场”相邻，+4 [ICON_CULTURE] 文化值。可以修建在冻土、冻土丘陵、雪地和雪地丘陵之上。无法建造在另一座冰球场旁，+2魅力。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ROCK_HEWN_CHURCH_EXPANSION2_DESCRIPTION",	"解锁建造者建造埃塞俄比亚特色改良设施独石教堂的能力。[NEWLINE][NEWLINE]+1 [ICON_FAITH] 信仰值，+1 [ICON_FOOD] 食物。每相邻1个丘陵或山脉+1 [ICON_FAITH] 信仰值。可以在此城市中用信仰购买建造者和开拓者。只能建造在丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MISSION_EXPANSION2_DESCRIPTION",			"解锁建造者建造西班牙特色改良传教团的能力。[NEWLINE][NEWLINE]+2 [ICON_Faith] 信仰值。解锁“探索”市政后额外+2 [ICON_SCIENCE] 科技值。每相邻1个学院或圣地+1 [ICON_Science] 科技值。在拥有相邻圣地的传教团的城市中，每位 [ICON_CITIZEN] 公民+0.2 [ICON_FAITH] 信仰值。在拥有相邻学院的传教团的城市中，每位 [ICON_CITIZEN] 公民+0.2 [ICON_SCIENCE] 科技值。在与 [ICON_CAPITAL] 首都不在同一大陆的城市或您占领的城市中，这些给 [ICON_CITIZEN] 公民的加成翻倍。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_POLDER_NAME",								"滨海圩田"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_POLDER_DESCRIPTION",						"解锁建造者建造荷兰特色改良滨海圩田的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物、+1 [ICON_Production] 生产力、+0.5 [ICON_Housing] 住房。每相邻2个滨海圩田或淤滩圩田+1 [ICON_FOOD] 食物，解锁“海军传统”市政后变为每相邻1个滨海圩田或淤滩圩田。解锁“蒸汽动力”科技后每相邻1个滨海圩田或淤滩圩田额外+1 [ICON_FOOD] 食物。每相邻2个滨海圩田或淤滩圩田+1 [ICON_PRODUCTION] 生产力，解锁“批量生产”科技后变为每相邻1个滨海圩田或淤滩圩田。解锁“土木工程”科技后每相邻1个滨海圩田或淤滩圩田+2 [ICON_GOLD] 金币。必须建在相邻可通行陆地单元格的海岸或湖泊上，可以建在礁石上。[ICON_Movement] 移动力消耗增加2点。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_LAND_POLDER_NAME",							"淤滩圩田"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_LAND_POLDER_DESCRIPTION",					"解锁建造者建造荷兰特色改良淤滩圩田的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物、+1 [ICON_Production] 生产力、+0.5 [ICON_Housing] 住房。每相邻2个滨海圩田或淤滩圩田+1 [ICON_FOOD] 食物，解锁“扶壁”科技后变为每相邻1个滨海圩田或淤滩圩田。解锁“蒸汽动力”科技后每相邻1个滨海圩田或淤滩圩田额外+1 [ICON_FOOD] 食物。每相邻2个滨海圩田或淤滩圩田+1 [ICON_PRODUCTION] 生产力，解锁“批量生产”科技后变为每相邻1个滨海圩田或淤滩圩田。解锁“土木工程”科技后每相邻1个滨海圩田或淤滩圩田+2 [ICON_GOLD] 金币。必须建在相邻可通行陆地单元格的海岸或湖泊上，可以建在礁石上。[ICON_Movement] 移动力消耗增加2点。"),
	-- 城邦改良	
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",					"解锁建造者建造大寺的能力。[NEWLINE][NEWLINE]+2 [ICON_SCIENCE] 科技值、+1 [Icon_Housing] 住房。每相邻1个学院或圣地区域+1 [ICON_Science] 科技值，解锁“王权神授”市政后变为+2 [ICON_Science] 科技值。每相邻1个社区+1 [ICON_SCIENCE] 科技值。必须建在平坦地貌上。无法建在另一个大寺旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",					"解锁建造者建造圆顶市集的能力。[NEWLINE][NEWLINE]获得等同于您的圆顶集市改良的每一种奢侈资源基础产出相同的产出。研究“货币”科技后，此城出发的 [ICON_TRADEROUTE] 贸易路线获得与圆顶集市相同的产出，研究“经济”科技后翻倍。若建造在沙漠单元格（非泛滥平原），则+2 [ICON_FOOD] 食物，+1 [ICON_PRODUCTION] 生产力。只能建造在陆地奢侈品资源上，且城市可以利用该资源。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",			"解锁建造者建造修道院的能力。[NEWLINE][NEWLINE]+2 [ICON_Faith] 信仰值，+1 [ICON_HOUSING] 住房。此单元格上的友方宗教单位生命值恢复+15（前提是其当前回合未发动攻击）。每相邻1个区域+2 [ICON_FAITH] 信仰值，解锁“归正会”市政后变为+3 [ICON_FAITH] 信仰值。解锁“殖民主义”市政后额外 +1 [ICON_HOUSING] 住房。每座城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",			"解锁建造者建造阿卡萨城堡的能力。[NEWLINE][NEWLINE]+2 [ICON_Culture] 文化值。提供等同于单元格魅力的 [ICON_SCIENCE] 科技值。占领单位 [ICON_Strength] 防御力+4，并自动获得2回合驻扎加成。无法建在另一座阿卡萨城堡旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_BATEY_DESCRIPTION",						"解锁建造者建造巴特依的能力。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值。每相邻1个加成资源、奢侈资源、娱乐中心或社区+1 [ICON_Culture] 文化值，完成“人文主义”市政后变为+2 [ICON_Culture] 文化值。无法建造在另一座巴特依旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_COLOSSAL_HEAD_EXPANSION2_DESCRIPTION", 	"解锁建造者建造巨神头像的能力。[NEWLINE][NEWLINE]+1 [ICON_Faith] 信仰值。每相邻2个雨林+1 [ICON_Faith] 信仰值，解锁“人文主义”市政后变为每相邻1个雨林。每相邻2个森林+1 [ICON_Faith] 信仰值，解锁“人文主义”市政后变为每相邻1个森林。可以建造在雨林或森林上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MOUND_DESCRIPTION",						"解锁建造者建造卡霍基亚土墩的能力。[NEWLINE][NEWLINE]+3 [ICON_GOLD] 金币、+1 [Icon_Housing] 住房。有卡霍基亚土墩的城市获得+1 [ICON_AMENITIES] 宜居度，有至少2个卡霍基亚土墩的城市额外+1 [ICON_AMENITIES] 宜居度。每相邻1个区域+1 [ICON_FOOD] 食物，解锁“历史哲学”市政后变为+2 [ICON_FOOD] 食物。无法建造在另一个卡霍基亚土墩旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_NAZCA_LINE_DESCRIPTION",					"解锁建造者建造纳斯卡巨画的能力。[NEWLINE][NEWLINE]相邻的单元格+1 [ICON_FOOD] 食物。解锁“工程”科技后额外+1 [ICON_FOOD] 食物，解锁“批量生成”科技后额外+1 [ICON_PRODUCTION] 生产力。相邻地资源+1 [ICON_Faith] 信仰值。相邻纳斯卡巨画的城市+2 [ICON_HOUSING] 住房。给学院、圣地和剧院广场提供标准相邻加成，解锁“考古学”市政后变为大量相邻加成。仅能建在平坦的沙漠上。无法建在另一个纳斯卡巨画旁。此单元格无法被工作。"),
	("zh_Hans_CN",	"LOC_NAZCA_LINE_HOLY_SITE_ADJACENCY_DESCRIPTION",			"+{1_num} [ICON_FAITH] 信仰值来自相邻的纳斯卡巨画。"),
	("zh_Hans_CN",	"LOC_NAZCA_LINE_CAMPUS_ADJACENCY_DESCRIPTION",				"+{1_num} [ICON_SCIENCE] 科技值来自相邻的纳斯卡巨画。"),
	("zh_Hans_CN",	"LOC_NAZCA_LINE_THEATER_ADJACENCY_DESCRIPTION",				"+{1_num} [ICON_CULTURE] 文化值来自相邻的纳斯卡巨画。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MOAI_DESCRIPTION",							"解锁建造者建造摩艾石像的能力。[NEWLINE][NEWLINE]+2 [ICON_Culture] 文化值。在火山土上或与其相邻时+2 [ICON_Culture] 文化值。相邻湖泊或近海时+1 [ICON_Culture] 文化值。每相邻2个摩艾石像+1 [ICON_Culture] 文化值，解锁“中世纪集市”后变为每相邻1个摩艾石像。获得等同于 [ICON_Culture] 文化值产出的 [ICON_Tourism] 旅游业绩。只可建在平原、平原丘陵、草原、草原丘陵或火山土单元格之上。无法建在与树林或雨林相邻的单元格上。"),
	-- 总督改良
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",					"产出1 [ICON_Culture] 文化值，为相邻单元格+2魅力。无法建在另一个市立公园旁。当“测量师”总督梁（必须拥有“公园与休憩”升级）在城市就职时，市立公园为相邻单元格提供+1所有产出。"),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION", 				"所有区域（除市中心外）不移除树林、雨林、沼泽地貌。建在这些区域中的建筑以及区域本体和奇观将获得以下收益：建在树林上提供+2 [ICON_Production] 生产力、建在雨林上提供+2 [ICON_Food] 食物、建在沼泽上提供+2 [ICON_Science] 科技值。拥有“神秘主义”市政后即可栽种树林。"); 