--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                 Text)
values
    -- Base Improvements
    ("LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",               "Unlocks the Builder ability to construct Mines.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Production] Production if adjacent to mountaion tiles (obsolete with Apprenticeship Technology). +1 [ICON_Production] Production for each adjacent Industrial Zone District (except Hansa District). Extra +1 [ICON_Production] Production if the city owns a Workshop. -1 Appeal to all adjacent tiles. [NEWLINE][NEWLINE]Can be built on hills or valid resources. If built on Luxury or Strategic resources, the city will gain use of that resource."),
    ("LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",             "Unlocks the Builder ability to construct Quarries.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. +1 [ICON_Production] Production for each adjacent Industrial Zone District (except Hansa District). Extra +1 [ICON_Production] Production if a city owns a Workshop. -1 Appeal to all adjacent tiles. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on a Luxury resource, the city will gain use of that resource. [NEWLINE][NEWLINE]For each city owns a Quarry, +10% Production when building ancient and classical Wonders and 5% when building medieval era or renaissance era Wonders. And it doubles when the city owns the second Quarry."),
    ("LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",      "Unlocks the Builder ability to construct Fishing Boats.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Food] Food if the city owns a Harbor. +2 [ICON_Gold] Gold for each adjacent Harbor District.[NEWLINE][NEWLINE]Can only be built on valid resources. If built on Luxury resources, the city will gain use of that resource."),
    ("LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",         "Unlocks the Builder ability to construct Plantations.[NEWLINE][NEWLINE]+2 [ICON_Gold] Gold. Extra +1 [ICON_Food] Food if adjacent to fresh water or Aqueduct District. +2 [ICON_Gold] Gold for each adjacent Commercial Hub District. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on Luxury resources, the city will gain use of that resource."),
    ("LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",            "Unlocks the Builder ability to construct Pastures.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. [NEWLINE][NEWLINE]Can only be built on valid resources. If built on Strategic resources, the city will gain use of that resource."),
    ("LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",               "Unlocks the Builder ability to construct Farms.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. All farms that are adjacent to fresh water or Aquedect District +1 [ICON_Food] Food if the city owns a Aqueduct District.[NEWLINE][NEWLINE]Can only be built on Grassland or Plains. Once Civil Engineering is unlocked it can also be built on Grassland Hills or Plains Hills."),
    ("LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",               "Unlocks the Builder ability to construct Camps.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. +2 [ICON_Gold] Gold for each adjacent Entertainment Complex District. [NEWLINE][NEWLINE]Can only be built on valid resources. Once Archery is unlocked it can also be built on Forests. Once Guilds is unlocked it can also be built on Rainforest. [NEWLINE][NEWLINE]If built on Luxury resources, the city will gain use of that resource."),
    ("LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",        "Unlocks the Builder ability to construct a Lumber Mill.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. Extra +1 [ICON_Production] Production if adjacent to rivers.[NEWLINE][NEWLINE]Can only be built on Woods. Once Guilds is unlocked it can also be built on Rainforest."),
    ("LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",            "Unlocks the Builder ability to construct a Fishery.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +0.5 [ICON_Housing] Housing; +1 additional [ICON_Food] Food for each adjacent sea resource. Must be built on a coastal plot."),
    -- UI of Majors
    ("LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",          "Unlocks the Builder ability to construct a Terrace Farm, unique to the Inca.[NEWLINE][NEWLINE]+1 [ICON_FOOD] Food. Provides +1 [ICON_Housing] Housing for every Terrace Farms. +1 [ICON_FOOD] Food for each adjacent Mountain Tile ,+1 [ICON_FOOD] Food after researching Engineeing. Gain +2 [ICON_PRODUCTION] Production for each adjacent Aqueduct district. Receive +1 [ICON_PRODUCTION] Production if adjacent to Fresh Water and not an Aqueduct district. Additional [ICON_FOOD] Food as you advance through the Civics and Technology Tree for adjacency with other Terrace Farms. Can be placed on Grassland Hills, Plains Hills, and Desert Hills."),
    ("LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",             "Unlocks the Builder ability to construct a Chemamull, unique to Mapuche.[NEWLINE][NEWLINE]+1 [Icon_Production] Production. Provides [ICON_CULTURE] Culture equal to 100% of the tile's Appeal. Additional [ICON_TOURISM] Tourism after researching Flight. Minimum Appeal of Charming."),
    ("LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",     "Unlocks the Builder ability to construct a Sphinx, unique to Egypt.[NEWLINE][NEWLINE]+1 [ICON_Faith] Faith and +1 [ICON_Culture] Culture. +2 Appeal. +2 [ICON_Faith] Faith if next to a wonder. +1 [ICON_CULTURE] Culture if built on Floodplains. Each Sphinx +1 [Icon_food] Food to adjacent Farm if the Farm is built on Floodplains. [NEWLINE] Additional [ICON_CULTURE] Culture once Natural History is discovered. Provides [ICON_TOURISM] Tourism after researching Flight. Cannot be built next to another Sphinx. Cannot be built on Snow or Snow Hills."),
    ("LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",               "Unlocks the Builder ability to construct a Mekewap, unique to Cree.[NEWLINE][NEWLINE]Provides +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing. Extra +1 [ICON_Housing] Housing after completing Civil Service. +1 [ICON_GOLD] Gold if adjacent to a Luxury resource. For every adjacent Bonus Resource +1 [ICON_FOOD] Food. Additional [ICON_PRODUCTION] Production, [ICON_GOLD] Gold as you advance through the Civics and Technology Tree. Must be placed adjacent to a Bonus or Luxury resource. Cannot be built adjacent to another Mekewap."),
    ("LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",              "Unlocks the Builder ability to construct a Hacienda, unique to Gran Colombia.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold, +1 [ICON_PRODUCTION] Production, and +0.5 [Icon_Housing] Housing. +1 [ICON_Food] Food for every adjacent Plantation (increased to +2 [ICON_Food] Food for every Plantation with Replaceable Parts). Plantations and Haciendas receive +1 [ICON_Production] Production for every two adjacent Haciendas (increased to every Hacienda with Mercantilism). Can only be built on Plains, Plains Hills, Grassland and Grassland Hills."),
    ("LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",            "Unlocks the Builder ability to construct a Pairidaeza, unique to Persia.[NEWLINE][NEWLINE]+1 [ICON_CULTURE] Culture and +2 [ICON_GOLD] Gold. +2 Appeal. +1 [ICON_CULTURE] Culture for each adjacent Holy Site and Theater Square. +1 [ICON_GOLD] Gold for each adjacent Commercial Hub and City Center. City receive +1 [ICON_AMENITIES] Amenity from their first Priidaeza improment.Additional [ICON_Culture] Culture and [ICON_Tourism] Tourism as you advance through the Technology and Civics Tree. Cannot be built on Snow, Tundra, Snow Hills, or Tundra Hills or adjacent to another Pairidaeza."),
    ("LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",               "Improvement that unlocks with Masonry and can be built on Desert Floodplains, Desert, Plains, Grass (including Hills). +2 [ICON_Faith] Faith and +1 [ICON_Food] Food. +1 [ICON_FOOD] Food after researching Theology. Receives additional yields from adjacent districts. +1 [ICON_Food] Food if adjacent to a city center. For all other districts that award adjacency bonuses: +1 of the appropriate yield if that district is adjacent. If build on Desert, Desert Hills extra +2 [ICON_Faith] Faith and +2 [ICON_Food] Food."),
    -- UI of Minors
    ("LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",            "Your Builders can now make Mahavihara improvements.[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] Science and +1 [Icon_Housing] Housing. +1 [ICON_Science] Science for every adjacent Campus district or Holy Site district. After researching Scientific Theory receive an additional +1 [Icon_Science] Science for every adjacent Campus. Must be built on flat terrain not adjacent to another Mahavihara."),
    ("LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",          "Your Builders can now make Trading Dome improvements.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold. +1 [ICON_Gold] Gold for every adjacent Luxury resource. Your outgoing international [ICON_TradeRoute] Trade Routes grant +2 [ICON_GOLD] Gold per Trading Dome at the origin. Cannot be built next to another Trading Dome."),
    ("LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",  "Your Builders can now make Monastery improvements.[NEWLINE][NEWLINE]Monasteries provide +2 [ICON_Faith] Faith. +15 HP healing for friendly religious unit on this tile that has not attacked this turn. +1 [ICON_FAITH] Faith for every adjacent Districts. +2 [ICON_FAITH] Faith for every adjacent Districts once Divine Right is discovered. Provides +1 [ICON_HOUSING] Housing. Receive an additional [ICON_HOUSING] Housing once Colonialism is discovered. Cannot be built next to another Monastery."),
    ("LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",    "Unlocks the Builder ability to construct an Alcázar.[NEWLINE][NEWLINE]+3 [ICON_Culture] Culture. Provides [ICON_SCIENCE] Science equal to 75% of the tile's Appeal. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification. Provides [ICON_TOURISM] Tourism after researching Flight. Cannot be built next to another Alcázar."),
    ("LOC_IMPROVEMENT_BATEY_DESCRIPTION",                 "Unlocks the Builder ability to construct a Batey.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture for every adjacent Bonus Resource and Entertainment Complex (increased to +2 [Icon_Culture] Culture when Humanism is discovered). Provides [Icon_Tourism] Tourism after researching Flight. Cannot be built adjacent to another Batey or on Hills."),
    -- UI of Governor
    ("LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",             "+2 Appeal to adjacent tiles and +1 [ICON_Culture] Culture. Cannot be adjacent to another City Park. If the city park is in a city with a Surveyor Governor with the Parks and Recreation promotion, it provides +1 of all yields to all adjacent tiles.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                 Text)
values
    -- 基础改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",               "解锁建造者建造矿山的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若靠近山脉单元格，额外+1 [ICON_Production] 生产力（学徒后失效）。 每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。若本城有工作坊，额外+1 [ICON_Production] 生产力。 相邻单元格-1魅力。[NEWLINE][NEWLINE]只能在丘陵或有效资源上建造。如果建在奢侈品资源或战略资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",             "解锁建造者建造采石场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。每相邻1个工业区（商业同业公会除外）单元格，额外+1 [ICON_Production] 生产力。若本城有工作坊，额外+1 [ICON_Production] 生产力。 相邻单元格-1魅力。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。[NEWLINE][NEWLINE]城市若拥有采石场，则建造远古和古典奇观加速10%，建造中古和文艺复兴的奇观加速5%。若该城市还拥有第二个采石场，则该加成加倍。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",      "解锁建造者建造渔船的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若城市有港口区域，则+1 [ICON_Food] 食物。每相邻1个港口区域则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",         "解锁建造者建造种植园的能力。[NEWLINE][NEWLINE]+2 [ICON_Gold] 金币。拥有淡水或相邻水渠的种植园+1 [ICON_Food] 食物。每相邻1个商业中心单元格则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在奢侈品资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",            "解锁建造者建造牧场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]只能在有效资源上建造。如果建在战略资源上，城市则可以利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",               "解锁建造者建造农场的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物。若本城有水渠，则相邻淡水或水渠的农场+1 [ICON_Food] 食物。[NEWLINE][NEWLINE]只能建在草原或平原上。解锁“土木工程”市政后也能建造在草原丘陵或平原丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",               "解锁建造者建造营地的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物。每相邻1个娱乐中心单元格则+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]只能在有效资源上建造。解锁“弓箭”科技后也可建造在森林上。解锁“公会”市政后也可建造在雨林上。[NEWLINE][NEWLINE]如建在奢侈品资源上，城市则能利用该资源。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",        "解锁建造者建造伐木场的能力。[NEWLINE][NEWLINE]+1 [ICON_Production] 生产力。若沿河，额外+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]只能建在树林上。解锁“公会”市政后也能建造在雨林上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",            "解锁建造者建造渔场的能力。[NEWLINE][NEWLINE]+1 [ICON_Food] 食物，+0.5 [ICON_Housing] 住房。每与1个海洋资源相邻，则额外+1 [ICON_Food] 食物；必须建在海岸格位上。"),
    -- 文明特色改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",          "解锁建造者建造印加特色设施印加梯田的能力。[NEWLINE][NEWLINE]+1 [ICON_FOOD] 食物；每块印加梯田+1 [ICON_Housing] 住房。每个相邻的山脉单元格+1 [ICON_FOOD] 食物，解锁工程科技后，每个相邻的山脉单元格额外+1 [ICON_FOOD] 食物。每个相邻的水渠区域+2 [ICON_PRODUCTION] 生产力。与淡水资源（非水渠区域）相邻时，+1 [ICON_PRODUCTION] 生产力（无法相互叠加）。随着市政与科技的发展，与其他印加梯田相邻时还可额外获得 [ICON_FOOD] 食物加成。可建在草原丘陵、平原丘陵与沙漠丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",             "解锁建造者建造马普切木人（马普切特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [Icon_Production] 生产力。提供等同于所在单元格魅力100%的 [ICON_CULTURE] 文化值。研究完“飞行”后可获得额外 [ICON_TOURISM] 旅游业绩。要求单元格至少达到迷人魅力。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",     "解锁建造者建造狮身人面像（埃及特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [ICON_Faith] 信仰值、+1 [ICON_Culture] 文化值。+2魅力。如果与奇观相邻，+2 [ICON_Faith] 信仰值。如建在泛滥平原上，+1 [ICON_CULTURE] 文化值。每个相邻的狮身人面像为相邻的建造在泛滥平原上的农场+1 [ICON_FOOD]食物。获得“自然历史”市政后将产出更多 [ICON_CULTURE] 文化值。[NEWLINE] 研究完“飞行”后其将提供 [ICON_TOURISM] 旅游业绩。无法建在另一个狮身人面像旁。无法建在雪地或雪地丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",               "解锁建造者建造棚屋（克里特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Housing] 住房。完成行政部门后额外+1 [ICON_HOUSING] 住房。如与奢侈品资源相邻，则+1 [ICON_GOLD] 金币。相邻的每个加成资源可使其+1 [ICON_FOOD] 食物。解锁更多市政和科技后即可获得更多 [ICON_PRODUCTION] 生产力和 [ICON_GOLD] 金币。必须建在与加成或奢侈品资源相邻的单元格上。无法建在另一个棚屋旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",              "解锁建造者建造大庄园（大哥伦比亚特色改良设施）的能力。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币、+1 [ICON_PRODUCTION] 生产力并+0.5 [Icon_Housing] 住房。每与1座种植园相邻则+1 [ICON_Food] 食物（解锁科技“零件规格化”后，每与1座种植园相邻便能获得+2 [ICON_Food] 食物）。每与2座大庄园相邻，种植园与大庄园便+1 [ICON_Production] 生产力（获得市政“重商主义”后，每与1座大庄园相邻便能获得加成）。只能建造在平原、平原丘陵、草原和草原丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",            "解锁建造者建造波斯庭院（波斯特色改良设施）的能力。[NEWLINE][NEWLINE]+1 [ICON_CULTURE] 文化值并+2 [ICON_GOLD] 金币。+2魅力。每个相邻圣地和剧院广场+1 [ICON_CULTURE] 文化值。每个相邻商业中心和市中心+1 [ICON_GOLD] 金币。城市建造首座波斯庭院改良设施可提供+1点 [ICON_AMENITIES] 宜居度。解锁更多科技和市政树后可提供更多 [ICON_Culture] 文化值和 [ICON_Tourism] 旅游业绩。无法建在雪地、冻土、雪地丘陵或冻土丘陵上，也无法建在另一座波斯庭院旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_KURGAN_DESCRIPTION",                "解锁建造者建造斯基泰特色坟墩的能力。[NEWLINE][NEWLINE]+1 [ICON_Faith] 信仰值、+3 [ICON_Gold] 金币。每与一座牧场相邻便+1 [ICON_Faith] 信仰值（研究完“马镫”后提升为+2）。研究完“飞行”之后将根据 [ICON_FAITH] 信仰值提供 [ICON_TOURISM] 旅游业绩。不能建在丘陵上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CHATEAU_DESCRIPTION",               "解锁建造者建造法国特色建筑法国城堡的能力。[NEWLINE][NEWLINE]+2 [ICON_Culture] 文化值、+1 [ICON_Gold] 金币。+1魅力。每与一座奇观相邻便+1 [ICON_Culture] 文化值（研究“飞行”科技后提升为+2）。如处在包含河岸的单元格上，则+2 [ICON_Gold] 金币。研究完“飞行”之后，将根据 [ICON_CULTURE] 文化值提供 [ICON_TOURISM] 旅游业绩。必须建在加成或奢侈品资源旁。无法建在另一座法国城堡旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",               "随“砌砖”科技解锁的改良设施。可以建造在沙漠泛滥平原，沙漠、草原、平原（包括对应丘陵）上。+2 [ICON_Faith] 信仰值、+1 [ICON_Food] 食物，解锁神学后，+1 [ICON_Food] 食物。可从相邻区域获得额外产出。与市中心相邻则+1 [ICON_Food] 食物。如与提供相邻加成的其他任意区域相邻，则相应产出+1。建造在沙漠或者沙漠丘陵上时，额外+2 [ICON_Faith] 信仰值、+2 [ICON_Food] 食物。"),
    -- 城邦改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",            "您的建造者现在能够建造大寺改良设施。[NEWLINE][NEWLINE]+3 [ICON_SCIENCE] 科技值、+1 [Icon_Housing] 住房。每与1座学院或圣地区域相邻，则+1 [ICON_Science] 科技值。研究完“科学理论”之后，每与1座学院相邻则额外+1 [Icon_Science] 科技值。必须建在平坦地貌上，不能与其他大寺相邻。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",          "您的建造者现在能够建造圆顶市集改良设施。[NEWLINE][NEWLINE]+2 [ICON_GOLD] 金币。每与一个奢侈品资源相邻则+1 [ICON_Gold] 金币。起源城市每有一座圆顶市集，对外国际贸易 [ICON_TradeRoute] 路线提供的 [ICON_GOLD] 金币便+2。无法建在另一座圆顶市集旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",  "您的建造者现在能够建造修道院改良设施。[NEWLINE][NEWLINE]修道院提供+2 [ICON_Faith] 信仰值。此单元格上的友方宗教单位生命值恢复+15（前提是其当前回合未发动攻击）。每1个相邻的区域使其+1 [ICON_FAITH] 信仰值。解锁“王权神授”市政后每1个相邻的区域使其+2 [ICON_FAITH] 信仰值。提供+1 [ICON_HOUSING] 住房。解锁“殖民主义”市政后获得额外1点 [ICON_HOUSING] 住房。无法建在另一座修道院旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",    "您的建造者现在能够建造阿卡萨城堡改良设施。[NEWLINE][NEWLINE]阿卡萨城堡提供+3 [ICON_Culture] 文化值。提供等于单元格魅力75%的 [ICON_SCIENCE] 科技值。占领单位 [ICON_Strength] 防御力+4，并自动获得2回合防御工事。研究“飞行”科技后可提供 [ICON_TOURISM] 旅游业绩。无法建在另一座阿卡萨城堡旁。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_BATEY_DESCRIPTION",                 "您的建造者现在能够建造改良设施巴特依。[NEWLINE][NEWLINE]+1 [ICON_Culture] 文化值。每与1座加成资源和娱乐设施相邻，则+1 [ICON_Culture] 文化值（拥有“人文主义”市政后+2 [Icon_Culture] 文化值）。研究完“飞行”后将产出 [Icon_Tourism] 旅游业绩。无法建造在另一座巴特依旁。"),
    -- 总督改良
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",             "产出1 [ICON_Culture] 文化值，为相邻单元格+2魅力。无法建在另一个市立公园旁。当“测量师”总督梁（必须拥有“公园与休憩”升级）在城市就职时，市立公园为相邻单元格提供+1所有产出。");

