-------------------------------------
--       Beliefs Adjustments       --
-------------------------------------

-- GODDESS_OF_THE_HUNT
update Modifiers set SubjectRequirementSetId = 'PLOT_HAS_CAMP_AND_RESOURCE_REQUIREMENTS' where ModifierId = 'GODDESS_OF_THE_HUNT_CAMP_FOOD_MODIFIER';
update Modifiers set SubjectRequirementSetId = 'PLOT_HAS_CAMP_AND_RESOURCE_REQUIREMENTS' where ModifierId = 'GODDESS_OF_THE_HUNT_CAMP_PRODUCTION_MODIFIER';
update Beliefs set Description = 'LOC_BELIEF_GODDESS_OF_THE_HUNT_DL_DESCRIPTION' where BeliefType = 'BELIEF_GODDESS_OF_THE_HUNT';

-- Relogion Beliefs.
insert or replace into Types
	(Type,								Kind)
values
	-- Pantheon
	('BELIEF_THE_PEOPLE_OF_POLAR',		'KIND_BELIEF'),
	('BELIEF_GODDESS_OF_THE_DESERT',	'KIND_BELIEF'),
	('BELIEF_TENGRI',					'KIND_BELIEF'),
	('BELIEF_ONE_WITH_NATURE',			'KIND_BELIEF'),
	('BELIEF_ORAL_TRADITION',			'KIND_BELIEF'),
	('BELIEF_MESSENGER_OF_THE_GODS',	'KIND_BELIEF'),
	('BELIEF_GODDESS_OF_THE_HARVEST',	'KIND_BELIEF'),
	('BELIEF_OCEAN_MOTHER',				'KIND_BELIEF'),
	-- Follower
	('BELIEF_RELIGIOUS_ART',			'KIND_BELIEF'),
	('BELIEF_PRACTICAL_APPLICATION',	'KIND_BELIEF'),
	-- ('BELIEF_CASTE_SYSTEM',				'KIND_BELIEF'),
	-- ('BELIEF_THE_THIRD_TEMPLE',			'KIND_BELIEF'),
	-- Founder
	('BELIEF_CHURCH_PROPERTY',			'KIND_BELIEF'),
	('BELIEF_CANONIZATION_OF_SAINTS',	'KIND_BELIEF'),
	('BELIEF_TO_THE_GLORY_OF_GOD',		'KIND_BELIEF'),
	-- Enhancer
	('BELIEF_SCHOLASTICISM',			'KIND_BELIEF'),
	('BELIEF_PIOUS_MERCHANTS',			'KIND_BELIEF');

delete from Beliefs where BeliefType = 'BELIEF_GOD_OF_HEALING';
delete from Beliefs where BeliefType = 'BELIEF_INITIATION_RITES';
delete from Beliefs where BeliefType = 'BELIEF_RELIGIOUS_COLONIZATION';
delete from Beliefs where BeliefClassType = 'BELIEF_CLASS_FOLLOWER';
delete from Beliefs where BeliefClassType = 'BELIEF_CLASS_FOUNDER';

update Beliefs set Description = 'LOC_BELIEF_DANCE_OF_THE_AURORA_DL_DESCRIPTION' where BeliefType = 'BELIEF_DANCE_OF_THE_AURORA';
update Beliefs set Description = 'LOC_BELIEF_DESERT_FOLKLORE_DL_DESCRIPTION' where BeliefType = 'BELIEF_DESERT_FOLKLORE';
update Beliefs set Description = 'LOC_BELIEF_SACRED_PATH_DL_DESCRIPTION' where BeliefType = 'BELIEF_SACRED_PATH';
update Beliefs set Description = 'LOC_BELIEF_EARTH_GODDESS_DL_DESCRIPTION' where BeliefType = 'BELIEF_EARTH_GODDESS';
update Beliefs set Description = 'LOC_BELIEF_GODDESS_OF_FIRE_DL_DESCRIPTION' where BeliefType = 'BELIEF_GODDESS_OF_FIRE';
update Beliefs set Description = 'LOC_BELIEF_RELIGIOUS_IDOLS_DL_DESCRIPTION' where BeliefType = 'BELIEF_RELIGIOUS_IDOLS';
update Beliefs set Description = 'LOC_BELIEF_STONE_CIRCLES_DL_DESCRIPTION' where BeliefType = 'BELIEF_STONE_CIRCLES';
update Beliefs set Description = 'LOC_BELIEF_GODDESS_OF_FESTIVALS_DL_DESCRIPTION' where BeliefType = 'BELIEF_GODDESS_OF_FESTIVALS';
update Beliefs set Description = 'LOC_BELIEF_DIVINE_SPARK_DL_DESCRIPTION' where BeliefType = 'BELIEF_DIVINE_SPARK';
update Beliefs set Description = 'LOC_BELIEF_RIVER_GODDESS_DL_DESCRIPTION' where BeliefType = 'BELIEF_RIVER_GODDESS';
update Beliefs set Description = 'LOC_BELIEF_GOD_OF_WAR_DL_DESCRIPTION' where BeliefType = 'BELIEF_GOD_OF_WAR';
update Beliefs set Description = 'LOC_BELIEF_RELIGIOUS_SETTLEMENTS_DL_DESCRIPTION' where BeliefType = 'BELIEF_RELIGIOUS_SETTLEMENTS';
update Beliefs set Description = 'LOC_BELIEF_FERTILITY_RITES_DL_DESCRIPTION' where BeliefType = 'BELIEF_FERTILITY_RITES';
update Beliefs set Description = 'LOC_BELIEF_MONUMENT_TO_THE_GODS_DL_DESCRIPTION' where BeliefType = 'BELIEF_MONUMENT_TO_THE_GODS';
update Beliefs set Description = 'LOC_BELIEF_CITY_PATRON_GODDESS_DL_DESCRIPTION' where BeliefType = 'BELIEF_CITY_PATRON_GODDESS';
update Beliefs set Description = 'LOC_BELIEF_GOD_OF_THE_OPEN_SKY_DL_DESCRIPTION' where BeliefType = 'BELIEF_GOD_OF_THE_OPEN_SKY';
update Beliefs set Description = 'LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_DL_DESCRIPTION' where BeliefType = 'BELIEF_LADY_OF_THE_REEDS_AND_MARSHES';
update Beliefs set Description = 'LOC_BELIEF_GOD_OF_THE_SEA_DL_DESCRIPTION' where BeliefType = 'BELIEF_GOD_OF_THE_SEA';
--
update Beliefs set Description = 'LOC_BELIEF_DEFENDER_OF_FAITH_DL_DESCRIPTION' where BeliefType = 'BELIEF_DEFENDER_OF_FAITH';
update Beliefs set Description = 'LOC_BELIEF_JUST_WAR_DL_DESCRIPTION' where BeliefType = 'BELIEF_JUST_WAR';
update Beliefs set Description = 'LOC_BELIEF_HOLY_WATERS_DL_DESCRIPTION' where BeliefType = 'BELIEF_HOLY_WATERS';

insert or replace into Beliefs
	(BeliefType,						Name,										Description,											BeliefClassType)
values
	-- Pantheon
	('BELIEF_THE_PEOPLE_OF_POLAR',		'LOC_BELIEF_THE_PEOPLE_OF_POLAR_NAME',		'LOC_BELIEF_THE_PEOPLE_OF_POLAR_DL_DESCRIPTION',		'BELIEF_CLASS_PANTHEON'),
	('BELIEF_GODDESS_OF_THE_DESERT',	'LOC_BELIEF_GODDESS_OF_THE_DESERT_NAME',	'LOC_BELIEF_GODDESS_OF_THE_DESERT_DL_DESCRIPTION',		'BELIEF_CLASS_PANTHEON'),
	('BELIEF_TENGRI',					'LOC_BELIEF_TENGRI_NAME',					'LOC_BELIEF_TENGRI_DL_DESCRIPTION',						'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ONE_WITH_NATURE',			'LOC_BELIEF_ONE_WITH_NATURE_NAME',			'LOC_BELIEF_ONE_WITH_NATURE_DL_DESCRIPTION',			'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ORAL_TRADITION',			'LOC_BELIEF_ORAL_TRADITION_NAME',			'LOC_BELIEF_ORAL_TRADITION_DL_DESCRIPTION',				'BELIEF_CLASS_PANTHEON'),
	('BELIEF_MESSENGER_OF_THE_GODS',	'LOC_BELIEF_MESSENGER_OF_THE_GODS_NAME',	'LOC_BELIEF_MESSENGER_OF_THE_GODS_DL_DESCRIPTION',		'BELIEF_CLASS_PANTHEON'),
	('BELIEF_GODDESS_OF_THE_HARVEST',	'LOC_BELIEF_GODDESS_OF_THE_HARVEST_NAME',	'LOC_BELIEF_GODDESS_OF_THE_HARVEST_DL_DESCRIPTION',		'BELIEF_CLASS_PANTHEON'),
	('BELIEF_OCEAN_MOTHER',				'LOC_BELIEF_OCEAN_MOTHER_NAME',				'LOC_BELIEF_OCEAN_MOTHER_DL_DESCRIPTION',				'BELIEF_CLASS_PANTHEON'),
	-- Enhancer
	('BELIEF_SCHOLASTICISM',			'LOC_BELIEF_SCHOLASTICISM_NAME',			'LOC_BELIEF_SCHOLASTICISM_DL_DESCRIPTION',				'BELIEF_CLASS_ENHANCER'),
	('BELIEF_PIOUS_MERCHANTS',			'LOC_BELIEF_PIOUS_MERCHANTS_NAME',			'LOC_BELIEF_PIOUS_MERCHANTS_DL_DESCRIPTION',			'BELIEF_CLASS_ENHANCER'),
	('BELIEF_CANONIZATION_OF_SAINTS',	'LOC_BELIEF_CANONIZATION_OF_SAINTS_NAME',	'LOC_BELIEF_CANONIZATION_OF_SAINTS_DL_DESCRIPTION',		'BELIEF_CLASS_ENHANCER'),
	('BELIEF_MONASTIC_ISOLATION',		'LOC_BELIEF_MONASTIC_ISOLATION_NAME',		'LOC_BELIEF_MONASTIC_ISOLATION_DL_DESCRIPTION',			'BELIEF_CLASS_ENHANCER'),
	-- Follower
	('BELIEF_FEED_THE_WORLD',			'LOC_BELIEF_FEED_THE_WORLD_NAME',			'LOC_BELIEF_FEED_THE_WORLD_DL_DESCRIPTION',				'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_CHORAL_MUSIC',				'LOC_BELIEF_CHORAL_MUSIC_NAME',				'LOC_BELIEF_CHORAL_MUSIC_DL_DESCRIPTION',				'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_WARRIOR_MONKS',			'LOC_BELIEF_WARRIOR_MONKS_NAME',			'LOC_BELIEF_WARRIOR_MONKS_EXPANSION2_DESCRIPTION',		'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_DIVINE_INSPIRATION',		'LOC_BELIEF_DIVINE_INSPIRATION_NAME',		'LOC_BELIEF_DIVINE_INSPIRATION_DL_DESCRIPTION',			'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_JESUIT_EDUCATION',			'LOC_BELIEF_JESUIT_EDUCATION_NAME',			'LOC_BELIEF_JESUIT_EDUCATION_DL_DESCRIPTION',			'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_RELIQUARIES',				'LOC_BELIEF_RELIQUARIES_NAME',				'LOC_BELIEF_RELIQUARIES_DL_DESCRIPTION',				'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'LOC_BELIEF_RELIGIOUS_COMMUNITY_NAME',		'LOC_BELIEF_RELIGIOUS_COMMUNITY_DL_DESCRIPTION',		'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_ZEN_MEDITATION',			'LOC_BELIEF_ZEN_MEDITATION_NAME',			'LOC_BELIEF_ZEN_MEDITATION_DESCRIPTION',				'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_RELIGIOUS_ART',			'LOC_BELIEF_RELIGIOUS_ART_NAME',			'LOC_BELIEF_RELIGIOUS_ART_DL_DESCRIPTION',				'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_WORK_ETHIC',				'LOC_BELIEF_WORK_ETHIC_NAME',				'LOC_BELIEF_WORK_ETHIC_DL_DESCRIPTION',					'BELIEF_CLASS_FOLLOWER'),
	-- ('BELIEF_CASTE_SYSTEM',				'LOC_BELIEF_CASTE_SYSTEM_NAME',				'LOC_BELIEF_CASTE_SYSTEM_DL_DESCRIPTION',				'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_PRACTICAL_APPLICATION',	'LOC_BELIEF_PRACTICAL_APPLICATION_NAME',	'LOC_BELIEF_PRACTICAL_APPLICATION_DL_DESCRIPTION',		'BELIEF_CLASS_FOLLOWER'),
	-- ('BELIEF_THE_THIRD_TEMPLE',			'LOC_BELIEF_THE_THIRD_TEMPLE_NAME',			'LOC_BELIEF_THE_THIRD_TEMPLE_DL_DESCRIPTION',			'BELIEF_CLASS_FOLLOWER'),
	('BELIEF_RELIGIOUS_COLONIZATION',	'LOC_BELIEF_RELIGIOUS_COLONIZATION_NAME',	'LOC_BELIEF_RELIGIOUS_COLONIZATION_DL_DESCRIPTION',		'BELIEF_CLASS_FOLLOWER'),
	-- Founder
	('BELIEF_TITHE',					'LOC_BELIEF_TITHE_NAME',					'LOC_BELIEF_TITHE_DL_DESCRIPTION',						'BELIEF_CLASS_FOUNDER'),
	('BELIEF_RELIGIOUS_UNITY',			'LOC_BELIEF_RELIGIOUS_UNITY_NAME',			'LOC_BELIEF_RELIGIOUS_UNITY_DL_DESCRIPTION',			'BELIEF_CLASS_FOUNDER'),
	('BELIEF_WORLD_CHURCH',				'LOC_BELIEF_WORLD_CHURCH_NAME',				'LOC_BELIEF_WORLD_CHURCH_DL_DESCRIPTION',				'BELIEF_CLASS_FOUNDER'),
	('BELIEF_CROSS_CULTURAL_DIALOGUE',	'LOC_BELIEF_CROSS_CULTURAL_DIALOGUE_NAME',	'LOC_BELIEF_CROSS_CULTURAL_DIALOGUE_DL_DESCRIPTION',	'BELIEF_CLASS_FOUNDER'),
	('BELIEF_CHURCH_PROPERTY',			'LOC_BELIEF_CHURCH_PROPERTY_NAME',			'LOC_BELIEF_CHURCH_PROPERTY_DL_DESCRIPTION',			'BELIEF_CLASS_FOUNDER'),
	('BELIEF_PILGRIMAGE',				'LOC_BELIEF_PILGRIMAGE_NAME',				'LOC_BELIEF_PILGRIMAGE_DL_DESCRIPTION',					'BELIEF_CLASS_FOUNDER'),
	('BELIEF_LAY_MINISTRY',				'LOC_BELIEF_LAY_MINISTRY_NAME',				'LOC_BELIEF_LAY_MINISTRY_DL_DESCRIPTION',				'BELIEF_CLASS_FOUNDER'),
	('BELIEF_STEWARDSHIP',				'LOC_BELIEF_STEWARDSHIP_NAME',				'LOC_BELIEF_STEWARDSHIP_DL_DESCRIPTION',				'BELIEF_CLASS_FOUNDER'),
	('BELIEF_PAPAL_PRIMACY',			'LOC_BELIEF_PAPAL_PRIMACY_NAME',			'LOC_BELIEF_PAPAL_PRIMACY_DESCRIPTION',					'BELIEF_CLASS_FOUNDER'),
	('BELIEF_SACRED_PLACES',			'LOC_BELIEF_SACRED_PLACES_NAME',			'LOC_BELIEF_SACRED_PLACES_DESCRIPTION',					'BELIEF_CLASS_FOUNDER'),
	('BELIEF_INITIATION_RITES',			'LOC_BELIEF_INITIATION_RITES_NAME',			'LOC_BELIEF_INITIATION_RITES_DL_DESCRIPTION',			'BELIEF_CLASS_FOUNDER'),
	('BELIEF_TO_THE_GLORY_OF_GOD',		'LOC_BELIEF_TO_THE_GLORY_OF_GOD_NAME',		'LOC_BELIEF_TO_THE_GLORY_OF_GOD_DL_DESCRIPTION',		'BELIEF_CLASS_FOUNDER');

delete from BeliefModifiers where BeliefType = 'BELIEF_GODDESS_OF_FESTIVALS'; -- and ModifierID = 'GODDESS_OF_FESTIVALS_PLANTATION_CULTURE';
delete from BeliefModifiers where BeliefType = 'BELIEF_FERTILITY_RITES'; -- and ModifierID = 'FERTILITY_RITES_BUILDER';
delete from BeliefModifiers where BeliefType = 'BELIEF_RELIGIOUS_SETTLEMENTS'; -- and ModifierID = 'RELIGIOUS_SETTLEMENTS_SETTLER';

insert or replace into BeliefModifiers
	(BeliefType,							ModifierID)
values
	-- Pantheon
	('BELIEF_DANCE_OF_THE_AURORA',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD'),
	('BELIEF_DANCE_OF_THE_AURORA',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD'),
	('BELIEF_DANCE_OF_THE_AURORA',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE'),
	('BELIEF_DANCE_OF_THE_AURORA',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE'),
	('BELIEF_DESERT_FOLKLORE',				'DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD'),
	('BELIEF_DESERT_FOLKLORE',				'DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD'),
	('BELIEF_DESERT_FOLKLORE',				'DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH'),
	('BELIEF_DESERT_FOLKLORE',				'DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH'),
	('BELIEF_SACRED_PATH',					'SACRED_PATH_HOLYSITE_JUNGLE_CULTURE'),
	('BELIEF_THE_PEOPLE_OF_POLAR',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD'),
	('BELIEF_THE_PEOPLE_OF_POLAR',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD'),
	('BELIEF_THE_PEOPLE_OF_POLAR',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH'),
	('BELIEF_THE_PEOPLE_OF_POLAR',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH'),
	('BELIEF_THE_PEOPLE_OF_POLAR',			'THE_PEOPLE_OF_POLAR_GREAT_PROPHET'),
	('BELIEF_GODDESS_OF_THE_DESERT',		'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD'),
	('BELIEF_GODDESS_OF_THE_DESERT',		'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD'),
	('BELIEF_GODDESS_OF_THE_DESERT',		'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH'),
	('BELIEF_GODDESS_OF_THE_DESERT',		'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH'),
	('BELIEF_GODDESS_OF_THE_DESERT',		'GODDESS_OF_THE_DESERT_GREAT_PROPHET'),
	('BELIEF_EARTH_GODDESS',				'EARTH_GODDESS_APPEAL_CHARMING_FAITH'),
	('BELIEF_EARTH_GODDESS',				'EARTH_GODDESS_APPEAL_GREAT_PROPHET'),
	('BELIEF_GODDESS_OF_FIRE',				'GODDESS_OF_FIRE_GREAT_PROPHET'),
	('BELIEF_RELIGIOUS_IDOLS',				'RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE'),
	('BELIEF_RELIGIOUS_IDOLS',				'RELIGIOUS_IDOLS_BONUS_MINE_CULTURE'),
	('BELIEF_RELIGIOUS_IDOLS',				'RELIGIOUS_IDOLS_GREAT_PROPHET'),
	('BELIEF_STONE_CIRCLES',				'STONE_CIRCLES_GREAT_PROPHET'),
	('BELIEF_GODDESS_OF_FESTIVALS',			'GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY'),
	('BELIEF_GODDESS_OF_FESTIVALS',			'GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD'),
	('BELIEF_GODDESS_OF_FESTIVALS',			'GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH'),
	('BELIEF_TENGRI',						'TENGRI_FAITH_PASTURE_ADJACENCY'),
	('BELIEF_TENGRI',						'TENGRI_HOLYSITE_PASTURE_PRODUCTION'),
	('BELIEF_TENGRI',						'TENGRI_HOLYSITE_PASTURE_FAITH'),
	('BELIEF_ONE_WITH_NATURE',				'ONE_WITH_NATURE_WONDER_GREAT_PROPHET'),
	('BELIEF_DIVINE_SPARK',					'DIVINE_SPARK_MERCHANT'),
	('BELIEF_DIVINE_SPARK',					'DIVINE_SPARK_ENGINEER'),
	('BELIEF_RIVER_GODDESS',				'RIVER_GODDESS_FAITH_RIVER_ADJACENCY'),
	('BELIEF_RIVER_GODDESS',				'RIVER_GODDESS_GREAT_PROPHET'),
	('BELIEF_GOD_OF_WAR',					'GOD_OF_WAR_GREAT_PROPHET_KILLS'),
	('BELIEF_RELIGIOUS_SETTLEMENTS',		'RELIGIOUS_SETTLEMENTS_CULTUREBORDER'),
	('BELIEF_RELIGIOUS_SETTLEMENTS',		'RELIGIOUS_SETTLEMENTS_INCREASED_TILES'),
	('BELIEF_FERTILITY_RITES',				'FERTILITY_RITES_GRANARY_GROWTH'),
	('BELIEF_FERTILITY_RITES',				'FERTILITY_RITES_GRANARY_FAITH_PURCHASE'),
	('BELIEF_FERTILITY_RITES',				'FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT'),
	('BELIEF_MONUMENT_TO_THE_GODS',			'MONUMENT_TO_THE_GODS_MONUMENT_CULTURE'),
	('BELIEF_MONUMENT_TO_THE_GODS',			'MONUMENT_TO_THE_GODS_MONUMENT_FAITH_PURCHASE'),
	('BELIEF_MONUMENT_TO_THE_GODS',			'MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT'),
	('BELIEF_CITY_PATRON_GODDESS',			'CITY_PATRON_GODDESS_CASTLEPRODUCTION'),
	('BELIEF_CITY_PATRON_GODDESS',			'CITY_PATRON_GODDESS_WALLSPRODUCTION'),
	('BELIEF_CITY_PATRON_GODDESS',			'CITY_PATRON_GODDESS_STARFORTPRODUCTION'),
	('BELIEF_CITY_PATRON_GODDESS',			'CITY_PATRON_GODDESS_TSIKHEPRODUCTION'),
	('BELIEF_CITY_PATRON_GODDESS',			'CITY_PATRON_GODDESS_INNERDEFENSE'),
	('BELIEF_CITY_PATRON_GODDESS',			'CITY_PATRON_GODDESS_RANGEDSTRIKE'),
	('BELIEF_MESSENGER_OF_THE_GODS',		'MESSENGER_OF_THE_GODS_FREE_SCOUT'),
	('BELIEF_MESSENGER_OF_THE_GODS',		'MESSENGER_OF_THE_GODS_SCOUT_MOVEMENT'),
	('BELIEF_GOD_OF_THE_OPEN_SKY',			'GOD_OF_THE_OPEN_SKY_PASTURE_FOOD'),
	('BELIEF_ORAL_TRADITION',				'ORAL_TRADITION_PLANTATION_CULTURE'),
	('BELIEF_ORAL_TRADITION',				'ORAL_TRADITION_PLANTATION_GOLD'),
	('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES',	'LADY_OF_THE_MARSHES_SCIENCE'),
	('BELIEF_GODDESS_OF_THE_HARVEST',		'GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD'),
	('BELIEF_GOD_OF_THE_SEA',				'GOD_OF_THE_SEA_FISHINGBOATS_FOOD'),
	('BELIEF_OCEAN_MOTHER',					'OCEAN_MOTHER_COAST_FOOD'),
	('BELIEF_OCEAN_MOTHER',					'OCEAN_MOTHER_OCEAN_FOOD');

-- Pantheon
-- update Modifiers set SubjectRequirementSetId = 'PLOT_EIGHT_INCLUDE_CITY_CENTER' where ModifierId = 'GOD_OF_WAR_FAITH_KILLS_MODIFIER';
update Modifiers set SubjectRequirementSetId = NULL where ModifierId = 'GOD_OF_WAR_FAITH_KILLS_MODIFIER';

insert or replace into Modifiers
	(ModifierId,													ModifierType,										SubjectRequirementSetId)
values
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD',					'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD_MODIFIER',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_TUNDRA_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD',				'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_TUNDRA_HILL_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE',					'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_TUNDRA_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE',			'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE_MODIFIER',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_TUNDRA_HILL_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD',						'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD_MODIFIER',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_DESERT_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD',					'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD_MODIFIER',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_DESERT_HILL_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH',						'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH_MODIFIER',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_DESERT_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH',					'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH_MODIFIER',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_DESERT_HILL_REQUIREMENTS'),
	('SACRED_PATH_HOLYSITE_JUNGLE_CULTURE',							'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('SACRED_PATH_HOLYSITE_JUNGLE_CULTURE_MODIFIER',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_JUNGLE_REQUIREMENTS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER',		'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD',			'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER',	'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER',		'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH',			'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER',	'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('THE_PEOPLE_OF_POLAR_GREAT_PROPHET',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('THE_PEOPLE_OF_POLAR_GREAT_PROPHET_MODIFIER',					'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'PLOT_HAS_TUNDRA_OR_TUNDRA_HILL_REQUIREMENTS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER',		'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD',			'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER',	'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER',		'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH',			'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER', 'MODIFIER_SINGLE_CITY_TERRAIN_ADJACENCY',			NULL),
	('GODDESS_OF_THE_DESERT_GREAT_PROPHET',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_THE_DESERT_GREAT_PROPHET_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'PLOT_HAS_DESERT_OR_DESERT_HILL_REQUIREMENTS'),
	('EARTH_GODDESS_APPEAL_CHARMING_FAITH',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('EARTH_GODDESS_APPEAL_CHARMING_FAITH_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_CHARMING_APPEAL'),
	('EARTH_GODDESS_APPEAL_GREAT_PROPHET',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('EARTH_GODDESS_APPEAL_GREAT_PROPHET_MODIFIER',					'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'PLOT_BREATHTAKING_APPEAL'),
	('GODDESS_OF_FIRE_GREAT_PROPHET',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_FIRE_GREAT_PROPHET_MODIFIER',						'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'GODDESS_OF_FIRE_CITY_HAS_VOLCANO'),
	('RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_LUXURY_MINE_REQUIREMENTS'),
	('RELIGIOUS_IDOLS_BONUS_MINE_CULTURE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('RELIGIOUS_IDOLS_BONUS_MINE_CULTURE_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_BONUS_MINE_REQUIREMENTS'),
	('RELIGIOUS_IDOLS_GREAT_PROPHET',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('RELIGIOUS_IDOLS_GREAT_PROPHET_MODIFIER',						'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'RELIGIOUS_IDOLS_CITY_HAS_LUXURY_OR_BONUS_MINE'),
	('STONE_CIRCLES_GREAT_PROPHET',									'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('STONE_CIRCLES_GREAT_PROPHET_MODIFIER',						'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'STONE_CIRCLES_CITY_HAS_QUARRY'),
	('GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY',				'MODIFIER_ALL_CITIES_IMPROVEMENT_ADJACENCY',		'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD',				'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_PLANTATION_REQUIREMENTS'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH',				'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_PLANTATION_REQUIREMENTS'),
	('TENGRI_FAITH_PASTURE_ADJACENCY',								'MODIFIER_ALL_CITIES_IMPROVEMENT_ADJACENCY',		'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('TENGRI_HOLYSITE_PASTURE_PRODUCTION',							'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('TENGRI_HOLYSITE_PASTURE_PRODUCTION_MODIFIER',					'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_PASTURE_REQUIREMENTS'),
	('TENGRI_HOLYSITE_PASTURE_FAITH',								'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_AND_HOLYSITE_REQUIREMENTS'),
	('TENGRI_HOLYSITE_PASTURE_FAITH_MODIFIER',						'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'HOLYSITE_PASTURE_REQUIREMENTS'),
	('ONE_WITH_NATURE_WONDER_GREAT_PROPHET',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ONE_WITH_NATURE_WONDER_GREAT_PROPHET_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'ONE_WITH_NATURE_CITY_HAS_NATURAL_WONDER'),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY_MODIFIER',				'MODIFIER_SINGLE_CITY_RIVER_ADJACENCY',				NULL),
	('RIVER_GODDESS_GREAT_PROPHET',									'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('RIVER_GODDESS_GREAT_PROPHET_MODIFIER',						'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'PLOT_ADJACENT_TO_RIVER_REQUIREMENTS'),
	('DIVINE_SPARK_MERCHANT',										'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('DIVINE_SPARK_MERCHANT_MODIFIER',								'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'BUILDING_IS_MARKET'),
	('DIVINE_SPARK_ENGINEER',										'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('DIVINE_SPARK_ENGINEER_MODIFIER',								'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT',	'BUILDING_IS_WORKSHOP'),
	('GOD_OF_WAR_GREAT_PROPHET_KILLS',								'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',				'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('GOD_OF_WAR_GREAT_PROPHET_KILLS_MODIFIER',						'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',				NULL),
	('GOD_OF_WAR_GREAT_PROPHET_POINTS',								'MODIFIER_PLAYER_ADJUST_UNITS_GREAT_PEOPLE_POINTS_PER_KILL_BY_DEFEATED_STRENGTH',	NULL),
	('RELIGIOUS_SETTLEMENTS_INCREASED_TILES',						'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',				'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('RELIGIOUS_SETTLEMENTS_INCREASED_TILES_MODIFIER',				'MODIFIER_PLAYER_ADJUST_CITY_TILES',				NULL),
	('FERTILITY_RITES_GRANARY_GROWTH',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('FERTILITY_RITES_GRANARY_GROWTH_MODIFIER',						'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH',			'CITY_HAS_GRANARY'),
	('FERTILITY_RITES_GRANARY_FAITH_PURCHASE',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('FERTILITY_RITES_GRANARY_FAITH_PURCHASE_MODIFIER',				'MODIFIER_CITY_ENABLE_SPECIFIC_BUILDING_FAITH_PURCHASE', NULL),
	('FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT_MODIFIER',			'MODIFIER_CITY_ADJUST_BUILDING_PURCHASE_COST',		NULL),
	('MONUMENT_TO_THE_GODS_MONUMENT_CULTURE',						'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('MONUMENT_TO_THE_GODS_MONUMENT_CULTURE_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER',	'CITY_HAS_MONUMENT'),
	('MONUMENT_TO_THE_GODS_MONUMENT_FAITH_PURCHASE',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('MONUMENT_TO_THE_GODS_MONUMENT_FAITH_PURCHASE_MODIFIER',		'MODIFIER_CITY_ENABLE_SPECIFIC_BUILDING_FAITH_PURCHASE', NULL),
	('MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT_MODIFIER',	'MODIFIER_CITY_ADJUST_BUILDING_PURCHASE_COST',		NULL),
	('CITY_PATRON_GODDESS_CASTLEPRODUCTION',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('CITY_PATRON_GODDESS_CASTLEPRODUCTION_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION',	NULL),
	('CITY_PATRON_GODDESS_WALLSPRODUCTION',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('CITY_PATRON_GODDESS_WALLSPRODUCTION_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION',	NULL),
	('CITY_PATRON_GODDESS_STARFORTPRODUCTION',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('CITY_PATRON_GODDESS_STARFORTPRODUCTION_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION',	NULL),
	('CITY_PATRON_GODDESS_TSIKHEPRODUCTION',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('CITY_PATRON_GODDESS_TSIKHEPRODUCTION_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION',	NULL),
	('CITY_PATRON_GODDESS_INNERDEFENSE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('CITY_PATRON_GODDESS_INNERDEFENSE_MODIFIER',					'MODIFIER_SINGLE_CITY_ADJUST_INNER_DEFENSE',		NULL),
	('CITY_PATRON_GODDESS_RANGEDSTRIKE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('CITY_PATRON_GODDESS_RANGEDSTRIKE_MODIFIER',					'MODIFIER_SINGLE_CITY_ADJUST_RANGED_STRIKE',		NULL),
	('MESSENGER_OF_THE_GODS_FREE_SCOUT',							'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',				'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('MESSENGER_OF_THE_GODS_FREE_SCOUT_MODIFIER',					'MODIFIER_PLAYER_GRANT_UNIT_BY_CLASS_IN_CAPITAL',	'PLAYER_HAS_AT_LEAST_ONE_CITY_REQUIREMENTS'),
	('MESSENGER_OF_THE_GODS_SCOUT_MOVEMENT',						'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',				'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('MESSENGER_OF_THE_GODS_SCOUT_MOVEMENT_MODIFIER',				'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT',			'SURVEY_RECONUNITEXPERIENCE_REQUIREMENTS'), -- temp use
	('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_PASTURE_REQUIREMENTS'),
	('ORAL_TRADITION_PLANTATION_CULTURE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ORAL_TRADITION_PLANTATION_CULTURE_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_PLANTATION_REQUIREMENTS'),
	('ORAL_TRADITION_PLANTATION_GOLD',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ORAL_TRADITION_PLANTATION_GOLD_MODIFIER',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_PLANTATION_REQUIREMENTS'),
	('LADY_OF_THE_MARSHES_SCIENCE',									'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('LADY_OF_THE_MARSHES_SCIENCE_MODIFIER',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'ZOO_MARSH_REQUIREMENTS'),
	('GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD_MODIFIER',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_FARM_RESOURCE_REQUIREMENTS'),
	('GOD_OF_THE_SEA_FISHINGBOATS_FOOD',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('GOD_OF_THE_SEA_FISHINGBOATS_FOOD_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_FISHINGBOATS_REQUIREMENTS'),
	('OCEAN_MOTHER_COAST_FOOD',										'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('OCEAN_MOTHER_COAST_FOOD_MODIFIER',							'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_IS_COAST_NOT_LAKE_REQUIREMENTS'),
	('OCEAN_MOTHER_OCEAN_FOOD',										'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('OCEAN_MOTHER_OCEAN_FOOD_MODIFIER',							'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_IS_OCEAN_REQUIREMENTS');

insert or replace into ModifierArguments
	(ModifierId,													Name,					Value)
values
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD',					'ModifierId',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD_MODIFIER'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD_MODIFIER',			'YieldType',			'YIELD_FOOD'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_FOOD_MODIFIER',			'Amount',				1),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD',				'ModifierId',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD_MODIFIER'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD_MODIFIER',		'YieldType',			'YIELD_FOOD'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_FOOD_MODIFIER',		'Amount',				1),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE',					'ModifierId',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE_MODIFIER'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE_MODIFIER',		'YieldType',			'YIELD_CULTURE'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_CULTURE_MODIFIER',		'Amount',				1),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE',			'ModifierId',			'DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE_MODIFIER'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE_MODIFIER',	'YieldType',			'YIELD_CULTURE'),
	('DANCE_OF_THE_AURORA_HOLYSITE_TUNDRA_HILL_CULTURE_MODIFIER',	'Amount',				1),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD',						'ModifierId',			'DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD_MODIFIER'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD_MODIFIER',				'YieldType',			'YIELD_FOOD'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FOOD_MODIFIER',				'Amount',				1),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD',					'ModifierId',			'DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD_MODIFIER'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD_MODIFIER',			'YieldType',			'YIELD_FOOD'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FOOD_MODIFIER',			'Amount',				1),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH',						'ModifierId',			'DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH_MODIFIER'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH_MODIFIER',				'YieldType',			'YIELD_FAITH'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_FAITH_MODIFIER',				'Amount',				1),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH',					'ModifierId',			'DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH_MODIFIER'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH_MODIFIER',			'YieldType',			'YIELD_FAITH'),
	('DESERT_FOLKLORE_HOLYSITE_DESERT_HILL_FAITH_MODIFIER',			'Amount',				1),
	('SACRED_PATH_HOLYSITE_JUNGLE_CULTURE',							'ModifierId',			'SACRED_PATH_HOLYSITE_JUNGLE_CULTURE_MODIFIER'),
	('SACRED_PATH_HOLYSITE_JUNGLE_CULTURE_MODIFIER',				'YieldType',			'YIELD_CULTURE'),
	('SACRED_PATH_HOLYSITE_JUNGLE_CULTURE_MODIFIER',				'Amount',				1),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD',					'ModifierId',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER',		'DistrictType',			'DISTRICT_CITY_CENTER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER',		'YieldType',			'YIELD_FOOD'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER',		'TerrainType',			'TERRAIN_TUNDRA'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER',		'Amount',				1),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FOOD_MODIFIER',		'Description',			'LOC_DISTRICT_TUNDRA_FOOD'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD',			'ModifierId',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER',	'DistrictType',			'DISTRICT_CITY_CENTER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER',	'YieldType',			'YIELD_FOOD'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER',	'TerrainType',			'TERRAIN_TUNDRA_HILLS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER',	'Amount',				1),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FOOD_MODIFIER',	'Description',			'LOC_DISTRICT_TUNDRA_HILLS_FOOD'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH',				'ModifierId',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER',		'DistrictType',			'DISTRICT_CITY_CENTER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER',		'YieldType',			'YIELD_FAITH'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER',		'TerrainType',			'TERRAIN_TUNDRA'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER',		'Amount',				1),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_FAITH_MODIFIER',		'Description',			'LOC_DISTRICT_TUNDRA_FAITH'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH',			'ModifierId',			'THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER',	'DistrictType',			'DISTRICT_CITY_CENTER'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER',	'YieldType',			'YIELD_FAITH'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER',	'TerrainType',			'TERRAIN_TUNDRA_HILLS'),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER',	'Amount',				1),
	('THE_PEOPLE_OF_POLAR_CITY_CENTER_TUNDRA_HILL_FAITH_MODIFIER',	'Description',			'LOC_DISTRICT_TUNDRA_HILLS_FAITH'),
	('THE_PEOPLE_OF_POLAR_GREAT_PROPHET',							'ModifierId',			'THE_PEOPLE_OF_POLAR_GREAT_PROPHET_MODIFIER'),
	('THE_PEOPLE_OF_POLAR_GREAT_PROPHET_MODIFIER',					'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('THE_PEOPLE_OF_POLAR_GREAT_PROPHET_MODIFIER',					'Amount',				1),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD',				'ModifierId',			'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER',		'DistrictType',			'DISTRICT_CITY_CENTER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER',		'YieldType',			'YIELD_FOOD'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER',		'TerrainType',			'TERRAIN_DESERT'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER',		'Amount',				1),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FOOD_MODIFIER',		'Description',			'LOC_DISTRICT_DESERT_FOOD'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD',			'ModifierId',			'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER',	'DistrictType',			'DISTRICT_CITY_CENTER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER',	'YieldType',			'YIELD_FOOD'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER',	'TerrainType',			'TERRAIN_DESERT_HILLS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER',	'Amount',				1),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FOOD_MODIFIER',	'Description',			'LOC_DISTRICT_DESERT_HILLS_FOOD'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH',				'ModifierId',			'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER',		'DistrictType',			'DISTRICT_CITY_CENTER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER',		'YieldType',			'YIELD_FAITH'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER',		'TerrainType',			'TERRAIN_DESERT'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER',		'Amount',				1),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_FAITH_MODIFIER',		'Description',			'LOC_DISTRICT_DESERT_FAITH'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH',			'ModifierId',			'GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER', 'DistrictType',		'DISTRICT_CITY_CENTER'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER', 'YieldType',			'YIELD_FAITH'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER', 'TerrainType',			'TERRAIN_DESERT_HILLS'),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER', 'Amount',				1),
	('GODDESS_OF_THE_DESERT_CITY_CENTER_DESERT_HILL_FAITH_MODIFIER', 'Description',			'LOC_DISTRICT_DESERT_HILLS_FAITH'),
	('GODDESS_OF_THE_DESERT_GREAT_PROPHET',							'ModifierId',			'GODDESS_OF_THE_DESERT_GREAT_PROPHET_MODIFIER'),
	('GODDESS_OF_THE_DESERT_GREAT_PROPHET_MODIFIER',				'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('GODDESS_OF_THE_DESERT_GREAT_PROPHET_MODIFIER',				'Amount',				1),
	('EARTH_GODDESS_APPEAL_CHARMING_FAITH',							'ModifierId',			'EARTH_GODDESS_APPEAL_CHARMING_FAITH_MODIFIER'),
	('EARTH_GODDESS_APPEAL_CHARMING_FAITH_MODIFIER',				'YieldType',			'YIELD_FAITH'),
	('EARTH_GODDESS_APPEAL_CHARMING_FAITH_MODIFIER',				'Amount',				1),
	('EARTH_GODDESS_APPEAL_GREAT_PROPHET',							'ModifierId',			'EARTH_GODDESS_APPEAL_GREAT_PROPHET_MODIFIER'),
	('EARTH_GODDESS_APPEAL_GREAT_PROPHET_MODIFIER',					'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('EARTH_GODDESS_APPEAL_GREAT_PROPHET_MODIFIER',					'Amount',				1),
	('GODDESS_OF_FIRE_GREAT_PROPHET',								'ModifierId',			'GODDESS_OF_FIRE_GREAT_PROPHET_MODIFIER'),
	('GODDESS_OF_FIRE_GREAT_PROPHET_MODIFIER',						'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('GODDESS_OF_FIRE_GREAT_PROPHET_MODIFIER',						'Amount',				2),
	('RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE',							'ModifierId',			'RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE_MODIFIER'),
	('RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE_MODIFIER',				'YieldType',			'YIELD_CULTURE'),
	('RELIGIOUS_IDOLS_LUXURY_MINE_CULTURE_MODIFIER',				'Amount',				1),
	('RELIGIOUS_IDOLS_BONUS_MINE_CULTURE',							'ModifierId',			'RELIGIOUS_IDOLS_BONUS_MINE_CULTURE_MODIFIER'),
	('RELIGIOUS_IDOLS_BONUS_MINE_CULTURE_MODIFIER',					'YieldType',			'YIELD_CULTURE'),
	('RELIGIOUS_IDOLS_BONUS_MINE_CULTURE_MODIFIER',					'Amount',				1),
	('RELIGIOUS_IDOLS_GREAT_PROPHET',								'ModifierId',			'RELIGIOUS_IDOLS_GREAT_PROPHET_MODIFIER'),
	('RELIGIOUS_IDOLS_GREAT_PROPHET_MODIFIER',						'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('RELIGIOUS_IDOLS_GREAT_PROPHET_MODIFIER',						'Amount',				1),
	('STONE_CIRCLES_GREAT_PROPHET',									'ModifierId',			'STONE_CIRCLES_GREAT_PROPHET_MODIFIER'),
	('STONE_CIRCLES_GREAT_PROPHET_MODIFIER',						'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('STONE_CIRCLES_GREAT_PROPHET_MODIFIER',						'Amount',				2),
	('GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY',				'DistrictType',			'DISTRICT_HOLY_SITE'),
	('GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY',				'YieldType',			'YIELD_FAITH'),
	('GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY',				'ImprovementType',		'IMPROVEMENT_PLANTATION'),
	('GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY',				'Amount',				2),
	('GODDESS_OF_FESTIVALS_FAITH_PLANTATION_ADJACENCY',				'Description',			'LOC_DISTRICT_PLANTATION_FAITH'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD',				'ModifierId',			'GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD_MODIFIER'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD_MODIFIER',		'YieldType',			'YIELD_FOOD'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FOOD_MODIFIER',		'Amount',				1),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH',				'ModifierId',			'GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH_MODIFIER'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH_MODIFIER',		'YieldType',			'YIELD_FAITH'),
	('GODDESS_OF_FESTIVALS_HOLYSITE_PLANTATION_FAITH_MODIFIER',		'Amount',				1),
	('TENGRI_FAITH_PASTURE_ADJACENCY',								'DistrictType',			'DISTRICT_HOLY_SITE'),
	('TENGRI_FAITH_PASTURE_ADJACENCY',								'YieldType',			'YIELD_FAITH'),
	('TENGRI_FAITH_PASTURE_ADJACENCY',								'ImprovementType',		'IMPROVEMENT_PASTURE'),
	('TENGRI_FAITH_PASTURE_ADJACENCY',								'Amount',				2),
	('TENGRI_FAITH_PASTURE_ADJACENCY',								'Description',			'LOC_DISTRICT_PASTURE_FAITH'),
	('TENGRI_HOLYSITE_PASTURE_PRODUCTION',							'ModifierId',			'TENGRI_HOLYSITE_PASTURE_PRODUCTION_MODIFIER'),
	('TENGRI_HOLYSITE_PASTURE_PRODUCTION_MODIFIER',					'YieldType',			'YIELD_PRODUCTION'),
	('TENGRI_HOLYSITE_PASTURE_PRODUCTION_MODIFIER',					'Amount',				1),
	('TENGRI_HOLYSITE_PASTURE_FAITH',								'ModifierId',			'TENGRI_HOLYSITE_PASTURE_FAITH_MODIFIER'),
	('TENGRI_HOLYSITE_PASTURE_FAITH_MODIFIER',						'YieldType',			'YIELD_FAITH'),
	('TENGRI_HOLYSITE_PASTURE_FAITH_MODIFIER',						'Amount',				1),
	('ONE_WITH_NATURE_WONDER_GREAT_PROPHET',						'ModifierId',			'ONE_WITH_NATURE_WONDER_GREAT_PROPHET_MODIFIER'),
	('ONE_WITH_NATURE_WONDER_GREAT_PROPHET_MODIFIER',				'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('ONE_WITH_NATURE_WONDER_GREAT_PROPHET_MODIFIER',				'Amount',				4),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY',							'ModifierId',			'RIVER_GODDESS_FAITH_RIVER_ADJACENCY_MODIFIER'),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY_MODIFIER',				'DistrictType',			'DISTRICT_HOLY_SITE'),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY_MODIFIER',				'YieldType',			'YIELD_FAITH'),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY_MODIFIER',				'Amount',				2),
	('RIVER_GODDESS_FAITH_RIVER_ADJACENCY_MODIFIER',				'Description',			'LOC_DISTRICT_RIVER_FAITH'),
	('RIVER_GODDESS_GREAT_PROPHET',									'ModifierId',			'RIVER_GODDESS_GREAT_PROPHET_MODIFIER'),
	('RIVER_GODDESS_GREAT_PROPHET_MODIFIER',						'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('RIVER_GODDESS_GREAT_PROPHET_MODIFIER',						'Amount',				1),
	('DIVINE_SPARK_MERCHANT',										'ModifierId',			'DIVINE_SPARK_MERCHANT_MODIFIER'),
	('DIVINE_SPARK_MERCHANT_MODIFIER',								'GreatPersonClassType',	'GREAT_PERSON_CLASS_MERCHANT'),
	('DIVINE_SPARK_MERCHANT_MODIFIER',								'Amount',				1),
	('DIVINE_SPARK_ENGINEER',										'ModifierId',			'DIVINE_SPARK_ENGINEER_MODIFIER'),
	('DIVINE_SPARK_ENGINEER_MODIFIER',								'GreatPersonClassType',	'GREAT_PERSON_CLASS_ENGINEER'),
	('DIVINE_SPARK_ENGINEER_MODIFIER',								'Amount',				1),
	('GOD_OF_WAR_GREAT_PROPHET_KILLS',								'ModifierId',			'GOD_OF_WAR_GREAT_PROPHET_KILLS_MODIFIER'),
	('GOD_OF_WAR_GREAT_PROPHET_KILLS_MODIFIER',						'AbilityType',			'ABILITY_GOD_OF_WAR_GREAT_PROPHET'),
	('GOD_OF_WAR_GREAT_PROPHET_POINTS',								'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
	('GOD_OF_WAR_GREAT_PROPHET_POINTS',								'Amount',				25),
	('RELIGIOUS_SETTLEMENTS_INCREASED_TILES',						'ModifierId',			'RELIGIOUS_SETTLEMENTS_INCREASED_TILES_MODIFIER'),
	('RELIGIOUS_SETTLEMENTS_INCREASED_TILES_MODIFIER',				'Amount',				4),
	('FERTILITY_RITES_GRANARY_GROWTH',								'ModifierId',			'FERTILITY_RITES_GRANARY_GROWTH_MODIFIER'),
	('FERTILITY_RITES_GRANARY_GROWTH_MODIFIER',						'Amount',				15),
	('FERTILITY_RITES_GRANARY_FAITH_PURCHASE',						'ModifierId',			'FERTILITY_RITES_GRANARY_FAITH_PURCHASE_MODIFIER'),
	('FERTILITY_RITES_GRANARY_FAITH_PURCHASE_MODIFIER',				'BuildingType',			'BUILDING_GRANARY'),
	('FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT',					'ModifierId',			'FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT_MODIFIER'),
	('FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT_MODIFIER',			'BuildingType',			'BUILDING_GRANARY'),
	('FERTILITY_RITES_GRANARY_PURCHASE_DISCOUNT_MODIFIER',			'Amount',				20),
	('MONUMENT_TO_THE_GODS_MONUMENT_CULTURE',						'ModifierId',			'MONUMENT_TO_THE_GODS_MONUMENT_CULTURE_MODIFIER'),
	('MONUMENT_TO_THE_GODS_MONUMENT_CULTURE_MODIFIER',				'YieldType',			'YIELD_CULTURE'),
	('MONUMENT_TO_THE_GODS_MONUMENT_CULTURE_MODIFIER',				'Amount',				10),
	('MONUMENT_TO_THE_GODS_MONUMENT_FAITH_PURCHASE',				'ModifierId',			'MONUMENT_TO_THE_GODS_MONUMENT_FAITH_PURCHASE_MODIFIER'),
	('MONUMENT_TO_THE_GODS_MONUMENT_FAITH_PURCHASE_MODIFIER',		'BuildingType',			'BUILDING_MONUMENT'),
	('MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT',				'ModifierId',			'MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT_MODIFIER'),
	('MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT_MODIFIER',	'BuildingType',			'BUILDING_MONUMENT'),
	('MONUMENT_TO_THE_GODS_MONUMENT_PURCHASE_DISCOUNT_MODIFIER',	'Amount',				20),
	('CITY_PATRON_GODDESS_CASTLEPRODUCTION',						'ModifierId',			'CITY_PATRON_GODDESS_CASTLEPRODUCTION_MODIFIER'),
	('CITY_PATRON_GODDESS_CASTLEPRODUCTION_MODIFIER',				'BuildingType',			'BUILDING_CASTLE'),
	('CITY_PATRON_GODDESS_CASTLEPRODUCTION_MODIFIER',				'Amount',				50),
	('CITY_PATRON_GODDESS_WALLSPRODUCTION',							'ModifierId',			'CITY_PATRON_GODDESS_WALLSPRODUCTION_MODIFIER'),
	('CITY_PATRON_GODDESS_WALLSPRODUCTION_MODIFIER',				'BuildingType',			'BUILDING_WALLS'),
	('CITY_PATRON_GODDESS_WALLSPRODUCTION_MODIFIER',				'Amount',				50),
	('CITY_PATRON_GODDESS_STARFORTPRODUCTION',						'ModifierId',			'CITY_PATRON_GODDESS_STARFORTPRODUCTION_MODIFIER'),
	('CITY_PATRON_GODDESS_STARFORTPRODUCTION_MODIFIER',				'BuildingType',			'BUILDING_STAR_FORT'),
	('CITY_PATRON_GODDESS_STARFORTPRODUCTION_MODIFIER',				'Amount',				50),
	('CITY_PATRON_GODDESS_TSIKHEPRODUCTION',						'ModifierId',			'CITY_PATRON_GODDESS_TSIKHEPRODUCTION_MODIFIER'),
	('CITY_PATRON_GODDESS_TSIKHEPRODUCTION_MODIFIER',				'BuildingType',			'BUILDING_TSIKHE'),
	('CITY_PATRON_GODDESS_TSIKHEPRODUCTION_MODIFIER',				'Amount',				50),
	('CITY_PATRON_GODDESS_INNERDEFENSE',							'ModifierId',			'CITY_PATRON_GODDESS_INNERDEFENSE_MODIFIER'),
	('CITY_PATRON_GODDESS_INNERDEFENSE_MODIFIER',					'Amount',				6),
	('CITY_PATRON_GODDESS_RANGEDSTRIKE',							'ModifierId',			'CITY_PATRON_GODDESS_RANGEDSTRIKE_MODIFIER'),
	('CITY_PATRON_GODDESS_RANGEDSTRIKE_MODIFIER',					'Amount',				3),
	('MESSENGER_OF_THE_GODS_FREE_SCOUT',							'ModifierId',			'MESSENGER_OF_THE_GODS_FREE_SCOUT_MODIFIER'),
	('MESSENGER_OF_THE_GODS_FREE_SCOUT_MODIFIER',					'UnitPromotionClassType', 'PROMOTION_CLASS_RECON'),
	('MESSENGER_OF_THE_GODS_SCOUT_MOVEMENT',						'ModifierId',			'MESSENGER_OF_THE_GODS_SCOUT_MOVEMENT_MODIFIER'),
	('MESSENGER_OF_THE_GODS_SCOUT_MOVEMENT_MODIFIER',				'Amount',				1),
	('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD',							'ModifierId',			'GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER'),
	('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',					'YieldType',			'YIELD_FOOD'),
	('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',					'Amount',				1),
	('ORAL_TRADITION_PLANTATION_CULTURE',							'ModifierId',			'ORAL_TRADITION_PLANTATION_CULTURE_MODIFIER'),
	('ORAL_TRADITION_PLANTATION_CULTURE_MODIFIER',					'YieldType',			'YIELD_CULTURE'),
	('ORAL_TRADITION_PLANTATION_CULTURE_MODIFIER',					'Amount',				1),
	('ORAL_TRADITION_PLANTATION_GOLD',								'ModifierId',			'ORAL_TRADITION_PLANTATION_GOLD_MODIFIER'),
	('ORAL_TRADITION_PLANTATION_GOLD_MODIFIER',						'YieldType',			'YIELD_GOLD'),
	('ORAL_TRADITION_PLANTATION_GOLD_MODIFIER',						'Amount',				2),
	('LADY_OF_THE_MARSHES_SCIENCE',									'ModifierId',			'LADY_OF_THE_MARSHES_SCIENCE_MODIFIER'),
	('LADY_OF_THE_MARSHES_SCIENCE_MODIFIER',						'YieldType',			'YIELD_SCIENCE'),
	('LADY_OF_THE_MARSHES_SCIENCE_MODIFIER',						'Amount',				1),
	('GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD',					'ModifierId',			'GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD_MODIFIER'),
	('GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD_MODIFIER',			'YieldType',			'YIELD_FOOD'),
	('GODDESS_OF_THE_HARVEST_FARM_RESOURCE_FOOD_MODIFIER',			'Amount',				1),
	('GOD_OF_THE_SEA_FISHINGBOATS_FOOD',							'ModifierId',			'GOD_OF_THE_SEA_FISHINGBOATS_FOOD_MODIFIER'),
	('GOD_OF_THE_SEA_FISHINGBOATS_FOOD_MODIFIER',					'YieldType',			'YIELD_FOOD'),
	('GOD_OF_THE_SEA_FISHINGBOATS_FOOD_MODIFIER',					'Amount',				1),
	('OCEAN_MOTHER_COAST_FOOD',										'ModifierId',			'OCEAN_MOTHER_COAST_FOOD_MODIFIER'),
	('OCEAN_MOTHER_COAST_FOOD_MODIFIER',							'YieldType',			'YIELD_FOOD'),
	('OCEAN_MOTHER_COAST_FOOD_MODIFIER',							'Amount',				1),
	('OCEAN_MOTHER_OCEAN_FOOD',										'ModifierId',			'OCEAN_MOTHER_OCEAN_FOOD_MODIFIER'),
	('OCEAN_MOTHER_OCEAN_FOOD_MODIFIER',							'YieldType',			'YIELD_FOOD'),
	('OCEAN_MOTHER_OCEAN_FOOD_MODIFIER',							'Amount',				1);

insert or replace into Types (Type, Kind) values ('ABILITY_GOD_OF_WAR_GREAT_PROPHET', 'KIND_ABILITY');
insert or replace into TypeTags (Type, Tag) values ('ABILITY_GOD_OF_WAR_GREAT_PROPHET', 'CLASS_ALL_COMBAT_UNITS');
insert or replace into UnitAbilities (UnitAbilityType, Name, Description, Inactive) values
	('ABILITY_GOD_OF_WAR_GREAT_PROPHET', 'LOC_ABILITY_GOD_OF_WAR_GREAT_PROPHET_NAME', 'LOC_ABILITY_GOD_OF_WAR_GREAT_PROPHET_DESCRIPTION', 1);
insert or replace into UnitAbilityModifiers (UnitAbilityType, ModifierId) values
	('ABILITY_GOD_OF_WAR_GREAT_PROPHET', 'GOD_OF_WAR_GREAT_PROPHET_POINTS');

update ModifierArguments set Value = 1 where Name = 'Amount' and ModifierId = 'EARTH_GODDESS_APPEAL_FAITH_MODIFIER';
update ModifierArguments set Value = 1 where Name = 'Amount' and
	(ModifierId = 'RELIGIOUS_IDOLS_LUXURY_MINE_FAITH_MODIFIER' or ModifierId = 'RELIGIOUS_IDOLS_BONUS_MINE_FAITH_MODIFIER');

-- Follower
delete from BeliefModifiers where BeliefType = 'BELIEF_WORK_ETHIC';
-- delete from BeliefModifiers where BeliefType = 'BELIEF_JESUIT_EDUCATION' and ModifierID = 'JESUIT_EDUCATION_CULTURE_BUILDINGS';
insert or replace into BeliefModifiers
	(BeliefType,						ModifierID)
values

	('BELIEF_FEED_THE_WORLD',			'FEED_THE_WORLD_SHRINE_FOOD3'),
	('BELIEF_FEED_THE_WORLD',			'FEED_THE_WORLD_TEMPLE_FOOD3'),
	('BELIEF_FEED_THE_WORLD',			'FEED_THE_WORLD_SHRINE_HOUSING'),
	('BELIEF_FEED_THE_WORLD',			'FEED_THE_WORLD_TEMPLE_HOUSING'),
	('BELIEF_FEED_THE_WORLD',			'FEED_THE_WORLD_POPULATION_FOOD'),
	--
	('BELIEF_CHORAL_MUSIC',				'CHORAL_MUSIC_SHRINE_CULTURE'),
	('BELIEF_CHORAL_MUSIC',				'CHORAL_MUSIC_TEMPLE_CULTURE'),
	('BELIEF_CHORAL_MUSIC',				'CHORAL_MUSIC_POPULATION_CULTURE'),
	--
	('BELIEF_DIVINE_INSPIRATION',		'DIVINE_INSPIRATION_WONDER_FAITH'),
	('BELIEF_DIVINE_INSPIRATION',		'DIVINE_INSPIRATION_FAITH_BUILDINGS'),
	--
	('BELIEF_JESUIT_EDUCATION',			'JESUIT_EDUCATION_SCIENCE_BUILDINGS'),
	('BELIEF_JESUIT_EDUCATION',			'JESUIT_EDUCATION_POPULATION_SCIENCE'),
	--
	('BELIEF_RELIQUARIES',				'RELIQUARIES_RELIC_FAITH'),
	('BELIEF_RELIQUARIES',				'RELIQUARIES_RELIC_TOURISM'),
	--
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_HOLY_SITE_TRADING'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_SHRINE_TRADING'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_TEMPLE_TRADING'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_TIER3_TRADING'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_TRADER_PURCHASE'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_TRADER_DISCOUNT'),
	('BELIEF_RELIGIOUS_COMMUNITY',		'RELIGIOUS_COMMUNITY_TRADER_CAPACITY'),
	--
	('BELIEF_ZEN_MEDITATION',			'ZEN_MEDITATION_AMENITY'),
	-- new ones
	('BELIEF_RELIGIOUS_ART',			'RELIGIOUS_ART_ADJACENCY_CULTURE'),
	('BELIEF_RELIGIOUS_ART',			'RELIGIOUS_ART_CULTURE_BUILDINGS'),
	('BELIEF_WORK_ETHIC',				'WORK_ETHIC_POPULATION_PRODUCTION'),
	('BELIEF_WORK_ETHIC',				'WORK_ETHIC_PRODUCTION_BUILDINGS'),
	('BELIEF_PRACTICAL_APPLICATION',	'PRACTICAL_APPLICATION_POPULATION_GOLD'),
	('BELIEF_PRACTICAL_APPLICATION',	'PRACTICAL_APPLICATION_GOLD_BUILDINGS'),
	-- ('BELIEF_THE_THIRD_TEMPLE',			'THE_THIRD_TEMPLE_DIPLOMACY_BUILDINGS'),
	-- ('BELIEF_THE_THIRD_TEMPLE',			'THE_THIRD_TEMPLE_BUILDER_PURCHASE'),
	-- ('BELIEF_THE_THIRD_TEMPLE',			'THE_THIRD_TEMPLE_BUILDER_DISCOUNT'),
	('BELIEF_RELIGIOUS_COLONIZATION',	'RELIGIOUS_COLONIZATION_DIPLOMACY_BUILDINGS'),
	('BELIEF_RELIGIOUS_COLONIZATION',	'RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT'),
	('BELIEF_RELIGIOUS_COLONIZATION',	'RELIGIOUS_COLONIZATION_GOVERNMENT_BUILDINGS'),
	-- ('BELIEF_RELIGIOUS_COLONIZATION',	'RELIGIOUS_COLONIZATION_SETTLER_PURCHASE'),
	('BELIEF_RELIGIOUS_COLONIZATION',	'RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT');

insert or replace into Modifiers
	(ModifierId,												ModifierType,													SubjectRequirementSetId)
values
	('FEED_THE_WORLD_POPULATION_FOOD',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('FEED_THE_WORLD_POPULATION_FOOD_MODIFIER',					'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',		NULL),
	('CHORAL_MUSIC_POPULATION_CULTURE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('CHORAL_MUSIC_POPULATION_CULTURE_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',		NULL),
	('DIVINE_INSPIRATION_FAITH_BUILDINGS',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('DIVINE_INSPIRATION_FAITH_BUILDINGS_MODIFIER',				'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	('JESUIT_EDUCATION_POPULATION_SCIENCE',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('JESUIT_EDUCATION_POPULATION_SCIENCE_MODIFIER',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',		NULL),
	('RELIGIOUS_COMMUNITY_TRADER_PURCHASE',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COMMUNITY_TRADER_PURCHASE_MODIFIER',			'MODIFIER_CITY_ENABLE_UNIT_FAITH_PURCHASE',						NULL),
	('RELIGIOUS_COMMUNITY_TRADER_DISCOUNT',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COMMUNITY_TRADER_DISCOUNT_MODIFIER',			'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',				NULL),
	('RELIGIOUS_COMMUNITY_TRADER_CAPACITY',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COMMUNITY_TRADER_CAPACITY_MODIFIER',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',					NULL),
	('RELIGIOUS_ART_ADJACENCY_CULTURE',							'MODIFIER_ALL_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',	'RELIGIOUS_ART_ADJACENCY_CULTURE_REQUIREMENTS'),
	('RELIGIOUS_ART_CULTURE_BUILDINGS',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_ART_CULTURE_BUILDINGS_MODIFIER',				'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	('WORK_ETHIC_POPULATION_PRODUCTION',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('WORK_ETHIC_POPULATION_PRODUCTION_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',		NULL),
	('WORK_ETHIC_PRODUCTION_BUILDINGS',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('WORK_ETHIC_PRODUCTION_BUILDINGS_MODIFIER',				'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	('PRACTICAL_APPLICATION_POPULATION_GOLD',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('PRACTICAL_APPLICATION_POPULATION_GOLD_MODIFIER',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',		NULL),
	('PRACTICAL_APPLICATION_GOLD_BUILDINGS',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('PRACTICAL_APPLICATION_GOLD_BUILDINGS_MODIFIER',			'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	-- Builder and Settler
	-- ('THE_THIRD_TEMPLE_DIPLOMACY_BUILDINGS',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	-- ('THE_THIRD_TEMPLE_DIPLOMACY_BUILDINGS_MODIFIER',			'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	-- ('THE_THIRD_TEMPLE_BUILDER_PURCHASE',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	-- ('THE_THIRD_TEMPLE_BUILDER_PURCHASE_MODIFIER',				'MODIFIER_CITY_ENABLE_UNIT_FAITH_PURCHASE',						NULL),
	-- ('THE_THIRD_TEMPLE_BUILDER_DISCOUNT',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	-- ('THE_THIRD_TEMPLE_BUILDER_DISCOUNT_MODIFIER',				'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',				NULL),
	('RELIGIOUS_COLONIZATION_DIPLOMACY_BUILDINGS',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COLONIZATION_DIPLOMACY_BUILDINGS_MODIFIER',		'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	('RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',				NULL),
	('RELIGIOUS_COLONIZATION_GOVERNMENT_BUILDINGS',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COLONIZATION_GOVERNMENT_BUILDINGS_MODIFIER',	'MODIFIER_CITY_ENABLE_BUILDING_FAITH_PURCHASE',					NULL),
	-- ('RELIGIOUS_COLONIZATION_SETTLER_PURCHASE',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	-- ('RELIGIOUS_COLONIZATION_SETTLER_PURCHASE_MODIFIER',		'MODIFIER_CITY_ENABLE_UNIT_FAITH_PURCHASE',						NULL),
	('RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',				NULL);

insert or replace into ModifierArguments
	(ModifierId,												Name,					Value)
values
	-- Follower
	('FEED_THE_WORLD_POPULATION_FOOD',							'ModifierId',			'FEED_THE_WORLD_POPULATION_FOOD_MODIFIER'),
	('FEED_THE_WORLD_POPULATION_FOOD_MODIFIER',					'YieldType',			'YIELD_FOOD'),
	('FEED_THE_WORLD_POPULATION_FOOD_MODIFIER',					'Amount',				0.5),
	--
	('CHORAL_MUSIC_POPULATION_CULTURE',							'ModifierId',			'CHORAL_MUSIC_POPULATION_CULTURE_MODIFIER'),
	('CHORAL_MUSIC_POPULATION_CULTURE_MODIFIER',				'YieldType',			'YIELD_CULTURE'),
	('CHORAL_MUSIC_POPULATION_CULTURE_MODIFIER',				'Amount',				0.5),
	--
	('DIVINE_INSPIRATION_FAITH_BUILDINGS',						'ModifierId',			'DIVINE_INSPIRATION_FAITH_BUILDINGS_MODIFIER'),
	('DIVINE_INSPIRATION_FAITH_BUILDINGS_MODIFIER',				'DistrictType',			'DISTRICT_HOLY_SITE'),
	--
	('JESUIT_EDUCATION_POPULATION_SCIENCE',						'ModifierId',			'JESUIT_EDUCATION_POPULATION_SCIENCE_MODIFIER'),
	('JESUIT_EDUCATION_POPULATION_SCIENCE_MODIFIER',			'YieldType',			'YIELD_SCIENCE'),
	('JESUIT_EDUCATION_POPULATION_SCIENCE_MODIFIER',			'Amount',				0.5),
	--
	('RELIGIOUS_COMMUNITY_TRADER_PURCHASE',						'ModifierId',			'RELIGIOUS_COMMUNITY_TRADER_PURCHASE_MODIFIER'),
	('RELIGIOUS_COMMUNITY_TRADER_PURCHASE_MODIFIER',			'Tag',					'CLASS_TRADER'),
	('RELIGIOUS_COMMUNITY_TRADER_DISCOUNT',						'ModifierId',			'RELIGIOUS_COMMUNITY_TRADER_DISCOUNT_MODIFIER'),
	('RELIGIOUS_COMMUNITY_TRADER_DISCOUNT_MODIFIER',			'UnitType',				'UNIT_TRADER'),
	('RELIGIOUS_COMMUNITY_TRADER_DISCOUNT_MODIFIER',			'Amount',				20),
	('RELIGIOUS_COMMUNITY_TRADER_CAPACITY',						'ModifierId',			'RELIGIOUS_COMMUNITY_TRADER_CAPACITY_MODIFIER'),
	('RELIGIOUS_COMMUNITY_TRADER_CAPACITY_MODIFIER',			'Amount',				1),
	--
	('RELIGIOUS_ART_ADJACENCY_CULTURE',							'YieldTypeToMirror',	'YIELD_FAITH'),
	('RELIGIOUS_ART_ADJACENCY_CULTURE',							'YieldTypeToGrant',		'YIELD_CULTURE'),
	('RELIGIOUS_ART_CULTURE_BUILDINGS',							'ModifierId',			'RELIGIOUS_ART_CULTURE_BUILDINGS_MODIFIER'),
	('RELIGIOUS_ART_CULTURE_BUILDINGS_MODIFIER',				'DistrictType',			'DISTRICT_THEATER'),
	--
	('WORK_ETHIC_POPULATION_PRODUCTION',						'ModifierId',			'WORK_ETHIC_POPULATION_PRODUCTION_MODIFIER'),
	('WORK_ETHIC_POPULATION_PRODUCTION_MODIFIER',				'YieldType',			'YIELD_PRODUCTION'),
	('WORK_ETHIC_POPULATION_PRODUCTION_MODIFIER',				'Amount',				0.5),
	('WORK_ETHIC_PRODUCTION_BUILDINGS',							'ModifierId',			'WORK_ETHIC_PRODUCTION_BUILDINGS_MODIFIER'),
	('WORK_ETHIC_PRODUCTION_BUILDINGS_MODIFIER',				'DistrictType',			'DISTRICT_INDUSTRIAL_ZONE'),
	--
	('PRACTICAL_APPLICATION_POPULATION_GOLD',					'ModifierId',			'PRACTICAL_APPLICATION_POPULATION_GOLD_MODIFIER'),
	('PRACTICAL_APPLICATION_POPULATION_GOLD_MODIFIER',			'YieldType',			'YIELD_GOLD'),
	('PRACTICAL_APPLICATION_POPULATION_GOLD_MODIFIER',			'Amount',				1),
	('PRACTICAL_APPLICATION_GOLD_BUILDINGS',					'ModifierId',			'PRACTICAL_APPLICATION_GOLD_BUILDINGS_MODIFIER'),
	('PRACTICAL_APPLICATION_GOLD_BUILDINGS_MODIFIER',			'DistrictType',			'DISTRICT_COMMERCIAL_HUB'),
	-- Builder and Settler
	-- ('THE_THIRD_TEMPLE_DIPLOMACY_BUILDINGS',					'ModifierId',			'THE_THIRD_TEMPLE_DIPLOMACY_BUILDINGS_MODIFIER'),
	-- ('THE_THIRD_TEMPLE_DIPLOMACY_BUILDINGS_MODIFIER',			'DistrictType',			'DISTRICT_DIPLOMATIC_QUARTER'),
	-- ('THE_THIRD_TEMPLE_BUILDER_PURCHASE',						'ModifierId',			'THE_THIRD_TEMPLE_BUILDER_PURCHASE_MODIFIER'),
	-- ('THE_THIRD_TEMPLE_BUILDER_PURCHASE_MODIFIER',				'Tag',					'CLASS_BUILDER'),
	-- ('THE_THIRD_TEMPLE_BUILDER_DISCOUNT',						'ModifierId',			'THE_THIRD_TEMPLE_BUILDER_DISCOUNT_MODIFIER'),
	-- ('THE_THIRD_TEMPLE_BUILDER_DISCOUNT_MODIFIER',				'UnitType',				'UNIT_BUILDER'),
	-- ('THE_THIRD_TEMPLE_BUILDER_DISCOUNT_MODIFIER',				'Amount',				20),
	('RELIGIOUS_COLONIZATION_DIPLOMACY_BUILDINGS',				'ModifierId',			'RELIGIOUS_COLONIZATION_DIPLOMACY_BUILDINGS_MODIFIER'),
	('RELIGIOUS_COLONIZATION_DIPLOMACY_BUILDINGS_MODIFIER',		'DistrictType',			'DISTRICT_DIPLOMATIC_QUARTER'),
	('RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT',					'ModifierId',			'RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT_MODIFIER'),
	('RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT_MODIFIER',		'UnitType',				'UNIT_BUILDER'),
	('RELIGIOUS_COLONIZATION_BUILDER_DISCOUNT_MODIFIER',		'Amount',				20),
	('RELIGIOUS_COLONIZATION_GOVERNMENT_BUILDINGS',				'ModifierId',			'RELIGIOUS_COLONIZATION_GOVERNMENT_BUILDINGS_MODIFIER'),
	('RELIGIOUS_COLONIZATION_GOVERNMENT_BUILDINGS_MODIFIER',	'DistrictType',			'DISTRICT_GOVERNMENT'),
	-- ('RELIGIOUS_COLONIZATION_SETTLER_PURCHASE',					'ModifierId',			'RELIGIOUS_COLONIZATION_SETTLER_PURCHASE_MODIFIER'),
	-- ('RELIGIOUS_COLONIZATION_SETTLER_PURCHASE_MODIFIER',		'Tag',					'CLASS_SETTLER'),
	('RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT',					'ModifierId',			'RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT_MODIFIER'),
	('RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT_MODIFIER',		'UnitType',				'UNIT_SETTLER'),
	('RELIGIOUS_COLONIZATION_SETTLER_DISCOUNT_MODIFIER',		'Amount',				20);

-- Founder
-- delete from BeliefModifiers where BeliefType = 'BELIEF_LAY_MINISTRY';
-- delete from BeliefModifiers where BeliefType = 'BELIEF_STEWARDSHIP';
-- delete from BeliefModifiers where BeliefType = 'BELIEF_RELIGIOUS_UNITY';
insert or replace into BeliefModifiers
	(BeliefType,						ModifierID)
values
	-- Founder
	('BELIEF_TITHE',					'TITHE_GOLD_FOLLOWER'),
	('BELIEF_RELIGIOUS_UNITY',			'RELIGIOUS_UNITY_FAITH_FOLLOWER'),
	('BELIEF_WORLD_CHURCH',				'WORLD_CHURCH_CULTURE_FOLLOWER'),
	('BELIEF_CROSS_CULTURAL_DIALOGUE',	'CROSS_CULTURAL_DIALOGUE_SCIENCE_FOLLOWER'),
	('BELIEF_CHURCH_PROPERTY',			'CHURCH_PROPERTY_GOLD_CITY'),
	('BELIEF_PILGRIMAGE',				'PILGRIMAGE_FAITH_CITY'),
	('BELIEF_LAY_MINISTRY',				'LAY_MINISTRY_CULTURE_CITY'),
	('BELIEF_STEWARDSHIP',				'STEWARDSHIP_SCIENCE_CITY'),
	('BELIEF_PAPAL_PRIMACY',			'PAPAL_PRIMACY_PRESSURE_ON_ADOPTION'),
	('BELIEF_SACRED_PLACES',			'SACRED_PLACES_FAITH_WONDER_CITY'),
	('BELIEF_SACRED_PLACES',			'SACRED_PLACES_CULTURE_WONDER_CITY'),
	('BELIEF_SACRED_PLACES',			'SACRED_PLACES_SCIENCE_WONDER_CITY'),
	('BELIEF_SACRED_PLACES',			'SACRED_PLACES_GOLD_WONDER_CITY'),
	('BELIEF_INITIATION_RITES',			'INITIATION_RITES_GOLD_POPULATION'),
	-- Enhancer
	('BELIEF_PIOUS_MERCHANTS',			'PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE'),
	('BELIEF_CANONIZATION_OF_SAINTS',	'CANONIZATION_OF_SAINTS_GP_RELIGIOUS_PRESSURE');
	-- Worship

-- x yield per follower
update ModifierArguments set Value = 1 where ModifierId = 'TITHE_GOLD_FOLLOWER_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 1 where ModifierId = 'TITHE_GOLD_FOLLOWER_MODIFIER' and Name = 'PerXItems';
update ModifierArguments set Value = 2 where ModifierId = 'WORLD_CHURCH_CULTURE_FOLLOWER_MODIFIER' and Name = 'PerXItems';
update ModifierArguments set Value = 2 where ModifierId = 'CROSS_CULTURAL_DIALOGUE_SCIENCE_FOLLOWER_MODIFIER' and Name = 'PerXItems';
-- x yield per city
update ModifierArguments set Value = 4 where ModifierId = 'PILGRIMAGE_FAITH_CITY_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 8 where ModifierId = 'CHURCH_PROPERTY_GOLD_CITY_MODIFIER' and Name = 'Amount';

insert or replace into Modifiers
	(ModifierId,											ModifierType,												SubjectRequirementSetId)
values
	-- Founder
	('LAY_MINISTRY_CULTURE_CITY',								'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('LAY_MINISTRY_CULTURE_CITY_MODIFIER',						'MODIFIER_PLAYER_RELIGION_ADD_RELIGIOUS_BELIEF_YIELD',		NULL),
	('STEWARDSHIP_SCIENCE_CITY',								'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('STEWARDSHIP_SCIENCE_CITY_MODIFIER',						'MODIFIER_PLAYER_RELIGION_ADD_RELIGIOUS_BELIEF_YIELD',		NULL),
	('RELIGIOUS_UNITY_FAITH_FOLLOWER',							'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('RELIGIOUS_UNITY_FAITH_FOLLOWER_MODIFIER',					'MODIFIER_PLAYER_RELIGION_ADD_RELIGIOUS_BELIEF_YIELD',		NULL),
	('INITIATION_RITES_GOLD_POPULATION',						'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('INITIATION_RITES_GOLD_POPULATION_MODIFIER',				'MODIFIER_PLAYER_UNITS_ADJUST_INITIATION_YIELD_POPULATION',	NULL),
	-- Enhancer
	('PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE_MODIFIER',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_RELIGIOUS_PRESSURE',	NULL),
	('CANONIZATION_OF_SAINTS_GP_RELIGIOUS_PRESSURE',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('CANONIZATION_OF_SAINTS_GP_RELIGIOUS_PRESSURE_MODIFIER',	'MODIFIER_PLAYER_GRANT_RELIGIOUS_PRESSURE_GREAT_PERSON_ACTIVATED',	NULL);

insert or replace into ModifierArguments
	(ModifierId,											Name,					Value)
values
	-- Founder

	('RELIGIOUS_UNITY_FAITH_FOLLOWER',							'ModifierId',			'RELIGIOUS_UNITY_FAITH_FOLLOWER_MODIFIER'),
	('RELIGIOUS_UNITY_FAITH_FOLLOWER_MODIFIER',					'BeliefYieldType',		'BELIEF_YIELD_PER_FOLLOWER'),
	('RELIGIOUS_UNITY_FAITH_FOLLOWER_MODIFIER',					'YieldType',			'YIELD_FAITH'),
	('RELIGIOUS_UNITY_FAITH_FOLLOWER_MODIFIER',					'Amount',				1),
	('RELIGIOUS_UNITY_FAITH_FOLLOWER_MODIFIER',					'PerXItems',			2),
	('LAY_MINISTRY_CULTURE_CITY',								'ModifierId',			'LAY_MINISTRY_CULTURE_CITY_MODIFIER'),
	('LAY_MINISTRY_CULTURE_CITY_MODIFIER',						'BeliefYieldType',		'BELIEF_YIELD_PER_CITY'),
	('LAY_MINISTRY_CULTURE_CITY_MODIFIER',						'YieldType',			'YIELD_CULTURE'),
	('LAY_MINISTRY_CULTURE_CITY_MODIFIER',						'Amount',				4),
	('LAY_MINISTRY_CULTURE_CITY_MODIFIER',						'PerXItems',			1),
	('STEWARDSHIP_SCIENCE_CITY',								'ModifierId',			'STEWARDSHIP_SCIENCE_CITY_MODIFIER'),
	('STEWARDSHIP_SCIENCE_CITY_MODIFIER',						'BeliefYieldType',		'BELIEF_YIELD_PER_CITY'),
	('STEWARDSHIP_SCIENCE_CITY_MODIFIER',						'YieldType',			'YIELD_SCIENCE'),
	('STEWARDSHIP_SCIENCE_CITY_MODIFIER',						'Amount',				4),
	('STEWARDSHIP_SCIENCE_CITY_MODIFIER',						'PerXItems',			1),
	('INITIATION_RITES_GOLD_POPULATION',						'ModifierId',			'INITIATION_RITES_GOLD_POPULATION_MODIFIER'),
	('INITIATION_RITES_GOLD_POPULATION_MODIFIER',				'YieldType',			'YIELD_GOLD'),
	('INITIATION_RITES_GOLD_POPULATION_MODIFIER',				'Amount',				50),
	-- Enhancer
	('PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE',				'ModifierId',			'PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE_MODIFIER'),
	('PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE_MODIFIER',		'Origin',				1),
	('PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE_MODIFIER',		'Destination',			1),
	('PIOUS_MERCHANTS_TRADER_RELIGIOUS_PRESSURE_MODIFIER',		'Amount',				100),
	('CANONIZATION_OF_SAINTS_GP_RELIGIOUS_PRESSURE',			'ModifierId',			'CANONIZATION_OF_SAINTS_GP_RELIGIOUS_PRESSURE_MODIFIER'),
	('CANONIZATION_OF_SAINTS_GP_RELIGIOUS_PRESSURE_MODIFIER',	'Amount',				400);

-- Enhancer
-- update ModifierArguments set Value = 25 where ModifierId = 'HOLY_ORDER_MISSIONARY_DISCOUNT_MODIFIER' and Name = 'Amount';
-- update ModifierArguments set Value = 25 where ModifierId = 'HOLY_ORDER_APOSTLE_DISCOUNT_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 5 where ModifierId = 'JUST_WAR_COMBAT_BONUS_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'DEFENDER_OF_FAITH_COMBAT_BONUS_MODIFIER' and Name = 'Amount';

update Modifiers set ModifierType = 'MODIFIER_ALL_UNITS_ADJUST_HEAL_PER_TURN' where ModifierId = 'HOLY_WATERS_HEALING_MODIFIER';
update ModifierArguments set Value = 20 where ModifierId = 'HOLY_WATERS_HEALING_MODIFIER' and Name = 'Amount';
-- update Beliefs set BeliefClassType = 'BELIEF_CLASS_ENHANCER' where BeliefType = 'BELIEF_GOD_OF_HEALING';

-- By 小小雨10101
-- Reliquaries add tourism for shrine and temple.
-- Sacred path value updated
--

insert or replace into BeliefModifiers
	(BeliefType,							ModifierID)
values
	('BELIEF_RELIQUARIES',					'BELIEF_RELIQUARIES_SHRINE_TOURISM'),
	('BELIEF_RELIQUARIES',					'BELIEF_RELIQUARIES_TEMPLE_TOURISM');

insert or replace into Modifiers
	(ModifierId,										ModifierType,										SubjectRequirementSetId)
values
	('BELIEF_RELIQUARIES_SHRINE_TOURISM',				'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_RELIGION_AND_HOLYSITE_REQUIREMENTS'),
	('BELIEF_RELIQUARIES_SHRINE_TOURISM_MODIFIER',		'MODIFIER_PLAYER_DISTRICT_ADJUST_TOURISM_CHANGE',	'BUILDING_IS_SHRINE'),
	('BELIEF_RELIQUARIES_TEMPLE_TOURISM',				'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER',			'CITY_FOLLOWS_RELIGION_AND_HOLYSITE_REQUIREMENTS'),
	('BELIEF_RELIQUARIES_TEMPLE_TOURISM_MODIFIER',		'MODIFIER_PLAYER_DISTRICT_ADJUST_TOURISM_CHANGE',	'BUILDING_IS_TEMPLE_XP2');

insert or replace into ModifierArguments
	(ModifierId,										Name,					Value)
values
	('BELIEF_RELIQUARIES_SHRINE_TOURISM',				'ModifierId',			'BELIEF_RELIQUARIES_SHRINE_TOURISM_MODIFIER'),
	('BELIEF_RELIQUARIES_SHRINE_TOURISM_MODIFIER',		'Amount',				2),
	('BELIEF_RELIQUARIES_TEMPLE_TOURISM',				'ModifierId',			'BELIEF_RELIQUARIES_TEMPLE_TOURISM_MODIFIER'),
	('BELIEF_RELIQUARIES_TEMPLE_TOURISM_MODIFIER',		'Amount',				4);

--SACRED_PLACES
update ModifierArguments set Value = 3 where ModifierId = 'SACRED_PLACES_FAITH_WONDER_CITY_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'SACRED_PLACES_CULTURE_WONDER_CITY_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'SACRED_PLACES_SCIENCE_WONDER_CITY_MODIFIER' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'SACRED_PLACES_GOLD_WONDER_CITY_MODIFIER' and Name = 'Amount';

--Founder
insert or replace into BeliefModifiers
	(BeliefType,											ModifierID)
values
	('BELIEF_PAPAL_PRIMACY',								'PAPAL_PRIMACY_LEVY_DISCOUNT'),
	('BELIEF_PAPAL_PRIMACY',								'RELIGIOUS_UNITY_ENVOY_ON_ADOPTION'),
	('BELIEF_TO_THE_GLORY_OF_GOD',							'TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT'),
	('BELIEF_TO_THE_GLORY_OF_GOD',							'TO_THE_GLORY_OF_GOD_GREAT_PERSON_FAVOR');				

insert or replace into Modifiers
	(ModifierId,											ModifierType,												SubjectRequirementSetId)
values
	('PAPAL_PRIMACY_LEVY_DISCOUNT',							'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('PAPAL_PRIMACY_LEVY_DISCOUNT_MODIFIER',				'MODIFIER_PLAYER_ADJUST_LEVY_DISCOUNT_PERCENT',				NULL),
--	('PAPAL_PRIMACY_ENVOY_ON_ADOPTION',						'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
--	('PAPAL_PRIMACY_ENVOY_ON_ADOPTION_MODIFIER',			'MODIFIER_PLAYER_RELIGION_ENABLE_AWARDS_ENVOY',				NULL),
	('TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT_MODIFIER',	'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_PATRONAGE_DISCOUNT_PERCENT',NULL),
	('TO_THE_GLORY_OF_GOD_GREAT_PERSON_FAVOR',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('TO_THE_GLORY_OF_GOD_GREAT_PERSON_FAVOR_MODIFIER',		'MODIFIER_PLAYER_ADJUST_GREATPERSON_FAVOR_MODIFIER',		NULL);

insert or replace into ModifierArguments
	(ModifierId,											Name,							Value)
values	
	('PAPAL_PRIMACY_LEVY_DISCOUNT',							'ModifierId',					'PAPAL_PRIMACY_LEVY_DISCOUNT_MODIFIER'),
	('PAPAL_PRIMACY_LEVY_DISCOUNT_MODIFIER',				'Percent',						20),
--	('PAPAL_PRIMACY_ENVOY_ON_ADOPTION',						'ModifierId',					'PAPAL_PRIMACY_ENVOY_ON_ADOPTION_MODIFIER'),
--	('PAPAL_PRIMACY_ENVOY_ON_ADOPTION_MODIFIER',			'Enable',						1),
	('TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT',			'ModifierId',					'TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT_MODIFIER'),
	('TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT_MODIFIER',	'YieldType',					'YIELD_FAITH'),
	('TO_THE_GLORY_OF_GOD_GREAT_PRESON_DISCOUNT_MODIFIER',	'Amount',						25),
	('TO_THE_GLORY_OF_GOD_GREAT_PERSON_FAVOR',				'ModifierId',					'TO_THE_GLORY_OF_GOD_GREAT_PERSON_FAVOR_MODIFIER'),
	('TO_THE_GLORY_OF_GOD_GREAT_PERSON_FAVOR_MODIFIER',		'Amount',						50);


-- By 利牙菠萝
insert or replace into BeliefModifiers
	(BeliefType,						ModifierID)
values
	('BELIEF_SCHOLASTICISM',			'SCHOLASTICISM_COMBAT_STRENGTH'),
	('BELIEF_MONASTIC_ISOLATION',		'MONASTIC_ISOLATION_INQUISITOR_DISCOUNT'),
	('BELIEF_MONASTIC_ISOLATION',		'MONASTIC_ISOLATION_INQUISITOR_CHARGE'),
	('BELIEF_MONASTIC_ISOLATION',		'MONASTIC_ISOLATION_PRESSURE_REDUCTION');

insert or replace into Modifiers
	(ModifierId,											ModifierType,												SubjectRequirementSetId)
values
	('MONASTIC_ISOLATION_PRESSURE_REDUCTION',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('MONASTIC_ISOLATION_PRESSURE_REDUCTION_MODIFIER',		'MODIFIER_PLAYER_CITIES_RELIGION_IGNORE_PRESSURE',			NULL),
	('MONASTIC_ISOLATION_INQUISITOR_DISCOUNT',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('MONASTIC_ISOLATION_INQUISITOR_DISCOUNT_MODIFIER',		'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',			NULL),
	('MONASTIC_ISOLATION_INQUISITOR_CHARGE',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('MONASTIC_ISOLATION_INQUISITOR_CHARGE_MODIFIER',		'MODIFIER_PLAYER_UNITS_ADJUST_SPREAD_CHARGES',				'UNIT_IS_INQUISITOR'),

	('SCHOLASTICISM_COMBAT_STRENGTH',						'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',						'PLAYER_FOUNDED_RELIGION_REQUIREMENTS'),
	('SCHOLASTICISM_COMBAT_STRENGTH_MODIFIER',				'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',						NULL);

insert or replace into ModifierArguments
	(ModifierId,											Name,					Value)
values
	('MONASTIC_ISOLATION_PRESSURE_REDUCTION',				'ModifierId',			'MONASTIC_ISOLATION_PRESSURE_REDUCTION_MODIFIER'),
	('MONASTIC_ISOLATION_PRESSURE_REDUCTION_MODIFIER',		'Enable',				1),
	('MONASTIC_ISOLATION_INQUISITOR_DISCOUNT',				'ModifierId',			'MONASTIC_ISOLATION_INQUISITOR_DISCOUNT_MODIFIER'),
	('MONASTIC_ISOLATION_INQUISITOR_DISCOUNT_MODIFIER',		'UnitType',				'UNIT_INQUISITOR'),
	('MONASTIC_ISOLATION_INQUISITOR_DISCOUNT_MODIFIER',		'Amount',				30),
	('MONASTIC_ISOLATION_INQUISITOR_CHARGE',				'ModifierId',			'MONASTIC_ISOLATION_INQUISITOR_CHARGE_MODIFIER'),
	('MONASTIC_ISOLATION_INQUISITOR_CHARGE_MODIFIER',		'Amount',				1),

	('SCHOLASTICISM_COMBAT_STRENGTH',						'ModifierId',			'SCHOLASTICISM_COMBAT_STRENGTH_MODIFIER'),
	('SCHOLASTICISM_COMBAT_STRENGTH_MODIFIER',				'AbilityType',			'ABILITY_SCHOLASTICISM_BUFF');
