-- Adding Yield Creator building as a dummy building. i.e. InternalOnly = true.
INSERT INTO Types (Type, Kind) VALUES
('BUILDING_YIELD_CREATOR', 'KIND_BUILDING');

INSERT INTO Buildings (BuildingType, Name, Cost, Description, InternalOnly) VALUES
('BUILDING_YIELD_CREATOR', 'LOC_BUILDING_YIELD_CREATOR_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_DESCRIPTION', 1);

-- Adding Yield Creator Worker buildings as dummy buildinsg to help granting Yield. i.e. InternalOnly = true.
INSERT INTO Types (Type, Kind) VALUES
-- Gold
('BUILDING_YIELD_CREATOR_WORKER_GOLD_10',   'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_5',    'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_2',    'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_1',    'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_10_N', 'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_5_N',  'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_2_N',  'KIND_BUILDING'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_1_N',  'KIND_BUILDING');

INSERT INTO Buildings (BuildingType, Name, Cost, Description, InternalOnly) VALUES
-- Gold
('BUILDING_YIELD_CREATOR_WORKER_GOLD_10',   'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_5',    'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_2',    'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_1',    'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_10_N', 'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_5_N',  'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_2_N',  'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_1_N',  'LOC_BUILDING_YIELD_CREATOR_WORKER_NAME', 1, 'LOC_BUILDING_YIELD_CREATOR_WORKER_DESCRIPTION', 1);

INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
-- Gold
('BUILDING_YIELD_CREATOR_WORKER_GOLD_10',   'YIELD_CREATOR_GOLD_10'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_5',    'YIELD_CREATOR_GOLD_5'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_2',    'YIELD_CREATOR_GOLD_2'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_1',    'YIELD_CREATOR_GOLD_1'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_10_N', 'YIELD_CREATOR_GOLD_10_N'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_5_N',  'YIELD_CREATOR_GOLD_5_N'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_2_N',  'YIELD_CREATOR_GOLD_2_N'),
('BUILDING_YIELD_CREATOR_WORKER_GOLD_1_N',  'YIELD_CREATOR_GOLD_1_N');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent) VALUES
-- Gold
('YIELD_CREATOR_GOLD_10',   'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_5',    'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_2',    'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_1',    'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_10_N', 'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_5_N',  'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_2_N',  'MODIFIER_YIELD_CREATOR', 1, 1),
('YIELD_CREATOR_GOLD_1_N',  'MODIFIER_YIELD_CREATOR', 1, 1);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
-- Gold
('YIELD_CREATOR_GOLD_10',   'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_5',    'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_2',    'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_1',    'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_10_N', 'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_5_N',  'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_2_N',  'BuildingType', 'BUILDING_YIELD_CREATOR'),
('YIELD_CREATOR_GOLD_1_N',  'BuildingType', 'BUILDING_YIELD_CREATOR'),

('YIELD_CREATOR_GOLD_10',   'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_5',    'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_2',    'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_1',    'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_10_N', 'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_5_N',  'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_2_N',  'YieldType', 'YIELD_GOLD'),
('YIELD_CREATOR_GOLD_1_N',  'YieldType', 'YIELD_GOLD'),

('YIELD_CREATOR_GOLD_10',   'Amount', '10'),
('YIELD_CREATOR_GOLD_5',    'Amount', '5'),
('YIELD_CREATOR_GOLD_2',    'Amount', '2'),
('YIELD_CREATOR_GOLD_1',    'Amount', '1'),
('YIELD_CREATOR_GOLD_10_N', 'Amount', '-10'),
('YIELD_CREATOR_GOLD_5_N',  'Amount', '-5'),
('YIELD_CREATOR_GOLD_2_N',  'Amount', '-2'),
('YIELD_CREATOR_GOLD_1_N',  'Amount', '-1');


-- Dynamic modifier MODIFIER_YIELD_CREATOR declaration.
INSERT INTO Types (Type, Kind) VALUES 
('MODIFIER_YIELD_CREATOR', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODIFIER_YIELD_CREATOR', 'COLLECTION_OWNER_CITY', 'EFFECT_ADJUST_BUILDING_YIELD_CHANGE');
