-- Create 50 sets of modifiers through the loop below.
WITH RECURSIVE
  Indices(i) AS (SELECT 1 UNION ALL SELECT (i + 1) FROM Indices LIMIT 50)
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent)
SELECT "YIELD_CREATOR_FOOD_" || i, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FOOD_" || i || "_N", 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_PRODUCTION_" || i, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_PRODUCTION_" || i || "_N", 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_GOLD_" || i, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_GOLD_" || i || "_N", 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FAITH_" || i, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FAITH_" || i || "_N", 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_SCIENCE_" || i, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_SCIENCE_" || i || "_N", 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_CULTURE_" || i, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_CULTURE_" || i || "_N", 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 1, 1 FROM Indices;

WITH RECURSIVE
  Indices(i) AS (SELECT 1 UNION ALL SELECT (i + 1) FROM Indices LIMIT 50)
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT "YIELD_CREATOR_FOOD_" || i, 'YieldType', 'YIELD_FOOD' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FOOD_" || i, 'Amount', i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FOOD_" || i || "_N", 'YieldType', 'YIELD_FOOD' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FOOD_" || i || "_N", 'Amount', -i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_PRODUCTION_" || i, 'YieldType', 'YIELD_PRODUCTION' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_PRODUCTION_" || i, 'Amount', i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_PRODUCTION_" || i || "_N", 'YieldType', 'YIELD_PRODUCTION' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_PRODUCTION_" || i || "_N", 'Amount', -i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_GOLD_" || i, 'YieldType', 'YIELD_GOLD' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_GOLD_" || i, 'Amount', i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_GOLD_" || i || "_N", 'YieldType', 'YIELD_GOLD' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_GOLD_" || i || "_N", 'Amount', -i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FAITH_" || i, 'YieldType', 'YIELD_FAITH' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FAITH_" || i, 'Amount', i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FAITH_" || i || "_N", 'YieldType', 'YIELD_FAITH' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_FAITH_" || i || "_N", 'Amount', -i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_SCIENCE_" || i, 'YieldType', 'YIELD_SCIENCE' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_SCIENCE_" || i, 'Amount', i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_SCIENCE_" || i || "_N", 'YieldType', 'YIELD_SCIENCE' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_SCIENCE_" || i || "_N", 'Amount', -i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_CULTURE_" || i, 'YieldType', 'YIELD_CULTURE' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_CULTURE_" || i, 'Amount', i FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_CULTURE_" || i || "_N", 'YieldType', 'YIELD_CULTURE' FROM Indices
UNION ALL
SELECT "YIELD_CREATOR_CULTURE_" || i || "_N", 'Amount', -i FROM Indices;
