-------------------------------------
--     GreatPeople Adjustments     --
-------------------------------------

-- TODO: Great prophet grant 1 extra district slot.
-------------------------------------------------------------------------------------------------------------------------------------------
---  Great Engineer
-------------------------------------------------------------------------------------------------------------------------------------------
-- bisheng:if printing eruka is boosted grant this tech GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_MATHEMATICS
-- chengqiangge: +1 great engineer points for each level wall 
-- davinci: +1 production for workshop
-- CHARLES_CORREA: +2 appeal nationwide&ALVAR_AALTO: +1 appeal nationwide
-- SHAH_JAHAN :tourism from district adjacency nationwide
-- JOHN_A_ROEBLING: little goldengate + wonder tourism
-- SHAH_JAHAN: to renissance era

delete from GreatPersonIndividualActionModifiers where ModifierId = 'GREATPERSON_PRINTINGTECHBOOST';
-- update ModifierArguments set Value = 2 where ModifierId = 'GREATPERSON_WORKSHOP_CULTURE' and Name = 'Amount';
delete from GreatPersonIndividualActionModifiers where ModifierId = 'GREATPERSON_CULTURE_BOMB_TRIGGER_INDUSTRIAL_ZONE';
delete from GreatPersonIndividualActionModifiers where ModifierId = 'GREATPERSON_CITY_APPEAL_SMALL';	
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_KENZO_TANGE';
update GreatPersonIndividuals set EraType = 'ERA_RENAISSANCE' where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_SHAH_JAHAN';
insert or replace into GreatPersonIndividualActionModifiers 
	(GreatPersonIndividualType, 						ModifierId)
values
	('GREAT_PERSON_INDIVIDUAL_BI_SHENG', 				'GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_PRINTING'),
	('GREAT_PERSON_INDIVIDUAL_JAMES_OF_ST_GEORGE',		'GREAT_PERSON_INDIVIDUAL_WALL_GEP'),
	('GREAT_PERSON_INDIVIDUAL_JAMES_OF_ST_GEORGE',		'GREAT_PERSON_INDIVIDUAL_CASTLE_GEP'),
	('GREAT_PERSON_INDIVIDUAL_JAMES_OF_ST_GEORGE',		'GREAT_PERSON_INDIVIDUAL_STAR_WALL_GEP'),
	-- ('GREAT_PERSON_INDIVIDUAL_LEONARDO_DA_VINCI',		'GREATPERSON_WORKSHOP_PRODUCTION'),
	('GREAT_PERSON_INDIVIDUAL_ALVAR_AALTO',				'GREATPERSON_NATIONAL_APPEAL'),
	('GREAT_PERSON_INDIVIDUAL_JOHN_A_ROEBLING',			'GREATPERSON_SINGLECITY_APPEAL'),
	('GREAT_PERSON_INDIVIDUAL_JOHN_A_ROEBLING',			'GREATPERSON_SINGLECITY_WONDER_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_JOHN_A_ROEBLING',			'GREATPERSON_SINGLECITY_IMPROVEMENT_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_JOHN_A_ROEBLING',			'GREATPERSON_SINGLECITY_NATIONAL_PARK_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_CHARLES_CORREA',			'GREATPERSON_NATIONAL_APPEAL_BIG'),
	('GREAT_PERSON_INDIVIDUAL_KENZO_TANGE',				'GREATPERSON_NATIONAL_DISTRICT_SCIENCE_ADJACENCY_AS_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_KENZO_TANGE',				'GREATPERSON_NATIONAL_DISTRICT_CULTURE_ADJACENCY_AS_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_KENZO_TANGE',				'GREATPERSON_NATIONAL_DISTRICT_FAITH_ADJACENCY_AS_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_KENZO_TANGE',				'GREATPERSON_NATIONAL_DISTRICT_PRODUCTION_ADJACENCY_AS_TOURISM'),
	('GREAT_PERSON_INDIVIDUAL_KENZO_TANGE',				'GREATPERSON_NATIONAL_DISTRICT_GOLD_ADJACENCY_AS_TOURISM');

insert or replace into Modifiers
	(ModifierId, 										ModifierType, 								Runonce, Permanent, SubjectRequirementSetId)
values
	('GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_PRINTING',	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			1,1, 	NULL),
	('GREAT_PERSON_INDIVIDUAL_WALL_GEP',				'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT', 	0,1,	'CITY_HAS_ANCIENT_WALLS'),
	('GREAT_PERSON_INDIVIDUAL_CASTLE_GEP',				'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		0,1,	'CITY_HAS_MEDIEVAL_WALLS'),
	('GREAT_PERSON_INDIVIDUAL_STAR_WALL_GEP',			'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		0,1,	'CITY_HAS_RENAISSANCE_WALLS'),
	-- ('GREATPERSON_WORKSHOP_PRODUCTION',					'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 	0,1,	NULL),
	('GREATPERSON_NATIONAL_APPEAL',						'MODIFIER_PLAYER_CITIES_ADJUST_CITY_APPEAL',			0,1,	NULL),
	('GREATPERSON_SINGLECITY_APPEAL',					'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL',				0,1,	NULL),
	('GREATPERSON_SINGLECITY_WONDER_TOURISM',			'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',					0,1,	NULL),
	('GREATPERSON_SINGLECITY_IMPROVEMENT_TOURISM',		'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_TOURISM',		0,1,	NULL),	
	('GREATPERSON_SINGLECITY_NATIONAL_PARK_TOURISM',	'MODIFIER_SINGLE_CITY_ADJUST_NATIONAL_PARK_TOURISM',	0,1,	NULL),
	('GREATPERSON_NATIONAL_APPEAL_BIG',					'MODIFIER_PLAYER_CITIES_ADJUST_CITY_APPEAL',			0,1,	NULL);
	-- ('GREATPERSON_NATIONAL_DISTRICT_SCIENCE_ADJACENCY_AS_TOURISM','MODIFIER_PLAYER_CITIES_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',1,1,NULL),
	-- ('GREATPERSON_NATIONAL_DISTRICT_CULTURE_ADJACENCY_AS_TOURISM','MODIFIER_PLAYER_CITIES_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',1,1,NULL),
	-- ('GREATPERSON_NATIONAL_DISTRICT_FAITH_ADJACENCY_AS_TOURISM','MODIFIER_PLAYER_CITIES_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',1,1,NULL),
	-- ('GREATPERSON_NATIONAL_DISTRICT_PRODUCTION_ADJACENCY_AS_TOURISM','MODIFIER_PLAYER_CITIES_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',1,1,NULL),
	-- ('GREATPERSON_NATIONAL_DISTRICT_GOLD_ADJACENCY_AS_TOURISM','MODIFIER_PLAYER_CITIES_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',1,1,NULL);
insert or replace into ModifierArguments
	(ModifierId, 													Name,     			Value)
values
	('GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_PRINTING',				'TechType',			 	'TECH_PRINTING'),
	('GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_PRINTING', 			'GrantTechIfBoosted', 	1),
	('GREAT_PERSON_INDIVIDUAL_WALL_GEP',							'GreatPersonClassType', 'GREAT_PERSON_CLASS_ENGINEER'),
	('GREAT_PERSON_INDIVIDUAL_WALL_GEP',							'Amount',				1),
	('GREAT_PERSON_INDIVIDUAL_CASTLE_GEP',							'GreatPersonClassType', 'GREAT_PERSON_CLASS_ENGINEER'),
	('GREAT_PERSON_INDIVIDUAL_CASTLE_GEP',							'Amount',				1),
	('GREAT_PERSON_INDIVIDUAL_STAR_WALL_GEP',						'GreatPersonClassType', 'GREAT_PERSON_CLASS_ENGINEER'),
	('GREAT_PERSON_INDIVIDUAL_STAR_WALL_GEP',						'Amount',				1),
	-- ('GREATPERSON_WORKSHOP_PRODUCTION',								'BuildingType',			'BUILDING_WORKSHOP'),
	-- ('GREATPERSON_WORKSHOP_PRODUCTION',								'Amount',				1),
	-- ('GREATPERSON_WORKSHOP_PRODUCTION',								'YieldType',			'YIELD_PRODUCTION'),
	('GREATPERSON_NATIONAL_APPEAL',									'Amount',				1),
	('GREATPERSON_SINGLECITY_APPEAL',								'Amount',				2),
	('GREATPERSON_SINGLECITY_IMPROVEMENT_TOURISM',					'Amount',				100),
	('GREATPERSON_SINGLECITY_NATIONAL_PARK_TOURISM',				'Amount',				100),
	('GREATPERSON_SINGLECITY_WONDER_TOURISM',						'BoostsWonders',		1),
	('GREATPERSON_SINGLECITY_WONDER_TOURISM',						'ScalingFactor',		200),
	('GREATPERSON_NATIONAL_APPEAL_BIG',								'Amount',				2),
	('GREATPERSON_NATIONAL_DISTRICT_SCIENCE_ADJACENCY_AS_TOURISM',	'Amount',				100),
	('GREATPERSON_NATIONAL_DISTRICT_SCIENCE_ADJACENCY_AS_TOURISM',	'YieldType',			'YIELD_SCIENCE'),
	('GREATPERSON_NATIONAL_DISTRICT_CULTURE_ADJACENCY_AS_TOURISM',	'Amount',				100),
	('GREATPERSON_NATIONAL_DISTRICT_CULTURE_ADJACENCY_AS_TOURISM',	'YieldType',			'YIELD_CULTURE'),
	('GREATPERSON_NATIONAL_DISTRICT_FAITH_ADJACENCY_AS_TOURISM',	'Amount',				100),
	('GREATPERSON_NATIONAL_DISTRICT_FAITH_ADJACENCY_AS_TOURISM',	'YieldType',			'YIELD_FAITH'),
	('GREATPERSON_NATIONAL_DISTRICT_PRODUCTION_ADJACENCY_AS_TOURISM','Amount',				100),
	('GREATPERSON_NATIONAL_DISTRICT_PRODUCTION_ADJACENCY_AS_TOURISM','YieldType',			'YIELD_PRODUCTION'),
	('GREATPERSON_NATIONAL_DISTRICT_GOLD_ADJACENCY_AS_TOURISM',	     'Amount',				50),
	('GREATPERSON_NATIONAL_DISTRICT_GOLD_ADJACENCY_AS_TOURISM',	     'YieldType',			'YIELD_GOLD');
------------------------------------------------------------------------------------------------------------------------------
--- Great Scientist
-------------------------------------------------------------------------------------------------------------------------------
-- EUCLID +1 district capacity finish mathmatics if boosted
-- Darwin : +1000 science for each natural wonder tiles
-- galieo : +400 science for each ajacent mountain tiles
-- HILDEGARD_OF_BINGEN ： +200 faith when activate
-- ABU_AL_QASIM_AL_ZAHRAWI : sanitation boost or give full tech
-- issac_newton : natural philosophy 

update ModifierArguments set Value = 400 where ModifierId = 'GREATPERSON_ADJACENT_SNOWMOUNTAIN_SCIENCE' and Name = 'Amount';
update ModifierArguments set Value = 400 where ModifierId = 'GREATPERSON_ADJACENT_TUNDRAMOUNTAIN_SCIENCE' and Name = 'Amount';
update ModifierArguments set Value = 400 where ModifierId = 'GREATPERSON_ADJACENT_DESERTMOUNTAIN_SCIENCE' and Name = 'Amount';
update ModifierArguments set Value = 400 where ModifierId = 'GREATPERSON_ADJACENT_PLAINSMOUNTAIN_SCIENCE' and Name = 'Amount';
update ModifierArguments set Value = 400 where ModifierId = 'GREATPERSON_ADJACENT_GRASSMOUNTAIN_SCIENCE' and Name = 'Amount';
update ModifierArguments set Value = 1000 where ModifierId = 'GREATPERSON_ADJACENT_NATURALWONDER_SCIENCE' and Name = 'Amount';
delete from GreatPersonIndividualActionModifiers where ModifierId = 'GREATPERSON_1MEDIEVALRENAISSANCETECHBOOST';
update ModifierArguments set Value = 200 where ModifierId = 'GREATPERSON_FAITH' and  Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'GREATPERSON_UNIVERSITIES_SMALL_SCIENCE';

insert or replace into GreatPersonIndividualActionModifiers 
	(GreatPersonIndividualType, 						ModifierId)
values
	('GREAT_PERSON_INDIVIDUAL_EUCLID',					'GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_MATHEMATICS'),
	('GREAT_PERSON_INDIVIDUAL_EUCLID',					'GREATPERSON_EXTRA_DISTRICT_CAPACITY'),
	('GREAT_PERSON_INDIVIDUAL_ABU_AL_QASIM_AL_ZAHRAWI',	'GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_SANITATION');

insert or replace into Modifiers
	(ModifierId, 										ModifierType, 								Runonce, Permanent, SubjectRequirementSetId)
values
	('GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_SANITATION','MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			1,1, 	NULL);

insert or replace into ModifierArguments
	(ModifierId, 													Name,     			Value)
values
	('GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_SANITATION',			'TechType',			 'TECH_SANITATION'),
	('GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_SANITATION',			'GrantTechIfBoosted', 1);

insert or replace into GreatWorks
	(GreatWorkType, GreatWorkObjectType, GreatPersonIndividualType, Name, Audio, Image, Quote, Tourism, Eratype)
values
	('GREATWORK_NEWTON',	'GREATWORKOBJECT_WRITING',	'GREAT_PERSON_INDIVIDUAL_ISAAC_NEWTON',	'LOC_GREATWORK_NEWTON_NAME',	NULL,
		NULL, 'LOC_GREATWORK_NEWTON_QUOTE',	3,	'ERA_RENAISSANCE');

insert or replace into GreatWorkModifiers (GreatWorkType, ModifierId)
values ('GREATWORK_NEWTON','PRODUCT_SCIENCE_YIELD_BONUS_TURTLES');

-- todo: check why suonilaoban do not work
-- todo: add a button for Newton
-- and see if he is 30%sicence boost