-------------------------------------
--      Governors Adjustments      --
-------------------------------------

update GovernorPromotions set Level = 1, column = 2, BaseAbility = 0 where GovernorPromotionType = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_GROUNDBREAKER';
update GovernorPromotions set Level = 0, column = 1, BaseAbility = 1 where GovernorPromotionType = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_EXPEDITION';

update GovernorPromotionPrereqs set PrereqGovernorPromotion = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_EXPEDITION'
	where GovernorPromotionType = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_SURPLUS_LOGISTICS';
update GovernorPromotionPrereqs set PrereqGovernorPromotion = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_GROUNDBREAKER'
	where GovernorPromotionType = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_BLACK_MARKETEER';
update GovernorPromotionPrereqs set
	GovernorPromotionType = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_GROUNDBREAKER',
	PrereqGovernorPromotion = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_EXPEDITION'
	where GovernorPromotionType = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_EXPEDITION'
	and PrereqGovernorPromotion = 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_GROUNDBREAKER';

delete from GovernorPromotionSets where GovernorType = 'GOVERNOR_THE_RESOURCE_MANAGER';
insert or replace into GovernorPromotionSets (GovernorType, GovernorPromotion) values
	('GOVERNOR_THE_RESOURCE_MANAGER', 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_EXPEDITION'),
	('GOVERNOR_THE_RESOURCE_MANAGER', 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_SURPLUS_LOGISTICS'),
	('GOVERNOR_THE_RESOURCE_MANAGER', 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_GROUNDBREAKER'),
	('GOVERNOR_THE_RESOURCE_MANAGER', 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_INDUSTRIALIST'),
	('GOVERNOR_THE_RESOURCE_MANAGER', 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_BLACK_MARKETEER'),
	('GOVERNOR_THE_RESOURCE_MANAGER', 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_VERTICAL_INTEGRATION')
;
