-------------------------------------
--      Happiness Adjustments      --
-------------------------------------

-- Bug fix for the new great scientist IBN_KHALDUN.
-- [TODO] may not assume the data exists, cannot update the data (error).
update ModifierArguments set Value = 4
 where ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_SCIENCE' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_CULTURE' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_PRODUCTION' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_GOLD' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_FAITH' and Name = 'Amount'
;

update ModifierArguments set Value = 8
 where ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_SCIENCE' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_CULTURE' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_PRODUCTION' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_GOLD' and Name = 'Amount'
	or ModifierID = 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_FAITH' and Name = 'Amount'
;

insert into GreatPersonIndividualActionModifiers values
	-- (GreatPersonIndividualType, ModifierId, AttachmentTargetType)
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',
	'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_SCIENCE',
	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',
	'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_CULTURE',
	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',
	'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_PRODUCTION',
	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',
	'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_GOLD',
	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',
	'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_FAITH',
	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE')
;

insert into Modifiers (ModifierID, ModifierType, RunOnce, Permanent) values
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD_BAB', 1, 1),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD_BAB', 1, 1),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD_BAB', 1, 1),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD_BAB', 1, 1),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD_BAB', 1, 1)
;

insert into ModifierArguments (ModifierID, Name, Value) values
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_SCIENCE', 'HappinessType', 'HAPPINESS_DELIGHTED'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_SCIENCE', 'Amount', 2),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_CULTURE', 'HappinessType', 'HAPPINESS_DELIGHTED'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_CULTURE', 'YieldType', 'YIELD_CULTURE'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_CULTURE', 'Amount', 2),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_PRODUCTION', 'HappinessType', 'HAPPINESS_DELIGHTED'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_PRODUCTION', 'Amount', 2),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_GOLD', 'HappinessType', 'HAPPINESS_DELIGHTED'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_GOLD', 'YieldType', 'YIELD_GOLD'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_GOLD', 'Amount', 2),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_FAITH', 'HappinessType', 'HAPPINESS_DELIGHTED'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_FAITH', 'YieldType', 'YIELD_FAITH'),
	('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_DELIGHTED_FAITH', 'Amount', 2)
;
