----------------------------------------------------------------------------
-- add modifier string here
----------------------------------------------------------------------------
insert or replace into ModifierStrings
	(ModifierId,										Context, 	Text)
values
    ('GREAT_PERSON_INDIVIDUAL_ARYABHATA_CAMPUS_AMENITY', 'Summary', 'LOC_ARYABHATA_CAMPUS_AMENITY'),
	('GREAT_PERSON_HD_BOOST_OR_GRANT_PRINTING',			'Summary',	'LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_PRINTING'),
	('GREATPERSON_2MODERNATOMICTECHBOOST',				'Summary',	'LOC_GREATPERSON_2MODERNATOMICTECHBOOST'),
	('GREAT_PERSON_PLASTICS_TECHBOOST',					'Summary',	'LOC_GREAT_PERSON_PLASTICS_TECHBOOST'),
	('GREAT_PERSON_HD_BOOST_OR_GRANT_REFINING',			'Summary',	'LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_REFINING'),
	('GREAT_PERSON_HD_BOOST_OR_GRANT_SANITATION',		'Summary',	'LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_SANITATION'),
	('GREATPERSON_NATIONAL_APPEAL',						'Summary',	'LOC_GREATPERSON_NATIONAL_APPEAL'),
	('GREATPERSON_SINGLECITY_APPEAL',					'Summary',	'LOC_GREATPERSON_SINGLECITY_APPEAL'),
	('GREATPERSON_NATIONAL_APPEAL_BIG',					'Summary',	'LOC_GREATPERSON_NATIONAL_APPEAL_BIG'),
	('GREAT_PERSON_ADD_GREAT_PERSON_CLASS_ADMIRAL',		'Summary',	'LOC_GREATPERSON_GPP_BOOST'),
	('PIERO_DE_BARDI_GOLD',								'Summary',	'LOC_PIERO_DE_BARDI_GOLD'),
	('JAKOB_FUGGER_GOLD',								'Summary',	'LOC_JAKOB_FUGGER_GOLD'),
	('JOHN_JACOB_ASTOR_GOLD',							'Summary',	'LOC_JOHN_JACOB_ASTOR_GOLD'),
	('ZHOU_DAGUAN_TOKENS',								'Summary',	'LOC_ZHOU_DAGUAN_TOKENS'),
	('GREATPERSON_ELECTRICITY',							'Summary',	'LOC_GREATPERSON_ELECTRICITY'),
	('GREATPERSON_INDUSTRY_PRODUCTION_SCIENCE',			'Summary',	'LOC_GREATPERSON_INDUSTRY_PRODUCTION_SCIENCE'),
	('GREATPERSON_GRANT_PRODUCTION_IN_CITY_MODERN',		'Summary',	'LOC_GREATPERSON_GRANT_PRODUCTION_IN_CITY_MODERN'),
    ('GREATPERSON_EXTRA_TRADE_ROUTE_CAPACITY2', 		'Summary',  'LOC_GREATPERSON_EXTRA_TRADE_ROUTE_CAPACITY');
