-------------------------------------
-- Major Civilizations Adjustments --
-------------------------------------

insert or replace into TraitModifiers (TraitType,	ModifierId) values
	-- ('TRAIT_LEADER_MAJOR_CIV',						'DEITY_HUMAN_STARTING_MONEY'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_IMMORTAL_HUMAN_CITY_MAINTENANCE'),
	-- ('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_DEITY_HUMAN_CITY_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_IMMORTAL_HUMAN_4_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_IMMORTAL_HUMAN_7_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_IMMORTAL_HUMAN_10_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_IMMORTAL_HUMAN_15_POPULATION_MAINTENANCE'),
	-- ('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_IMMORTAL_HUMAN_20_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_DEITY_HUMAN_4_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_DEITY_HUMAN_7_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_DEITY_HUMAN_10_POPULATION_MAINTENANCE'),
	-- ('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_DEITY_HUMAN_20_POPULATION_MAINTENANCE'),
	('TRAIT_LEADER_MAJOR_CIV',						'AT_LEAST_DEITY_HUMAN_15_POPULATION_MAINTENANCE');

insert or replace into Modifiers
	(ModifierId,													ModifierType,												
	OwnerRequirementSetId,											SubjectRequirementSetId)
values
	-- ('DEITY_HUMAN_STARTING_MONEY',								'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE',
	-- 'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN_AND_HAS_CITY',	NULL),
	('AT_LEAST_IMMORTAL_HUMAN_CITY_MAINTENANCE',					'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',
	'PLAYER_IS_AT_LEAST_IMMORTAL_DIFFICULTY_HUMAN',					NULL),
	-- ('AT_LEAST_DEITY_HUMAN_CITY_MAINTENANCE',					'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',	
	-- 'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN',					NULL),
	('AT_LEAST_IMMORTAL_HUMAN_4_POPULATION_MAINTENANCE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_IMMORTAL_DIFFICULTY_HUMAN',					'CITY_HAS_4_POPULATION'),
	('AT_LEAST_IMMORTAL_HUMAN_7_POPULATION_MAINTENANCE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_IMMORTAL_DIFFICULTY_HUMAN',					'CITY_HAS_7_POPULATION'),
	('AT_LEAST_IMMORTAL_HUMAN_10_POPULATION_MAINTENANCE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_IMMORTAL_DIFFICULTY_HUMAN',					'CITY_HAS_10_POPULATION'),
	('AT_LEAST_IMMORTAL_HUMAN_15_POPULATION_MAINTENANCE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_IMMORTAL_DIFFICULTY_HUMAN',					'CITY_HAS_15_POPULATION'),
	('AT_LEAST_IMMORTAL_HUMAN_20_POPULATION_MAINTENANCE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_IMMORTAL_DIFFICULTY_HUMAN',					'CITY_HAS_20_POPULATION'),
	('AT_LEAST_DEITY_HUMAN_4_POPULATION_MAINTENANCE',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN',					'CITY_HAS_4_POPULATION'),
	('AT_LEAST_DEITY_HUMAN_7_POPULATION_MAINTENANCE',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN',					'CITY_HAS_7_POPULATION'),
	('AT_LEAST_DEITY_HUMAN_10_POPULATION_MAINTENANCE',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN',					'CITY_HAS_10_POPULATION'),
	('AT_LEAST_DEITY_HUMAN_15_POPULATION_MAINTENANCE',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN',					'CITY_HAS_15_POPULATION'),
	('AT_LEAST_DEITY_HUMAN_20_POPULATION_MAINTENANCE',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',
	'PLAYER_IS_AT_LEAST_DEITY_DIFFICULTY_HUMAN',					'CITY_HAS_20_POPULATION');

insert or replace into ModifierArguments
	(ModifierId,									Name,			Value)
values
	-- ('DEITY_HUMAN_STARTING_MONEY',					'YieldType',	'YIELD_GOLD'),
	-- ('DEITY_HUMAN_STARTING_MONEY',					'Amount',		6),
	('AT_LEAST_IMMORTAL_HUMAN_CITY_MAINTENANCE',			'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_IMMORTAL_HUMAN_CITY_MAINTENANCE',			'Amount',		-2),
	-- ('AT_LEAST_DEITY_HUMAN_CITY_MAINTENANCE',				'YieldType',	'YIELD_GOLD'),
	-- ('AT_LEAST_DEITY_HUMAN_CITY_MAINTENANCE',				'Amount',		-2),
	('AT_LEAST_IMMORTAL_HUMAN_4_POPULATION_MAINTENANCE',	'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_IMMORTAL_HUMAN_4_POPULATION_MAINTENANCE',	'Amount',		-0.25),
	('AT_LEAST_IMMORTAL_HUMAN_7_POPULATION_MAINTENANCE',	'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_IMMORTAL_HUMAN_7_POPULATION_MAINTENANCE',	'Amount',		-0.25),
	('AT_LEAST_IMMORTAL_HUMAN_10_POPULATION_MAINTENANCE',	'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_IMMORTAL_HUMAN_10_POPULATION_MAINTENANCE',	'Amount',		-0.25),
	('AT_LEAST_IMMORTAL_HUMAN_15_POPULATION_MAINTENANCE',	'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_IMMORTAL_HUMAN_15_POPULATION_MAINTENANCE',	'Amount',		-0.25),
	('AT_LEAST_IMMORTAL_HUMAN_20_POPULATION_MAINTENANCE',	'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_IMMORTAL_HUMAN_20_POPULATION_MAINTENANCE',	'Amount',		-0.25),
	('AT_LEAST_DEITY_HUMAN_4_POPULATION_MAINTENANCE',		'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_DEITY_HUMAN_4_POPULATION_MAINTENANCE',		'Amount',		-0.25),
	('AT_LEAST_DEITY_HUMAN_7_POPULATION_MAINTENANCE',		'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_DEITY_HUMAN_7_POPULATION_MAINTENANCE',		'Amount',		-0.25),
	('AT_LEAST_DEITY_HUMAN_10_POPULATION_MAINTENANCE',		'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_DEITY_HUMAN_10_POPULATION_MAINTENANCE',		'Amount',		-0.25),
	('AT_LEAST_DEITY_HUMAN_15_POPULATION_MAINTENANCE',		'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_DEITY_HUMAN_15_POPULATION_MAINTENANCE',		'Amount',		-0.25),
	('AT_LEAST_DEITY_HUMAN_20_POPULATION_MAINTENANCE',		'YieldType',	'YIELD_GOLD'),
	('AT_LEAST_DEITY_HUMAN_20_POPULATION_MAINTENANCE',		'Amount',		-0.25);
