-------------------------------------
--       Wonders Adjustments       --
-------------------------------------

-- Oracle gives 3 great person points each.
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATGENERALPOINTS' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATADMIRALPOINTS' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATENGINEERPOINTS' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATMERCHANTPOINTS' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATPROPHETPOINTS' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATSCIENTISTPOINTS' and Name = 'Amount';
update ModifierArguments set Value = 3 where ModifierId = 'ORACLE_GREATWRITERPOINTS' and Name = 'Amount';
-- ARTEMIS does not affect empty camp.
insert into RequirementSets (RequirementSetId, RequirementSetType) values
	('TEMPLE_ARTEMIS_AND_HAS_RESOURCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL')
;

insert into RequirementSetRequirements values
	('TEMPLE_ARTEMIS_AND_HAS_RESOURCE_REQUIREMENTS', 'PLOT_HAS_RESOURCE_REQUIREMENTS'),
	('TEMPLE_ARTEMIS_AND_HAS_RESOURCE_REQUIREMENTS', 'REQUIRES_PLOT_HAS_ARTEMIS_WITHIN_4')
;

update Modifiers set SubjectRequirementSetId = 'TEMPLE_ARTEMIS_AND_HAS_RESOURCE_REQUIREMENTS'
	where ModifierId = 'TEMPLE_ARTEMIS_CAMP_AMENITY';

-- Petra
update ModifierArguments set Value = '3,2,1' where ModifierId = 'PETRA_YIELD_MODIFIER' and Name = 'Amount';

-- MEENAKSHI_TEMPLE
update Buildings set PrereqCivic = 'CIVIC_DIVINE_RIGHT' where BuildingType = 'BUILDING_MEENAKSHI_TEMPLE';
--STBASILS
update ModifierArguments set Value = 2 where ModifierId = 'STBASILS_ADDFOOD_MODIFIER' and Name = 'Amount';
--chichen itza
insert or replace into BuildingModifiers
	(BuildingType,							ModifierId)
values
	('BUILDING_CHICHEN_ITZA',				'CHICHEN_ITZA_JUNGLE_FOOD');

insert or replace into Modifiers
	(ModifierId, 							ModifierType,										SubjectRequirementSetId)
values
	('CHICHEN_ITZA_JUNGLE_FOOD',			'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_HAS_CHICHEN_ITZA_REQUIREMENTS'),
	('CHICHEN_ITZA_JUNGLE_FOOD_MODIFIER',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'PLOT_HAS_JUNGLE_REQUIREMENTS');

insert or replace into ModifierArguments
	(ModifierId,								Name,					Value)
values
	('CHICHEN_ITZA_JUNGLE_FOOD',				'ModifierId',			'CHICHEN_ITZA_JUNGLE_FOOD_MODIFIER'),		
	('CHICHEN_ITZA_JUNGLE_FOOD_MODIFIER',		'YieldType',			'YIELD_FOOD'),
	('CHICHEN_ITZA_JUNGLE_FOOD_MODIFIER',		'Amount',				1);

-- hanging garden boost great people born in this city
-- insert or replace into BuildingModifiers
-- 	(BuildingType,							ModifierId)
-- values
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST1'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST2'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST3'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST4'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST5'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST6'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST7'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST8'),
-- 	('BUILDING_HANGING_GARDENS',			'HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST9');

-- insert or replace into Modifiers
-- 	(ModifierId,											ModifierType)
-- values
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST1',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST2',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST3',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST4',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST5',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST6',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST7',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST8',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST9',		'MODIFIER_PLAYER_ADJUST_CITY_GREAT_PERSON_POINTS_PERCENT');

-- insert or replace into ModifierArguments
-- 	(ModifierId,										Name,					Value)
-- values
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST1','GreatPersonClassType',	'GREAT_PERSON_CLASS_ADMIRAL'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST1','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST2','GreatPersonClassType',	'GREAT_PERSON_CLASS_GENERAL'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST2','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST3','GreatPersonClassType',	'GREAT_PERSON_CLASS_ENGINEER'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST3','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST4','GreatPersonClassType',	'GREAT_PERSON_CLASS_ARTIST'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST4','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST5','GreatPersonClassType',	'GREAT_PERSON_CLASS_MERCHANT'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST5','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST6','GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST6','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST7','GreatPersonClassType',	'GREAT_PERSON_CLASS_SCIENTIST'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST7','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST8','GreatPersonClassType',	'GREAT_PERSON_CLASS_WRITER'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST8','Amount',					15),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST9','GreatPersonClassType',	'GREAT_PERSON_CLASS_MUSICIAN'),
-- 	('HANGING_GARDENS_SINGLE_CITY_GREATPERSON_BOOST9','Amount',					15);

