insert or replace into LocalizedText
	(Language,		Tag,												Text)
values
	("en_US",		"LOC_PROMOTION_CLASS_MONK_NAME",					"Religious Arm"),
	("zh_Hans_CN",	"LOC_PROMOTION_CLASS_MONK_NAME",					"宗教武装"),
	("en_US",		"LOC_UNIT_HD_ARMED_BELIEVER_NAME",					"Armed Believer"),
	("zh_Hans_CN",	"LOC_UNIT_HD_ARMED_BELIEVER_NAME",					"武装教徒"),
	("en_US",		"LOC_UNIT_HD_EXPEDITIONARY_NAME",					"Expeditionary"),
	("zh_Hans_CN",	"LOC_UNIT_HD_EXPEDITIONARY_NAME",					"远征军"),
	("en_US",		"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_NAME",				"Theocratic Guardian"),
	("zh_Hans_CN",	"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_NAME",				"神权卫队"),
	("en_US",		"LOC_UNIT_HD_RESISTANCE_ARMY_NAME",					"Resistance Army"),
	("zh_Hans_CN",	"LOC_UNIT_HD_RESISTANCE_ARMY_NAME",					"抵抗军"),
	("en_US",		"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_NAME",			"Revolutionary Guardian"),
	("zh_Hans_CN",	"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_NAME",			"革命卫队"),
	("en_US",		"LOC_UNIT_HD_DEUX_EX_MACHINA_NAME",					"Deus ex machina"),
	("zh_Hans_CN",	"LOC_UNIT_HD_DEUX_EX_MACHINA_NAME",					"机械降神"),
	("en_US",		"LOC_UNIT_HD_ARMED_BELIEVER_DESCRIPTION",			"Classical Era Religious Arm Unit. Cost 2 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_ARMED_BELIEVER_DESCRIPTION",			"古典时代宗教武装单位。消耗2 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_EXPEDITIONARY_DESCRIPTION",			"Medieval Era Religious Arm Unit. Cost 3 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_EXPEDITIONARY_DESCRIPTION",			"中世纪宗教武装单位。消耗3 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_DESCRIPTION",		"Renaissance Era Religious Arm Unit. Cost 4 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_DESCRIPTION",		"文艺复兴时代宗教武装单位。消耗4 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_RESISTANCE_ARMY_DESCRIPTION",			"Industrial Era Religious Arm Unit. Cost 5 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_RESISTANCE_ARMY_DESCRIPTION",			"工业时代宗教武装单位。消耗5 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_DESCRIPTION",	"Modern Era Religious Arm Unit. Cost 6 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_DESCRIPTION",	"现代宗教武装单位。消耗6 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_DEUX_EX_MACHINA_DESCRIPTION",			"Information Era Religious Arm Unit. Cost 15 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_DEUX_EX_MACHINA_DESCRIPTION",			"信息时代宗教武装单位。消耗15 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_RELIGIOUS_ARM_COMMON",					"[NEWLINE][NEWLINE]Religious Arm: Can only be purchased with [ICON_FAITH] Faith. Combat victories provide [ICON_FAITH] Faith equal to 50% of the [ICON_STRENGTH] Combat Strength of the defeated unit."),
	("zh_Hans_CN",	"LOC_UNIT_HD_RELIGIOUS_ARM_COMMON",					"[NEWLINE][NEWLINE]宗教武装：只能使用 [ICON_FAITH] 信仰值购买。击杀单位时，获得被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_FAITH] 信仰值。");