insert or replace into LocalizedText
	(Language,		Tag,																Text)
values
	("en_US",		"LOC_PROMOTION_CLASS_MONK_NAME",									"Religious Arm"),
	("zh_Hans_CN",	"LOC_PROMOTION_CLASS_MONK_NAME",									"宗教武装"),
	("en_US",		"LOC_UNIT_HD_RELIGIOUS_ARM_COMMON",									"[NEWLINE][NEWLINE]Religious Arm: Can only be purchased with [ICON_FAITH] Faith. Combat victories provide [ICON_FAITH] Faith equal to 50% of the [ICON_STRENGTH] Combat Strength of the defeated unit."),
	("zh_Hans_CN",	"LOC_UNIT_HD_RELIGIOUS_ARM_COMMON",									"[NEWLINE][NEWLINE]宗教武装：只能使用 [ICON_FAITH] 信仰值购买。击杀单位时，获得被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_FAITH] 信仰值。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_DESCRIPTION",								"Combat victories provide [ICON_FAITH] Faith equal to 50% of the [ICON_STRENGTH] Combat Strength of the defeated unit."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_DESCRIPTION",								"击杀单位时，获得被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_FAITH] 信仰值。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_MELEE_ANTC_DESCRIPTION",					"+5 [ICON_STRENGTH] Combat Strength v.s. Melee and Anti Cavalry units."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_MELEE_ANTC_DESCRIPTION",					"对战近战和抗骑兵单位+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_FLAT_DESCRIPTION",						"+5 [ICON_STRENGTH] Combat Strength on flat lands."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_FLAT_DESCRIPTION",						"在平坦地形上战斗时+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_DISTRICT_DESCRIPTION",					"+5 [ICON_STRENGTH] Combat Strength on districts."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_DISTRICT_DESCRIPTION",					"位于区域上时+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_ABILITY_2_FAITH_MAINTENANCE_DESCRIPTION",						"Cost 2 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_2_FAITH_MAINTENANCE_DESCRIPTION",						"消耗2 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_3_FAITH_MAINTENANCE_DESCRIPTION",						"Cost 3 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_3_FAITH_MAINTENANCE_DESCRIPTION",						"消耗3 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_4_FAITH_MAINTENANCE_DESCRIPTION",						"Cost 4 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_4_FAITH_MAINTENANCE_DESCRIPTION",						"消耗4 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_5_FAITH_MAINTENANCE_DESCRIPTION",						"Cost 5 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_5_FAITH_MAINTENANCE_DESCRIPTION",						"消耗5 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_6_FAITH_MAINTENANCE_DESCRIPTION",						"Cost 6 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_6_FAITH_MAINTENANCE_DESCRIPTION",						"消耗6 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_15_FAITH_MAINTENANCE_DESCRIPTION",						"Cost 15 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_15_FAITH_MAINTENANCE_DESCRIPTION",						"消耗15 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_RELIGOUS_ARM_MELEE_ANTC",										"+{1_Amount} Strength v.s. Melee and Anti Cavalry units."),
	("zh_Hans_CN",	"LOC_RELIGOUS_ARM_MELEE_ANTC",										"对战近战和抗骑兵单位+{1_Amount}力。"),
	("en_US",		"LOC_RELIGOUS_ARM_FLAT",											"+{1_Amount} Strength on flat lands."),
	("zh_Hans_CN",	"LOC_RELIGOUS_ARM_FLAT",											"在平坦地形上战斗+{1_Amount}力。"),
	("en_US",		"LOC_RELIGOUS_ARM_DISTRICT",										"+{1_Amount} Strength on districts."),
	("zh_Hans_CN",	"LOC_RELIGOUS_ARM_DISTRICT",										"位于区域上+{1_Amount}力。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_DISABLED_TT",						"[COLOR_RED]Insufficient [ICON_FAITH] Faith.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_DISABLED_TT",						"[COLOR_RED][ICON_FAITH]信仰不足。[ENDCOLOR]"),
	("en_US",		"LOC_PROMOTION_NRYANA_NAME",										"Nryana"),
	("zh_Hans_CN",	"LOC_PROMOTION_NRYANA_NAME",										"那罗延"),
	("en_US",		"LOC_PROMOTION_NRYANA_DESCRIPTION",									"+5 [ICON_STRENGTH] Combat Strength when attacking."),
	("zh_Hans_CN",	"LOC_PROMOTION_NRYANA_DESCRIPTION",									"进攻时+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_NRYANA_ATTACK",												"+{1_Amount} Strength when attacking (Nryana)."),
	("zh_Hans_CN",	"LOC_NRYANA_ATTACK",												"进攻时+{1_Amount}力（那罗延）。"),
	("en_US",		"LOC_PROMOTION_DRAGONS_SHAME_NAME",									"Dragon's Shame"),
	("zh_Hans_CN",	"LOC_PROMOTION_DRAGONS_SHAME_NAME",									"亢龙有悔"),
	("en_US",		"LOC_PROMOTION_DRAGONS_SHAME_DESCRIPTION",							"When on a feature or Natural Wonder, +15 [ICON_DAMAGED] Healing per turn and +7 [ICON_STRENGTH] Combat Strength when defending."),
	("zh_Hans_CN",	"LOC_PROMOTION_DRAGONS_SHAME_DESCRIPTION",							"位于地貌或自然奇观时，每回合额外回复15点 [ICON_DAMAGED] 生命值且防御时+7 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_DRAGONS_SHAME_DEFEND",											"+{1_Amount} Strength when defending on feature or Natural Wonder (Dragon's Shame)."),
	("zh_Hans_CN",	"LOC_DRAGONS_SHAME_DEFEND",											"位于地貌或自然奇观防御时+{1_Amount}力（亢龙有悔）。"),
	("en_US",		"LOC_PROMOTION_UNIVERSAL_RESTORATION_NAME",							"Universal Restoration"),
	("zh_Hans_CN",	"LOC_PROMOTION_UNIVERSAL_RESTORATION_NAME",							"普渡众生"),
	("en_US",		"LOC_PROMOTION_UNIVERSAL_RESTORATION_DESCRIPTION",					"+7 [ICON_STRENGTH] Combat Strength when being flanked. Can use 3 [ICON_MOVEMENT] Movement and [ICON_FAITH] Faith equal to 200% of the base [ICON_STRENGTH] Combat Strength to deal damage to adjacent enemy units equal to the base [ICON_STRENGTH] Strength of this unit."),
	("zh_Hans_CN",	"LOC_PROMOTION_UNIVERSAL_RESTORATION_DESCRIPTION",					"被夹击时+7 [ICON_STRENGTH] 战斗力。可以花费3 [ICON_MOVEMENT] 移动力和基础 [ICON_STRENGTH] 战斗力200%的 [ICON_FAITH] 信仰值来对周围敌方战斗单位造成基础 [ICON_STRENGTH] 战斗力的伤害。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DESCRIPTION",	"Use 3 [ICON_MOVEMENT] Movement and {1_Amount} [ICON_FAITH] Faith to deal {2_Amount} damage to all adjacent enemy units."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DESCRIPTION",	"花费3 [ICON_MOVEMENT] 移动力和{1_Amount} [ICON_FAITH] 信仰值来对周围敌方战斗单位造成{2_Amount}点伤害。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DISABLED_TT",	"[COLOR_RED]Insufficient [ICON_MOVEMENT] Movement or [ICON_FAITH] Faith.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DISABLED_TT",	"[COLOR_RED][ICON_MOVEMENT] 移动力或 [ICON_FAITH]信仰不足。[ENDCOLOR]"),
	("en_US",		"LOC_UNIVERSAL_RESTORATION_FLANK",									"+{1_Amount} Strength when being flanked (Universal Restoration)."),
	("zh_Hans_CN",	"LOC_UNIVERSAL_RESTORATION_FLANK",									"被夹击时+{1_Amount}力（普渡众生）。"),
	("en_US",		"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_NAME",						"Liberate The Holy Land"),
	("zh_Hans_CN",	"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_NAME",						"解放圣地"),
	("en_US",		"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_DESCRIPTION",					"+1 [ICON_MOVEMENT] Movement."),
	("zh_Hans_CN",	"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_DESCRIPTION",					"+1 [ICON_MOVEMENT] 移动力。"),
	("en_US",		"LOC_PROMOTION_PUNCITIVE_LAND_NAME",								"Punitive Land"),
	("zh_Hans_CN",	"LOC_PROMOTION_PUNCITIVE_LAND_NAME",								"征伐之地"),
	("en_US",		"LOC_PROMOTION_PUNCITIVE_LAND_DESCRIPTION",							"+10 [ICON_STRENGTH] Combat Strength when fighting in districts. Can use [ICON_FAITH] Faith equal to 50% of the base [ICON_STRENGTH] Combat Strength to restore [ICON_MOVEMENT] Movement. Can be used once each turn."),
	("zh_Hans_CN",	"LOC_PROMOTION_PUNCITIVE_LAND_DESCRIPTION",							"在区域中作战时+10 [ICON_STRENGTH] 战斗力。可以花费基础 [ICON_STRENGTH] 战斗力50%的 [ICON_FAITH] 信仰值来恢复全部移动力。每回合只能恢复一次。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DESCRIPTION",			"Use {1_Amount} [ICON_FAITH] Faith to restore [ICON_MOVEMENT] Movement. Can be used once each turn."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DESCRIPTION",			"花费{1_Amount} [ICON_FAITH] 信仰值来恢复全部移动力。每回合只能恢复一次。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DISABLED_TT",			"[COLOR_RED]Insufficient [ICON_FAITH] Faith or have been used this turn.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DISABLED_TT",			"[COLOR_RED][ICON_FAITH] 信仰值不足或本回合已经恢复过移动力。[ENDCOLOR]"),
	("en_US",		"LOC_PUNCITIVE_LAND_DISTRICT",										"+{1_Amount} Strength when fighting in districts (Punitive Land)."),
	("zh_Hans_CN",	"LOC_PUNCITIVE_LAND_DISTRICT",										"在区域中作战时+{1_Amount}力（征伐之地）。"),
	("en_US",		"LOC_PROMOTION_PROMISED_LAND_NAME",									"Promised Land"),
	("zh_Hans_CN",	"LOC_PROMOTION_PROMISED_LAND_NAME",									"应许之地"),
	("en_US",		"LOC_PROMOTION_PROMISED_LAND_DESCRIPTION",							"+7 [ICON_STRENGTH] Combat Strength when attacking [ICON_DAMAGED] Damaged units. Can use 5 [ICON_RESOURCE_HORSES] Horses and [ICON_FAITH] Faith equal to 50% of the base [ICON_STRENGTH] Combat Strength to jump across any terrain."),
	("zh_Hans_CN",	"LOC_PROMOTION_PROMISED_LAND_DESCRIPTION",							"攻击[ICON_DAMAGED] 受伤单位时+7 [ICON_STRENGTH] 战斗力。可以花费5 [ICON_RESOURCE_HORSES] 马和基础 [ICON_STRENGTH] 战斗力50%的 [ICON_FAITH] 信仰值来越过任意地形。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DESCRIPTION",			"Use 5 [ICON_RESOURCE_HORSES] Horses and {1_Amount} [ICON_FAITH] Faith to jump across any terrain."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DESCRIPTION",			"花费5 [ICON_RESOURCE_HORSES] 马和{1_Amount} [ICON_FAITH] 信仰值来越过任意地形。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DISABLED_TT",			"[COLOR_RED]Insufficient [ICON_RESOURCE_HORSES] Horses, [ICON_FAITH] Faith or [ICON_MOVEMENT] Movement.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DISABLED_TT",			"[COLOR_RED][ICON_RESOURCE_HORSES] 马、 [ICON_FAITH] 信仰值或 [ICON_MOVEMENT] 移动力不足。[ENDCOLOR]"),
	("en_US",		"LOC_PROMISED_LAND_ATTACK_DAMAGED",									"+{1_Amount} Strength when attacking Damaged units (Promised Land)."),
	("zh_Hans_CN",	"LOC_PROMISED_LAND_ATTACK_DAMAGED",									"攻击受伤单位时+{1_Amount}力（应许之地）。"),
	("en_US",		"LOC_PROMOTION_NATARAJ_NAME",										"Nataraj"),
	("zh_Hans_CN",	"LOC_PROMOTION_NATARAJ_NAME",										"那吒罗阇"),
	("en_US",		"LOC_PROMOTION_NATARAJ_DESCRIPTION",								"+7 [ICON_STRENGTH] Combat Strength when defending against ranged attack. +7 [ICON_STRENGTH] Combat Strength when attacking districts."),
	("zh_Hans_CN",	"LOC_PROMOTION_NATARAJ_DESCRIPTION",								"防御远程攻击时+7 [ICON_STRENGTH] 战斗力。攻击区域时+7 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_NATARAJ_DEFEND_RANGE",											"+{1_Amount} Strength when defending against ranged attack (Nataraj)."),
	("zh_Hans_CN",	"LOC_NATARAJ_DEFEND_RANGE",											"防御远程攻击时+{1_Amount}力（那吒罗阇）。"),
	("en_US",		"LOC_NATARAJ_ATTACK_DISTRICT",										"+{1_Amount} Strength when attacking districts (Nataraj)."),
	("zh_Hans_CN",	"LOC_NATARAJ_ATTACK_DISTRICT",										"攻击区域时+{1_Amount}力（那吒罗阇）。"),
	("en_US",		"LOC_PROMOTION_HD_PILGRIM_NAME",									"Pilgrim"),
	("zh_Hans_CN",	"LOC_PROMOTION_HD_PILGRIM_NAME",									"朝圣者"),
	("en_US",		"LOC_PROMOTION_HD_PILGRIM_DESCRIPTION",								"Does not suffer combat penalties from being damaged. Can use [ICON_FAITH] Faith equal to 10% of the base [ICON_STRENGTH] Combat Strength to build road."),
	("zh_Hans_CN",	"LOC_PROMOTION_HD_PILGRIM_DESCRIPTION",								"不会因受伤遭受战斗减益。可以花费基础 [ICON_STRENGTH] 战斗力10%的 [ICON_FAITH] 信仰值来修建道路。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_HD_PILGRIM_DESCRIPTION",				"Use {1_Amount} [ICON_FAITH] Faith to build road on this tile."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_HD_PILGRIM_DESCRIPTION",				"花费{1_Amount} [ICON_FAITH] 信仰值来在该单元格上创建道路。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_HD_PILGRIM_DISABLED_TT",				"[COLOR_RED]Insufficient [ICON_FAITH] Faith, or the plot already has a Road with era at least as late as you are currently in.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_HD_PILGRIM_DISABLED_TT",				"[COLOR_RED][ICON_FAITH] 信仰值不足，或该单元格上已有与您所处时代的相同或更晚的道路。[ENDCOLOR]"),
	("en_US",		"LOC_PROMOTION_SHARING_GODS_FAVOR_NAME",							"Sharing God's Favor"),
	("zh_Hans_CN",	"LOC_PROMOTION_SHARING_GODS_FAVOR_NAME",							"共沐主恩"),
	("en_US",		"LOC_PROMOTION_SHARING_GODS_FAVOR_DESCRIPTION",						"+2 [ICON_STRENGTH] Combat Strength to all adjacent Religious Arm units."),
	("zh_Hans_CN",	"LOC_PROMOTION_SHARING_GODS_FAVOR_DESCRIPTION",						"所有相邻的宗教武装单位+2 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_SHARING_GODS_FAVOR_ADJACENT",									"+{1_Amount} Strength from adjacent units with 'Sharing God's Favor' Promotion."),
	("zh_Hans_CN",	"LOC_SHARING_GODS_FAVOR_ADJACENT",									"+{1_Amount}力来自相邻具有“共沐主恩”晋升的单位。"),
	("en_US",		"LOC_PROMOTION_MIND_OVER_MATTER_NAME",								"Mind Over Matter"),
	("zh_Hans_CN",	"LOC_PROMOTION_MIND_OVER_MATTER_NAME",								"心胜于物"),
	("en_US",		"LOC_PROMOTION_MIND_OVER_MATTER_DESCRIPTION",						"Can move after attack. Can use [ICON_FAITH] Faith equal to 100% of the base [ICON_STRENGTH] Combat Strength to restore attack."),
	("zh_Hans_CN",	"LOC_PROMOTION_MIND_OVER_MATTER_DESCRIPTION",						"攻击后可以移动。可以花费基础 [ICON_STRENGTH] 战斗力100%的 [ICON_FAITH] 信仰值来回复攻击次数。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_MIND_OVER_MATTER_DESCRIPTION",		"Use {1_Amount} [ICON_FAITH] Faith to restore attack."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_MIND_OVER_MATTER_DESCRIPTION",		"花费{1_Amount} [ICON_FAITH] 信仰值来回复攻击次数。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_MIND_OVER_MATTER_DISABLED_TT",		"[COLOR_RED]Insufficient [ICON_FAITH] Faith or [ICON_MOVEMENT] Movement.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_MIND_OVER_MATTER_DISABLED_TT",		"[COLOR_RED][ICON_FAITH] 信仰值或 [ICON_MOVEMENT] 移动力不足。[ENDCOLOR]"),
	("en_US",		"LOC_UNIT_HD_ARMED_BELIEVER_NAME",									"Armed Believer"),
	("zh_Hans_CN",	"LOC_UNIT_HD_ARMED_BELIEVER_NAME",									"武装教徒"),
	("en_US",		"LOC_UNIT_HD_EXPEDITIONARY_NAME",									"Expeditionary"),
	("zh_Hans_CN",	"LOC_UNIT_HD_EXPEDITIONARY_NAME",									"远征军"),
	("en_US",		"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_NAME",								"Theocratic Guardian"),
	("zh_Hans_CN",	"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_NAME",								"神权卫队"),
	("en_US",		"LOC_UNIT_HD_RESISTANCE_ARMY_NAME",									"Resistance Army"),
	("zh_Hans_CN",	"LOC_UNIT_HD_RESISTANCE_ARMY_NAME",									"抵抗军"),
	("en_US",		"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_NAME",							"Revolutionary Guardian"),
	("zh_Hans_CN",	"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_NAME",							"革命卫队"),
	("en_US",		"LOC_UNIT_HD_DEUX_EX_MACHINA_NAME",									"Deus ex machina"),
	("zh_Hans_CN",	"LOC_UNIT_HD_DEUX_EX_MACHINA_NAME",									"机械降神"),
	("en_US",		"LOC_UNIT_HD_ARMED_BELIEVER_DESCRIPTION",							"Classical Era Religious Arm Unit. Cost 2 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_ARMED_BELIEVER_DESCRIPTION",							"古典时代宗教武装单位。消耗2 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_EXPEDITIONARY_DESCRIPTION",							"Medieval Era Religious Arm Unit. Cost 3 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_EXPEDITIONARY_DESCRIPTION",							"中世纪宗教武装单位。消耗3 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_DESCRIPTION",						"Renaissance Era Religious Arm Unit. Cost 4 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_DESCRIPTION",						"文艺复兴时代宗教武装单位。消耗4 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_RESISTANCE_ARMY_DESCRIPTION",							"Industrial Era Religious Arm Unit. Cost 5 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_RESISTANCE_ARMY_DESCRIPTION",							"工业时代宗教武装单位。消耗5 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_DESCRIPTION",					"Modern Era Religious Arm Unit. Cost 6 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_DESCRIPTION",					"现代宗教武装单位。消耗6 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_DEUX_EX_MACHINA_DESCRIPTION",							"Information Era Religious Arm Unit. Cost 15 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_DEUX_EX_MACHINA_DESCRIPTION",							"信息时代宗教武装单位。消耗15 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_BATTERING_RAM_EXPANSION2_DESCRIPTION",					"Ancient era support unit. When adjacent to a city, attacking melee, anti-cavalry and Religious Arm units do full damage to the city's Walls. Does not affect cities with Medieval or Renaissance Walls. Ineffective against Urban Defenses."),
	("zh_Hans_CN",	"LOC_UNIT_BATTERING_RAM_EXPANSION2_DESCRIPTION",					"远古时代支援单位。与城市相邻时，近战，抗骑兵和宗教武装单位发起进攻可对城墙输出全额伤害。对拥有中世纪或文艺复兴城墙的城市无效。对现代城市防御无效。"),
	("en_US",		"LOC_UNIT_SIEGE_TOWER_EXPANSION2_DESCRIPTION",						"Medieval era support unit. When adjacent to a city, attacking melee, anti-cavalry and Religious Arm units ignore Walls and immediately assault the city. Does not affect cities with Renaissance Walls. Ineffective against Urban Defenses."),
	("zh_Hans_CN",	"LOC_UNIT_SIEGE_TOWER_EXPANSION2_DESCRIPTION",						"中世纪支援单位。与城市相邻时，近战、抗骑兵和宗教武装单位可无视城墙直接对城市发起进攻。对拥有文艺复兴城墙的城市无效。对现代城市防御无效。"),
	("en_US",		"LOC_UNIT_WARRIOR_MONK_DESCRIPTION",								"Religious Arm Unit. Have one build charge to be removed and complete 20% of a Holy Site district. Can only be purchased with [ICON_FAITH] Faith in cities with a Temple. Cost 3 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_UNIT_WARRIOR_MONK_DESCRIPTION",								"宗教武装单位，拥有一点劳动力，可以移除该单位来推进圣地区域20%的建造进度。只能在有寺庙的城市通过 [ICON_FAITH] 信仰购买。消耗3 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_BELIEF_WARRIOR_MONKS_EXPANSION2_DESCRIPTION",					"Culture Bomb adjacent tiles when completing a Holy Site. Holy Site provides [ICON_FAITH] Faith equal to its [ICON_FAITH] Faith adjacency bonus. Unlocks the Religious Arm Unit 'Warrior Monk', which has one build charge to complete 20% of a Holy Site district. Can only be purchased with [ICON_FAITH] Faith in cities with a Temple."),
	("zh_Hans_CN",	"LOC_BELIEF_WARRIOR_MONKS_EXPANSION2_DESCRIPTION",					"建成圣地后对相邻单元格施放文化炸弹。圣地区域的 [ICON_FAITH] 信仰值相邻加成提供额外等量的 [ICON_FAITH] 信仰值。解锁宗教武装单位“武僧”，拥有一点劳动力，可以推进圣地区域20%的建造进度。只能在有寺庙的城市通过 [ICON_FAITH] 信仰购买。"),
	("en_US",		"LOC_BELIEF_JUST_WAR_DL_DESCRIPTION",								"+50 [ICON_Faith] Faith when pillaging District or Improvement. Religous Arm units and Religious units gain +1 [ICON_Movement] Movement if they begin a turn on a flat tile."),
	("zh_Hans_CN",	"LOC_BELIEF_JUST_WAR_DL_DESCRIPTION",								"劫掠区域和改良时+50 [ICON_FAITH] 信仰值。宗教武装单位和宗教单位在平坦地形开始回合时+1 [ICON_Movement] 移动力。"),
	("en_US",		"LOC_ABILITY_RELIGIION_START_MOVE_DESCRIPTION",						"+1 [ICON_Movement] Movement if starts a turn on flat tile."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGIION_START_MOVE_DESCRIPTION",						"在平坦地形开始回合+1 [ICON_Movement] 移动力。"),
	("en_US",		"LOC_BELIEF_FRATERNITY_NAME",										"Fraternity"),
	("zh_Hans_CN",	"LOC_BELIEF_FRATERNITY_NAME",										"兄弟会"),
	("en_US",		"LOC_BELIEF_FRATERNITY_DESCRIPTION",								"+50 [ICON_Faith] Faith when pillaging. Double support and flanking bonus from Religious Arm Units and Religious Units."),
	("zh_Hans_CN",	"LOC_BELIEF_FRATERNITY_DESCRIPTION",								"劫掠时+50 [ICON_FAITH] 信仰值。宗教武装单位和宗教单位的支援和夹击加成翻倍。"),
	("en_US",		"LOC_BELIEF_SILKH_SWORD_BAPTISM_NAME",								"Silkh Sword Baptism"),
	("zh_Hans_CN",	"LOC_BELIEF_SILKH_SWORD_BAPTISM_NAME",								"剑礼"),
	("en_US",		"LOC_BELIEF_SILKH_SWORD_BAPTISM_DESCRIPTION",						"All units heal 15 [ICON_DAMAGED] Health when defeating units of different religion or of no religion, gaining control of a city or being promoted. Newly trained Religious Unit provides +5 [ICON_Strength] Combat Strength to Religious Arm unit in the same tile."),
	("zh_Hans_CN",	"LOC_BELIEF_SILKH_SWORD_BAPTISM_DESCRIPTION",						"所有单位击败其它宗教或无神论单位、占领城市或晋升时恢复15点 [ICON_DAMAGED] 生命值。新生产的宗教单位给同一单元格的宗教武装单位+5 [ICON_Strength] 战斗力。"),
	("en_US",		"LOC_ABILITY_JUST_WAR_RELIGIOUS_ALL_COMBAT_BUFF_DESCRIPTION",		"+5 [ICON_Strength] Combat Strength to Religious Arm unit in the same tile."),
	("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_RELIGIOUS_ALL_COMBAT_BUFF_DESCRIPTION",		"为同一单元格的宗教武装单位+5 [ICON_Strength] 战斗力。"),
	("en_US",		"LOC_ABILITY_JUST_WAR_STRENGTH_DESCRIPTION",						"Religious Arm unit gets +5 [ICON_Strength] Combat Strength when in the same tile with a Religious unit."),
	("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_STRENGTH_DESCRIPTION",						"宗教武装单位与宗教单位位于同一单元格+5 [ICON_Strength] 战斗力。"),
	("en_US",		"LOC_ABILITY_JUST_WAR_STRENGTH_PREVIEW_TEXT",						" Strength from Silkh Sword Baptism"),
	("zh_Hans_CN",  "LOC_ABILITY_JUST_WAR_STRENGTH_PREVIEW_TEXT",						"力来自剑礼"),
	("en_US",		"LOC_PEDIA_RELIGIONS_PAGE_RELIGION_SIKHISM_CHAPTER_HISTORY_PARA_2",	"Sikhs are known for their generosity towards others, as one of the primary tenets of their religion is the idea that all people are created equal, regardless of religion, race, or sex. In differing from other major religions, Sikhism supports that belief that acts of good in service to others are more important than any form of ritual.[NEWLINE]Silkh Sword Baptism rite of passage in Sikh religion,Similar to Christian baptism, Sikhs use water stirred by double-edged swords to bathe believers."),
	("zh_Hans_CN",  "LOC_PEDIA_RELIGIONS_PAGE_RELIGION_SIKHISM_CHAPTER_HISTORY_PARA_2",	"锡克教徒因对他人慷慨而众所周知，他们宗教的首要信条之一是无论宗教、种族或性别，人人生而平等。不同于其他主流宗教，锡克教支持这一观点：为他人服务的行为比任何形式的仪式更重要。[NEWLINE]剑礼是锡克教的成人礼仪式，类似于基督教洗礼，锡克教徒使用双锋剑搅匀的水为信徒沐浴。"),
	("en_US",		"LOC_BELIEF_SHAOLIN_TEMPLE_NAME",									"Shaolin Temple"),
	("zh_Hans_CN",	"LOC_BELIEF_SHAOLIN_TEMPLE_NAME",									"少林寺"),
	("en_US",		"LOC_BELIEF_SHAOLIN_TEMPLE_DESCRIPTION",							"Allows construction of Shaolin Temple (+8 [ICON_FAITH] Faith, +50% construction speed of Religious Arm units. When completed, grant a free Religious Arm unit with one Promotion)."),
	("zh_Hans_CN",	"LOC_BELIEF_SHAOLIN_TEMPLE_DESCRIPTION",							"允许建造少林寺（+8 [ICON_FAITH] 信仰值，+50%宗教武装单位建造速度。建成时赠送一个拥有一次升级的宗教武装单位）。"),
	("en_US",		"LOC_BUILDING_SHAOLIN_TEMPLE_NAME",									"Shaolin Temple"),
	("zh_Hans_CN",	"LOC_BUILDING_SHAOLIN_TEMPLE_NAME",									"少林寺"),
	("en_US",		"LOC_BUILDING_SHAOLIN_TEMPLE_DESCRIPTION",							"+50% construction speed of Religious Arm units. When completed, grant a free Religious Arm unit with one Promotion."),
	("zh_Hans_CN",	"LOC_BUILDING_SHAOLIN_TEMPLE_DESCRIPTION",							"+50%宗教武装单位建造速度。建成时赠送一个拥有一次升级的宗教武装单位。"),
	("en_US",		"LOC_BELIEF_MOSQUE_DL_DESCRIPTION",									"Allows construction of Mosques (+8 [ICON_FAITH] Faith, Missionary and Apostles created in this city gets +1 spread charge, all Religious Arm units get +1 [ICON_STRENGTH] Combat Strength)."),
	("zh_Hans_CN",	"LOC_BELIEF_MOSQUE_DL_DESCRIPTION",									"允许建造清真寺（+8 [ICON_FAITH] 信仰值，此城创建的传教士和使徒+1传教次数，所有宗教武装单位+1 [ICON_STRENGTH] 战斗力）。"),
	("en_US",		"LOC_BUILDING_MOSQUE_DL_DESCRIPTION",								"Missionary and Apostles created in this city gets +1 spread charge. All Religious Arm units get +1 [ICON_STRENGTH] Combat Strength."),
	("zh_Hans_CN",	"LOC_BUILDING_MOSQUE_DL_DESCRIPTION",								"此城创建的传教士和使徒+1传教次数。所有宗教武装单位+1 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_MOSQUE_RELIGIOUS_ARM_STRENGTH",								"+{1_Amount} Strength from Mosque"),
	("zh_Hans_CN",	"LOC_MOSQUE_RELIGIOUS_ARM_STRENGTH",								"+{1_Amount}力来自清真寺"),
	("en_US",		"LOC_BELIEF_DEFENDER_OF_FAITH_DL_DESCRIPTION",						"When within borders of cities that follow this Religion, Combat and Religious units gain +1 [ICON_MOVEMENT] Movement in case of friendly cities, or +5 [ICON_STRENGTH] Combat Strength otherwise."),
	("zh_Hans_CN",	"LOC_BELIEF_DEFENDER_OF_FAITH_DL_DESCRIPTION",						"战斗单位和宗教单位处于信奉该宗教的城市境内时，若为友方城市则+1 [ICON_MOVEMENT] 移动力，否则+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_PROMOTION_DEFENDER_OF_FAITH_DESCRIPTION",						"+{1_Amount} Strength from Defender of Faith"),
	("zh_Hans_CN",	"LOC_PROMOTION_DEFENDER_OF_FAITH_DESCRIPTION",						"+{1_Amount}力来自信仰护卫者"),
	("en_US",		"LOC_BELIEF_CAPELLANI_DL_DESCRIPTION",								"Upon combat victories, add +100 Religious Pressure to cities within 6 tiles. Upon conquering a city, gain 100 [ICON_FAITH] for each [ICON_CITIZEN] citizen in that city."),
	("zh_Hans_CN",	"LOC_BELIEF_CAPELLANI_DL_DESCRIPTION",								"战斗胜利后，对6个单元格内的城市施加100宗教压力。占领一座城市后，其中每有一个 [ICON_CITIZEN] 人口便获得100 [ICON_FAITH] 信仰值。"),
	("en_US",		"LOC_UNIT_NORWEGIAN_ULFHEDNAR_DESCRIPTION",							"Norwegian unique ancient era Religious Arm unit. Can be trained or purchased without a major religion. +50% Experience for adjacent units.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_NORWEGIAN_ULFHEDNAR_DESCRIPTION",							"挪威远古时代特色宗教武装单位，不需要主流宗教就可以训练或购买。为相邻单位提供+50%经验值。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_JAPANESE_SOHEI_DESCRIPTION",								"Japanese unique Religious Arm that replaces the Expeditionary. May be purchased with [ICON_GOLD] Gold. Cost 3 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_JAPANESE_SOHEI_DESCRIPTION",								"日本特色宗教武装单位，取代远征军。可以用 [ICON_GOLD] 金币购买。消耗3 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_ELEANOR_TEMPLAR_DESCRIPTION",								"Unique Medieval Riligious Arm unit for Eleanor of Aquitaine. +5 [ICON_STRENGTH] Combat Strength when opponent is of another religion. +5 [ICON_STRENGTH] Combat Strength when adjacent to a Holy Site District. Blocks the first non-lethal attack each turn. Cost 3 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_ELEANOR_TEMPLAR_DESCRIPTION",								"阿基坦埃莉诺中世纪特色宗教武装单位。对抗异教徒时+5 [ICON_STRENGTH] 战斗力，相邻圣地时+5 [ICON_STRENGTH] 战斗力。格挡每回合受到的第一次非致命攻击。消耗3 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_INDONESIAN_KRIS_SWORDSMAN_DESCRIPTION",					"Indonesian unique Riligious Arm unit that replaces the Armed Believer. May be purchased with [ICON_GOLD] Gold. Cost 2 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_INDONESIAN_KRIS_SWORDSMAN_DESCRIPTION",					"印度尼西亚特色宗教武装单位，取代武装教徒。可以用 [ICON_GOLD] 金币购买。消耗2 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_LAHORE_NIHANG_DESCRIPTION",								"Lahore City-State unique Riligious Arm unit. +2 [ICON_STRENGTH] Combat Strength if there is a Barracks in your empire, extra +2 if there is an Armory, extra +2 if there is a Military Academy. Cost 2 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_LAHORE_NIHANG_DESCRIPTION",								"拉合尔城邦特色宗教武装单位。如果国内有兵营则+2 [ICON_STRENGTH] 战斗力，如果有兵工厂则额外+2，如果有军事学院再额外+2。消耗2 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_LEADER_TRAIT_LAHORE_DESCRIPTION",								"Unlocks the Lahore City-State unique Riligious Arm unit Nihang. +15 [ICON_STRENGTH] Combat Strength for all Nihang units."),
	("zh_Hans_CN",	"LOC_LEADER_TRAIT_LAHORE_DESCRIPTION",								"解锁拉合尔城邦特色宗教武装单位尼杭战士。所有尼杭战士+15 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_MINOR_CIV_LAHORE_NIHANG_STRENGTH",								"+{1_Amount} Strength from being the Suzerain of Lahore"),
	("zh_Hans_CN",	"LOC_MINOR_CIV_LAHORE_NIHANG_STRENGTH",								"+{1_Amount}力来自拉合尔宗主国"),
	("en_US",		"LOC_LEADER_TRAIT_JERUSALEM_DESCRIPTION_EXPANSION",					"Upon conquering a city with Religious Arm unit or with Religious Arm unit adjacent to the city center, your majority religion becomes the dominant religion in that city."),
	("zh_Hans_CN",	"LOC_LEADER_TRAIT_JERUSALEM_DESCRIPTION_EXPANSION",					"用宗教武装单位攻占城市或攻占城市时有宗教武装单位与城市中心相邻，您的主流宗教成为该城市的主流宗教。"),
	("en_US",		"LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",					"Unlocks the Builder ability to construct a Monastery.[NEWLINE][NEWLINE]+2 [ICON_FAITH] Faith, +1 [ICON_HOUSING] Housing. +2 [ICON_GOLD] Gold for every adjacent District. Religious Arm unit trained in cities with a Monastery gain +50% experience."),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",					"解锁建造者建造修道院的能力。[NEWLINE][NEWLINE]+2 [ICON_FAITH] 信仰值，+1 [ICON_HOUSING] 住房。每相邻1个区域+2 [ICON_GOLD] 金币。有修道院的城市训练的宗教武装单位+50%经验。");

insert or replace into LocalizedText
	(Language,		Tag,																Text)
select
	"en_US",		"LOC_UNIT_WARRIOR_MONK_DESCRIPTION",								"Religious Arm Unit. Have one build charge to be removed and complete 20% of a Holy Site district. Can only be purchased with [ICON_FAITH] Faith in cities with a Temple or Church. Cost 3 [ICON_FAITH] Faith to maintain."
where exists (select Text from LocalizedText where Tag = 'LOC_BUILDING_JNR_MONASTERY_NAME');
insert or replace into LocalizedText
	(Language,		Tag,																Text)
select
	"zh_Hans_CN",	"LOC_UNIT_WARRIOR_MONK_DESCRIPTION",								"宗教武装单位，拥有一点劳动力，可以移除该单位来推进圣地区域20%的建造进度。只能在有寺庙或教堂的城市通过 [ICON_FAITH] 信仰购买。消耗3 [ICON_FAITH] 信仰维护费。"
where exists (select Text from LocalizedText where Tag = 'LOC_BUILDING_JNR_MONASTERY_NAME');
insert or replace into LocalizedText
	(Language,		Tag,																Text)
select
	"en_US",		"LOC_BELIEF_WARRIOR_MONKS_EXPANSION2_DESCRIPTION",					"Culture Bomb adjacent tiles when completing a Holy Site. Holy Site provides [ICON_FAITH] Faith equal to its [ICON_FAITH] Faith adjacency bonus. Unlocks the Religious Arm Unit 'Warrior Monk', which has one build charge to complete 20% of a Holy Site district. Can only be purchased with [ICON_FAITH] Faith in cities with a Temple or Church."
where exists (select Text from LocalizedText where Tag = 'LOC_BUILDING_JNR_MONASTERY_NAME');
insert or replace into LocalizedText
	(Language,		Tag,																Text)
select
	"zh_Hans_CN",	"LOC_BELIEF_WARRIOR_MONKS_EXPANSION2_DESCRIPTION",					"建成圣地后对相邻单元格施放文化炸弹。圣地区域的 [ICON_FAITH] 信仰值相邻加成提供额外等量的 [ICON_FAITH] 信仰值。解锁宗教武装单位“武僧”，拥有一点劳动力，可以推进圣地区域20%的建造进度。只能在有寺庙或教堂的城市通过 [ICON_FAITH] 信仰购买。"
where exists (select Text from LocalizedText where Tag = 'LOC_BUILDING_JNR_MONASTERY_NAME');
insert or replace into LocalizedText
	(Language,		Tag,																Text)
select
	"en_US",		"LOC_UNIT_LAHORE_NIHANG_DESCRIPTION",								"Lahore City-State unique Riligious Arm unit. +2 [ICON_STRENGTH] Combat Strength if there is a Barracks or Frontier Juncture in your empire, extra +2 if there is an Armory, Supply Depot or Conscription Service, extra +2 if there is a Military Academy, Military Science Academy or Military Propaganda Agency. Cost 2 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"
where exists (select Text from LocalizedText where Tag = 'LOC_BUILDING_JNR_TARGET_RANGE_NAME');
insert or replace into LocalizedText
	(Language,		Tag,																Text)
select
	"zh_Hans_CN",	"LOC_UNIT_LAHORE_NIHANG_DESCRIPTION",								"拉合尔城邦特色宗教武装单位。如果国内有兵营或边关则+2 [ICON_STRENGTH] 战斗力，如果有兵工厂、补给站或募兵所则额外+2，如果有军事学院、军事研究院或军事政治处再额外+2。消耗2 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"
where exists (select Text from LocalizedText where Tag = 'LOC_BUILDING_JNR_TARGET_RANGE_NAME');