insert or replace into LocalizedText
	(Language,		Tag,												Text)
values
	("en_US",		"LOC_PROMOTION_CLASS_MONK_NAME",					"Religious Arm"),
	("zh_Hans_CN",	"LOC_PROMOTION_CLASS_MONK_NAME",					"宗教武装"),
	("en_US",		"LOC_UNIT_HD_RELIGIOUS_ARM_COMMON",					"[NEWLINE][NEWLINE]Religious Arm: Can only be purchased with [ICON_FAITH] Faith. Combat victories provide [ICON_FAITH] Faith equal to 50% of the [ICON_STRENGTH] Combat Strength of the defeated unit."),
	("zh_Hans_CN",	"LOC_UNIT_HD_RELIGIOUS_ARM_COMMON",					"[NEWLINE][NEWLINE]宗教武装：只能使用 [ICON_FAITH] 信仰值购买。击杀单位时，获得被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_FAITH] 信仰值。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_DESCRIPTION",				"Combat victories provide [ICON_FAITH] Faith equal to 50% of the [ICON_STRENGTH] Combat Strength of the defeated unit."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_DESCRIPTION",				"击杀单位时，获得被击杀单位 [ICON_Strength] 战斗力50%的 [ICON_FAITH] 信仰值。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_MELEE_ANTC_DESCRIPTION",	"+5 [ICON_STRENGTH] Combat Strength v.s. Melee and Anti Cavalry units."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_MELEE_ANTC_DESCRIPTION",	"对战近战和抗骑兵单位+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_FLAT_DESCRIPTION",		"+5 [ICON_STRENGTH] Combat Strength on flat lands."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_FLAT_DESCRIPTION",		"在平坦地形上战斗时+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_ABILITY_RELIGOUS_ARM_DISTRICT_DESCRIPTION",	"+5 [ICON_STRENGTH] Combat Strength on districts."),
	("zh_Hans_CN",	"LOC_ABILITY_RELIGOUS_ARM_DISTRICT_DESCRIPTION",	"位于区域上时+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_ABILITY_2_FAITH_MAINTENANCE_DESCRIPTION",		"Cost 2 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_2_FAITH_MAINTENANCE_DESCRIPTION",		"消耗2 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_3_FAITH_MAINTENANCE_DESCRIPTION",		"Cost 3 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_3_FAITH_MAINTENANCE_DESCRIPTION",		"消耗3 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_4_FAITH_MAINTENANCE_DESCRIPTION",		"Cost 4 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_4_FAITH_MAINTENANCE_DESCRIPTION",		"消耗4 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_5_FAITH_MAINTENANCE_DESCRIPTION",		"Cost 5 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_5_FAITH_MAINTENANCE_DESCRIPTION",		"消耗5 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_6_FAITH_MAINTENANCE_DESCRIPTION",		"Cost 6 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_6_FAITH_MAINTENANCE_DESCRIPTION",		"消耗6 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_ABILITY_15_FAITH_MAINTENANCE_DESCRIPTION",		"Cost 15 [ICON_FAITH] Faith to maintain."),
	("zh_Hans_CN",	"LOC_ABILITY_15_FAITH_MAINTENANCE_DESCRIPTION",		"消耗15 [ICON_FAITH] 信仰维护费。"),
	("en_US",		"LOC_RELIGOUS_ARM_MELEE_ANTC",						"+{1_Amount} Strength v.s. Melee and Anti Cavalry units."),
	("zh_Hans_CN",	"LOC_RELIGOUS_ARM_MELEE_ANTC",						"对战近战和抗骑兵单位+{1_Amount}力。"),
	("en_US",		"LOC_RELIGOUS_ARM_FLAT",							"+{1_Amount} Strength on flat lands."),
	("zh_Hans_CN",	"LOC_RELIGOUS_ARM_FLAT",							"在平坦地形上战斗+{1_Amount}力。"),
	("en_US",		"LOC_RELIGOUS_ARM_DISTRICT",						"+{1_Amount} Strength on districts."),
	("zh_Hans_CN",	"LOC_RELIGOUS_ARM_DISTRICT",						"位于区域上+{1_Amount}力。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_DISABLED_TT",		"[COLOR_RED]Insufficient [ICON_FAITH] Faith.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_DISABLED_TT",		"[COLOR_RED][ICON_FAITH]信仰不足。[ENDCOLOR]"),
	("en_US",		"LOC_PROMOTION_NRYANA_NAME",						"Nryana"),
	("zh_Hans_CN",	"LOC_PROMOTION_NRYANA_NAME",						"那罗延"),
	("en_US",		"LOC_PROMOTION_NRYANA_DESCRIPTION",					"+5 [ICON_STRENGTH] Combat Strength when attacking."),
	("zh_Hans_CN",	"LOC_PROMOTION_NRYANA_DESCRIPTION",					"进攻时+5 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_NRYANA_ATTACK",								"+{1_Amount} Strength when attacking (Nryana)."),
	("zh_Hans_CN",	"LOC_NRYANA_ATTACK",								"进攻时+{1_Amount}力（那罗延）。"),
	("en_US",		"LOC_PROMOTION_DRAGONS_SHAME_NAME",					"Dragon's Shame"),
	("zh_Hans_CN",	"LOC_PROMOTION_DRAGONS_SHAME_NAME",					"亢龙有悔"),
	("en_US",		"LOC_PROMOTION_DRAGONS_SHAME_DESCRIPTION",			"When on a feature or Natural Wonder, +15 [ICON_DAMAGED] Healing per turn and +7 [ICON_STRENGTH] Combat Strength when defending."),
	("zh_Hans_CN",	"LOC_PROMOTION_DRAGONS_SHAME_DESCRIPTION",			"位于地貌或自然奇观时，每回合额外回复15点 [ICON_DAMAGED] 生命值且防御时+7 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_DRAGONS_SHAME_DEFEND",							"+{1_Amount} Strength when defending on feature or Natural Wonder (Dragon's Shame)."),
	("zh_Hans_CN",	"LOC_DRAGONS_SHAME_DEFEND",							"位于地貌或自然奇观防御时+{1_Amount}力（亢龙有悔）。"),
	("en_US",		"LOC_PROMOTION_UNIVERSAL_RESTORATION_NAME",			"Universal Restoration"),
	("zh_Hans_CN",	"LOC_PROMOTION_UNIVERSAL_RESTORATION_NAME",			"普渡众生"),
	("en_US",		"LOC_PROMOTION_UNIVERSAL_RESTORATION_DESCRIPTION",	"+7 [ICON_STRENGTH] Combat Strength when being flanked. Can use 3 [ICON_MOVEMENT] Movement and [ICON_FAITH] Faith equal to 200% of the base [ICON_STRENGTH] Combat Strength to deal damage to adjacent enemy units equal to the base [ICON_STRENGTH] Strength of this unit."),
	("zh_Hans_CN",	"LOC_PROMOTION_UNIVERSAL_RESTORATION_DESCRIPTION",	"被夹击时+7 [ICON_STRENGTH] 战斗力。可以花费3 [ICON_MOVEMENT] 移动力和基础 [ICON_STRENGTH] 战斗力200%的 [ICON_FAITH] 信仰值来对周围敌方战斗单位造成基础 [ICON_STRENGTH] 战斗力的伤害。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DESCRIPTION",	"Use 3 [ICON_MOVEMENT] Movement and {1_Amount} [ICON_FAITH] Faith to deal {2_Amount} damage to all adjacent enemy units."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DESCRIPTION",	"花费3 [ICON_MOVEMENT] 移动力和{1_Amount} [ICON_FAITH] 信仰值来对周围敌方战斗单位造成{2_Amount}点伤害。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DISABLED_TT",	"[COLOR_RED]Insufficient [ICON_MOVEMENT] Movement or [ICON_FAITH] Faith.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_UNIVERSAL_RESTORATION_DISABLED_TT",	"[COLOR_RED][ICON_MOVEMENT] 移动力或 [ICON_FAITH]信仰不足。[ENDCOLOR]"),
	("en_US",		"LOC_UNIVERSAL_RESTORATION_FLANK",					"+{1_Amount} Strength when being flanked (Universal Restoration)."),
	("zh_Hans_CN",	"LOC_UNIVERSAL_RESTORATION_FLANK",					"被夹击时+{1_Amount}力（普渡众生）。"),
	("en_US",		"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_NAME",		"Liberate The Holy Land"),
	("zh_Hans_CN",	"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_NAME",		"解放圣地"),
	("en_US",		"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_DESCRIPTION",	"+1 [ICON_MOVEMENT] Movement."),
	("zh_Hans_CN",	"LOC_PROMOTION_LIBERATE_THE_HOLY_LAND_DESCRIPTION",	"+1 [ICON_MOVEMENT] 移动力。"),
	("en_US",		"LOC_PROMOTION_PUNCITIVE_LAND_NAME",				"Punitive Land"),
	("zh_Hans_CN",	"LOC_PROMOTION_PUNCITIVE_LAND_NAME",				"征伐之地"),
	("en_US",		"LOC_PROMOTION_PUNCITIVE_LAND_DESCRIPTION",			"+10 [ICON_STRENGTH] Combat Strength when fighting in districts. Can use [ICON_FAITH] Faith equal to 50% of the base [ICON_STRENGTH] Combat Strength to restore [ICON_MOVEMENT] Movement. Can be used once each turn."),
	("zh_Hans_CN",	"LOC_PROMOTION_PUNCITIVE_LAND_DESCRIPTION",			"在区域中作战时+10 [ICON_STRENGTH] 战斗力。可以花费基础 [ICON_STRENGTH] 战斗力50%的 [ICON_FAITH] 信仰值来恢复全部移动力。每回合只能恢复一次。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DESCRIPTION",		"Use {1_Amount} [ICON_FAITH] Faith to restore [ICON_MOVEMENT] Movement. Can be used once each turn."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DESCRIPTION",		"花费{1_Amount} [ICON_FAITH] 信仰值来恢复全部移动力。每回合只能恢复一次。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DISABLED_TT",		"[COLOR_RED]Insufficient [ICON_FAITH] Faith or have been used this turn.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PUNCITIVE_LAND_DISABLED_TT",		"[COLOR_RED][ICON_FAITH] 信仰值不足或本回合已经恢复过移动力。[ENDCOLOR]"),
	("en_US",		"LOC_PUNCITIVE_LAND_DISTRICT",						"+{1_Amount} Strength when fighting in districts (Punitive Land)."),
	("zh_Hans_CN",	"LOC_PUNCITIVE_LAND_DISTRICT",						"在区域中作战时+{1_Amount}力（征伐之地）。"),
	("en_US",		"LOC_PROMOTION_PROMISED_LAND_NAME",					"Promised Land"),
	("zh_Hans_CN",	"LOC_PROMOTION_PROMISED_LAND_NAME",					"应许之地"),
	("en_US",		"LOC_PROMOTION_PROMISED_LAND_DESCRIPTION",			"+7 [ICON_STRENGTH] Combat Strength when attacking [ICON_DAMAGED] Damaged units. Can use 5 [ICON_RESOURCE_HORSES] Horses and [ICON_FAITH] Faith equal to 50% of the base [ICON_STRENGTH] Combat Strength to jump across any terrain."),
	("zh_Hans_CN",	"LOC_PROMOTION_PROMISED_LAND_DESCRIPTION",			"攻击[ICON_DAMAGED] 受伤单位时+7 [ICON_STRENGTH] 战斗力。可以花费5 [ICON_RESOURCE_HORSES] 马和基础 [ICON_STRENGTH] 战斗力50%的 [ICON_FAITH] 信仰值来越过任意地形。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DESCRIPTION",	"Use 5 [ICON_RESOURCE_HORSES] Horses and {1_Amount} [ICON_FAITH] Faith to jump across any terrain."),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DESCRIPTION",	"花费5 [ICON_RESOURCE_HORSES] 马和{1_Amount} [ICON_FAITH] 信仰值来越过任意地形。"),
	("en_US",		"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DISABLED_TT",	"[COLOR_RED]Insufficient [ICON_RESOURCE_HORSES] Horses or [ICON_FAITH] Faith.[ENDCOLOR]"),
	("zh_Hans_CN",	"LOC_UNITCOMMAND_RELIGIOUS_ARM_PROMISED_LAND_DISABLED_TT",	"[COLOR_RED][ICON_RESOURCE_HORSES] 马或 [ICON_FAITH] 信仰值不足。[ENDCOLOR]"),
	("en_US",		"LOC_PROMISED_LAND_ATTACK_DAMAGED",					"+{1_Amount} Strength when attacking Damaged units (Promised Land)."),
	("zh_Hans_CN",	"LOC_PROMISED_LAND_ATTACK_DAMAGED",					"攻击受伤单位时+{1_Amount}力（应许之地）。"),
	("en_US",		"LOC_PROMOTION_NATARAJ_NAME",						"Nataraj"),
	("zh_Hans_CN",	"LOC_PROMOTION_NATARAJ_NAME",						"那吒罗阇"),
	("en_US",		"LOC_PROMOTION_NATARAJ_DESCRIPTION",				"+7 [ICON_STRENGTH] Combat Strength when defending against ranged attack. +7 [ICON_STRENGTH] Combat Strength when attacking districts."),
	("zh_Hans_CN",	"LOC_PROMOTION_NATARAJ_DESCRIPTION",				"防御远程攻击时+7 [ICON_STRENGTH] 战斗力。攻击区域时+7 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_NATARAJ_DEFEND_RANGE",							"+{1_Amount} Strength when defending against ranged attack (Nataraj)."),
	("zh_Hans_CN",	"LOC_NATARAJ_DEFEND_RANGE",							"防御远程攻击时+{1_Amount}力（那吒罗阇）。"),
	("en_US",		"LOC_NATARAJ_ATTACK_DISTRICT",						"+{1_Amount} Strength when attacking districts (Nataraj)."),
	("zh_Hans_CN",	"LOC_NATARAJ_ATTACK_DISTRICT",						"攻击区域时+{1_Amount}力（那吒罗阇）。"),
	("en_US",		"LOC_PROMOTION_HD_PILGRIM_NAME",					"Pilgrim"),
	("zh_Hans_CN",	"LOC_PROMOTION_HD_PILGRIM_NAME",					"朝圣者"),
	("en_US",		"LOC_PROMOTION_HD_PILGRIM_DESCRIPTION",				"Does not suffer combat penalties from being damaged. Can use [ICON_FAITH] Faith equal to 10% of the base [ICON_STRENGTH] Combat Strength to build road."),
	("zh_Hans_CN",	"LOC_PROMOTION_HD_PILGRIM_DESCRIPTION",				"不会因受伤遭受战斗减益。可以花费基础 [ICON_STRENGTH] 战斗力10%的 [ICON_FAITH] 信仰值来修建道路。"),
	("en_US",		"LOC_PROMOTION_SHARING_GODS_FAVOR_NAME",			"Sharing God's Favor"),
	("zh_Hans_CN",	"LOC_PROMOTION_SHARING_GODS_FAVOR_NAME",			"共沐主恩"),
	("en_US",		"LOC_PROMOTION_SHARING_GODS_FAVOR_DESCRIPTION",		"+2 [ICON_STRENGTH] Combat Strength to all adjacent Religious Arm units."),
	("zh_Hans_CN",	"LOC_PROMOTION_SHARING_GODS_FAVOR_DESCRIPTION",		"所有相邻的宗教武装单位+2 [ICON_STRENGTH] 战斗力。"),
	("en_US",		"LOC_SHARING_GODS_FAVOR_ADJACENT",					"+{1_Amount} Strength from adjacent units with 'Sharing God's Favor' Promotion."),
	("zh_Hans_CN",	"LOC_SHARING_GODS_FAVOR_ADJACENT",					"+{1_Amount}力来自相邻具有“共沐主恩”晋升的单位。"),
	("en_US",		"LOC_PROMOTION_MIND_OVER_MATTER_NAME",				"Mind Over Matter"),
	("zh_Hans_CN",	"LOC_PROMOTION_MIND_OVER_MATTER_NAME",				"心胜于物"),
	("en_US",		"LOC_PROMOTION_MIND_OVER_MATTER_DESCRIPTION",		"Can move after attack. Can use [ICON_FAITH] Faith equal to 100% of the base [ICON_STRENGTH] Combat Strength to restore attack."),
	("zh_Hans_CN",	"LOC_PROMOTION_MIND_OVER_MATTER_DESCRIPTION",		"攻击后可以移动。可以花费基础 [ICON_STRENGTH] 战斗力100%的 [ICON_FAITH] 信仰值来回复攻击次数。"),
	("en_US",		"LOC_UNIT_HD_ARMED_BELIEVER_NAME",					"Armed Believer"),
	("zh_Hans_CN",	"LOC_UNIT_HD_ARMED_BELIEVER_NAME",					"武装教徒"),
	("en_US",		"LOC_UNIT_HD_EXPEDITIONARY_NAME",					"Expeditionary"),
	("zh_Hans_CN",	"LOC_UNIT_HD_EXPEDITIONARY_NAME",					"远征军"),
	("en_US",		"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_NAME",				"Theocratic Guardian"),
	("zh_Hans_CN",	"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_NAME",				"神权卫队"),
	("en_US",		"LOC_UNIT_HD_RESISTANCE_ARMY_NAME",					"Resistance Army"),
	("zh_Hans_CN",	"LOC_UNIT_HD_RESISTANCE_ARMY_NAME",					"抵抗军"),
	("en_US",		"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_NAME",			"Revolutionary Guardian"),
	("zh_Hans_CN",	"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_NAME",			"革命卫队"),
	("en_US",		"LOC_UNIT_HD_DEUX_EX_MACHINA_NAME",					"Deus ex machina"),
	("zh_Hans_CN",	"LOC_UNIT_HD_DEUX_EX_MACHINA_NAME",					"机械降神"),
	("en_US",		"LOC_UNIT_HD_ARMED_BELIEVER_DESCRIPTION",			"Classical Era Religious Arm Unit. Cost 2 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_ARMED_BELIEVER_DESCRIPTION",			"古典时代宗教武装单位。消耗2 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_EXPEDITIONARY_DESCRIPTION",			"Medieval Era Religious Arm Unit. Cost 3 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_EXPEDITIONARY_DESCRIPTION",			"中世纪宗教武装单位。消耗3 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_DESCRIPTION",		"Renaissance Era Religious Arm Unit. Cost 4 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_THEOCRATIC_GUARDIAN_DESCRIPTION",		"文艺复兴时代宗教武装单位。消耗4 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_RESISTANCE_ARMY_DESCRIPTION",			"Industrial Era Religious Arm Unit. Cost 5 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_RESISTANCE_ARMY_DESCRIPTION",			"工业时代宗教武装单位。消耗5 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_DESCRIPTION",	"Modern Era Religious Arm Unit. Cost 6 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_REVOLUTIONARY_GUARDIAN_DESCRIPTION",	"现代宗教武装单位。消耗6 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("en_US",		"LOC_UNIT_HD_DEUX_EX_MACHINA_DESCRIPTION",			"Information Era Religious Arm Unit. Cost 15 [ICON_FAITH] Faith to maintain.{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}"),
	("zh_Hans_CN",	"LOC_UNIT_HD_DEUX_EX_MACHINA_DESCRIPTION",			"信息时代宗教武装单位。消耗15 [ICON_FAITH] 信仰维护费。{LOC_UNIT_HD_RELIGIOUS_ARM_COMMON}");