--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                   Text)
values
    -- Options
    ("LOC_GAME_CITY_STATES_START_WITH_WALLS",               "Free Walls for City-States"),
    ("LOC_GAME_CITY_STATES_START_WITH_WALLS_DESCRIPTION",   "City-States will start with Walls in their city."),
    ("LOC_GAME_POSTPONE_WORLD_CONGRESS",                    "Postpone World Congress"),
    ("LOC_GAME_POSTPONE_WORLD_CONGRESS_DESCRIPTION",        "Postpone the World Congress. Starts in Industrial Era. Halves the World Congress intervals."),
    ("LOC_GAME_CAPTURE_SETTLERS_AS_BUILDERS",               "Captured Settlers become Builders"),
    ("LOC_GAME_CAPTURE_SETTLERS_AS_BUILDERS_DESCRIPTION",   "Captured Settlers become Builders"),
    ("LOC_GAME_AI_GET_COPY_FOR_MILITARY_UNITS",             "AI Double Military Units"),
    ("LOC_GAME_AI_GET_COPY_FOR_MILITARY_UNITS_DESCRIPTION", "Whenever an AI trains a military unit, it will get a free copy.[NEWLINE]ONLY ENABLE WHEN YOU TRY TO CHALLENGE YOURSELF."),
    ("LOC_GAME_FOREVER_WAR",                                "War last forever"),
    ("LOC_GAME_FOREVER_WAR_DESCRIPTION",                    "The war will last forever once started."),
    ("LOC_GAME_REAL_START_LOCATIONS",                       "Better Starting Location"),
    ("LOC_GAME_REAL_START_LOCATIONS_DESCRIPTION",           "Gives a starting location that respects their civilization's start biases. Copied from Zegangani's mod Origin - Real Start Locations."),
    ("LOC_GAME_HISTORICAL_RELIGIONS",                       "Historical Religions"),
    ("LOC_GAME_HISTORICAL_RELIGIONS_DESCRIPTION",           "Adds additional historical religions. Requires Tomatekh's Historical Religions mod to function."),
    ("LOC_GAME_TESTING_OPTION",                             "[TEST ONLY] All free"),
    ("LOC_GAME_TESTING_OPTION_DESCRIPTION",                 "Testing only, all techs, civics, districts, buildings and units will cost only 1."),
    -- GameModes
    ("LOC_GAMEMODE_MILITARY_NAME",                          "Testing Military Mode"),
    ("LOC_GAMEMODE_MILITARY_DESCRIPTION",                   "[COLOR_Red]Inner Testing Usage Only, please do not enable[ENDCOLOR]. Mode for Testing, current testing mode contains the military adjustments."),
    ("LOC_GAMEMODE_DEVTEST_NAME",                           "Testing Dev Mode"),
    ("LOC_GAMEMODE_DEVTEST_DESCRIPTION",                    "[COLOR_Red]Inner Testing Usage Only, please do not enable[ENDCOLOR]. Mode for Testing, current testing mode contains the Dev adjustments."),
    ("LOC_GAMEMODE_RILIGIOUS_ARM_NAME",                     "Religious Arm Mode"),
    ("LOC_GAMEMODE_RILIGIOUS_ARM_DESCRIPTION",              "Adds a new unit class: Religious Arm. Adds and adjusts several units, beliefs and city states.."),
    ("LOC_GAMEMODE_AITEST_NAME",                            "Testing AI Mode"),
    ("LOC_GAMEMODE_AITEST_DESCRIPTION",                     "[COLOR_Red]Inner Testing Usage Only, please do not enable[ENDCOLOR]. Mode for Testing, current testing mode contains the AI adjustments."),
    ("LOC_GAMEMODE_MPTEST_NAME",                            "Multi Player Mode"),
    ("LOC_GAMEMODE_MPTEST_DESCRIPTION",                     "This is an annotation indicating whether the ""[COLOR_Civ6LightBlue]Harmony in Diversity[ENDCOLOR] Multiplayer mod"" is enabled or not. Currently it is NOT enabled, to get better balanced game experience for Multiplayer, please Subscribe that standalone mod."),
    ("LOC_GAMEMODE_WILD_NAME",                              "Testing Wild Mode"),
    ("LOC_GAMEMODE_WILD_DESCRIPTION",                       "[COLOR_Red]This Mode is still under test, please do not enable[ENDCOLOR]. Mode for testing some ideas."),
    ("LOC_GAMEMODE_MONOPOLIES_NAME",                        "Industries and Corporations Mode"),
    ("LOC_GAMEMODE_MONOPOLIES_DESCRIPTION",                 "[COLOR_Magenta]Please Subscribe ""Harmony in Diversity"": Industries and Corporations Mode (standalone MOD), We have overhaul the whole game mode, including redesigning the benefits of Industries, Corporations and Products.[ENDCOLOR][NEWLINE][NEWLINE]Control, improve, and expand upon your Luxury resources! The Industries and Corporations mode enables you to build profitable Industries around Luxury resources, found Corporations to further their development, and manufacture unique Products to secure your place in business history."),
    ("LOC_GAMEMODE_SECRETSOCIETIES_DESCRIPTION",            "[COLOR_Magenta]""Harmony in Diversity"": There is no value adjustments made by us yet, the balance cannot be guaranteed for this game mode.[ENDCOLOR][NEWLINE][NEWLINE]This game mode adds up to four powerful, mysterious, and often nefarious Secret Societies to the world, each based upon fictional or mythical organizations from the past. Their traces can be found in Barbarian Camps, Tribal Villages, or by sending Envoys to City-States and finding Natural Wonders. Alternatively, if other leaders have discovered a Society, you can learn about them by increasing your diplomatic visibility levels with them.[NEWLINE][NEWLINE]Discovering a Society does not mean joining it automatically, but it unlocks a new Governor that does not need to be assigned to a city. Spending a Governor Title on this governor means joining the society, giving you powerful bonuses. But choose wisely - once you appoint that Governor, you commit to membership for the rest of the game, and other leaders will react to your decision. Spend additional Governor Titles to prove your commitment to the Society and unlock its deeper mysteries."),
    ("LOC_GAMEMODE_BARBARIAN_CLANS_DESCRIPTION",            "[COLOR_Magenta]""Harmony in Diversity"": There is no value adjustments made by us yet, the balance cannot be guaranteed for this game mode.[ENDCOLOR][NEWLINE][NEWLINE]This game mode replaces standard Barbarian Tribes with a diverse set of Clans, each with its own terrain and combat preferences. Additionally, the mode introduces new player actions for peaceful interactions with Barbarians that provide increased strategic options."),
    ("LOC_GAMEMODE_DRAMATICAGES_DESCRIPTION",               "[COLOR_Magenta]""Harmony in Diversity"": This game mode is not a good experience in high difficulty, currently not recommended to enable, please wait patiently for us to make adaptation for this.[ENDCOLOR][NEWLINE][NEWLINE]This game mode makes Dark Ages and Golden Ages more potent than ever. Heroic Ages are removed, and players can only be in a Normal Age in the first era. After that, they will either earn a Dark or a Golden Age.[NEWLINE][NEWLINE]Instead of making Dedications, players get access to powerful new Social Policies based on their Age. Dark Policies make a return with refreshed powerful effects. Brand new Golden Policies are available to those who make it to a Golden Age. To keep earning Era Score, complete Techs and Civics and earn military unit promotions.[NEWLINE][NEWLINE]Dark Ages are particularly dangerous. Players in Dark Ages will have a portion of their empire immediately fall into Free Cities, and Free Cities can exert pressure on other cities. On easier difficulty settings, AI players lose a lot of cities. On harder difficulty settings, human players do. On Prince, they lose an equal amount.[NEWLINE][NEWLINE]Georgia's civilization unique ability is brand new, to match the mode's unique rules."),
    ("LOC_GAMEMODE_APOCALYPSE_DESCRIPTION",                 "[COLOR_Magenta]""Harmony in Diversity"": This game mode is not recommended at this point as we haven't made much adaptation for this.[ENDCOLOR][NEWLINE][NEWLINE]This game mode adds new natural disasters, larger and more impactful versions of existing disasters, and increases the chances of all natural disasters. Apocalypse Mode also adds the Soothsayer unit to the game, and should the climate reach its final level of change, comets pummel the earth and destroy humanity."),
    ("LOC_GAMEMODE_HEROES_DESCRIPTION",                     "[COLOR_Magenta]""Harmony in Diversity"": This game mode is not recommended at this point as we haven't made much adaptation for this.[ENDCOLOR][NEWLINE][NEWLINE]This game mode adds twelve powerful Hero units from the world's myths and legends.[NEWLINE][NEWLINE]Discover Heroes by exploring the world and influencing City-States, then claim them in your Cities. Each Hero is unique in the world and can be claimed by just one civilization.[NEWLINE][NEWLINE]Heroes possess great power and unique abilities, but also a limited lifespan. Whenever a Hero appears, they remain for a set number of turns before their time is up and they naturally expire. After a Hero is gone, however, their claiming civilization can recall them by spending Faith.[NEWLINE][NEWLINE]Each of the twelve Heroes has their own special powers and distinct role. In the hands of a wise player, the right Hero can truly be a game-changing force!"),    
    ("LOC_GAMEMODE_TREE_RANDOMIZER_DESCRIPTION",            "[COLOR_Magenta]""Harmony in Diversity"": We have adjusted the cost of Techs and Civics accordingly, but be careful to enable as it randomize the tech and civic tree.[ENDCOLOR][NEWLINE][NEWLINE]This game mode shuffles techs and civics within their historical eras, leading to different costs and prerequisites than normal. The resulting trees are the same for all players. Techs and civics are also hidden until a prerequisite is earned, preserving the mystery of discovery all the way until the end of the game."),
    ("LOC_GAMEMODE_TOWERDEFENSE_DESCRIPTION",               "[COLOR_Red]""Harmony in Diversity"" Warning: This game mode is highly discouraged as its bad game experience. We will not make adjustments specifically to this mode.[ENDCOLOR][NEWLINE][NEWLINE]In this game mode, the dead rise to wreak havoc among the living!  Use new defensive structures to protect your territory, and manipulate zombies to slow your opponents."),
    -- Maps
    ("LOC_MAP_REGULAR_PANGAEA_NAME",                        "Regular Pangaea"),
    ("LOC_MAP_REGULAR_PANGAEA_DESCRIPTION",                 "An ellipse-shape Pangaea map."),
    ("LOC_MAP_TINY_ISLANDS_NAME",                           "Tiny Islands"),
    ("LOC_MAP_TINY_ISLANDS_DESCRIPTION",                    "Many tiny islands."),
    ("LOC_MAP_TINY_LAKES_NAME",                             "Tiny Lakes"),
    ("LOC_MAP_TINY_LAKES_DESCRIPTION",                      "Many tiny lakes."),
    ("LOC_MAP_WET_LAKES_NAME",                              "Mangrove Continent"),
    ("LOC_MAP_RIVERS_NAME",                              	"Rivers"),
    ("LOC_MAP_RIVERS_DESCRIPTION",                          "Many Rivers"),
    ("LOC_MAP_WET_LAKES_DESCRIPTION",                       "Endless marshes and swamps.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                    Text)
values
    -- Options
    ("zh_Hans_CN",  "LOC_GAME_CITY_STATES_START_WITH_WALLS",                "城邦初始城墙"),
    ("zh_Hans_CN",  "LOC_GAME_CITY_STATES_START_WITH_WALLS_DESCRIPTION",    "城邦在游戏开始时即获得城墙。"),
    ("zh_Hans_CN",  "LOC_GAME_POSTPONE_WORLD_CONGRESS",                     "推迟世界议会"),
    ("zh_Hans_CN",  "LOC_GAME_POSTPONE_WORLD_CONGRESS_DESCRIPTION",         "推迟世界议会到工业时代开始。减半世界议会的周期。"),
    ("zh_Hans_CN",  "LOC_GAME_CAPTURE_SETTLERS_AS_BUILDERS",                "抢占的开拓者变为建造者"),
    ("zh_Hans_CN",  "LOC_GAME_CAPTURE_SETTLERS_AS_BUILDERS_DESCRIPTION",    "抢占的开拓者变为建造者"),
    ("zh_Hans_CN",  "LOC_GAME_AI_GET_COPY_FOR_MILITARY_UNITS",              "AI双倍军事单位"),
    ("zh_Hans_CN",  "LOC_GAME_AI_GET_COPY_FOR_MILITARY_UNITS_DESCRIPTION",  "每当ai训练一个军事单位，其会免费获得一个同样的单位。[NEWLINE]请谨慎开启。"),
    ("zh_Hans_CN",  "LOC_GAME_FOREVER_WAR",                                 "永恒的战争"),
    ("zh_Hans_CN",  "LOC_GAME_FOREVER_WAR_DESCRIPTION",                     "战争一旦开始就无法结束。"),
    ("zh_Hans_CN",  "LOC_GAME_REAL_START_LOCATIONS",                        "关联优先的出生点分配"),
    ("zh_Hans_CN",  "LOC_GAME_REAL_START_LOCATIONS_DESCRIPTION",            "以文明的关联优先的出生点分配方式。复制自Zegangani的模组Origin - Real Start Locations。"),
    ("zh_Hans_CN",  "LOC_GAME_HISTORICAL_RELIGIONS",                        "历史上的宗教"),
    ("zh_Hans_CN",  "LOC_GAME_HISTORICAL_RELIGIONS_DESCRIPTION",            "添加了更多历史上的宗教。需要Tomatekh的模组Tomatekh's Historical Religions以生效。"),
    ("zh_Hans_CN",  "LOC_GAME_TESTING_OPTION",                              "[测试用]全免费"),
    ("zh_Hans_CN",  "LOC_GAME_TESTING_OPTION_DESCRIPTION",                  "用于测试的选项，所有的科技、市政、区域、建筑和单位均为最低花费。"),
    -- GameModes
    ("zh_Hans_CN",  "LOC_GAMEMODE_MILITARY_NAME",                           "测试军事模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_MILITARY_DESCRIPTION",                    "[COLOR_Red]内部测试专用，请勿开启[ENDCOLOR]。用于测试的模式，当前测试模式中调整了军事。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_DEVTEST_NAME",                            "测试开发模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_DEVTEST_DESCRIPTION",                     "[COLOR_Red]内部测试专用，请勿开启[ENDCOLOR]。用于测试的模式，当前测试模式包含了开发中内容。"),
	("zh_Hans_CN",  "LOC_GAMEMODE_RILIGIOUS_ARM_NAME",                      "宗教武装模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_RILIGIOUS_ARM_DESCRIPTION",               "添加了新单位类型：宗教武装。添加和改动了一些单位、信条和城邦。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_AITEST_NAME",                             "测试AI模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_AITEST_DESCRIPTION",                      "[COLOR_Red]内部测试专用，请勿开启[ENDCOLOR]。用于测试的模式，当前测试模式中调整了AI。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_MPTEST_NAME",                             "联机模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_MPTEST_DESCRIPTION",                      "这是用于标记[COLOR_Civ6LightBlue]和而不同[ENDCOLOR]联机模组是否启用的标识，当前联机模组未启用，为获得更平衡的联机体验，请订阅独立的[COLOR_Civ6LightBlue]和而不同[ENDCOLOR]联机模组。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_WILD_NAME",                               "测试狂野模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_WILD_DESCRIPTION",                        "[COLOR_Red]此模式仍在测试中，请勿开启[ENDCOLOR]。用于测试一些想法的模式。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_MONOPOLIES_NAME",                         "行业与公司模式"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_MONOPOLIES_DESCRIPTION",                  "[COLOR_Magenta]请订阅并启用“和而不同”行业与公司模式独立MOD，我们对该模式进行了全面的重制，包括行业、公司和产品的效果。[ENDCOLOR][NEWLINE][NEWLINE]控制、改良您的奢侈品资源，并在此之上进行拓展！在“行业与公司”模式中，您可以围绕奢侈品资源建立利润丰硕的行业、创建公司进行深度开发，并生产特色产品，确立您在商业历史中的显著地位。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_SECRETSOCIETIES_DESCRIPTION",             "[COLOR_Magenta]“和而不同”提示：我们尚未对此模式进行深入适配，平衡性无法保证。[ENDCOLOR][NEWLINE][NEWLINE]此游戏模式在世界中加入了4个强大而神秘的秘密结社，每个皆以现实中存在的组织为原型。清理蛮族营地、造访部落村庄、将使者派往城邦或寻找自然奇观，便能找到他们的蛛丝马迹。另外，如果其他领袖已经发现秘密结社，提高与其的外交能见度也能接触到秘密结社。[NEWLINE][NEWLINE]发现秘密结社并不代表自动加入，但会解锁一名不需要指定到城市的新总督。将头衔颁发给此总督则代表加入此结社，并获得强大加成。但此举需要谨慎抉择。一旦任命总督后，在整场游戏中便会成为此结社的成员，而其他领袖也会对此作出反应。颁发更多总督头衔可以证明自己对结社的忠诚，从而解锁深层秘密。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_BARBARIAN_CLANS_DESCRIPTION",             "[COLOR_Magenta]“和而不同”提示：我们尚未对此模式进行深入适配，平衡性无法保证。[ENDCOLOR][NEWLINE][NEWLINE]此游戏模式替代了标准的蛮族部落，取而代之的是野蛮氏族，每个氏族皆有其自身的领土及战斗偏好。此外，此模式还加入了与蛮族的和平交往，为玩家带来更具策略性的选择。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_DRAMATICAGES_DESCRIPTION",                "[COLOR_Magenta]“和而不同”提示：高难度下此模式体验不佳，目前不推荐开启，请耐心等待我们进行适配性调整。[ENDCOLOR][NEWLINE][NEWLINE]这个模式让黄金时代和黑暗时代更加强大。英雄时代已被移除，玩家最初只会进入普通时代，随后便会进入黄金时代或黑暗时代。[NEWLINE][NEWLINE]玩家可以根据自己所处的时代选择强大的全新社会政策，不再设定着力点。黑暗政策再度回归，并带来了全新的强大效果。而进入黄金时代后玩家可以选择全新的黄金政策。玩家需要多多解锁科技和市政、升级单位，不断获取时代得分。[NEWLINE][NEWLINE]黑暗时代将变得凶险万分。进入黑暗时代后，玩家帝国的一部分将直接沦为自由城市，而自由城市会对其他城市释放忠诚度压力。在较简单的难度下，AI玩家会失去大量城市；而在较难的难度下，真人玩家会失去大量城市。在“王子”难度下，两者失去的城市数量相同。[NEWLINE][NEWLINE]为匹配此模式的特殊规则，格鲁吉亚的文明特色能力已更新。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_APOCALYPSE_DESCRIPTION",                  "[COLOR_Magenta]“和而不同”提示：我们尚未对此模式进行适配，目前不推荐开启。[ENDCOLOR][NEWLINE][NEWLINE]此游戏模式新增全新的自然灾害、现有的灾害将变得更大更强、所有自然灾害的发生几率将增加。天启模式将在游戏中加入单位“预言者”；如气候达到变化的最后等级，彗星将撞击地球，终结人类文明。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_HEROES_DESCRIPTION",                      "[COLOR_Magenta]“和而不同”提示：我们尚未对此模式进行适配，目前不推荐开启。[ENDCOLOR][NEWLINE][NEWLINE]此游戏模式加入了12位世界神话与传说中的强力英雄单位。[NEWLINE][NEWLINE]通过探索世界或影响城邦来发现这些英雄，然后在城市中获得他们。每位英雄在世界上只有一位，且只能被一个文明获得。[NEWLINE][NEWLINE]英雄拥有强大能力和特色技能，但寿命有限。英雄出现后，其将在游戏中存在一定时间，之后将自然消亡。英雄离开之后，曾拥有他们的文明可以花费信仰值来将其召回。[NEWLINE][NEWLINE]12位英雄都拥有特殊能力和专属角色。如果使用得当，他们将能一举扭转游戏中的局势！"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_TREE_RANDOMIZER_DESCRIPTION",             "[COLOR_Magenta]“和而不同”提示：我们重新调整了该模式下科技和市政的需求以对齐常规模式，但该模式随机打乱了设计好的科技树和市政树，一般不推荐开启。[ENDCOLOR][NEWLINE][NEWLINE]此模式会随机选择历史时代中的科技与市政，带来不同寻常的花费与先决条件。所有玩家的科技与市政树皆相同。此外，在达到先决条件前，科技与市政为隐藏状态，一路保留探索秘密的神秘感，直至游戏结束。"),
    ("zh_Hans_CN",  "LOC_GAMEMODE_TOWERDEFENSE_DESCRIPTION",                "[COLOR_Red]“和而不同”提示：此模式体验较差，非常不推荐开启，我们也不会针对该模式进行适配调整。[ENDCOLOR][NEWLINE][NEWLINE]在此模式中，活死人将从地上爬起，给活人带来混乱恐慌！利用全新的防御建筑来保护您的领土，并操纵丧尸阻扰对手。"),
    -- ("zh_Hans_CN",  "LOC_ADD_STEEL_N_THUNDER_UU_NAME",                   "添加WE对ST特色单位的支持"),
    -- ("zh_Hans_CN",  "LOC_ADD_STEEL_N_THUNDER_UU_DESC",                   "添加Warfare Expanded对SteelThunder特色单位的支持{LOC_WER_MOD_NOTE}"),
    ("zh_Hans_CN",  "LOC_CSE_FAVOR_CONSULAR_DESC",                          "[COLOR_Magenta]请订阅并启用“和而不同”城邦扩展独立MOD，我们在CIVITAS城邦扩展的基础上重新设计了新的农业和航海城邦：[ENDCOLOR][NEWLINE]启用时，领事城邦会给予文明外交支持作为派遣使者的奖励；禁用时，则改为给予忠诚度奖励。"),
    ("zh_Hans_CN",  "LOC_CSE_ETHIOPIA_MODE_DESC",                           "[COLOR_Civ6LightBlue]“和而不同”：我们已全面调整了使者加成机制，该模式失效，请勿开启，将于后续移除该模式。[ENDCOLOR][NEWLINE]启用时，使者加成将随相关区域建筑阶级提升而增加，且会因外交区建筑而获得额外加成，与[COLOR:ResGoldLabelCS]“新纪元季票——埃塞俄比亚DLC”[ENDCOLOR]中所做改动类似。"),
    ("zh_Hans_CN",  "LOC_CSE_WALLS_DESC",                                   "[COLOR_Magenta]城邦多样化：和而不同本体已增加该选项，请勿启用，将于后续移除该模式。[ENDCOLOR][NEWLINE]启用时，城邦生成伊始便拥有城墙。"),
    -- Maps
    ("zh_Hans_CN",  "LOC_MAP_REGULAR_PANGAEA_NAME",                         "规则的盘古大陆"),
    ("zh_Hans_CN",  "LOC_MAP_REGULAR_PANGAEA_DESCRIPTION",                  "椭圆状的较为规则的盘古大陆。"),
    ("zh_Hans_CN",  "LOC_MAP_TINY_ISLANDS_NAME",                            "米粒岛屿"),
    ("zh_Hans_CN",  "LOC_MAP_TINY_ISLANDS_DESCRIPTION",                     "很多如米粒般大小的岛屿。"),
    ("zh_Hans_CN",  "LOC_MAP_TINY_LAKES_NAME",                              "星罗棋布"),
    ("zh_Hans_CN",  "LOC_MAP_TINY_LAKES_DESCRIPTION",                       "星罗棋布的湖泊。"),
    ("zh_Hans_CN",  "LOC_MAP_WET_LAKES_NAME",                               "红树林大陆"),
    ("zh_Hans_CN",  "LOC_MAP_RIVERS_NAME",                              	"千河"),
    ("zh_Hans_CN",  "LOC_MAP_RIVERS_DESCRIPTION",                           "密集的河流。"),
    ("zh_Hans_CN",  "LOC_MAP_WET_LAKES_DESCRIPTION",                        "一望无际的湿地和沼泽。");

    -- ("zh_Hans_CN",  "LOC_WER_MOD_NOTE",                         "[NEWLINE][NEWLINE][COLOR_Red]来自mod“[ICON_Unit]Warfare Expanded Reloaded[ICON_Unit]”[ENDCOLOR]"),
