-- City State Texts, Ethiopia

-- --------------------------------------------------------------------------------
-- -- Language: zh_Hans_CN
-- insert or replace into LocalizedText
--     (Language,      Tag,                                                        Text)
-- values
--     ("zh_Hans_CN",  "LOC_CSE_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS",           "建造奇观、建筑、区域时，[ICON_Capital] 首都+1 [ICON_Production] 生产力。"),
--     ("zh_Hans_CN",  "LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS",          "建造奇观、建筑、区域时，[ICON_Capital] 每个工具铺、水力作坊和风车+1 [ICON_Production] 生产力。"),
--     ("zh_Hans_CN",  "LOC_CSE_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS",           "建造奇观、建筑、区域时，每个{LOC_BUILDING_CONSULATE_COMMA}工作坊和手工工场+3 [ICON_Production] 生产力。"),
--     ("zh_Hans_CN",  "LOC_CSE_INDUSTRIAL_TRAIT_LARGEST_INFLUENCE_BONUS",         "建造奇观、建筑、区域时，每个{LOC_BUILDING_CHANCERY_COMMA}工厂和化工厂+3 [ICON_Production] 生产力。");
