-------------------------------------
--     Temp Testing Adjustments    --
-------------------------------------

-- update CivicRandomCosts set Cost = 6300 where Cost = 4800;
-- update CivicRandomCosts set Cost = 6400 where Cost = 4900;

-- update Civics set Cost = 260 where CivicType = 'CIVIC_LITERARY_TRADITION_HD';  
-- update Civics set Cost = 500 where CivicType = 'CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD';  
-- update Civics set Cost = 1200 where CivicType = 'CIVIC_EVOLUTION_THEORY_HD'; 
-- update Civics set Cost = 1200 where CivicType = 'CIVIC_HISTORICAL_PHILOSOPHY_HD'; 
-- update Civics set Cost = 1200 where CivicType = 'CIVIC_ETHICS_HD'; 
-- update Civics set Cost = 1800 where CivicType = 'CIVIC_SOCIAL_SCIENCE_HD'; 
-- -- Civic Tree v4
-- update Civics set Cost = 20 where CivicType = 'CIVIC_CODE_OF_LAWS';  
-- update Civics set Cost = 40 where CivicType = 'CIVIC_CRAFTSMANSHIP';  
-- update Civics set Cost = 40 where CivicType = 'CIVIC_FOREIGN_TRADE'; 
-- update Civics set Cost = 50 where CivicType = 'CIVIC_MILITARY_TRADITION'; 
-- update Civics set Cost = 50 where CivicType = 'CIVIC_MYSTICISM'; 
-- update Civics set Cost = 70 where CivicType = 'CIVIC_STATE_WORKFORCE'; 
-- update Civics set Cost = 70 where CivicType = 'CIVIC_EARLY_EMPIRE'; 
-- update Civics set Cost = 130 where CivicType = 'CIVIC_GAMES_RECREATION'; 
-- update Civics set Cost = 130 where CivicType = 'CIVIC_DRAMA_POETRY'; 
-- update Civics set Cost = 160 where CivicType = 'CIVIC_POLITICAL_PHILOSOPHY'; 
-- update Civics set Cost = 260 where CivicType = 'CIVIC_MILITARY_TRAINING'; 
-- update Civics set Cost = 260 where CivicType = 'CIVIC_DEFENSIVE_TACTICS';    
-- update Civics set Cost = 260 where CivicType = 'CIVIC_RECORDED_HISTORY';    
-- update Civics set Cost = 260 where CivicType = 'CIVIC_THEOLOGY';    
-- update Civics set Cost = 500 where CivicType = 'CIVIC_NAVAL_TRADITION';    
-- update Civics set Cost = 500 where CivicType = 'CIVIC_FEUDALISM';    
-- update Civics set Cost = 500 where CivicType = 'CIVIC_MEDIEVAL_FAIRES';  
-- update Civics set Cost = 500 where CivicType = 'CIVIC_DIVINE_RIGHT';   
-- update Civics set Cost = 750 where CivicType = 'CIVIC_CIVIL_SERVICE';    
-- update Civics set Cost = 750 where CivicType = 'CIVIC_MERCENARIES';      
-- update Civics set Cost = 750 where CivicType = 'CIVIC_GUILDS';     
-- update Civics set Cost = 850 where CivicType = 'CIVIC_EXPLORATION';      
-- update Civics set Cost = 850 where CivicType = 'CIVIC_REFORMED_CHURCH';    
-- update Civics set Cost = 1000 where CivicType = 'CIVIC_HUMANISM';    
-- update Civics set Cost = 1000 where CivicType = 'CIVIC_DIPLOMATIC_SERVICE';  
-- update Civics set Cost = 1200 where CivicType = 'CIVIC_MERCANTILISM';    
-- update Civics set Cost = 1200 where CivicType = 'CIVIC_THE_ENLIGHTENMENT';   
-- update Civics set Cost = 1800 where CivicType = 'CIVIC_COLONIALISM';   
-- update Civics set Cost = 1800 where CivicType = 'CIVIC_CIVIL_ENGINEERING';   
-- update Civics set Cost = 1800 where CivicType = 'CIVIC_NATIONALISM';   
-- update Civics set Cost = 1800 where CivicType = 'CIVIC_OPERA_BALLET';   
-- update Civics set Cost = 2400 where CivicType = 'CIVIC_NATURAL_HISTORY';   
-- update Civics set Cost = 2400 where CivicType = 'CIVIC_SCORCHED_EARTH';   
-- update Civics set Cost = 2400 where CivicType = 'CIVIC_URBANIZATION';   
-- update Civics set Cost = 3000 where CivicType = 'CIVIC_CONSERVATION';   
-- update Civics set Cost = 3000 where CivicType = 'CIVIC_MASS_MEDIA';   
-- update Civics set Cost = 3000 where CivicType = 'CIVIC_MOBILIZATION';   
-- update Civics set Cost = 3600 where CivicType = 'CIVIC_IDEOLOGY';   
-- update Civics set Cost = 3600 where CivicType = 'CIVIC_SUFFRAGE';   
-- update Civics set Cost = 3600 where CivicType = 'CIVIC_TOTALITARIANISM';  
-- update Civics set Cost = 3600 where CivicType = 'CIVIC_CLASS_STRUGGLE';   
-- update Civics set Cost = 3600 where CivicType = 'CIVIC_CAPITALISM';     
-- update Civics set Cost = 3900 where CivicType = 'CIVIC_NUCLEAR_PROGRAM';  
-- update Civics set Cost = 4200 where CivicType = 'CIVIC_CULTURAL_HERITAGE';   
-- update Civics set Cost = 4500 where CivicType = 'CIVIC_COLD_WAR';   
-- update Civics set Cost = 4500 where CivicType = 'CIVIC_PROFESSIONAL_SPORTS';   
-- update Civics set Cost = 4800 where CivicType = 'CIVIC_RAPID_DEPLOYMENT';   
-- update Civics set Cost = 4800 where CivicType = 'CIVIC_SPACE_RACE';   
-- update Civics set Cost = 5400 where CivicType = 'CIVIC_GLOBALIZATION';   
-- update Civics set Cost = 5400 where CivicType = 'CIVIC_SOCIAL_MEDIA';   
-- update Civics set Cost = 5400 where CivicType = 'CIVIC_ENVIRONMENTALISM';   
-- update Civics set Cost = 5700 where CivicType = 'CIVIC_CORPORATE_LIBERTARIANISM';   
-- update Civics set Cost = 5700 where CivicType = 'CIVIC_DIGITAL_DEMOCRACY';   
-- update Civics set Cost = 5700 where CivicType = 'CIVIC_SYNTHETIC_TECHNOCRACY';   
-- update Civics set Cost = 6000 where CivicType = 'CIVIC_NEAR_FUTURE_GOVERNANCE';   
-- update Civics set Cost = 6300 where CivicType = 'CIVIC_GLOBAL_WARMING_MITIGATION';   
-- update Civics set Cost = 6300 where CivicType = 'CIVIC_SMART_POWER_DOCTRINE';   
-- update Civics set Cost = 6300 where CivicType = 'CIVIC_INFORMATION_WARFARE';  
-- update Civics set Cost = 6300 where CivicType = 'CIVIC_EXODUS_IMPERATIVE';  
-- update Civics set Cost = 6300 where CivicType = 'CIVIC_CULTURAL_HEGEMONY';  
-- update Civics set Cost = 6600 where CivicType = 'CIVIC_FUTURE_CIVIC';

update PseudoYields set DefaultValue = 3 where PseudoYieldType = 'PSEUDOYIELD_RESOURCE_LUXURY'; -- previous 6
update PseudoYields set DefaultValue = 0.2 where PseudoYieldType = 'PSEUDOYIELD_HAPPINESS'; -- previous 1
update AiFavoredItems set Value = 30 where ListType = 'CatherineAltLuxuries'; -- previous 50