--------------------------
-- Resourceful 2 by xhh --
--------------------------

-- Delete
delete from Types where Type = 'RESOURCE_MAPLE';
delete from Types where Type = 'RESOURCE_CORAL';
delete from Types where Type = 'RESOURCE_CAVIAR';
delete from Types where Type = 'RESOURCE_SORGHUM';
delete from Types where Type = 'RESOURCE_SEASHELLS';
delete from Types where Type = 'RESOURCE_OXEN';
delete from Types where Type = 'RESOURCE_MACKEREL';
delete from Types where Type = 'RESOURCE_ALGAE';
delete from Types where Type = 'RESOURCE_GOLD2';

delete from Resource_YieldChanges where ResourceType = 'RESOURCE_WOLF' or ResourceType = 'RESOURCE_TRAVERTINE' or ResourceType = 'RESOURCE_TOXINS' 
	or ResourceType = 'RESOURCE_TIGER' or ResourceType = 'RESOURCE_STRAWBERRY' or ResourceType = 'RESOURCE_SPONGE' or ResourceType = 'RESOURCE_SEA_URCHIN' 
	or ResourceType = 'RESOURCE_SANDALWOOD' or ResourceType = 'RESOURCE_SAKURA' or ResourceType = 'RESOURCE_SAFFRON' or ResourceType = 'RESOURCE_RUBY' 
	or ResourceType = 'RESOURCE_POPPIES' or ResourceType = 'RESOURCE_PLATINUM' or ResourceType = 'RESOURCE_ORCA' or ResourceType = 'RESOURCE_LION' 
	or ResourceType = 'RESOURCE_LAPIS' or ResourceType = 'RESOURCE_EBONY' or ResourceType = 'RESOURCE_CASHMERE' or ResourceType = 'RESOURCE_BAMBOO' 
	or ResourceType = 'RESOURCE_ALABASTER' or ResourceType = 'RESOURCE_TOMATO' or ResourceType = 'RESOURCE_TIN' or ResourceType = 'RESOURCE_SALMON' 
	or ResourceType = 'RESOURCE_RUBBER' or ResourceType = 'RESOURCE_QUARTZ' or ResourceType = 'RESOURCE_PINE' or ResourceType = 'RESOURCE_OAK' 
	or ResourceType = 'RESOURCE_MUSSELS' or ResourceType = 'RESOURCE_MUSHROOMS' or ResourceType = 'RESOURCE_MEDIHERBS' or ResourceType = 'RESOURCE_LIMESTONE' 
	or ResourceType = 'RESOURCE_LEAD' or ResourceType = 'RESOURCE_HAM' or ResourceType = 'RESOURCE_GRANITE' or ResourceType = 'RESOURCE_DATES' 
	or ResourceType = 'RESOURCE_COD' or ResourceType = 'RESOURCE_BERRIES' or ResourceType = 'RESOURCE_BARLEY' or ResourceType = 'RESOURCE_ALOE';
delete from Resource_ValidTerrains where ResourceType = 'RESOURCE_WOLF' or ResourceType = 'RESOURCE_TRAVERTINE' or ResourceType = 'RESOURCE_TOXINS' 
	or ResourceType = 'RESOURCE_TIGER' or ResourceType = 'RESOURCE_STRAWBERRY' or ResourceType = 'RESOURCE_SPONGE' or ResourceType = 'RESOURCE_SEA_URCHIN' 
	or ResourceType = 'RESOURCE_SANDALWOOD' or ResourceType = 'RESOURCE_SAKURA' or ResourceType = 'RESOURCE_SAFFRON' or ResourceType = 'RESOURCE_RUBY' 
	or ResourceType = 'RESOURCE_POPPIES' or ResourceType = 'RESOURCE_PLATINUM' or ResourceType = 'RESOURCE_ORCA' or ResourceType = 'RESOURCE_LION' 
	or ResourceType = 'RESOURCE_LAPIS' or ResourceType = 'RESOURCE_EBONY' or ResourceType = 'RESOURCE_CASHMERE' or ResourceType = 'RESOURCE_BAMBOO' 
	or ResourceType = 'RESOURCE_ALABASTER' or ResourceType = 'RESOURCE_TOMATO' or ResourceType = 'RESOURCE_TIN' or ResourceType = 'RESOURCE_SALMON' 
	or ResourceType = 'RESOURCE_RUBBER' or ResourceType = 'RESOURCE_QUARTZ' or ResourceType = 'RESOURCE_PINE' or ResourceType = 'RESOURCE_OAK' 
	or ResourceType = 'RESOURCE_MUSSELS' or ResourceType = 'RESOURCE_MUSHROOMS' or ResourceType = 'RESOURCE_MEDIHERBS' or ResourceType = 'RESOURCE_LIMESTONE' 
	or ResourceType = 'RESOURCE_LEAD' or ResourceType = 'RESOURCE_HAM' or ResourceType = 'RESOURCE_GRANITE' or ResourceType = 'RESOURCE_DATES' 
	or ResourceType = 'RESOURCE_COD' or ResourceType = 'RESOURCE_BERRIES' or ResourceType = 'RESOURCE_BARLEY' or ResourceType = 'RESOURCE_ALOE';
delete from Resource_ValidFeatures where ResourceType = 'RESOURCE_WOLF' or ResourceType = 'RESOURCE_TRAVERTINE' or ResourceType = 'RESOURCE_TOXINS' 
	or ResourceType = 'RESOURCE_TIGER' or ResourceType = 'RESOURCE_STRAWBERRY' or ResourceType = 'RESOURCE_SPONGE' or ResourceType = 'RESOURCE_SEA_URCHIN' 
	or ResourceType = 'RESOURCE_SANDALWOOD' or ResourceType = 'RESOURCE_SAKURA' or ResourceType = 'RESOURCE_SAFFRON' or ResourceType = 'RESOURCE_RUBY' 
	or ResourceType = 'RESOURCE_POPPIES' or ResourceType = 'RESOURCE_PLATINUM' or ResourceType = 'RESOURCE_ORCA' or ResourceType = 'RESOURCE_LION' 
	or ResourceType = 'RESOURCE_LAPIS' or ResourceType = 'RESOURCE_EBONY' or ResourceType = 'RESOURCE_CASHMERE' or ResourceType = 'RESOURCE_BAMBOO' 
	or ResourceType = 'RESOURCE_ALABASTER' or ResourceType = 'RESOURCE_TOMATO' or ResourceType = 'RESOURCE_TIN' or ResourceType = 'RESOURCE_SALMON' 
	or ResourceType = 'RESOURCE_RUBBER' or ResourceType = 'RESOURCE_QUARTZ' or ResourceType = 'RESOURCE_PINE' or ResourceType = 'RESOURCE_OAK' 
	or ResourceType = 'RESOURCE_MUSSELS' or ResourceType = 'RESOURCE_MUSHROOMS' or ResourceType = 'RESOURCE_MEDIHERBS' or ResourceType = 'RESOURCE_LIMESTONE' 
	or ResourceType = 'RESOURCE_LEAD' or ResourceType = 'RESOURCE_HAM' or ResourceType = 'RESOURCE_GRANITE' or ResourceType = 'RESOURCE_DATES' 
	or ResourceType = 'RESOURCE_COD' or ResourceType = 'RESOURCE_BERRIES' or ResourceType = 'RESOURCE_BARLEY' or ResourceType = 'RESOURCE_ALOE';
delete from Resource_Harvests where ResourceType = 'RESOURCE_WOLF' or ResourceType = 'RESOURCE_TRAVERTINE' or ResourceType = 'RESOURCE_TOXINS' 
	or ResourceType = 'RESOURCE_TIGER' or ResourceType = 'RESOURCE_STRAWBERRY' or ResourceType = 'RESOURCE_SPONGE' or ResourceType = 'RESOURCE_SEA_URCHIN' 
	or ResourceType = 'RESOURCE_SANDALWOOD' or ResourceType = 'RESOURCE_SAKURA' or ResourceType = 'RESOURCE_SAFFRON' or ResourceType = 'RESOURCE_RUBY' 
	or ResourceType = 'RESOURCE_POPPIES' or ResourceType = 'RESOURCE_PLATINUM' or ResourceType = 'RESOURCE_ORCA' or ResourceType = 'RESOURCE_LION' 
	or ResourceType = 'RESOURCE_LAPIS' or ResourceType = 'RESOURCE_EBONY' or ResourceType = 'RESOURCE_CASHMERE' or ResourceType = 'RESOURCE_BAMBOO' 
	or ResourceType = 'RESOURCE_ALABASTER' or ResourceType = 'RESOURCE_TOMATO' or ResourceType = 'RESOURCE_TIN' or ResourceType = 'RESOURCE_SALMON' 
	or ResourceType = 'RESOURCE_RUBBER' or ResourceType = 'RESOURCE_QUARTZ' or ResourceType = 'RESOURCE_PINE' or ResourceType = 'RESOURCE_OAK' 
	or ResourceType = 'RESOURCE_MUSSELS' or ResourceType = 'RESOURCE_MUSHROOMS' or ResourceType = 'RESOURCE_MEDIHERBS' or ResourceType = 'RESOURCE_LIMESTONE' 
	or ResourceType = 'RESOURCE_LEAD' or ResourceType = 'RESOURCE_HAM' or ResourceType = 'RESOURCE_GRANITE' or ResourceType = 'RESOURCE_DATES' 
	or ResourceType = 'RESOURCE_COD' or ResourceType = 'RESOURCE_BERRIES' or ResourceType = 'RESOURCE_BARLEY' or ResourceType = 'RESOURCE_ALOE';

-- Basic
update Resources set ResourceClassType = 'RESOURCECLASS_LUXURY', Happiness = 4 
	where ResourceType = 'RESOURCE_COD' or ResourceType = 'RESOURCE_SALMON' or ResourceType = 'RESOURCE_ALOE' or ResourceType = 'RESOURCE_MEDIHERBS' or ResourceType = 'RESOURCE_QUARTZ';
update Resources set Happiness = 4 where ResourceType = 'RESOURCE_RUBY';

-- Yield
insert or replace into Resource_YieldChanges
	(ResourceType,				YieldType,				YieldChange)
values
	-- 奢侈
	('RESOURCE_WOLF',			'YIELD_PRODUCTION',		1),
	('RESOURCE_WOLF',			'YIELD_GOLD',			1),
	('RESOURCE_TRAVERTINE',		'YIELD_SCIENCE',		1),
	('RESOURCE_TRAVERTINE',		'YIELD_GOLD',			1),
	('RESOURCE_TOXINS',			'YIELD_SCIENCE',		1),
	('RESOURCE_TOXINS',			'YIELD_GOLD',			1),
	('RESOURCE_TIGER',			'YIELD_SCIENCE',		1),
	('RESOURCE_TIGER',			'YIELD_GOLD',			1),
	('RESOURCE_STRAWBERRY',		'YIELD_FOOD',			1),
	('RESOURCE_STRAWBERRY',		'YIELD_GOLD',			1),
	('RESOURCE_SPONGE',			'YIELD_GOLD',			3),
	('RESOURCE_SEA_URCHIN',		'YIELD_FOOD',			1),
	('RESOURCE_SEA_URCHIN',		'YIELD_GOLD',			1),
	('RESOURCE_SANDALWOOD',		'YIELD_FAITH',			1),
	('RESOURCE_SANDALWOOD',		'YIELD_GOLD',			1),
	('RESOURCE_SAKURA',			'YIELD_CULTURE',		1),
	('RESOURCE_SAKURA',			'YIELD_GOLD',			1),
	('RESOURCE_SAFFRON',		'YIELD_CULTURE',		1),
	('RESOURCE_SAFFRON',		'YIELD_GOLD',			1),
	('RESOURCE_RUBY',			'YIELD_PRODUCTION',		1),
	('RESOURCE_RUBY',			'YIELD_GOLD',			1),
	('RESOURCE_POPPIES',		'YIELD_CULTURE',		1),
	('RESOURCE_POPPIES',		'YIELD_GOLD',			1),
	('RESOURCE_PLATINUM',		'YIELD_PRODUCTION',		1),
	('RESOURCE_PLATINUM',		'YIELD_GOLD',			1),
	('RESOURCE_ORCA',			'YIELD_GOLD',			3),
	('RESOURCE_LION',			'YIELD_CULTURE',		1),
	('RESOURCE_LION',			'YIELD_GOLD',			1),
	('RESOURCE_LAPIS',			'YIELD_SCIENCE',		1),
	('RESOURCE_LAPIS',			'YIELD_GOLD',			1),
	('RESOURCE_EBONY',			'YIELD_PRODUCTION',		1),
	('RESOURCE_EBONY',			'YIELD_GOLD',			1),
	('RESOURCE_CASHMERE',		'YIELD_GOLD',			3),
	('RESOURCE_BAMBOO',			'YIELD_PRODUCTION',		1),
	('RESOURCE_BAMBOO',			'YIELD_GOLD',			1),
	('RESOURCE_ALABASTER',		'YIELD_CULTURE',		1),
	('RESOURCE_ALABASTER',		'YIELD_GOLD',			3),
	('RESOURCE_COD',			'YIELD_SCIENCE',		1),
	('RESOURCE_COD',			'YIELD_GOLD',			1),
	('RESOURCE_SALMON',			'YIELD_CULTURE',		1),
	('RESOURCE_SALMON',			'YIELD_GOLD',			1),
	('RESOURCE_ALOE',			'YIELD_FOOD',			1),
	('RESOURCE_ALOE',			'YIELD_GOLD',			1),
	('RESOURCE_MEDIHERBS',		'YIELD_SCIENCE',		1),
	('RESOURCE_MEDIHERBS',		'YIELD_GOLD',			1),
	('RESOURCE_QUARTZ',			'YIELD_FAITH',			1),
	('RESOURCE_QUARTZ',			'YIELD_GOLD',			1),
	-- 加成
	('RESOURCE_TOMATO',			'YIELD_FOOD',			1),
	('RESOURCE_TIN',			'YIELD_GOLD',			2),
	('RESOURCE_RUBBER',			'YIELD_PRODUCTION',		1),
	('RESOURCE_PINE',			'YIELD_PRODUCTION',		1),
	('RESOURCE_OAK',			'YIELD_FOOD',			1),
	('RESOURCE_MUSSELS',		'YIELD_PRODUCTION',		1),
	('RESOURCE_MUSHROOMS',		'YIELD_FAITH',			1),
	('RESOURCE_GRANITE',		'YIELD_PRODUCTION',		1),
	('RESOURCE_LIMESTONE',		'YIELD_FOOD',			-1),
	('RESOURCE_LIMESTONE',		'YIELD_PRODUCTION',		1),
	('RESOURCE_LIMESTONE',		'YIELD_GOLD',			2),
	('RESOURCE_LEAD',			'YIELD_FOOD',			-1),
	('RESOURCE_LEAD',			'YIELD_PRODUCTION',		2),
	('RESOURCE_HAM',			'YIELD_FOOD',			1),
	('RESOURCE_DATES',			'YIELD_FOOD',			1),
	('RESOURCE_BERRIES',		'YIELD_FOOD',			1),
	('RESOURCE_BARLEY',			'YIELD_FOOD',			1),
	('RESOURCE_BARLEY',			'YIELD_GOLD',			1);

-- Terrain
insert or replace into Resource_ValidTerrains
	(ResourceType,				TerrainType)
values
	-- 奢侈
	('RESOURCE_WOLF',			'TERRAIN_GRASS'),
	('RESOURCE_WOLF',			'TERRAIN_GRASS_HILLS'),
	('RESOURCE_WOLF',			'TERRAIN_PLAINS'),
	('RESOURCE_WOLF',			'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_TRAVERTINE',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_STRAWBERRY',		'TERRAIN_GRASS'),
	('RESOURCE_RUBY',			'TERRAIN_DESERT_HILLS'),
	('RESOURCE_RUBY',			'TERRAIN_GRASS_HILLS'),
	('RESOURCE_RUBY',			'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_POPPIES',		'TERRAIN_PLAINS'),
	('RESOURCE_POPPIES',		'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_PLATINUM',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_PLATINUM',		'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_PLATINUM',		'TERRAIN_TUNDRA_HILLS'),
	('RESOURCE_ORCA',			'TERRAIN_COAST'),
	('RESOURCE_LION',			'TERRAIN_PLAINS'),
	('RESOURCE_LION',			'TERRAIN_DESERT'),
	('RESOURCE_LAPIS',			'TERRAIN_DESERT'),
	('RESOURCE_LAPIS',			'TERRAIN_DESERT_HILLS'),
	('RESOURCE_LAPIS',			'TERRAIN_GRASS'),
	('RESOURCE_LAPIS',			'TERRAIN_GRASS_HILLS'),
	('RESOURCE_LAPIS',			'TERRAIN_PLAINS'),
	('RESOURCE_LAPIS',			'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_CASHMERE',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_CASHMERE',		'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_CASHMERE',		'TERRAIN_DESERT_HILLS'),
	('RESOURCE_CASHMERE',		'TERRAIN_TUNDRA_HILLS'),
	('RESOURCE_BAMBOO',			'TERRAIN_GRASS'),
	('RESOURCE_ALABASTER',		'TERRAIN_TUNDRA'),
	('RESOURCE_ALABASTER',		'TERRAIN_TUNDRA_HILLS'),
	('RESOURCE_COD',			'TERRAIN_COAST'),
	('RESOURCE_SALMON',			'TERRAIN_COAST'),
	('RESOURCE_ALOE',			'TERRAIN_GRASS'),
	('RESOURCE_ALOE',			'TERRAIN_PLAINS'),
	('RESOURCE_ALOE',			'TERRAIN_DESERT'),
	('RESOURCE_MEDIHERBS',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_MEDIHERBS',		'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_QUARTZ',			'TERRAIN_DESERT'),
	('RESOURCE_QUARTZ',			'TERRAIN_DESERT_HILLS'),
	('RESOURCE_QUARTZ',			'TERRAIN_PLAINS'),
	('RESOURCE_QUARTZ',			'TERRAIN_PLAINS_HILLS'),
	-- 加成
	('RESOURCE_TOMATO',			'TERRAIN_GRASS'),
	('RESOURCE_TOMATO',			'TERRAIN_PLAINS'),
	('RESOURCE_TIN',			'TERRAIN_GRASS_HILLS'),
	('RESOURCE_TIN',			'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_MUSSELS',		'TERRAIN_COAST'),
	('RESOURCE_LIMESTONE',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_GRANITE',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_GRANITE',		'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_GRANITE',		'TERRAIN_TUNDRA_HILLS'),
	('RESOURCE_LEAD',			'TERRAIN_GRASS'),
	('RESOURCE_LEAD',			'TERRAIN_GRASS_HILLS'),
	('RESOURCE_LEAD',			'TERRAIN_PLAINS'),
	('RESOURCE_LEAD',			'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_LEAD',			'TERRAIN_TUNDRA'),
	('RESOURCE_LEAD',			'TERRAIN_TUNDRA_HILLS'),
	('RESOURCE_HAM',			'TERRAIN_GRASS'),
	('RESOURCE_HAM',			'TERRAIN_PLAINS'),
	('RESOURCE_BERRIES',		'TERRAIN_GRASS'),
	('RESOURCE_BERRIES',		'TERRAIN_GRASS_HILLS'),
	('RESOURCE_BERRIES',		'TERRAIN_PLAINS'),
	('RESOURCE_BERRIES',		'TERRAIN_PLAINS_HILLS'),
	('RESOURCE_BERRIES',		'TERRAIN_TUNDRA'),
	('RESOURCE_BERRIES',		'TERRAIN_TUNDRA_HILLS'),
	('RESOURCE_BARLEY',			'TERRAIN_TUNDRA'),
	('RESOURCE_BARLEY',			'TERRAIN_TUNDRA_HILLS');

delete from Resource_ValidTerrains where TerrainType = 'TERRAIN_TUNDRA_HILLS' and ResourceType = 'RESOURCE_GYPSUM';

-- Feature
insert or replace into Resource_ValidFeatures
	(ResourceType,				FeatureType)
values
	-- 奢侈
	('RESOURCE_WOLF',			'FEATURE_FOREST'),
	('RESOURCE_TRAVERTINE',		'FEATURE_GEOTHERMAL_FISSURE'),
	('RESOURCE_TOXINS',			'FEATURE_JUNGLE'),
	('RESOURCE_TOXINS',			'FEATURE_MARSH'),
	('RESOURCE_TIGER',			'FEATURE_FOREST'),
	('RESOURCE_TIGER',			'FEATURE_JUNGLE'),
	('RESOURCE_SPONGE',			'FEATURE_REEF'),
	('RESOURCE_SEA_URCHIN',		'FEATURE_REEF'),
	('RESOURCE_SANDALWOOD',		'FEATURE_JUNGLE'),
	('RESOURCE_SAKURA',			'FEATURE_FOREST'),
	('RESOURCE_SAFFRON',		'FEATURE_FLOODPLAINS'),
	('RESOURCE_RUBY',			'FEATURE_JUNGLE'),
	('RESOURCE_LAPIS',			'FEATURE_JUNGLE'),
	('RESOURCE_EBONY',			'FEATURE_JUNGLE'),
	('RESOURCE_BAMBOO',			'FEATURE_JUNGLE'),
	('RESOURCE_ALOE',			'FEATURE_OASIS'),
	('RESOURCE_MEDIHERBS',		'FEATURE_FOREST'),
	('RESOURCE_MEDIHERBS',		'FEATURE_MARSH'),
	('RESOURCE_QUARTZ',			'FEATURE_GEOTHERMAL_FISSURE'),
	-- 加成
	('RESOURCE_TIN',			'FEATURE_GEOTHERMAL_FISSURE'),
	('RESOURCE_RUBBER',			'FEATURE_JUNGLE'),
	('RESOURCE_PINE',			'FEATURE_FOREST'),
	('RESOURCE_OAK',			'FEATURE_FOREST'),
	('RESOURCE_MUSSELS',		'FEATURE_REEF'),
	('RESOURCE_GRANITE',		'FEATURE_GEOTHERMAL_FISSURE'),
	('RESOURCE_MUSHROOMS',		'FEATURE_FOREST'),
	('RESOURCE_MUSHROOMS',		'FEATURE_JUNGLE'),
	('RESOURCE_MUSHROOMS',		'FEATURE_MARSH'),
	('RESOURCE_DATES',			'FEATURE_FLOODPLAINS'),
	('RESOURCE_DATES',			'FEATURE_OASIS'),
	('RESOURCE_BERRIES',		'FEATURE_FOREST');

-- Frequency
update Resources set SeaFrequency = 5 where ResourceType = 'RESOURCE_SPONGE' or ResourceType = 'RESOURCE_SEA_URCHIN';
update Resources set SeaFrequency = 1 where ResourceType = 'RESOURCE_COD' or ResourceType = 'RESOURCE_SALMON';
update Resources set Frequency = 6 where ResourceType = 'RESOURCE_TRAVERTINE' or ResourceType = 'RESOURCE_SANDALWOOD';

-- Improvement
	-- 伐木场改良
update Improvements set PrereqTech = 'TECH_MINING' where ImprovementType = 'IMPROVEMENT_LUMBER_MILL';
update Adjacency_YieldChanges set PrereqTech = 'TECH_BRONZE_WORKING' where ID = 'Lumber_Mill_River_Production';
	-- 地热有资矿山、采石场
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_MINE';
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_QUARRY';
	-- 礁石有资渔船
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_FISHING_BOATS';
	-- 雨林有资伐木场
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_LUMBER_MILL';
	-- 行业和公司
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_INDUSTRY';
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_CORPORATION';

-- Harvest
insert or replace into Resource_Harvests
	(ResourceType,				YieldType,			Amount,			PrereqTech)
values
	-- 奢侈
	('RESOURCE_WOLF',			'YIELD_GOLD',			80,			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_TRAVERTINE',		'YIELD_GOLD',			80,			'TECH_MINING'),
	('RESOURCE_TOXINS',			'YIELD_GOLD',			80,			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_TIGER',			'YIELD_GOLD',			80,			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_STRAWBERRY',		'YIELD_GOLD',			80,			'TECH_POTTERY'),
	('RESOURCE_SPONGE',			'YIELD_GOLD',			80,			'TECH_IRRIGATION'),
	('RESOURCE_SEA_URCHIN',		'YIELD_GOLD',			80,			'TECH_IRRIGATION'),
	('RESOURCE_SANDALWOOD',		'YIELD_GOLD',			80,			'TECH_BRONZE_WORKING'),
	('RESOURCE_SAKURA',			'YIELD_GOLD',			80,			'TECH_BRONZE_WORKING'),
	('RESOURCE_SAFFRON',		'YIELD_GOLD',			80,			'TECH_MASONRY'),
	('RESOURCE_RUBY',			'YIELD_GOLD',			80,			'TECH_MINING'),
	('RESOURCE_POPPIES',		'YIELD_GOLD',			80,			'TECH_MASONRY'),
	('RESOURCE_PLATINUM',		'YIELD_GOLD',			80,			'TECH_MINING'),
	('RESOURCE_ORCA',			'YIELD_GOLD',			80,			'TECH_IRRIGATION'),
	('RESOURCE_LION',			'YIELD_GOLD',			80,			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_LAPIS',			'YIELD_GOLD',			80,			'TECH_MINING'),
	('RESOURCE_EBONY',			'YIELD_GOLD',			80,			'TECH_BRONZE_WORKING'),
	('RESOURCE_CASHMERE',		'YIELD_GOLD',			80,			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_BAMBOO',			'YIELD_GOLD',			80,			'TECH_BRONZE_WORKING'),
	('RESOURCE_ALABASTER',		'YIELD_GOLD',			80,			'TECH_MINING'),
	('RESOURCE_COD',			'YIELD_GOLD',			80,			'TECH_IRRIGATION'),
	('RESOURCE_SALMON',			'YIELD_GOLD',			80,			'TECH_IRRIGATION'),
	('RESOURCE_ALOE',			'YIELD_GOLD',			80,			'TECH_MASONRY'),
	('RESOURCE_MEDIHERBS',		'YIELD_GOLD',			80,			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_QUARTZ',			'YIELD_GOLD',			80,			'TECH_MINING'),
	-- 加成
	('RESOURCE_TOMATO',			'YIELD_FOOD',			40			'TECH_POTTERY'),
	('RESOURCE_TIN',			'YIELD_PRODUCTION',		40			'TECH_MINING'),
	('RESOURCE_RUBBER',			'YIELD_PRODUCTION',		40			'TECH_BRONZE_WORKING'),
	('RESOURCE_PINE',			'YIELD_PRODUCTION',		40			'TECH_BRONZE_WORKING'),
	('RESOURCE_OAK',			'YIELD_PRODUCTION',		40			'TECH_BRONZE_WORKING'),
	('RESOURCE_MUSSELS',		'YIELD_PRODUCTION',		40			'TECH_IRRIGATION'),
	('RESOURCE_MUSHROOMS',		'YIELD_FOOD',			40			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_GRANITE',		'YIELD_PRODUCTION',		40			'TECH_MINING'),
	('RESOURCE_LIMESTONE',		'YIELD_PRODUCTION',		40			'TECH_MINING'),
	('RESOURCE_LEAD',			'YIELD_PRODUCTION',		40			'TECH_MINING'),
	('RESOURCE_HAM',			'YIELD_FOOD',			40			'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_DATES',			'YIELD_FOOD',			40			'TECH_MASONRY'),
	('RESOURCE_BERRIES',		'YIELD_FOOD',			40			'TECH_MASONRY'),
	('RESOURCE_BARLEY',			'YIELD_FOOD',			40			'TECH_POTTERY');

-- District
